### ISSUE TITLE
Uses of permissions

### ISSUE THREAD

**Issue by gordhub** [erosman/support#1]
I went to install this add-on, and noticed that it requires some fairly extensive permissions. I think it would be very helpful to would-be users if you document the uses the add-on makes of each permission. Thanks!
![firefox_edit_addon_permissions](https://user-images.githubusercontent.com/25326671/45040015-f4665280-b032-11e8-8d12-98a80aad43d8.png)

**Comment by erosman** [comment]
Sure.. I will add the explanation for the permissions.

**Comment by gordhub** [comment]
Great, thanks!
