### ISSUE TITLE
[FoxyTab] Copy functions don't work for addons.mozilla.org

### ISSUE THREAD

**Issue by jimjoh** [erosman/support#10]
The copy functions don't put anything in the clipboard.  I see the helper tab briefly appear after performing a copy action, but when I go to paste FoxyTab hasn't inserted anything into the clipboard.

I'm using FoxyTab 2.11 with Firefox 60.2.0esr (64-bit) on CentOS 7.

**Comment by jimjoh** [comment]
This problem comes and goes.  After not working all night it's currently working.  Is there anyway to grab debug info when it fails?

**Comment by erosman** [comment]
Firefox blocks scripts running on addons.mozilla.org (and some other sites).
The helper tab should have been able to bypass that problem.
Which copy function are you using in FoxyTab?

**Comment by jimjoh** [comment]
> Which copy function are you using in FoxyTab?
All of the copy functions fail.  I've also tried using a new profile where I only install FoxyTab and it also fails.  So no other extension of configuration change I've made is causing this.

**Comment by jimjoh** [comment]
I've verified that FoxyTab 2.11 fails to copy addons.mozilla.org sites with:
- Firefox 60.2.0esr (64-bit) on CentOS 7
- Firefox 62.0.2 (64-bit) on CentOS 7

It works correctly with:
- Firefox 60.2.1esr (32-bit) on Windows 7

So apparently it's not the Firefox version that's the problem, but instead running it on CentOS 7 seems to cause an issue.  I originally thought this problem occurred randomly, but now I know it only affects certain domains.  Do you have a list of sites where Firefox blocks scripts from running?

**Comment by erosman** [comment]
Thank you for checking it out.

> Do you have a list of sites where Firefox blocks scripts from running?

There are only a few and all related to Mozilla (_discovery.mozilla.org addons.mozilla.org testpilot.firefox.com_ and privileged pages such as _about:*_) however, as you have mentioned, it seems to be particular to CentOS 7.
There previously were some differences in Firefox for Linux too which AFAIK were resolved.

Finally, after over a year of discussion, Firefox 63 added a proper clipboard API so developers don't have to resort to using a Web API and injecting the copy into a page and getting a page to copy to the clipboard.

I don't have CentOS 7 to test it to see where the problem actually is. Were there any errors logged to console?

There is a temporary hack which you can try by removing _addons.mozilla.org_ from the _extensions.webextensions.restrictedDomains_.
I dont know if it works in this case or not.

**Comment by jimjoh** [comment]
I thought this problem occurred on more pages than just mozilla.org, but I may be confusing it with a different random issue I have where immediately after trying to do a copy function I get an error message that says something like "FoxyTab wasn't able to access the clipboard."  Usually if this happens and I simply try copying again it works.

I'll try to keep better track of when I have issues copying.  If it only affects mozilla.org URLs then I can live with that.    Hopefully the new clipboard API will mean all these issues go away.  Thanks for your help.

**Comment by erosman** [comment]
v2.12: Added New Clipboard API (FF63+) which works everywhere
