### ISSUE TITLE
[FireMonkey] Script repository

### ISSUE THREAD

**Issue by SMylk** [erosman/support#101]
Is there a script repository of working/modified scripts?
If not, will there be?

**Comment by erosman** [comment]
Not yet ....
Majority of the scripts made for other script mangers will work in FireMonkey without any issues,
Some scripts will need some minor adjustment.
Some scripts wont work.
AFA CSS repository, then FireMonkey is unique in that regard.

**Comment by SMylk** [comment]
I'm asking cause, I got a few scripts working per the instruction on the help page but a few thwart my every attempt:

[https://raw.githubusercontent.com/Nuklon/Steam-Economy-Enhancer/master/code.user.js](https://raw.githubusercontent.com/Nuklon/Steam-Economy-Enhancer/master/code.user.js)
[https://greasyfork.org/en/scripts/4336](https://greasyfork.org/en/scripts/4336)
[https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js](https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js)
[https://greasyfork.org/en/scripts/17154-imdb-link-em-all](https://greasyfork.org/en/scripts/17154-imdb-link-em-all)
[https://raw.githubusercontent.com/TagoDR/MangaOnlineViewer/master/Manga_OnlineViewer.user.js](https://raw.githubusercontent.com/TagoDR/MangaOnlineViewer/master/Manga_OnlineViewer.user.js)

If someone already converted them it would be helpful.

**Comment by erosman** [comment]
`https://raw.githubusercontent.com/Nuklon/Steam-Economy-Enhancer/master/code.user.js`

`@require` has not been implement in FireMonkey for security reasons but there is a method to achieve it and it is explained in the Help.
`unsafeWindow` again has not been implement in FireMonkey for security reasons but [unsafeWindow](https://wiki.greasespot.net/UnsafeWindow) shows workaround.


`https://greasyfork.org/en/scripts/4336`
`@require` & `@resource` same as above
`@icon` not really important

`https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js`
`unsafeWindow` as above

`https://greasyfork.org/en/scripts/17154-imdb-link-em-all`
`@require` & `@resource` same as above ... however, the gm4-polyfill.js in not needed in FireMonkey ;)

`https://raw.githubusercontent.com/TagoDR/MangaOnlineViewer/master/Manga_OnlineViewer.user.js`
RegEx `@include` is not possible. They have to be converted to match
`@connect` not supported, not supported in GM4 either
`@require` same as above

Generally speaking, scripts using match and fine for matches. Script using include, may need to be fixed.

**Comment by SMylk** [comment]
Thanks for the help, unfortunately was unable to cobble them together, guess I will wait a later version which corrects these errors.

**Comment by erosman** [comment]
v1,24 Added `unsafeWindow` support
