### ISSUE TITLE
[FireMonkey][Feature Request] Sync

### ISSUE THREAD

**Issue by ivysrono** [erosman/support#102]
Sync by browser sync?
Sync by cloud server just like onedrive googledrive dropbox webdav and so on?

**Comment by erosman** [comment]
Which extension for?

**Comment by ivysrono** [comment]
FireMonkey

**Comment by erosman** [comment]
I have not included any Sync option in any of my add-ons yet.

While it makes it easier to use the same setting on multiple location, it can also be less secure.

However, if there is a popular demand for it, I will add it.

**Comment by ivysrono** [comment]
All of GM TM VM have this feature.
I can't use FM without sync.

**Comment by erosman** [comment]
I see TM having the sync option but GM and VM dont seem to have it.

**Comment by ivysrono** [comment]
VM
![图片](https://user-images.githubusercontent.com/2649544/65949457-d2761400-e46e-11e9-8218-af6dd0064d79.png)

**Comment by erosman** [comment]
> [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync)
> You can store up to 100KB of data using this API.

Storage data of FireMonkey will be a lot more than 100kb is most cases so sync storage is not suitable.

**Comment by ivysrono** [comment]
So TM and VM use third party cloud like onedriveand webdav

**Comment by erosman** [comment]
> So TM and VM use third party cloud like onedriveand webdav

Firefox browser sync as well as [chrome.storage.sync](https://developer.chrome.com/extensions/storage#property-sync) have limits of 100kb overall and 8kb per item.

Last week a user was discussing a script that was 2.4mb which is impossible with the limit of 8kb.

Using 3rd party storage allows 3rd party tracking which is a privacy consideration.

Greasemonkey: No sync feature
Violentmonkey: Sync to Dropbox, OneDrive, Google Drive, or a WebDAV service
Tampermonkey: Sync to Dropbox, Google Drive, or a WebDAV service

**Comment by ivysrono** [comment]
`Using 3rd party storage allows 3rd party tracking which is a privacy consideration.`

Add opinion, disable it by default.

**Comment by erosman** [comment]
I have kept this topic open. Let's see how popular it is and what is the demand for it.

**Comment by rNiTnum** [comment]
+1

**Comment by gwarser** [comment]
Sync only original download URLs.

**Comment by Juraj-Masiar** [comment]
I think using "storage.sync" is a great idea -it's secure and super simple to use.
The issue with limited resources (100KB) can be improved by zipping the scripts - since it's just text data, you can zip it to less than 30% of original size (the bigger file, the better ratio).

Also you could make it selective - some checkboxes next to scripts to choose which script to sync.

I have now 8 scripts with total size only 11KB and I would really like to have them synchronized.
Thanks!

**Comment by erosman** [comment]
There are a few problems with `storage.sync`

- **Firefox sync:** My own preference size is around 700kb which is over the 100kb limit. Zipping require additional zip library and it is slow to zip/unzip on every storage read/write. Every time toolbar pop-up is opened storage has to be read. Any changes require storage read/write. Additionally, making external calls to save it to the sync location is slow. `storage.sync` is best for some small data that doesn't require regular read/write.
- **External Sync:** Making a request to an external storage is even slower that Firefox built in sync.
- **Requires login:** "_Items in sync storage are synced by the browser, and are available across all instances of that browser that the user is logged into_ "


> [chrome.storage](https://developer.chrome.com/extensions/storage)
> Confidential user information should not be stored! The storage area isn't encrypted. 


Manual syncing is an option where preferences are saved on a flash and imported. The benefit is that it doesn't require login and it is safe (can be deleted afterwards) which is especially good on shared computers.
The problem with Manual syncing is that it is not automatic. ;)

**Comment by ivysrono** [comment]
> 
> 
> Sync only original download URLs.

+1

**Comment by erosman** [comment]
> Sync only original download URLs.
@gwarser  @ivysrono 
Please explain a bit more.

@Juraj-Masiar 
There was also a request for sync of user-script stored data (i.e. `GM_setValue`) and not the entire storage which includes the scripts themselves.
Any thoughts on that?


I am thinking of maybe adding a MANUAL sync feature!!
A button to save to sync storage & and a button to get from sync storage.

That way, the data stays in local.storage but only a copy uploaded to be retrieved elsewhere.
How about that?

Saving everything to sync will fail once storage gets large and data will be lost. Furthermore, many operations like showing of the pop-up requires storage access and sync.storage access is a lot slower since it is remote.

**Comment by ivysrono** [comment]
`Please explain a bit more.`
For example:
`https://github.com/the1812/Bilibili-Evolved#%E5%A4%87%E7%94%A8%E5%AE%89%E8%A3%85%E6%BA%90`
you can sync just:
{
	@downloadURL: https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js,
	isEnabled: true|false
}
That's all, not all js content.
As I know, GM sync as it.
I'm not sure GM4, however GM3 is.

**Comment by erosman** [comment]
I see... that would work only with script that have `@downloadURL` and that would mean everything the user starts the Firefox anywhere, every script has to be re-downloaded.

**Comment by ivysrono** [comment]
If the script without `@downloadURL`, store the install url.
If the script has been installed while the user starts the Firefox, not re-download, just check isEnable and isDeleted. Can we?

**Comment by erosman** [comment]
In my own case, I have over 700kb script and ALL of them are mine and not on any repository. Not only that it goes over 100kb limit, there is no option of using @downloadURL 

re: isEnabled
That works at the start but once it is enabled somewhere, it wont work until it is received from remote location and installed. 

Let's get more feedback and ideas and see what is most feasible to do.

**Comment by erosman** [comment]
Notes:

> [storage.sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync)
>
> The main use case of this API is to store preferences about your extension and allow the user to sync them to different profiles. You can store up to **100KB of data** using this API. If you try to store more than this, the **call will fail** with an error message. The API is provided **without any guarantees about uptime or performance**.

I was thinking of maybe checking the storage size and then sync if it is under 100kb.
However, [StorageArea.getBytesInUse()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/getBytesInUse) is not implemented in Firefox yet.

**Comment by Juraj-Masiar** [comment]
@erosman regarding "getBytesInUse", you can implement your own, see (and vote) the bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1385832

Also I'm pretty sure accessing "browser.storage.sync" is not "slower" in any way as the data are stored and accessed locally, not remotely. Firefox then synchronizes the storage once in a while, sometimes it takes minutes till the sync happens.

**Comment by erosman** [comment]
> Also I'm pretty sure accessing "browser.storage.sync" is not "slower" in any way as the data are stored and accessed locally, not remotely. Firefox then synchronizes the storage once in a while, sometimes it takes minutes till the sync happens.

@Juraj-Masiar Can that be confirmed for sure? It would have a bearing to know that for a fact.

**Comment by erosman** [comment]
v1.27
Added Storage Sync option

This is Firefox Sync and limited to under 100KB
