### ISSUE TITLE
Error when pasting plain text, but the operations seems to complete without issue.

### ISSUE THREAD

**Issue by theparkway** [erosman/support#104]
I recently installed the Copy PlainText plugin for Firefox. I am moving from Chrome where this functionality is baked into the browser so I was excited to see a plugin that did exactly what I was looking for.

Anyway, after installing the plugin, I tried it out, and although it appears to work great, I get an error that appears every time I use the Paste PlainText option. The error message say "There was an error with the operation" but again, it does seem to paste into the browser without issue.

![image](https://user-images.githubusercontent.com/56312917/66411586-3473d380-e9b1-11e9-97d3-855547a16022.png)

![image](https://user-images.githubusercontent.com/56312917/66411942-d2679e00-e9b1-11e9-82d7-ef2e7e29061c.png)

![image](https://user-images.githubusercontent.com/56312917/66411913-c11e9180-e9b1-11e9-8b9c-75676784b77e.png)

Just thought I would let you know of this issue.

Thank you.

**Comment by erosman** [comment]
Some websites, block the copy/paste operation (e.g. some Google sites, Mozilla etc).

Which site are you trying it out?

**Comment by erosman** [comment]
v1.10 uploaded

**Comment by theparkway** [comment]
In this particular instance, I was pasting into a Gmail new message compose
box, so it would have been on mail.google.com, but I am also seeing the
issue when pasting into a message compose box when using my work email,
which is run on Office 365, so that domain would have been
outlook.office.com

Thank you for the update. I look forward to the v1.10 version being
available for me to install.

Tyler

**Comment by erosman** [comment]
v1,10 has already been uploaded but all recommended extensions get manually reviewed by AMO before release and that is the reason for not appearing intermediately on AMO.
