### ISSUE TITLE
[FoxyTab] [Feature Request] Reload all from Host

### ISSUE THREAD

**Issue by ganego** [erosman/support#106]
After a restart/crash I only want to reload all tabs from a specific site.  

I propose to add a "Reload all" into the "Host" submenu.

Thank you.

-----
Question: If I remove this flag indicator from my address bar, will the whole function of retrieving this information be disabled? I don't want FoxyTab to send any data to whatever website to get the country information.

**Comment by erosman** [comment]
> I propose to add a "Reload all" into the "Host" submenu.

OK.. let's see

> If I remove this flag indicator from my address bar, will the whole function of retrieving this information be disabled? 

Yes the whole process will be disabled

> I don't want FoxyTab to send any data to whatever website to get the country information.

FoxyTab doesn't send the information anywhere. It has a database of IP/Countries inside the addon

**Comment by erosman** [comment]
Done in v2.16
