### ISSUE TITLE
FoxTab tab counter only show three number

### ISSUE THREAD

**Issue by yuxh** [erosman/support#107]
it seems too short to show counter more than thousand in Firefox 69 and 70

**Comment by erosman** [comment]
The badge can only show a maximum of 4 characters. Therefore 9999 would be the biggest it can show.

**Comment by erosman** [comment]
I have noticed lately in the Firefox Nightly, that it is showing only 3 characters now.
I don't know if this a Nightly bug or Firefox have done it intentionally. !!!

**Comment by erosman** [comment]
It was a bug and a bug was filed [( Bug 1602230 )](https://bugzilla.mozilla.org/show_bug.cgi?id=1602230) 2019-12-07

At the end, they decided not to fix it.

> [Extensions in Firefox 74](https://blog.mozilla.org/addons/2020/03/05/extensions-in-firefox-74/)
> 
> There were some issues with long <a href="https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeText">browserAction badge texts</a> wrapping incorrectly. The badge text supports three characters, a fourth may fit in depending on the letters used. Everything else will be cropped. Please keep this in mind when setting your badge text (Thank you Brian)
