### ISSUE TITLE
[FireMonkey] Please clarify in doc `@allFrames`/`@noframes`

### ISSUE THREAD

**Issue by gwarser** [erosman/support#109]
- Is [`@noframes`](https://wiki.greasespot.net/Metadata_Block#.40noframes) supported at all? It should prevent injecting into frames when present.
- Are scripts injected into frames by default?
- Are styles injected into frames by default?
- Do `@allFrames` work in both styles and scripts?

**Comment by erosman** [comment]
From FireMonkey Help

> @allFrames (Optional, true or false (default))

FireMonkey is set like the actual Firefox API. The default is `false` which means not injected into frames
Setting it to `true`  e.g. `@allFrames true` will inject into ALL frames. The behaviour is the same for Styles & Scripts.
