### ISSUE TITLE
[FoxyTab] Feature request: Ability to create custom copy formats

### ISSUE THREAD

**Issue by jimjoh** [erosman/support#11]
I'd like the abuilty to define custom formats for how the page info is copied.
For example with keywords like this:
```
${title}
${url}
${newline}
${tab} //This would insert a tab character, not to be confused with a Firefox tab
${ip}
${tabnumber}
${date}
${time}
```

Then users could define themselves what info they want to copy and in what format.  I personally like this format:
`[${title} ${ip}]${newline}${url}`

Which would copy the tab info like this:
```
[Google 123.123.123.123]
https://www.google.com/
```

**Comment by erosman** [comment]
I am working on a single tab operation at the moment with these parameters:
`{ip} {title} {url} {date} {time}`

**Comment by jimjoh** [comment]
The one other parameter I would really like to have is ${newline}
