### ISSUE TITLE
[Open source] Howto: Download the code

### ISSUE THREAD

**Issue by mdhooge** [erosman/support#110]
Hello,
It is stated on AMO that FireMonkey is provided under the Mozilla Public License, version 2.0. But I can't find its source; the Homepage link points to this Support repository.
So I wonder: is FireMonkey open source?
Thanks for your clarification.

**Comment by erosman** [comment]
Hi

The source is in the extension for anyone to inspect. I don't publish the code separately.

Previously: #97

**Comment by mdhooge** [comment]
Thank you for the clarification! This is so common nowadays to have compiled/obfuscated/compressed code that I didn't even think about that option — sorry.
And it seems I missed #97 when I created my issue. But this also means that your process isn't that usual :sweat_smile:; but totally valid from the MPL point of view.
As a conclusion, I managed to download the XPI with `wget` — don't know if it is possible from the website — and unzip it.

**Comment by erosman** [comment]
> This is so common nowadays to have compiled/obfuscated/compressed code 

True and I dislike compiled/obfuscated/compressed code and all my extensions' code are clear and I never use libraries

>  don't know if it is possible from the website 

Sure... go to add-on page, right click on Install button (**+ Add to Firefox**) an select **Save Link As ...**

**Comment by mdhooge** [comment]
> select Save Link As

:scream: :sob: stupid me

**Comment by adamency** [comment]
I made a git repository of all the history of the project I could salvage: https://github.com/adamency/firemonkey

I explained my reasoning and motive in detail here: https://github.com/erosman/support/issues/415#issuecomment-1865520465

PS: And I intend on keeping it updated.
