### ISSUE TITLE
[FireMonkey] Implement Stylus style Compatibility

### ISSUE THREAD

**Issue by erosman** [erosman/support#111]
I have no idea if it is possible but I will try to find a way to enable users to use Stylus style code.

```
@-moz-document domain('images.example.com')
@-moz-document url-prefix("http://www.example.com")
@-moz-document url(http://www.example.com/test.html)
@-moz-document regexp('http://www\\.example\\.(com|de)/images/.*') 
```

**Update:**  
After verifying from Mozilla engineers, it seems extensions can not apply Stylish/Stylus type `@-moz-document`

**Conversion Guide:**
The following 3 are quite straight forward and easy to convert:
```
@-moz-document domain('images.example.com')
⬇⬇⬇
@match        *://images.example.com/*
```

```
@-moz-document url-prefix("http://www.example.com")
⬇⬇⬇
@match        http://www.example.com/*
```

```
@-moz-document url(http://www.example.com/test.html)
⬇⬇⬇
@match        http://www.example.com/test.html
```

The only difficulty is with the `regex()`. The more complex the RegEx, the more `@match` may be needed but once done, it is easy to read and maintain.
```
@-moz-document regexp('http://www\\.example\\.(com|de)/images/.*') 
⬇⬇⬇
@match        http://www.example.com/images/*
@match        http://www.example.de/images/*
```

**Comment by EstherMoellman** [comment]
@erosman , I only can say that after my small difficulties at the beginning (most of them due to my own ignorance) when I needed to move tons of stuff from Stylus to FireMonkey, after doing that... I never look back again, in just few days I totally adapted myself to FireMonkey. Today FireMonkey is a natural part of my browsing, I can't point to a single situation where I needed Stylus or similar. FireMonkey may not be perfect (no add-on is perfect), but let's say that is more than enough for me, the right shoe size for my foot size.
Having said that, if you can build this compatibility with Stylus style code, it won't hurt, certainly will help lot of Stylus' addicted users, it will make easier to them to use FireMonkey. I just hope this wont come at the price of worsening FireMonkey' performance.

**Comment by erosman** [comment]
After talking with Mozilla engineers, it seems extension can not apply Stylish/Stylus type `@-moz-document`

Furthermore ..... 

> [@-moz-document url-prefix() CSS hack will no longer work](https://www.fxsitecompat.dev/en-CA/docs/2018/moz-document-url-prefix-css-hack-will-no-longer-work/)
> The @-moz-document CSS at-rule has been disabled with Firefox 61 to mitigate the risk of CSS injection attacks, but the empty url-prefix function is still being parsed because it’s known to be used as a CSS hack targeting Firefox.


Subsequent discussions with Mozilla engineers revealed that Stylish/Stylus actually do not apply those rules either (like the legacy era).

In Firefox Quantum, any such style will have to:

- Break each style document into pieces for each `@-moz-document`
- Listeners has to be added to monitor changes to tab/iframe URLs
- Run a comparison against each tab and its iframes and each `@-moz-document` in each style document in all style documents
- If there is a match, inject the style segment into 

Above is considerably resource intensive in comparison to using a dedicated API to inject Style/CSS.

Additionally, as an example, Stylus has to inject multiple files into each tab and each iframe, regardless of whether there is an Style set for it or not, in order to achieve that.

```
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "run_at": "document_start",
      "all_frames": true,
      "match_about_blank": true,
      "js": [
        "js/polyfill.js",
        "js/promisify.js",
        "js/msg.js",
        "js/prefs.js",
        "content/style-injector.js",
        "content/apply.js"
      ]
    }
```


To be frank, the use of `@-moz-document` by an extension turns out to be considerably resource intensive. In fact, it is not used as all in that form and it has to be converted in order to be used by extensions, at a cost. 

Extensions still adhere to the format since there are many styles written in that format which was for the old legacy Firefox and the change is cumbersome.


I will add some conversion examples to the first post to help out with the transition.

**Comment by sergeevabc** [comment]
Is it possible to style Firefox Reader?

The old way to do that is as follows
```
@namespace url(http://www.w3.org/1999/xhtml);
@-moz-document url-prefix("about:reader") {
  body.sans-serif {
    font-family: "Ubuntu", sans-serif !important;
  }
}
```
However converting it to the following form does not help.
```
/*
==UserCSS==
@name           Firefox Reader
@match          about:reader
@version        1.0
@run-at         document-start
==/UserCSS==
*/

body.sans-serif {
  font-family: "Ubuntu", sans-serif !important;
}
```

**Comment by erosman** [comment]
@sergeevabc Let me test it out.

**Comment by erosman** [comment]
Note: `@document` `@-moz-document` causes error when injected to a page

> ref: [Is there a CSS selector that applies when matching specific values in the URL?](https://stackoverflow.com/questions/45727055/is-there-a-css-selector-that-applies-when-matching-specific-values-in-the-url)
> 
> Test code testing @document rule:
> 
> ```JavaScript
> var styleTag = document.createElement ("style");
> document.head.appendChild (styleTag);
> var sheet = styleTag.sheet;
> sheet.insertRule ("@document url('http://www.google.com') { html {color:red}}", 0);
> ```
> 
> Results:
> 
> `Exception: SyntaxError: An invalid or illegal string was specified`

I also tested it with `@-moz-document`  and it results in the same error.

**Comment by erosman** [comment]
From: [@document](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)


Implemented with the vendor prefix: `-moz-`

**Notes Disabled by default in web pages**, except for an empty `url-prefix()` value, which is supported due to its use in Firefox browser detection. Still supported in **user stylesheets**.

Disabled From version 61: this feature is behind the `layout.css.moz-document.content.enabled` preference (needs to be set to true). To change preferences in Firefox, visit `about:config`.

**Comment by erosman** [comment]
**Update:** 
I am writing a `UserStyle` processor for FireMonkey but `regexp()` cant be handled by the API)

Since the handling is going to be different, I think it is better to keep the `UserCSS` for FireMonkey native and `UserStyle` for Stylus etc compatibility.

**Comment by erosman** [comment]
v1.34
Partial compatibility with <a href="https://www.w3schools.com/css/css_syntax.asp" target="_blank">standard CSS syntax</a> UserStyle <code>==UserStyle== ... ==/UserStyle==</code> is also available (v1.34). Few basic <code>regexp()</code> are converted to match pattern but other sections with <code>regexp()</code> are ignored as browser API does not support Regular Expression.
 The default <code>'run-at'</code> is set to <code>'document-start'</code> for UserStyles.

**Comment by sergeevabc** [comment]
@erosman, I [asked](https://github.com/erosman/support/issues/111#issuecomment-556824035) about styling `about:reader` in this thread, but received no reply. Perhaps you could tell then how to match `https://libreddit.*/r/` within UserCSS?

**Comment by erosman** [comment]
> I https://github.com/erosman/support/issues/111#issuecomment-556824035 about styling about:reader in this thread, but received no reply. That resource seems to be protected by Mozilla, so one has to style it via an external file userContent.css.

At the time, I asked Mozilla about it and they have not provided a method to apply JS/CSS to Reader View.
I have also been interested in the subject as I have a userScript which has to duplicate many features of the Reader mode.

See also: [Allow content scripts on reader mode pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786)

> That resource seems to be protected by Mozilla, so one has to style it via an external file `userContent.css`.

It is more like the code was written without a consideration for extension access so it has no API access and there hasn't been an interest to give it an API access.

> Perhaps you could tell then how to match `https://libreddit.*/r/*` within UserCSS? `@-moz-document regexp("...")` is not supported, `@match` throws an error as follows “* in host must be at start”.

`https://libreddit.*/r/*` is not a valid [Match Patterns](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/match_patterns).

You can use the following:
- The least robust `@include` e.g.
```js
@include          https://libreddit.*/r/*
```
- The more robust `@match` TLD e.g.
```js
@match            https://libreddit.TLD/r/*
```
- The most robust `@match` series e.g.
```js
@match            https://libreddit.nl/r/*
@match            https://libreddit.se/r/*
...
```
