### ISSUE TITLE
[FoxyTab] Merge All windows (but separate private vs non-private tabs)

### ISSUE THREAD

**Issue by meoso** [erosman/support#112]
Can `Merge All Windows` keep the private windows separated from non-private?

example, i had three private windows open, I used merge-all expecting only the 3 windows to combine, but instead my main non-private browser window merged in also.

thank you FoxyTab is simply the best even since the early days.

**Comment by erosman** [comment]
It is possible but require adding more menu items or do you suggest that it should always only merge not private windows?

Merge All Windows
Merge All Windows keep private

**Comment by meoso** [comment]
maybe keep one menu command, and it merge all private-windows into one private-window and _concurrently_ merges all the non-private windows into one non-private window.

**Comment by erosman** [comment]
That is not a bad idea.... Let's see

**Comment by erosman** [comment]
At the moment ....

if active window is PRIVATE, all other tabs will be added and become PRIVATE.

if active window is NORMAL, normal tabs are merged into current one and private ones into a private window.

Is that what you meant?

**Comment by meoso** [comment]
hmmm # 2 is correct, # 1 should be: active window is PRIVATE, all other private tabs will be added and become PRIVATE

**Comment by erosman** [comment]
> hmmm # 2 is correct, # 1 should be: active window is PRIVATE, all other private tabs will be added and become PRIVATE

Then what about normal tabs?

**Comment by meoso** [comment]
merge all private-windows into one private-window 
and concurrently 
merge all the non-private (normal) windows into one non-private (normal) window.

**Comment by erosman** [comment]
This feature is included in next release v2.16
