### ISSUE TITLE
[FoxyTab] "Close Tabs to the Left" should not close hidden tabs

### ISSUE THREAD

**Issue by yfdyh000** [erosman/support#113]
It will close the hidden tabs (like tabs in other groups).
e.g. https://addons.mozilla.org/firefox/addon/tiled-tab-groups/

**Comment by erosman** [comment]
What are hidden tabs?

**Comment by yfdyh000** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide

**Comment by erosman** [comment]
Is the API only available via an extension?
I dont see a Firefox menu for it.

Next, what if a user wants to close the hidden tabs?

**Comment by yfdyh000** [comment]
> Is the API only available via an extension?

Yes.

> I dont see a Firefox menu for it.

If it is used, a hidden tabs menu appears on all tabs dropdown menu.

> Next, what if a user wants to close the hidden tabs?

By extensions to switch, or disable the extensions, or switch to tab from the hidden tabs menu above.

In the current, "Close Tabs to the Left" menu will close all the hidden tabs.

**Comment by erosman** [comment]
How does original Firefox "Close Tabs to the Right" behave with hidden tabs?

**Comment by yfdyh000** [comment]
"Close Tabs to the Right" work fine. I guess maybe hidden tabs like index = negative.

**Comment by erosman** [comment]
OK... I will add it to the next update
