### ISSUE TITLE
[FoxyTab] Exclusive pinned tabs from being sorted

### ISSUE THREAD

**Issue by Keith94** [erosman/support#114]
>Sort Tabs (pinned and unpinned) by URL or Title, Ascending or Descending

Is there any way to leave pinned tabs alone when sorting?

**Comment by erosman** [comment]
OK, I will look into it when preparing the next upgrade

**Comment by erosman** [comment]
Currently, pinned tabs are sorted in pinned group and unpinned ones in an unpinned group.

Is there any issue with this sorting?

**Comment by Keith94** [comment]
Hey,

I was hoping to not sort pinned tabs at all. In my case I have just a few pinned tabs, and they are kept in a certain order that I like to leave unsorted. That's why I rather not sort them, but I can't speak for everyone else's use case.

**Comment by erosman** [comment]
I am add "**Selected Tab**" option to all applicable functions.

That means if there are selected tabs, action will be applied to the selected tabs only.

That way you can select a range of tab and sort those only.

You can also Shift-click to select a lot together.

**Comment by Keith94** [comment]
Sounds good
