### ISSUE TITLE
[FoxyTab] Show number of duplicate tabs in tab badge

### ISSUE THREAD

**Issue by Keith94** [erosman/support#115]
This would be intended to notify when duplicate tabs are present at a glance.

**Comment by erosman** [comment]
Badge only allows 4 characters so there is not enough room for that.

**Comment by Keith94** [comment]
You couldn't show the number of duplicates rather than the total amount of tabs?

**Comment by erosman** [comment]
> You couldn't show the number of duplicates rather than the total amount of tabs?

What about users who want the number of tabs?

**Comment by Keith94** [comment]
I guess there could be an option to choose between the two, if possible.

**Comment by erosman** [comment]
OK ... I will see if there is a popular demand for it
