### ISSUE TITLE
Show script version number and allow downgrade to lower version numbers

### ISSUE THREAD

**Issue by bsto** [erosman/support#116]
May I request some improvements:

Since an existing scripts is only updated when a new script with higher version number is dragged the version number is important.
Therefore when I click on the FireMonkey icon in Toolbar all currently existing scripts are shown.

Could append the current version after with brackets? Sample:

myscript (1.3)

Moreover I wonder whether there is a necessity to allow only updates by scripts with higher version number.
What if users want to revert back to on older version of their scripts.

Could you add an option "Allow downgrade script version number"?

Thank you
Ben

**Comment by erosman** [comment]
Higher version is only used for auto-update.

Manually editing or importing script is not affected so you can always import/paste an older version.


> Could append the current version after with brackets? Sample:
> 
> myscript (1.3)

Renaming them with version number is not possible as FireMonkey uses names as IDs. Displaying them on the sidebar is not practical as most scripts have long names.

Older versions are not stored so it is not possible to 'revert' automatically.
