### ISSUE TITLE
Allow "auto-add" script to (=before) another script is executed

### ISSUE THREAD

**Issue by bsto** [erosman/support#117]
As I learning in another thread old GM script commands like GM_addStyle() are not longer supported in 
new (FireMonkey) scripts.

I was told to add as workaround a function:

function GM_addStyle(css) {
  const head = document.querySelector('head');
  if (head) {
    const style = document.createElement('style');
    style.textContent = css;
    head.appendChild(style);
  }
}

at the top of such a script to let GM_addStyle() be executed successfully.

Since I don't want (now) to adjust all my existing scripts to a non-GM_addStyle()-solution I would have to
change all my scripts and add the function mentioned above.
That means adding it manually to approx. 30-40 scripts. Very unhandy and uncomfortable

What about if FireMonkey would allow the definition of a user customizable "default" script which runs
automatically before another script is performed.

Into this script I could write ONCE (!) the GM_addStyle() function above and would have immediately 30-40 runnable scripts.

If this "default.user.js" script is not existing, then it would not be executed (for users which don't use it).

Can you add this feature?

Thank you
Ben

**Comment by erosman** [comment]
Let me see what can be done... although it is more resource-intensive than adding `GM_addStyle()` support.

**Comment by erosman** [comment]
> [GM addStyle](https://wiki.greasespot.net/GM_addStyle)
> As of Greasemonkey 4.0, this method has been removed. 

- GM4 no longer supports `GM_addStyle()`. Therefore, scripts would need to be updated anyway.
- [TamperMonkey](https://www.tampermonkey.net/documentation.php) still supports it.
- [Violentmonkey](https://violentmonkey.github.io/api/gm/) supports it but as an asyn Promise

**Comment by erosman** [comment]
I might be able to do something about that ... let me think about it.

**Comment by erosman** [comment]
Features has been added for v1.23 (to be released)

please read: #132

**Comment by bsto** [comment]
Ok hmm?

Does that mean I have (can) just add 

// @require       myfirstscript.user.js

to the top of other *.user.js scripts and myfirstscript.user.js will then automatically be executed before the remaining part of the actual script?

**Comment by erosman** [comment]
Does that mean I have (can) just add
```

// @require myfirstscript.user.js

to the top of other *.user.js scripts and myfirstscript.user.js will then automatically be executed before the remaining part of the actual script?
```

Almost....

Scripts are saved by **name** in FireMonkey

So if you have a script named `// @name   myfirstscript` you can included in in another script and it will be injected before that script.
For example:

```
// ==UserScript==
// @name          My Other Script
// @description   Scripting is fun
// @match         http://www.example.com/*
// @match         http://www.example.org/*
// @version       1.0
// @require       myfirstscript
// ==/UserScript==

..... code .....
```

In this case, `myfirstscript` will be injected first and then the content of `My Other Script`

This feature will be available in the next release of FireMonkey v1.23

**Comment by erosman** [comment]
v1.23 uploaded

**Comment by erosman** [comment]
v1.24 Added **GM.addStyle/GM_addStyle**
