### ISSUE TITLE
Edit: remember last used tag format

### ISSUE THREAD

**Issue by gordhub** [erosman/support#12]
I am using this extension for adding formatted text to an issue tracker in HTML format. Great extension. 

Every time I close and open my browser, the format selection under `Tags` goes back to `BBCode`. It would be great if the extension remembered the last used format and re-established it automatically.

**Comment by erosman** [comment]
Thank you for your kind words.

Sure .... I will add recall to BBCode/HTML selection in the next update.

**Comment by erosman** [comment]
**Edit** v1.3 recalls the last tag type selection

**Comment by gordhub** [comment]
Great...works! Thanks! Closing.
