### ISSUE TITLE
[FireMonkey] Modyfying GF script code disables update functionality

### ISSUE THREAD

**Issue by Hlsgs** [erosman/support#120]
Any script that said there's no new version after installing and clicking "update" starts issuing "Script/CSS does not have updateURL or version" after modifying something in the code(or even just saving without changing anything).

**Comment by erosman** [comment]
Can you explain a bit more please?

**Comment by Hlsgs** [comment]
1. download any script from GF
2. open it and hit update > "there is no new version"
3. hit save
4. hit update again > "Script/CSS does not have updateURL or version"

**Comment by erosman** [comment]
Oh ........... I see ... thank you .... let me test it out and fix it then.

**Comment by Hlsgs** [comment]
3. is the bare minimum you need to do for that to happen, but I would like to maintain update functionality even if i change somethign in the code.

**Comment by erosman** [comment]
FıreMonkey script update is based on `@version` so you can edit the script and it wont affect the `@version`

Did you GF script have version number?
Which script was it? So that I can test with the same script.

**Comment by Hlsgs** [comment]
All I've tried behave like this, and this is one of them: https://greasyfork.org/en/scripts/5421-soundtake-soundcloud-downloader

**Comment by erosman** [comment]
I tested it now with https://greasyfork.org/en/scripts/5421-soundtake-soundcloud-downloader

The update is working fine without errors.

But... if you edit the script, it gives that error .... 
It is a bug. I will fix it.

**Comment by erosman** [comment]
v1.20 will have the fix

**Comment by erosman** [comment]
v1.20 Uploaded

**Comment by Hlsgs** [comment]
Solved, thank you! Closing.
