### ISSUE TITLE
[FireMonkey] on/off

### ISSUE THREAD

**Issue by ubone** [erosman/support#123]
when I disable css for a site, the script for the same size doesn't start

to 'fix' it I disable and enable FM from the addons page

**Comment by erosman** [comment]
Thank you for the report. Let me check it and fix any problems with it.

**Comment by ubone** [comment]
from popup

different names

**Comment by erosman** [comment]
I tested it and dont see the problem.

I set a CSS and JS for a page and both are enabled.
I disabled the CSS form the popup and refreshed/reloaded the page.
JS is working fine.

**Comment by ubone** [comment]
could be the script, it's fairly long.

**Comment by erosman** [comment]
> could be the script, it's fairly long.

That shouldn't be an issue in this case. Did you reload the tab?
