### ISSUE TITLE
FoxyTab - Save Tab as PDF not working in Firefox 71

### ISSUE THREAD

**Issue by slipslider** [erosman/support#125]
Hi, I've been using FoxyTab for >1 year, and regularly used Save Tab As PDF, but with latest Firefox 71, Save Tab As PDF does nothing.
Please help.   Thanks, Slipslider

**Comment by erosman** [comment]
I am on 73.0a1 (2019-12-19) (64-bit) and it is working ofr me.

Does the pop-up to save appear?
Does it happen everywhere or on some pages?
Is there any error logged to the console?

**Comment by erosman** [comment]
Let me know if there are still issues.
