### ISSUE TITLE
[FireMonkey] Failed to load dependencies from @require instruction

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [erosman/support#126]
This is reproduced with FireMonkey 1.22 on Firefox 71. Greasy Fork has [hls.user.js](https://greasyfork.org/en/scripts/26981-hls-user-js) to help Firefox works with HLS, but this user script has `@require` instruction, which specified an external script from jsDelivr.

Steps to reproduce:
1. Install FireMonkey
2. Install hls.user.js from Greasy Fork
3. Install CORS Everywhere extension and enable it
4. Open https://walterebert.com/playground/video/hls/

Actual results:
All HTML5 players failed to load videos at Walter Ebert’s page, `@require` doesn’t work

Expected results:
Two HTML5 players should be works, as reproduced with Violentmonkey extension.

**Comment by erosman** [comment]
It is stated in the Help that `@require` is not supported in  currently FireMonkey plus the reason and workaround.

**Comment by erosman** [comment]
`@require` to point to other userscripts has been added to v1.23 _(to be released)_

Please read: #132

**Comment by erosman** [comment]
v1.23 uploaded

**Comment by erosman** [comment]
`@require remote-URL` support has been added to v1.27 _(experimental)_
