### ISSUE TITLE
FoxyTab - Duplicate tab in new window?

### ISSUE THREAD

**Issue by yossidme** [erosman/support#127]
1. Is there a way in FoxyTab to Move a single tab to a new window (regular or private)? I only see options to move groups of tabs (To the Left, to the Right) to a new window.

2. Why not offer all the Move options also for Duplicate?

3. After moving a group of tabs to a new window, is there a way to move them back? I see the Merge All Windows option, but if there are more than two windows open that wouldn't work. One would have to first merge all tabs to a single window them all then move some back to another window.

Thanks.

**Comment by erosman** [comment]
> Is there a way in FoxyTab to Move a single tab to a new window (regular or private)? I only see options to move groups of tabs (To the Left, to the Right) to a new window.

Move -> To private Window

For move to a new normal window, I normally drag the tab outside the current window.

> Why not offer all the Move options also for Duplicate?

It has not been asked before. Additionally, people usually duplicate in the same window.

> After moving a group of tabs to a new window, is there a way to move them back? I see the Merge All Windows option, but if there are more than two windows open that wouldn't work. One would have to first merge all tabs to a single window them all then move some back to another window.

Merge windows, merges all into 2 windows maximum, a normal and a private window (depending if there are both types.

There is no way to know which tab someone wants to move to which window.

**Comment by erosman** [comment]
Firefox already has the menu:

Right-click Tab -> Move Tab -> Move to New Window

If more tabs are highlighted/selected:
Right-click Tab -> Move Tabs -> Move to New Window


![image](https://user-images.githubusercontent.com/6458876/80677511-442e4300-8ace-11ea-909e-8295af4bc3aa.png)
