### ISSUE TITLE
[FoxyTab] Feature Request: Close duplicate tabs - extra button in addon symbol

### ISSUE THREAD

**Issue by adeorato** [erosman/support#128]
In Foxy Tab there is an option to close duplicate tabs. To activate this I have to click to the context menu of one tab, then Foxy Tab, then duplicate tabs.

I wish that in the fox tab symbol itself, there should be the menu for closing dupes like there is already the menu entry for recount. 

![grafik](https://user-images.githubusercontent.com/20139218/71380723-a206c780-25d0-11ea-9c05-5843302681b1.png)

**Comment by erosman** [comment]
That is possible, but what about the rest of the options? Should buttons be made for all of them?

A user may use another function regularly and want to have a button of that one.

Anyway, let me see what I can do.

**Comment by adeorato** [comment]
About the other options: All options are "current tab" specific.  Therefore it is reasonable that it only in the tab "Context menu". E.g. "Host" is only meaningful when there is a selected tab.

But a few options have no "current tab context":
- Close duplicate
- Sort (this has a sub context menu)
- Merge all windows
- Recount

So in my opinion, only this five are allowed as buttons in the addon-popup.
But listening to your argument seems that you believe, that this has to configurable which increases the work for the programmer much.
Writing this, I notice I use all the other functions regularly, but for strange reasons, I only saw it as problem with dupes, maybe because I saw an addon for chrome, where this was triggered by the main button. But this addon could only dupes, nothing else.  BTW: You created a real cool addon with many useful features. Thanks for your effort.

Resources Argument: Only during the open time? Is this relevant (except mobile devices)?

`Anyway, let me see what I can do.`
Thanks. Consider it as a low priority feature request.

**Comment by erosman** [comment]
> a few options have no "current tab context"

That is a good point. 

Opening the toolbar pop-up uses a lot more resources (it has to read the storage asynchronously and then process & display the pop-up) than context-menu.

However ...................... there is another possibility.

I can add up to 6 context-menu items to the toolbar icon itself (right-click on the toolbar icon) which doesn't use any more resources.

**Comment by erosman** [comment]
I have started adding item to the toolbar icon context-menu

![foxytab-toolbar-contextmenu](https://user-images.githubusercontent.com/6458876/71422662-1c028380-2699-11ea-8979-ef2a959fb9a5.jpg)

**Comment by erosman** [comment]
All above were added and will be in the next release v2.16.

![browserAction-menu](https://user-images.githubusercontent.com/6458876/80299039-89890280-87a6-11ea-8977-468338ccfc5a.jpg)
