### ISSUE TITLE
Host and Reload Actions

### ISSUE THREAD

**Issue by Mike-Reddick** [erosman/support#129]
Please add:

Host -> Reload
Bookmark -> All
Bookmark -> All to New Folder

**Comment by erosman** [comment]
> Bookmark -> All

It was asked before and already done for the next release

> Host -> Reload

OK ... let's see


> Bookmark -> All to New Folder
I have to look into it

**Comment by erosman** [comment]
Bookmark All, Left, Right is added to next release v2.16
Host reload is added to next release v2.16

Bookmark (All. Left, Right) to a new folder will create another set of menus (there are many new menus in 2.16). I will add it if there is a popular demand.
