### ISSUE TITLE
[FoxyTab] Feature request: Faviconize Tabs

### ISSUE THREAD

**Issue by httan999** [erosman/support#13]
hi there,
First I would like to extend my gratitude for your effort by making this add-on.

Secondly, I was looking at the features and I was impressed, they are very very good, but it lacks one more to be complete. if possible to add a new feature called (Faviconize Tabs) which basically shorten The width of the specified tab becomes small up to the size of favicon.

the feature is already exist in GitHup but not updated since 2 years ago.

if you need more info please refer to the below links:

https://github.com/ktakayama/faviconizetab/
https://addons.mozilla.org/en-US/firefox/addon/faviconizetab/
http://espion.just-size.jp/archives/06/308085916.html

Looking forward for your replay.

Best Regards,

**Comment by erosman** [comment]
That you for your kind comments.

AFAIK, the new Firefox WebExtension API does allow that. If Firefox adds the possibility, I will add the feature.
