### ISSUE TITLE
[FoxyTab] Country Flag of IPv6 Websites

### ISSUE THREAD

**Issue by darwei555** [erosman/support#131]
It seems FoxyTab can only show country flags of websites with IPv4 addresses.  When I visit a website with IPv6 support (e.g. Google), FoxyTab shows a question mark as country flag and if I hover the mouse cursor over the flag, a small popup window shows its IPv6 address and the word Unknown under the address.

I'm running 64-bit Firefox version 71.0 on Windows and FoxyTab version 2.15.

**Comment by erosman** [comment]
That is correct, as mentioned the the Help.

At the moment, I use an IPv4 database so no processing for the IPv6 yet.

PS. I noticed that the DB provider has made it more difficult to get their free DB.

**Comment by erosman** [comment]
I will see if it can be added.

**Comment by darwei555** [comment]
Thanks for your clarification, looking forward to the new version.

**Comment by erosman** [comment]
IPv6 processing (& IPv6 database) added to v2.16 (to be released)
There is also a new IP database source (IP2Location)

Can you give me some sites to test?

**Comment by darwei555** [comment]
Linkedin: 2620:109:c002::6cae:a0a
Youtube: 2607:f8b0:4005:80b::200e
Yahoo: 2001:4998:c:1023::5

Since I'm located in the US, I believe all these should be in the US as well.

**Comment by erosman** [comment]
I get IPv6 when I try to connect to those sites.

**Comment by erosman** [comment]
This feature is included in next release v2.16
