### ISSUE TITLE
[FireMonkey] Add @require support

### ISSUE THREAD

**Issue by erosman** [erosman/support#132]
<p>The <code>@require</code> in <i>FireMonkey</i> was added (v1.23) to facilitate user-script developers, however please note that it differs from the <code>@require</code> in other script mangers.</p>
<p><code>@require</code> can be used to pre-include other existing scripts into a script (or other existing CSS into a CSS). For example:</p>
<pre class="comment">
@require       My Script
</pre>

  <h4>@require script-name</h4>
    <p>For example, user/developer can save some code as a script and name it <code>HelperSet</code>. It does not need to have <code>match/matches/include/includeGlobs</code> etc. It is best to keep the script DISABLED (not enabled) e.g.:</p>

<pre><div class="comment">// ==UserScript==
// @name          HelperSet
// @description   A set of helper functions
// @version       1.0
// ==/UserScript==</div>

<span class="keyword">function</span> someFunc(id) {

  <span class="comment">// some code </span>
}

<span class="keyword">function</span> otherFunc(text) {

  <span class="comment">// some code </span>
}</pre>

  <p>Then include it in other scripts:</p>

<pre class="comment">// ==UserScript==
// @name          My Script
// @description   Scripting is fun
// @match         http://www.example.com/*
// @match         http://www.example.org/*
// @version       1.0
// @require       HelperSet
// ==/UserScript==

..... code .....</pre>

  <p>Multiple scripts can be required and will be injected in order:</p>

<pre class="comment">
// @require       jquery3
// @require       HelperSet
</pre>

  <p>You can use <code>@require</code> for CSS e.g.:</p>

<pre class="comment">/*
==UserCSS==
@name          My CSS
@description   CSS is fun
@match         http://www.example.com/*
@match         http://www.example.org/*
@version       1.0
@require       DefaultCSS
==/UserCSS==
*/</pre>

  <h4>@require URL</h4>
  <p>Few libraries have been packed with <i>FireMonkey</i> (v1.24) which will be injected for user-scripts using <code>@require</code> to get jQuery from original sources. A shorthand <code>jquery1/jquery2/jquery3/jquery-ui1</code> (case-insensitive) can also be used.</p>
  <br><br>
  <p>Folowing sources are processed: jQuery/jQuery UI</p>

  <ul>
    <li>code.jquery.com</li>
    <li>ajax.googleapis.com</li>
    <li>unpkg.com</li>
    <li>cdnjs.com</li>
    <li>www.jsdelivr.com</li>
  </ul>
  
  
  <p>All the following will result in injection of the latest jQuery v3 (e.g. 3.4.1):</p>
<pre class="comment">
// @require       jquery3
// @require       https://code.jquery.com/jquery-3.*.*.js
// @require       https://code.jquery.com/jquery-3.*.*.min.js
// @require       https://code.jquery.com/jquery-3.*.*.slim.js
// @require       https://code.jquery.com/jquery-3.*.*.slim.min.js
// @require       https://ajax.googleapis.com/ajax/libs/jquery/3.*.*/jquery.js
  ... etc
// @require       https://unpkg.com/jquery@3.*.*/dist/jquery.js
  ... etc
</pre>

  <p>All the following will result in injection of jQuery v2.2.4:</p>
<pre class="comment">
// @require       jquery2
// @require       https://code.jquery.com/jquery-2.*.*.js
  ... etc
</pre>

  <p>All the following will result in injection of jQuery v1.12.4:</p>
<pre class="comment">
// @require       jquery1
// @require       https://code.jquery.com/jquery-1.*.*.js
  ... etc
</pre>

  <p>All the following will result in injection of jQuery UI v1.12.1:</p>
<pre class="comment">
// @require       jquery-ui1
// @require       https://code.jquery.com/ui/1.*.*/jquery-ui.js
  ... etc
</pre>

  <p>On popular demand, more libraries may be added in future.</p>

**Note:** v1.24 Added `GM.addStyle/GM_addStyle`

**Comment by erosman** [comment]
v1.23 uploaded

**Comment by erosman** [comment]
Note: While `@require` in FireMonkey is different comparing to GM/VM/TM, AFAIK, ability to include other scripts is unique.

ref: @StephGbzh
```
Make @require able to point to other userscripts
https://github.com/Tampermonkey/tampermonkey/issues/853
```

**Comment by Hlsgs** [comment]
@erosman This is excellent, man, and I think I know how you could make it so GF scripts with extenal dependencies can work without requiring intervention after an auto-update. Please bare with me.

**Method 1, which may already work, but is suboptimal:**

Say a script has `// @require     https://code.jquery.com/jquery-3.4.1.min.js`. We could create a script like so:
```
// ==UserScript==
// @name          https://code.jquery.com/jquery-3.4.1.min.js
// @description   To be included
// @version       3.4.1
// ==/UserScript==

..... jquery-3.4.1.min code .....
```
Would that work? Can script names be URLs?

**Method 2 would not use messy URLs as names and would also allow for one script to be used in multiple third party scripts:**

Say a script has `// @require     https://code.jquery.com/jquery-3.4.1.min.js` and another `// @require     https://code.jquery.com/jquery-3.2.1.min.js`. If you could implement name aliases, we could do something like this:
```
// ==UserScript==
// @name          JQuery3
// @description   To be included
// @version       3.4.1
// @fm_alias      https://code.jquery.com/jquery-3.4.1.min.js
// @fm_alias      https://code.jquery.com/jquery-3.2.1.min.js
// ==/UserScript==

..... jquery-3.4.1.min code .....
```
Would this be feasible?

**Comment by erosman** [comment]
> Can script names be URLs?

Name is text and can be anything.

**The problem with external dependencies via `@require`**

- Script manager must get them first and the script can not be injected before.
First time a script is installed, it wont work until the dependencies has been downloaded

- Storage of dependencies
Script A require https://code.jquery.com/jquery-3.4.1.min.js
Script B require https://code.jquery.com/jquery-3.4.0.min.js
Script C require https://code.jquery.com/jquery-3.3.1.min.js
Script D require https://code.jquery.com/jquery-3.3.0.min.js
Script E require https://code.jquery.com/jquery-2.2.1.min.js
Script F require https://code.jquery.com/jquery-2.2.0.min.js
Script G require https://code.jquery.com/jquery-2.1.0.min.js
...
Script Y require https://code.jquery.com/jquery-1.2.1.min.js
Script Z require https://code.jquery.com/jquery-1.2.1.js

**Important Note:** Very large storage means longer time and more resources every time the storage is accessed for read/write which affects browser speed & CPU/Memory usage

Above is only for JQuery. There are many other libraries that are used by script developers. 
Ref: [Greasy Fork's policy on external scripts](https://greasyfork.org/en/scripts/3249-yet-another-weibo-filter/code)

In legacy Firefox, GM/TM/VM used to save these libraries as files to users' HD. That is not possible any more and they have to be saved to extension storage.

> Would this be feasible?

I actually started by packing JQuery3 with FM but run into the issue of other libraries. AMO does not allow JQuery 1 & 2 inclusion in add-on due to security problems of those old libraries.
Aliasing all JQuery to JQuery3 can break some scripts written for JQuery 2 or JQuery 1.
Then, we run into the user complaint about why `@require` only works for A and not B.

That is why I finally left it to developers and users. Developers can create library sets and then mention on script that it requires installation of A, B, C etc as well

```
// ==UserScript==
// @name          My Script
// @description   Scripting is fun
// @match         http://www.example.com/*
// @match         http://www.example.org/*
// @version       1.0
// @require       JQuery3
// @note           This script requires JQuery3 (https://greasyfork.org/en/scripts/0000- JQuery3/)
// ==/UserScript==

..... code .....
```

I am still open to ideas and suggestions.

**Comment by Hlsgs** [comment]
Thanks for the quick answer.

I'm not suggesting that you pack any dependencies or automate anything, just that you implement name aliases, so users can satisfy their third party scripts' dependencies without resorting to URLs as names and with the possibility of using one dependency for multiple scripts(say one jQuery 3 for all scripts that require jQuery 3, one jQuery 2 for all that require jQuery 2 etc.).

I know that you are not trying to make FireMonkey a drop-in replacement for the classic userscript managers and very much appreciate your commitment to safety. So, while keeping things safe, this would facilitate a user like me doing an initial setup and then not having to intervene on every update, except, ofcourse, if one third party script changes dependencies say like from jQ2 to jQ3. But that's seldom the case.

**Comment by erosman** [comment]
I am working on some ideas to parse `@requrie` entries and pack JQuery 1, 2, 3 (the latest release of each) at the moment. 

Let's see how it works out ;)

**Comment by Hlsgs** [comment]
> 
> 
> @Hlsgs I am working on some ideas to parse `@require` entries and pack JQuery 1, 2, 3 (the latest release of each) at the moment.
> 
> Let's see how it works out ;)

That sound cool ad would certainly help adoption with "lazyer" users, but there's no way you'll ever goind to be able to cover anything more that jQ, so please leave this open/keep it in mind. Thank you!

**Comment by erosman** [comment]
@Hlsgs Updated the first post... **@require URL**

**Comment by erosman** [comment]
v1.24 Added **GM.addStyle/GM_addStyle**

**Comment by Hlsgs** [comment]
@erosman I got to testing this and everything works just fine. Great stuff!

Don't know if this qualifies as "popular demand", but `arrive.js` is also present in quite a few of my userscript, both from CDNs `https://cdnjs.cloudflare.com/ajax/libs/arrive/2.4.1/arrive.min.js` and greasyfork `https://greasyfork.org/scripts/21927-arrive-js/code/arrivejs.js`

**Comment by erosman** [comment]
>  `arrive.js` is also present in quite a few of my userscript

It is quite a small library.

These are the considerations;

- Number of scripts that use it (i.e. the demand)
- Recognition by AMO
Some libraries are already recognized (https://github.com/mozilla/dispensary/blob/master/src/hashes.txt)
Others would require review by an admin which blocks auto-approval and delays future updates
- Acceptable source/CDN ([Third Party Library Usage](https://extensionworkshop.com/documentation/publish/third-party-library-usage/))

**Comment by erosman** [comment]
@Hlsgs  I also asked GreasyFork about stats. 
`https://github.com/JasonBarnabe/greasyfork/issues/649`

BTW, are these script for your own use of public?
In both cases, you can install `arrive.js` as a script and then require it (or tell users that they also need to install xyz)

**Comment by erosman** [comment]
Thanks to @JasonBarnabe for providing the data:

8011/31170 (26%) use `@require`.

Top 10 URLs required are:
```
338    http://code.jquery.com/jquery-latest.js
288    http://code.jquery.com/jquery-3.3.1.min.js
288    http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
218    http://code.jquery.com/jquery-latest.min.js
205    https://code.jquery.com/jquery-3.3.1.min.js
174    https://code.jquery.com/ui/1.12.0/jquery-ui.min.js
172    https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js
172    https://greasyfork.org/scripts/368273-msgpack/code/msgpack.js?version=598723 
138    https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
133    http://cdn.bootcss.com/jquery/1.8.3/jquery.min.js
```

**Comment by Hlsgs** [comment]
> 
> 
> @Hlsgs I also asked GreasyFork about stats.
> `https://github.com/JasonBarnabe/greasyfork/issues/649`
> 
> BTW, are these script for your own use of public?
> In both cases, you can install `arrive.js` as a script and then require it (or tell users that they also need to install xyz)

Sorry for the late reply. I am not a script developer, so the point is to be able to use scripts that require `arrive.js`. I have several and some are must use for me. I have tried naming a custom script containing arrive `https://cdnjs.cloudflare.com/ajax/libs/arrive/2.4.1/arrive.min.js` and `https://greasyfork.org/scripts/21927-arrive-js/code/arrivejs.js`, but that doesn't work.

**Comment by erosman** [comment]
> Sorry for the late reply. I am not a script developer, so the point is to be able to use scripts that require arrive.js. I have several and some are must use for me. I have tried naming a custom script containing arrive https://cdnjs.cloudflare.com/ajax/libs/arrive/2.4.1/arrive.min.js and https://greasyfork.org/scripts/21927-arrive-js/code/arrivejs.js, but that doesn't work.

@Hlsgs  I have not added support for `arrive.min.js` so using `@require     https://cdnjs.cloudflare.com/.../arrive.min.js` for it will not work now.

I checked GreasyFork stats and 35 user-scripts out of 31,170 (0.1%) use `arrive.js` which is not a considerable number of users.

**What you can do**

- Create a new script
```
// ==UserScript==
// @name          arrive
// @description   Arrive JS Library
// @version       2.4.1
// ==/UserScript==

..... paste the arrive.min.js code here .....
```
- Save the script
- In other scripts that need `arrive` add the following

```
// @require       arrive
```

**Comment by Hlsgs** [comment]
@erosman 
I tried  doing this instead(since you've said that script names can be anything), but it doesn't work:
```
// ==UserScript==
// @name          https://cdnjs.cloudflare.com/ajax/libs/arrive/2.4.1/arrive.min.js
// @description   Arrive JS Library
// @version       2.4.1
// ==/UserScript==



arrive.min.js code
```
The ideea beeing not having to modify the third party script on each update, and this goes back to my original https://github.com/erosman/support/issues/132#issuecomment-580508245

**Comment by erosman** [comment]
> The ideea beeing not having to modify the third party script on each update, and this goes back to my original #132 (comment)

I understand .... at the moment, there are not enough arrive users to warrant packing it with the extension and the extension doesn't have the feature at the moment to get remote scripts (for the reason explained in the Help).

**Comment by aranapatona** [comment]
sorry to hijack but i think it relates:
how to include fuse.js?
// @require     https://cdn.jsdelivr.net/npm/fuse.js@7.1.0

**Comment by erosman** [comment]
> how to include fuse.js?
> // [@require](https://github.com/require) https://cdn.jsdelivr.net/npm/fuse.js@7.1.0

Doesn’t `@require` work?

**Comment by aranapatona** [comment]
Well I tried, but probably doing it wrong. I could not make it work.
(thats probably just me being ignorant)
https://greasyfork.org/en/scripts/538371-duck-ai-chat-search-duckduckgo-s-ai

**Comment by erosman** [comment]
> Well I tried, but probably doing it wrong. I could not make it work.
> (thats probably just me being ignorant)
> https://greasyfork.org/en/scripts/538371-duck-ai-chat-search-duckduckgo-s-ai

That script has `// @run-at      document-load` which is not correct.
AFA `@require`, it is working but I haven’t checked the script itself.
