### ISSUE TITLE
feature request [FoxyTab]: [customizable] keyboard shortcut keys

### ISSUE THREAD

**Issue by meoso** [erosman/support#133]
i'd love the ability to setup custom shortcut keys.
for example, i'd like to choose shortcut keys to:
- de-duplicate tabs
- merge windows
- duplicate a tab

**Comment by erosman** [comment]
The problem is that most of shortcuts are already taken by Firefox which can not be overridden. The available ones would be a 3-key keyboard shortcut which would be even less user-friendly.

**Comment by xim** [comment]
I still think it means sense, especially if you want to do the same options to several tabs. I'd be a heavy user of this feature.

**Comment by nerdCopter** [comment]
i would `ctrl-alt-shift-D` --> `dedupe`,  and
 `ctrl-alt-shift-S` --> `sort`, all day long 🤷‍♂️

**Comment by erosman** [comment]
Previously: #62 

In v2.16

- Added Context-menu to Toolbar Icon
- Added Keyboard Shortcuts option
