### ISSUE TITLE
[FireMonkey] Add TLD support

### ISSUE THREAD

**Issue by erosman** [erosman/support#137]
**TLD**  _(v1.25+)_

A TLD (case-insensitive) wildcard can be used and _FireMonkey_ will automatically generate a list of most common country TLD `@matches`. Due to the extra Firefox API processing for many `@matches`, it is best to use it only when necessary.

```
.com     .au      .br      .ca      .ch      .cn      .co.uk
.de      .es      .fr      .in      .it      .jp      .mx
.nl      .no      .pl      .ru      .se      .uk      .us
```

__`*://*.example.TLD/*` (general use)__
```
*://*.example.com/*     *://*.example.au/*      *://*.example.br/*
*://*.example.ca/*      *://*.example.ch/*      *://*.example.cn/*
*://*.example.co.uk/*   *://*.example.de/*      *://*.example.es/*
*://*.example.fr/*      *://*.example.in/*      *://*.example.it/*
*://*.example.jp/*      *://*.example.mx/*      *://*.example.nl/*
*://*.example.no/*      *://*.example.pl/*      *://*.example.ru/*
*://*.example.se/*      *://*.example.uk/*      *://*.example.us/*
```
**.amazon.TLD (domain specific)**
```
.amazon.ca      .amazon.cn      .amazon.co.jp   .amazon.co.uk
.amazon.com     .amazon.com.au  .amazon.com.br  .amazon.com.mx
.amazon.com.sg  .amazon.com.tr  .amazon.de      .amazon.es
.amazon.fr      .amazon.in      .amazon.it      .amazon.nl
```
**.ebay.TLD (domain specific)**
```
.ebay.at        .ebay.be        .ebay.ca        .ebay.ch        .ebay.cn
.ebay.co.th     .ebay.co.uk     .ebay.com.au    .ebay.com.cn    .ebay.com.hk
.ebay.com.my    .ebay.com.sg    .ebay.com.tw    .ebay.com       .ebay.de
.ebay.dk        .ebay.es        .ebay.fi        .ebay.fr        .ebay.gr
.ebay.hu        .ebay.ie        .ebay.in        .ebay.it        .ebay.nl
.ebay.no        .ebay.ph        .ebay.ph        .ebay.pl        .ebay.ru
.ebay.vn
```

**.google.TLD (domain specific)**
```
.google.ae      .google.al      .google.am      .google.as
.google.at      .google.az      .google.ba      .google.be
.google.bf      .google.bg      .google.bi      .... etc
```

Let me know if additional items are needed.

**Comment by kekkc** [comment]
Advertising a bit for https://bugzilla.mozilla.org/show_bug.cgi?id=1315558

BTW: as a short list I use the following regex:
`const TLDs =  'ac(?:ademy)?|accountants|active|actor|ad|ae(?:ro)?|af|ag(?:ency)?|ai(?:rforce)?|al|am|an|ao|aq|ar(?:chi)?|army|arpa|as(?:ia)?|associates|at(?:torney)?|au(?:dio)?|autos|aw|ax(?:a)?|az|ba(?:r(?:gains)?)?|bayern|bb|bd|be(?:er)?|berlin|best|bf|bg|bh|bi(?:d)?|bike|bio|biz|bj|black(?:friday)?|blue|bm(?:w)?|bn|bo(?:utique)?|br(?:ussels)?|bs|bt|build(?:ers)?|buzz|bv|bw|by|bz(?:h)?|ca(?:b)?|camera|camp|cancerresearch|capetown|capital|cards|care(?:er(?:s)?)?|cash|cat(?:ering)?|cc|cd|center|ceo|cf|cg|ch(?:eap)?|christmas|church|ci(?:tic)?|city|ck|cl(?:aims)?|cleaning|clinic|clothing|club|cm|cn|co(?:des)?|coffee|college|cologne|com(?:munity)?|company|computer|condos|construction|consulting|contractors|cooking|cool|coop|country|cr(?:edit(?:card)?)?|cruises|cu(?:isinella)?|cv|cw|cx|cy|cz|dance|dating|de(?:als)?|degree|democrat|dental|dentist|desi|diamonds|digital|direct(?:ory)?|discount|dj|dk|dm|dnp|do(?:mains)?|durban|dz|ec|edu(?:cation)?|ee|eg|email|engineer(?:ing)?|enterprises|equipment|er|es(?:tate)?|et|eu(?:s)?|events|exchange|expert|exposed|fail|farm|feedback|fi(?:nance)?|financial|fish(?:ing)?|fitness|fj|fk|flights|florist|fm|fo(?:o)?|foundation|fr(?:ogans)?|fund|furniture|futbol|ga(?:l(?:lery)?)?|gb|gd|ge(?:nt)?|gf|gg|gh|gi(?:ft)?|gives|gl(?:ass)?|global|globo|gm(?:o)?|gn|gop|gov|gp|gq|gr(?:aphics)?|gratis|green|gripe|gs|gt|gu(?:ide)?|guitars|guru|gw|gy|hamburg|haus|hiphop|hiv|hk|hm|hn|holdings|holiday|homes|horse|host|house|hr|ht|hu|id|ie|il|im(?:mobilien)?|in(?:dustries)?|info|ink|institute|insure|int(?:ernational)?|investments|io|iq|ir|is|it|je(?:tzt)?|jm|jo(?:bs)?|joburg|jp|juegos|kaufen|ke|kg|kh|ki(?:m)?|kitchen|kiwi|km|kn|koeln|kp|kr(?:ed)?|kw|ky|kz|la(?:nd)?|lawyer|lb|lc|lease|li(?:fe)?|lighting|limited|limo|link|lk|loans|london|lotto|lr|ls|lt|lu(?:xe)?|luxury|lv|ly|ma(?:ison)?|management|mango|market(?:ing)?|mc|md|me(?:dia)?|meet|melbourne|menu|mg|mh|miami|mil|mini|mk|ml|mm|mn|mo(?:bi)?|moda|moe|monash|mortgage|moscow|motorcycles|mp|mq|mr|ms|mt|mu(?:seum)?|mv|mw|mx|my|mz|na(?:goya)?|name|navy|nc|ne(?:t)?|neustar|nf|ng|nhk|ni(?:nja)?|nl|no|np|nr(?:w)?|nu|nyc|nz|okinawa|om|onl|org(?:anic)?|ovh|pa(?:ris)?|partners|parts|pe|pf|pg|ph(?:oto(?:graphy)?)?|photos|physio|pics|pictures|pink|pk|pl(?:ace)?|plumbing|pm|pn|post|pr(?:ess)?|pro(?:ductions)?|properties|ps|pt|pub|pw|py|qa|qpon|quebec|re(?:cipes)?|red|rehab|reise(?:n)?|ren(?:tals)?|repair|report|republican|rest|reviews|rich|rio|ro(?:cks)?|rodeo|rs|ru(?:hr)?|rw|ryukyu|sa(?:arland)?|sb|sc(?:b)?|schmidt|schule|scot|sd|se(?:rvices)?|sexy|sg|sh(?:iksha)?|shoes|si(?:ngles)?|sj|sk|sl|sm|sn|so(?:cial)?|software|sohu|solar|solutions|soy|space|sr|st|su(?:pplies)?|supply|support|surf|surgery|suzuki|sv|sx|sy(?:stems)?|sz|tattoo|tax|tc|td|technology|tel|tf|tg|th|tienda|tips|tirol|tj|tk|tl|tm|tn|to(?:day)?|tokyo|tools|town|toys|tp|tr(?:ade)?|training|travel|tt|tv|tw|tz|ua|ug|uk|university|uno|us|uy|uz|va(?:cations)?|vc|ve(?:gas)?|ventures|versicherung|vet|vg|vi(?:ajes)?|villas|vision|vlaanderen|vn|vodka|vote|voting|voto|voyage|vu|wang|watch|webcam|website|wed|wf|wien|wiki|works|ws|wtc|wtf|xn--3bst00m|xn--3ds443g|xn--3e0b707e|xn--45brj9c|xn--4gbrim|xn--55qw42g|xn--55qx5d|xn--6frz82g|xn--6qq986b3xl|xn--80adxhks|xn--80ao21a|xn--80asehdb|xn--80aswg|xn--90a3ac|xn--c1avg|xn--cg4bki|xn--clchc0ea0b2g2a9gcd|xn--czr694b|xn--czru2d|xn--d1acj3b|xn--fiq228c5hs|xn--fiq64b|xn--fiqs8s|xn--fiqz9s|xn--fpcrj9c3d|xn--fzc2c9e2c|xn--gecrj9c|xn--h2brj9c|xn--i1b6b1a6a2e|xn--io0a7i|xn--j1amh|xn--j6w193g|xn--kprw13d|xn--kpry57d|xn--kput3i|xn--l1acc|xn--lgbbat1ad8j|xn--mgb9awbf|xn--mgba3a4f16a|xn--mgbaam7a8h|xn--mgbab2bd|xn--mgbayh7gpa|xn--mgbbh1a71e|xn--mgbc0a9azcg|xn--mgberp4a5d4ar|xn--mgbx4cd0ab|xn--ngbc5azd|xn--nqv7f(?:s00ema)?|xn--o3cw4h|xn--ogbpf8fl|xn--p1ai|xn--pgbs0dh|xn--q9jyb4c|xn--rhqv96g|xn--s9brj9c|xn--ses554g|xn--unup4y|xn--wgbh1c|xn--wgbl6a|xn--xkc2al3hye2a|xn--xkc2dl3a5ee0h|xn--yfro4i67o|xn--ygbi2ammx|xn--zfr164b|xxx|xyz|yachts|ye|yokohama|yt|za|zm|zone|zw';`

To be able to get a correct hostname (TLD aware), I used some code from adblock (guess there's nothing existing that is more optimized for speed):
https://hg.adblockplus.org/adblockpluscore/file/tip/lib/url.js
https://hg.adblockplus.org/adblockpluscore/file/1a8ef89c04ad/data/publicSuffixList.json

```
function getDomain(hostname) {
	let bits = hostname.split(".");
	let cutoff = bits.length - 2;
	for (let i = 0, bitsLen = bits.length; i < bitsLen; i++){
		let offset = publicSuffixes[bits.slice(i).join(".")];
		if (typeof offset != "undefined"){
			cutoff = i - offset;
			break;
		}
	}
	if (cutoff <= 0) return hostname;
	return bits.slice(cutoff).join(".");
}
```
 
```
 publicSuffixes = {
    "0.bg": 1,
    "0emm.com": 2,
    "1.bg": 1,
    "12hp.at": 1
...
}

```

Concerning speed: this should be more than 200.000 urls parsed per second on a older PC. I parse this PSL usually for every link on a page (however I cannot find the benchmark github page any more that compared the different URL libraries). 

Overall, it would be awesome if FF would offer an option to parse it's internal PSL. Currently there's no easy way to get a TLD of a domain directly. Even https://developer.mozilla.org/en-US/docs/Web/API/URL is not TLD aware.

**Comment by erosman** [comment]
I had also asked about TLD support for WebExtension API in [TLD in Match patterns in Permissions](https://bugzilla.mozilla.org/show_bug.cgi?id=1362849).

In FireMonkey, the feature is added to facilitate userScript developers. In reality, only a few major domains (google, ebay, amazon) use multiple ccTLD and even then, they do not span the whole 1500+ available TLD.

FireMonkey uses the userScript API and the API only allow Match Pattern. Manually processing the URL would not be possible.

**Comment by erosman** [comment]
v1.25
Added TLD wildcard for @matches
