### ISSUE TITLE
Feature: Global Excludes (or easy temporary deactivation of FM)

### ISSUE THREAD

**Issue by kekkc** [erosman/support#138]
Hi,

are there any plans to add support for global excludes (sites where generally all scripts are deactivated)? 

For that matter I also realized it would be helpful to be able to deactivate FM from the icon with one click (even if it's just to test quickly if an error on a site is caused by a faulty userscript).

Didn't find any isses / feature requests for this & I guess FM should be lightweight, so I'm not sure if this was already considered.

Greetz

**Comment by erosman** [comment]
> are there any plans to add support for global excludes (sites where generally all scripts are deactivated)?

I have been thinking about persistent user preferences for scripts (similar to GM include/exclude `https://github.com/greasemonkey/greasemonkey/issues/2728`)

> For that matter I also realized it would be helpful to be able to deactivate FM from the icon with one click

Deactivating/reactivating FM completely, can be resource intensive for many scripts. Furthermore, once deactivated, any page that has user-script must be reloaded for the script to start working.

However, I have been thinking about deactivating script on a single tab temporarily. I have to see if it is possible or not without reloading.

**Comment by erosman** [comment]
I checked with Firefox engineers and it is not possible to disable a script on a single tab :(

**☰ User matches & excludeMatches (v1.25+)**

Persistent user matches & excludeMatches (one per line using Match Patterns) can be set for each script to supplement script's matches & excludeMatches.

**Comment by kekkc** [comment]
I thought this is done already: clicking on the FM icon and clicking on the blue hook to deactivate the script (at least the GUI suggests that the script is then deactivated for this tab). Is it not an option to do this for all scripts for a certain list of domains (and activate the scripts again if the tab / focus is changed)?

If this is too dirty, it might be a possibilty to simply append some exclude matches in the background (withouth showing it to the user or in the code) based on a global exclude list for all scripts. I think GM uses sth. similar in the background.

Possibility would be to exclude scripts e.g. on onlinebanking sites where usually no userscript at all is wanted.

**Comment by erosman** [comment]
> I thought this is done already: clicking on the FM icon and clicking on the blue hook to deactivate the script (at least the GUI suggests that the script is then deactivated for this tab). 

That blue ✔ is the same as ☑ Enable on scripts. It will enable/disable the script globally everywhere. The tabs that already have the script, will not change until tab is reloaded. It is not possible to remove the script after it is injected. 

> it might be a possibility to simply append some exclude matches in the background (without showing it to the user or in the code)

It will be possible with the new User matches & excludeMatches (v1.25+) but that is  per script, not for all scripts globally.

> based on a global exclude list for all scripts. I think GM uses sth. similar in the background.
> Possibility would be to exclude scripts e.g. on onlinebanking sites where usually no userscript at all is wanted.

That is possible to do as a new feature. I have to see.
Do other script mangers have global exclude?!

**Comment by kekkc** [comment]
Thx for the info ;) BTW: I know about https://github.com/greasemonkey/greasemonkey/issues/2843 (but looking at the code it was quite some magic what arantius did there, doesn't look very simple)

**Comment by erosman** [comment]
TBH, it is simple enough to add global exclude to FireMonkey. ;)

I am thinking to do it for **scripts** only (and not for CSS) !!??

**Comment by kekkc** [comment]
that would be amazing.

>I am thinking of doing it for scripts only (and not for CSS) !!??
Although I don't use CSS I verified the current script managers:
- GM: global excludes for scripts
- TM: global excludes for scripts (positive & negative list)
- VM: global excludes for scripts
(- USI: global CSS)

So I guess there's no big demand for CSS (worst thing that can happen is that some elements get hidden and that should be transparent).

**Comment by erosman** [comment]
> So I guess there's no big demand for CSS (worst thing that can happen is that some elements get hidden and that should be transparent).

Yes... I dont think there would be a security risk as such. I can add it later if there is a demand.

> TM: global excludes for scripts (positive & negative list)

Is that global exclude & global include?!

**Comment by kekkc** [comment]
>Is that global exclude & global include?!
![Unbenannt](https://user-images.githubusercontent.com/6283064/73958674-8d745980-4908-11ea-963c-139765f7984e.PNG)

Not really self-explanatory, tested as: 
- if a page filter mode "blacklist" is selected, no scripts are executed on the sites on the blacklist 
- if a page filter mode "whitelist" is selected, scripts are only executed on the sites on the whitelist

**Comment by erosman** [comment]
I have added **Global Script Exclude Matches** (global everywhere) and **User Matches** & **User Exclude Matches** (per script).

They are all **Match Pattern** (hence the names).

I may do **Global CSS Exclude Matches** later if there is a popular demand for it.

**Comment by erosman** [comment]
There is an issue with updating **Global Script Exclude Matches**.

The setting is implemented at script registration. Therefore, if a change has been made to the **Global Script Exclude Matches**, it will not have any effect until the script is re-registered (i.e. after disable/enable or Firefox restart).

Applying **Global Script Exclude Matches** changes would mean disabling all enabled scripts and re-enabling them again. Script that are already on open tabs will be removed but wont get re-injected until tab is reloaded. 
That takes a lot of resources....!!??

**Comment by kekkc** [comment]
Wow, you're amazingly fast.

>Applying Global Script Exclude Matches changes would mean disabling all enabled scripts and re-enabling them again

Wouldn't it be enough to simply include a text "settings take effect after the browser restart" (even FF handles it that way for some internal about:config settings)?

**Comment by erosman** [comment]
At the end, I decided to unregistered the script when **Global Script Exclude Matches** changes.

Result is that scripts are removed from all pages and on new tab (or reload) new setting will take effect.

**Comment by kekkc** [comment]
Pretty cool, cannot wait for the next version

**Comment by kekkc** [comment]
>I checked with Firefox engineers and it is not possible to disable a script on a single tab :(

BTW: there's already a bug for this (I anyhow wonder, why they didn't replace tabs.executeUserScript() with userscripts completely)
https://bugzilla.mozilla.org/show_bug.cgi?id=1516478

**Comment by erosman** [comment]
v1.25
    Added persistent User Matches & User Exclude Matches
    Added Global Script Exclude Matches
