### ISSUE TITLE
[Historia] Decrease permissiveness.

### ISSUE THREAD

**Issue by geeknik** [erosman/support#139]
Would it be possible to remove the `Access your data for all websites` permission from Historia? Seems pretty excessive just to remove some items from the Firefox history. Thank you.

**Comment by erosman** [comment]
I will add Permissions Explanation to its description (like my other add-ons)

Any add-on that has the permission "`<all_urls>`" will show on AMO as **Access your data for all websites**. However, that is limited to the APIs that addon uses.

Historia for deleting data needs to access:
- download for all websites
- history for all websites
- cookies for all websites

Sadly the Permissions display doesn't clarify which data is given access to.

**Comment by geeknik** [comment]
As a Firefox developer, I understand the permissions perfectly, I'm just curious why your extension needs `Access your data for all websites` when the [Clear recent browsing history, cookies, and related data](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_clear-recent-browsing-history-cookies-and-related-data) permission would be perfectly acceptable.

**Comment by erosman** [comment]
While [history](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/history) API does not require **host permissions**, [cookies](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies) API requires **host permissions**

> To use this API, you need to include the "cookies" API permission in your manifest.json file, as well as host permissions for the sites whose cookies you need to access.
