### ISSUE TITLE
[FoxyTab] Save to PDF function only saves partial pages

### ISSUE THREAD

**Issue by mlawren** [erosman/support#14]
As the subject says, the resulting PDF is incomplete. It looks like it is divided into multiple pages, but only the first "part/page" has content.

**Comment by erosman** [comment]
Thank you. I will test it and fix the issue.

**Comment by erosman** [comment]
Sorry for the delay..... I was working on other updates.

I tested now (FF65) and the PDF saves the entire page and in multiple pages if they become more than 1 page.

TBH, FoxyTab doesn't do anything in the PDF creation and all is done by Firefox.

Which version o FoxyTab, Firefox and which OS are you using?
Which page did it have problem with?
