### ISSUE TITLE
FM: Editor gets messed up when pasting ASCII text

### ISSUE THREAD

**Issue by kekkc** [erosman/support#140]
Hi all,

if a script is edited in the editor (FM Options) and some text with new lines & line breaks is pasted, the editor becomes messed up:
![lineNumbers](https://user-images.githubusercontent.com/6283064/74049507-8ca8f980-49d4-11ea-934d-03e72a6451c6.PNG)

The editor is refreshed only when clicking outside the editor or focussing another window. But usually someone just clicks anywhere else in the code. I think the editor should be refreshed directly after paste (I wasn't even aware that FM can display line numbers for pasted text until writing this issue here).

That the editor is not refreshed directly leads to a similar issue. If a new script is created, then everything selected & deleted (CTRL+A, DEL) and a very long line is pasted, no buttons are shown at the left side and it looks as if everything "froze".
[long line.txt](https://github.com/erosman/support/files/4172150/long.line.txt)

Furthermore, only ASCII input should be pasted. I don't see the sense to be able to paste pictures (that are not saved anyway).

Greetz

**Comment by erosman** [comment]
I wrote the syntax highlighting myself and it is a tiny script. It is not as good as CodeMirror that for example GM use but it doesn't use as much resources either.

The FM editor is only good for basic editing. I usually edit my code in a proper editor and then import or paste it in FM.

The reason that the issue happens is that the syntax highlighter creates many `div` & `span` and counter counts the `div`. When new text is entered, until it refreshes it (when you click outside i.e. losing focus), the display is raw and not processed.

CodeMirror processes the display on each character input which makes the editor look good and fast but uses a lot of resources to process.

> I think the editor should be refreshed directly after paste

It is... there is a paste listener which acts on 'paste'. I don't get any issues when pasting `long line.txt`

**Comment by kekkc** [comment]
Thx, using it also mostly for copy & paste (apart from small adjustments if I want to test sth. quickly).

>There is a paste listener which acts on 'paste'. I don't get any issues when pasting long line.txt
Guess that this paste listener is somehow not working for me. Illustration attached, scrollbar is at the very left side and there are no icons at the top. Nothing gets refreshed, until I clicked outside the window to stop the recording.
[2020-02-07 20-23-41.zip](https://github.com/erosman/support/files/4172601/2020-02-07.20-23-41.zip)

**Comment by erosman** [comment]
Ah.... that is a different case ....

FM edit area MUST have the metablock in order to know how to make the highlight (JS or CSS).

Deleting the metablock causes error. You should normally get an error notification. I will test that.

**Comment by kekkc** [comment]
Fixed in actual version ;)
