### ISSUE TITLE
[Feature Request]Direct Install scripts loaded into tab from github jsdelivr and so on

### ISSUE THREAD

**Issue by ivysrono** [erosman/support#143]
For example:
https://github.com/the1812/Bilibili-Evolved#%E5%A4%87%E7%94%A8%E5%AE%89%E8%A3%85%E6%BA%90

**Comment by erosman** [comment]
OK.... I will work on it.

Please note that the actual URL is the raw version eg:

```
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/bilibili-evolved.user.js
https://cdn.jsdelivr.net/gh/the1812/Bilibili-Evolved@master/bilibili-evolved.user.js
```

Would the update URL be the same? Or should the update URL be set according to the `@updateURL `  `@downloadURL`?

In above script, even when installing from github, the `@downloadURL` shows as `cdn.jsdelivr.net`.


Is **jsDelivr** also a user-script repository? or just a library CDN?

BTW, the @require on that script:

```
// supported
// @require      https://code.jquery.com/jquery-3.4.0.min.js

// Not supported
// @require      https://cdn.jsdelivr.net/npm/lodash@4.17.15/lodash.min.js
// @require      https://cdn.bootcss.com/jszip/3.1.5/jszip.min.js
// @require      https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js
// @require      https://unpkg.com/vuex@3.1.2/dist/vuex.js
```

**Comment by ivysrono** [comment]
1. Yes, the actual URL is right.
2. the update URL be set according to the @updateURL @downloadURL.
3. IMO, jsDelivr is a library CDN.

**Comment by erosman** [comment]
v1.27

Added Direct Install option for files loaded into tab ending in <code>*.user.js</code>
Added Direct Install option for files loaded into tab for `https://raw.githubusercontent.com/*/*.user.js` <i>(work-around for bug 1411641)</i>
