### ISSUE TITLE
[FireMonkey] Turning Universal Bypass into a userscript

### ISSUE THREAD

**Issue by MikeBlueberry** [erosman/support#146]
Hi erosman, thank you for being such a wizard.

Apologies beforehand if these are dumb questions, I'm just a simpleton.

1. Is it possible to turn Tim's [Universal Bypass](https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/) into a userscript? 
2. Or, if that is not possible, turn [Skip Redirect](https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/) into a userscript? 
3. I found [Just Redirect](https://greasyfork.org/en/scripts/37105-just-redirect/code) on greasyfork but it gives an error in FM?

**Comment by erosman** [comment]
No problem :)


> Is it possible to turn Tim's Universal Bypass into a userscript?

User-scripts work inside a page while add-ons can work directly with browser and handle/intercept Web request.

It is possible to write a user-script that is good-enough for the purpose of skiping link shroteners but a good add-ons will be more powerful.
As far the aforementioned, I have not tested it but after a quick glance at the code, it seems the same functionality could have been done with a lot less code.

> Or, if that is not possible, turn Skip Redirect into a userscript?

Similar to what I said above regarding user-script vs add-on. However, this add-on has a much slimmer code.

> I found Just Redirect on greasyfork but it gives an error in FM?

That is a simple script which can take care of some the redirects. A more complex user-script can handle more situations.

The error is due to the following which is easily fixed.

```
// @include         /^https?://.*https?://.*/
```


here is how : (I only changed the cause of error)

```
// ==UserScript==
// @name            Just redirect!
// @description     Go to the destination url without any page in the middle attacks.
// @author          tumpio
// @oujs:author     tumpio
// @namespace       tumpio@sci.fi
// @homepageURL     https://openuserjs.org/scripts/tumpio/Just_Redirect
// @supportURL      https://github.com/tumpio/gmscripts
// @include         *://*/*http://*
// @include         *://*/*https://*
// @run-at          document-start
// @grant           none
// @version         0.1
// ==/UserScript==

var url = window.location.href;
var i = url.search(/.https?:\/\//);
window.location.replace(url.substring(i + 1));
```

**Comment by accounts1github** [comment]
Thank you so much for getting back to me, erosman, you're such a stand-up guy and I only knew about your work when you were mentioned in 12bytes.org. The guy there mentions FireMonkey as the only add-on of this kind he trusts. I'm sure I'm leaving behind all the nuances and big/little details of the magic behind the scenes you do, but it's good you're helping the common folk ^_^

Having contacted Tim of Universal Bypass, he said something along the lines of what you did (in one line), but he didn't explained as you did, he just said "mine's better than a script". It's still a great plugin, and I'm either installing it, or going with Skip Redirect, as you mentioned is lighter on the code, and I'm all for minimalism/efficiency.

The way you corrected this code:
`// @include         /^https?://.*https?://.*/`

Into this:
`// @include         *://*/*http://*
// @include         *://*/*https://*`

[...] is already a good start for me to go through other scripts that weren't working with FireMonkey and changing those lines to see if they work. There are probably other things to lookout for when correcting those GM/TM/VM into FireMonkey, like I noticed there is the @include and the @match that seem similar in the scripts I've seen, sometimes the former is used, other times the latter is used. I don't think I'll quite get there on my own, but maybe I will gain the courage to go through your help files and see if I understand something of it.

Much appreciated the time and effort you're using (and on a Sunday of all days) to help a silly middle age guy.

**Comment by erosman** [comment]
You are welcome :)

> I noticed there is the `@include` and the `@match` that seem similar in the scripts I've seen, sometimes the former is used

`@match` is more restrictive and thus more robust.
`@include` is less restrictive and thus can match unintended targets.

FireMonkey uses the dedicated & more secure userScript API which **only** works with `@match`. FireMonkey converts some of the `@include` to `@match` but it is not possible to convert them all automatically (hence the errors). It is often possible to convert them though but a bit of knowledge and/or assistance is needed.
