### ISSUE TITLE
Feature Request: FM show number of active scripts

### ISSUE THREAD

**Issue by kekkc** [erosman/support#148]
Hi,

it would be awesome if FM would show the number of active scripts on the page and not the overall number (i.e. excluding deactivated scripts & user / global exclude).

Greetz

**Comment by erosman** [comment]
That is possible. It is good to have more feedback to decide which one is preferred.

I cant recall, how do other script managers do? :thinking:

**Comment by Maryse47** [comment]
+1 for this one. ViolentMonkey shows only active scripts number in toolbar badge. I think showing total number of active and inactive scripts may be confusing especially if user has many of those.

**Comment by erosman** [comment]
It is done for v1.29

**Comment by erosman** [comment]
v1.29 uploaded
