### ISSUE TITLE
[FoxyTab] [🐞 bug] Failure to auto-open in matching container (based on domain patterns) during restore session

### ISSUE THREAD

**Issue by metasean** [erosman/support#149]
If Firefox is closed, with restore session selected and when there are tabs that match a domain pattern for FoxyTab Containers, when those tabs are subsequently restored, they are *_not_* restored into their corresponding container.

Replication:
1. set Firefox to "Restore previous session" (on about:preferences pages)
2. create a container (e.g. an "Amazon" container)
3. create a new FoxyTab Container rule to trigger opening in that new container (e.g. `*.amazon.com` to open in the "Amazon" container)
4. open a new tab and navigate somewhere that the new rule will apply (e.g. https://amazon.com)
5. verify the new tab is now in the appropriate container
6. quit Firefox (without closing the new tab)
7. reopen Firefox
8. confirm that the new tab is no longer in a container :-( when it _should_ be in a specific container based on the FoxyTab's Container ruleset.

**Comment by erosman** [comment]
Did you "Save" after making changes?
