### ISSUE TITLE
[FoxyTab] Options > Help still points to Mozilla's Discourse instance

### ISSUE THREAD

**Issue by mlawren** [erosman/support#15]
This GitHub repository exists because you can't get into the Discourse instance... but the Options>Help>Support link still points to https://discourse.mozilla.org/t/support-foxytab/. I don't know if the change is going to be permanent...

**Comment by erosman** [comment]
Besides the new login issues in discourse, I think it would be easier to do it here where issues can have separate topics (not all in one as in discourse).

I will be changing the `Options>Help>Support link` in new updates of my add-ons.
