### ISSUE TITLE
[Firemonkey] exported JS is not binary compatible to original file (line breaks added, converted to mac)

### ISSUE THREAD

**Issue by kekkc** [erosman/support#150]
Hi,

the export function is "transforming" a script and is not exporting the original file. Use case:

1. an original JS is encoded as "Windows (CR LF) / ANSI" and contains:
```
/*
==UserScript==
@name			testencoding
@match			*
@version        1.0
==/UserScript==
*/

asdf();

bsdf();

```
2. exporting this JS again results in a file encoded as "Macintosh (CR) / ANSI" and contains:
```
/*

==UserScript==

@name			testencoding

@match			*

@version        1.0

==/UserScript==

*/



asdf();



bsdf();



```

For every line, there's an additional line break added (CR LF). In addition, the original filename is changed to the script name within the metablock data (that might be intended).

Original file & exported version:
[testfiles.zip](https://github.com/erosman/support/files/4245690/testfiles.zip)

**Comment by erosman** [comment]
I fixed the extra new lines... but the file is still saved as ANSI.
I am looking into forcing utf-8

**Comment by kekkc** [comment]
>I am looking into setting utf-8
Would propably don't convert encodings, seems there are common issues:
https://stackoverflow.com/questions/19492846/javascript-to-csv-export-encoding-issue
https://stackoverflow.com/questions/42462764/javascript-export-csv-encoding-utf-8-issue/42466254

BTW: this is also not really consistent with Github. If the "raw file" is downloaded from the Github Website, the line feed is Unix. But if Github Desktop is used, the files are still maintained with the windows line feed, i.e. if those are fetched from remote, they are stored locally as windows. 
GM is not changing anything at all (same encoding, line feed, filename...).

**Comment by erosman** [comment]
> GM is not changing anything at all (same encoding, line feed, filename...).

FM now doesn't change anything in export.
However with the blob, when importing a utf-8 and then exporting, it exports as ANSI :thinking: 

The editor is a different case. Through syntax Highlighting, lines are separated and then rejoined.
I dont know how CodeMirror behaves, Does it keep the line feed as it was?

**Comment by kekkc** [comment]
Didn't find anything regarding utf-8 / ANSI :(

>I dont know how CodeMirror behaves, Does it keep the line feed as it was?
No, just tested in GM. If it's imported as Windows CR LF, it will also export as Windows CR LF. But as soon as sth. is changed in CodeMirror, it will be exported as Unix LF (although I never realized this before).

**Comment by erosman** [comment]
I am thinking about maybe re-writing the Syntax Highlight code :thinking: 

That could solve some of the issues with editing. It may also make it faster!!

I have to see (it is all in my head now.. I have to write the code)

**Comment by kekkc** [comment]
More efficient editor would be fantastic.

BTW: I found an explanation why my files saved as UTF-8 always show as ANSI in Notepad++ (wouldn't use BOM though):

> BOM forces Notepad++ to identify file as UTF-8.
> Make sure that whatever software is consuming these files knows to skip the BOM. Most modern software knows to do it for many years but some systems that retain ancient legacy software pieces may not.
> Without BOM Notepad++ needs to guess the encoding and sometimes it guesses wrong.
> This forum has multiple discussions about this issue and the desire to be able to override this guessing with some default.
> 
> Since ANSI is a subset of UTF-8, in the absence of any special symbol within the file a UTF-8 is also an ANSI file and Notepad++ defaults to ANSI over UTF-8.

https://community.notepad-plus-plus.org/topic/14183/file-always-open-in-ansi-instead-of-utf-8

**Comment by erosman** [comment]
v1.30 uploaded
