### ISSUE TITLE
[Feature Request] Support local storage values

### ISSUE THREAD

**Issue by Hlsgs** [erosman/support#151]
I can see how `GM_registerMenuCommand`, `GM_getValue`, `GM_setValue` etc. would be a bit too much, but allowing for users to manually set values could prove useful.

**Comment by erosman** [comment]
Can you explain a bit more?
All those are supported.

**Comment by Hlsgs** [comment]
Right, my bad!
However, [this script](https://greasyfork.org/en/scripts/372366-instagram-source-opener/code) that uses `registerMenuCommand` to add two options to set custom keybindings always fails to save said values, while working properly in the ubiquitous script managers.

**Comment by erosman** [comment]
I had a quick look but didn't find the issue. It takes time to find the reason as I am not familiar with the script. Maybe the script dev can point out the problem!??
