### ISSUE TITLE
[Firemonkey] <all_urls> sometimes not properly registered

### ISSUE THREAD

**Issue by kekkc** [erosman/support#152]
Hi,

seems that for newer versions @match <all_urls> doesn't work anymore (clicking on new script and adjusting the following values within the FM editor):

```
/*
==UserScript==
@name asdf
@match <all_urls>
@version        1.0
==/UserScript==
*/
```
In the FM menu this will show up as: `*://allurls>/`

However, this was not the case for all my scripts (just for new ones). Was able to reproduce it with a FF Developer version & clean reinstall, but if someone can confirm that behavior, it would be great.

**Comment by erosman** [comment]
You are right. I have added new include to match conversion patterns and one of them is catching `<all_urls>`.
Fixed in v1.30

**Comment by kekkc** [comment]
Awesome.

BTW: no more issues from me (migrated all my scripts already to FM), absolutely fantastic user script manager, awesome support here / community, help documentation. Many thanks to you erosman, keep up the great work (as a next step maybe a donation button can be added & Moz should make FM a recommended extension in AMO) ;)

**Comment by erosman** [comment]
Thank you for your kind comment :+1: 

> Moz should make FM a recommended extension in AMO

I already have 2 extensions in the recommended extension and more might be misunderstood. :disappointed:

**Comment by erosman** [comment]
v1.30 uploaded
