### ISSUE TITLE
Copy page title and URL as …

### ISSUE THREAD

**Issue by grahamperrin** [erosman/support#154]
### Enhancement request

From <https://new.reddit.com/r/firefox/comments/fbu0io/-/>: 

![image](https://user-images.githubusercontent.com/192271/75628513-abfd0600-5bd1-11ea-8229-7fd9321f9c1b.png)

– a submenu of options for what's to be copied. 

I'd love an extension such as FoxyTab to gain this capability. 

TIA

----

CoLT source code: https://github.com/jgbishop/colt

**Comment by grahamperrin** [comment]
Praise for legacy CoLT (in the screenshot above): 

[Download of the Day: Copy Link Text Firefox extension](https://lifehacker.com/download-of-the-day-copy-link-text-firefox-extension-177804) (2006-06-01)

[Blogging With Split Browser Firefox Extension « Lorelle on WordPress](https://lorelle.wordpress.com/2007/06/29/blogging-with-split-browser-firefox-extension/) (2007-06-29): 

> As part of my [Web Browser Guide for Bloggers](http://www.blogherald.com/2007/05/21/web-browser-guide-for-bloggers/) series on the [Blog Herald](http://www.blogherald.com/), I explored a lot of new Firefox Extensions to improve my blogging skills and efficiency. …

> … my favorite Firefox Extension Copy Link Text (CoLT). …

[The Lifehacker Editors' Favorite Software and Hardware](https://lifehacker.com/the-lifehacker-editors-favorite-software-and-hardware-399296) (2008-07-27)

> … must-have Firefox extensions include: … CoLT …

**Comment by erosman** [comment]
That is possible if there is  popular demand for it. For the time being, if one form is the one you use most, you can use the Custom Copy.

There are a number of enhancement that have been done and/or are planned for FoxyTab but I have been mostly busy with FireMonkey updates.

Incidentally, there was another user recently who complained about too many options (i.e. drop-down submenus) so users' preferences vary.

**Comment by touwys** [comment]
Most frequently, I would share either single, or multiple, hyperlinked tab-titles. A new user to Foxytab, I was thus far unable to extract this extremely useful aspect from the Settings.  I also failed to create a custom copy for at least a single hyperlinked title. Therefore, I would be very grateful for any pointers as to how such may be achieved.

Also, are there custom-formatting options other than the given "{ip} {title} {url} {date} {time} \n \t", and where can I learn more about it? Sorry in advance for wherever I am using the incorrect terminology along the way, or post under an irrelevant heading.

Thanks for Foxytab, erosman.

**Comment by erosman** [comment]
@touwys The next upgrade will have more extensive Help file. For example in v2.15 if you want to create link like result you use 
`<a href="{url}">{title}</a>`

Multiple Custom Copy feature is included in v2.16 when it comes out.

Here is a copy of v2.16 Help regarding the Custom Copy (some of the parameters are not available pre-2.16)

<table>
  <caption>Custom Format</caption>
  <thead>
    <tr>
     <th width="30%">Code</th>
     <th>Result</th>
    </tr>
  </thead>
  <tbody>

  <tr><td>{ip}</td><td>Tab IP</td></tr>
  <tr><td>{title}</td><td>Tab tilte</td></tr>
  <tr><td>{url}</td><td>Tab URL</td></tr>
  <tr><td>{hostname}</td><td>e.g. www.example.com</td></tr>
  <tr><td>{date}</td><td>e.g. Fri Mar 20 2020</td></tr>
  <tr><td>{time}</td><td>e.g. 23:15:30</td></tr>
  <tr><td>{yyyy}</td><td>e.g. 2020</td></tr>
  <tr><td>{mm}</td><td>e.g. 03</td></tr>
  <tr><td>{dd}</td><td>e.g. 20</td></tr>
 </tbody>
</table>



<table>
  <caption>Examples</caption>
  <thead>
    <tr>
     <th width="30%">Custom Format</th>
     <th>Result</th>
    </tr>
  </thead>
  <tbody>
  <tr>
   <td>
{title}<br>
<br>
{ip}<br>
({url})<br>
{date} {time}
   </td>
   <td>
Example Title<br>
<br>
100.1.1.250<br>
(http://www.example.com/)<br>
Nov 03 2018 23:26<br>
   </td>
  </tr> 

  <tr>
   <td>
ref: {title} [{url}]<br>
   </td>
   <td>
ref: Example Title [http://www.example.com/]
   </td>
  </tr> 

  <tr>
   <td>
&lt;b&gt;Title:&lt;/b&gt; {title}<br>
<br>
&lt;a href="{url}"&gt;{url}&lt;/a&gt;<br>
   </td>
   <td>
&lt;b&gt;Title:&lt;/b&gt; Example Title<br>
<br>
&lt;a href="http://www.example.com/"&gt;http://www.example.com/&lt;/a&gt;<br>
   </td>
  </tr> 

 </tbody>
</table>

**Comment by touwys** [comment]
Thank you, I appreciate your very quick and precise response very much.

 

All the best to you,

 

Pierre

**Comment by grahamperrin** [comment]
> … I'd love an extension such as FoxyTab to gain this capability. …

https://old.reddit.com/r/firefox/comments/fbu0io/-/fl407d5/?context=1 (after I opened this issue) reminded me of [Link Text and Location Copier](https://addons.mozilla.org/addon/link-text-and-location-copier/). 

@erosman close this issue, if you like.
