### ISSUE TITLE
Conflict with aria2-integration/

### ISSUE THREAD

**Issue by ivysrono** [erosman/support#155]
https://addons.mozilla.org/firefox/addon/aria2-integration/

Violentmonkey is OK。

**Comment by erosman** [comment]
What is the conflict?

**Comment by ivysrono** [comment]
Show download dialog box, not intall tab.

**Comment by erosman** [comment]
Where does it happen?
When loading script into tab or when trying to install from GreasyFork etc?

**Comment by ivysrono** [comment]
https://github.com/ivysrono/iWebExtension/blob/master/userScripts/README.md#pc--mobile

Sometimes FireMonkey gets, sometimes Aria2-intergration gets

**Comment by erosman** [comment]
FireMonkey only listens to file ending '.user.js'
Aria2-intergration shouldn't really listen for these files.

In Firefox, when 2 or more extensions listen to the same thing, then it is a chance which one gets to it first. Extinctions act independently of each other.

It is best to ask Aria2-intergration why they listen to files ending in  '.user.js' which are not meant for download.
