### ISSUE TITLE
[FireMonkey] (Feature request) dumb editor

### ISSUE THREAD

**Issue by ubone** [erosman/support#156]
Can you pls add option for the editor to not be fancy at all, like Leafpad (notepad)?
Just a plain text box with (optional) soft word wrap.

**Comment by erosman** [comment]
Option is already there to disable Syntax Highlighting (although it is changing to a better format in v1.31)

**Comment by erosman** [comment]
v1.31 uploaded
The code section has had many updates. The code without syntax is now displayed in a plain textarea (which is simple and fast)

The controls are here:

![syntax](https://user-images.githubusercontent.com/6458876/76646990-2e41de80-6571-11ea-994b-c225948d47ee.jpg)
