### ISSUE TITLE
[EDIT] Buttons in Tags section not working in Firefox 74

### ISSUE THREAD

**Issue by jscher2000** [erosman/support#157]
Bold, Italic, Underline, etc. do not seem to work in Firefox 74. Find & Replace works.

Mozilla Support thread: https://support.mozilla.org/questions/1281862

**Comment by jscher2000** [comment]
toSource() is no longer available to web content or extensions.

Changing line 155 from

`const processFormat = (Array.isArray(action) ? 'text => ' : '') + action.toSource();`

to

`const processFormat = (Array.isArray(action) ? 'text => '  + JSON.stringify(action) : action.toString() );`

seems to work.

**Comment by erosman** [comment]
Thank you ... I will test it and upload a fix.

**Comment by erosman** [comment]
v1.4 uploaded
Fixed Firefox 74 removal of `Object.toSource()` (quick-fix interim upgrade)

**Comment by jscher2000** [comment]
Awesome, thanks.
