### ISSUE TITLE
[Firemonkey] v1.31 scripts not registered / settings not imported

### ISSUE THREAD

**Issue by kekkc** [erosman/support#158]
Hi,

for me there were a few issues with the latest v1.31:
- after the automatic update all my scripts were no longer registered (not executed on any webpage any more, although shown in FM as active)
- furthermore global excludes / includes were no longer shown in the settings
- after importing old settings from v1.30, global excludes / includes were not imported, also scripts didn't register

Am a little bit lost & tested it in a portable Firefox, too and was at least able to make FM register scripts again sometimes. However, all were reproducable for me with a clean install.

Greetz

**Comment by erosman** [comment]
Thank you for the report. Let me test it out.

Which version of Firefox are you using?
Is there any error?
Check Browser Console: `Ctrl + Shit + j`
Check FireMonkey Console: `about:debugging` -> FireMonkey -> inspect

`about:addons` -> Disable & enable FireMonkey

**Comment by erosman** [comment]
Update: You are right about **Global Script Exclude Matches**
There is an oversight. I will fix it now and upload a new version.

**Comment by erosman** [comment]
v1.32 uploaded
"Fixed an issue with Global Script Exclude Matches"

AFA scripts not registering, let me know after this update.

**Comment by erosman** [comment]
Actually, wait for 1.33
I found another issue. :man_facepalming:

**Comment by erosman** [comment]
v1.33 uploaded

The issue should be fixed now.

**Comment by kekkc** [comment]
Worked, many thanks for the direct fix ;)
