### ISSUE TITLE
[FireMonkey] Pasting code into editor doesn't detect breaklines

### ISSUE THREAD

**Issue by r-a-y** [erosman/support#159]
If I copy and paste some code into the editor, the editor doesn't detect breaklines.

I end up having to manually re-enter the breaklines.

**Comment by erosman** [comment]
Which version of FM?
There was an issue before but got fixed.

Is Syntax on or off?

I just tested in both on/off and it seems fine.

**Comment by r-a-y** [comment]
I'm on FM 1.33 on Firefox 74, Windows 10.

See GIF:

![GIF of breakline issue when pasting](https://user-images.githubusercontent.com/505921/76688922-5bea5e80-6629-11ea-82fb-09340498eb25.gif)

> Is Syntax on or off?
There used to be an option to disable syntax highlighting, but it's no longer in the Settings panel.

**Comment by erosman** [comment]
> There used to be an option to disable syntax highlighting, but it's no longer in the Settings panel.

The controls are here:

![syntax](https://user-images.githubusercontent.com/6458876/76646990-2e41de80-6571-11ea-994b-c225948d47ee.jpg)


I tried the same copy/paste and it is working for me. Where did you copy that text from?

**Comment by r-a-y** [comment]
Ahh! The Syntax option moved to the 3-dots menu!

I find that breaklines and syntax highlighting work after I switch tabs or when I double-click in the editor.

If I disable syntax highlighting, that also works.

**Comment by erosman** [comment]
Now I understand..... The syntax highlighting which results in line-numbers appearing, is set to refresh on `blur`.

It will refresh when you click outside the edit area.
It is documented in the help.

**Comment by r-a-y** [comment]
> It is documented in the help.

Ahh, yes I do see it in the help now!  I think users might get confused though if they do not read the help.

Maybe you can also add an event listener for `paste` as well?
https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event

**Comment by erosman** [comment]
> Maybe you can also add an event listener for paste as well?

There is one already which strips HTML from the paste & one for copy.

The problem is the browsers will copy & paste with HTML if you copy from somewhere with HTML (like another section of the editor with syntax highlight, or a web page).
That then messes the layout (can even break it).

Therefore, there is a listener for copy & paste and it removes the HTML (converts to plain text) when copying or pasting.

As mentioned before, I can run the syntax highlighting code after paste but that would clear the editor and creates a new content. If user types or make another paste while that is happening, it can have unexpected results.

**Comment by r-a-y** [comment]
Ahh, okay.  I moved over from ViolentMonkey and the editor they use [(CodeMirror)](https://github.com/codemirror/CodeMirror) seems to work fine for paste actions.

Not sure if you want to consider implementing CodeMirror as your editor, but thought I'd mention it.

Feel free to close this issue.

**Comment by erosman** [comment]
> Not sure if you want to consider implementing CodeMirror as your editor,

I never use library code in any of my extensions. ;)

Most extensions do use CodeMirror for syntax highlighting though.
While CodeMirror does a great job, and is faster, it is very resource intensive. It has an `input` listener which fires every time a single character is entered. It is also quite large 1mb+ which means a lot code processing for the browser.
Furthermore, it has many syntax language capabilities which are useless for JS/CSS handling extensions.

**Comment by erosman** [comment]
I decided to use CodeMirror. It will be in v1.48
