### ISSUE TITLE
[FoxyImage] Feature request: Reload all images

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [erosman/support#16]
With this menu item you will allowed to reload all images without refreshing a page, if a page failed to load images for an accidental reason.

**Comment by erosman** [comment]
I will add the feature in the next update. It is a hack since I didnt find a proper API.

**Comment by erosman** [comment]
v1.7 is available with Reload Image/All Images

**Comment by KrasnayaPloshchad** [comment]
OK, it’s good. Thank you.
