### ISSUE TITLE
FoxyTab Context Menu + Containers not working

### ISSUE THREAD

**Issue by Aezaeo** [erosman/support#160]
Using Windows 10 and Firefox 74.0

The Context menu does not appear at all, and Ive added sites to container and that doesn't seem to appear neither. I've tried disabling and re-enabling, I've uninstalled and reinstalled. After each disable and uninstall I restarted firefox to see if that would help before reanabling/reinstalling but to no avail.

Any help will be appreciated. I'd really like to try out this addon.

**Comment by erosman** [comment]
Do you have nay other addons that may have a conflict?

When going to Firefox Options (about:preferences) does it show FoxyTab?

![image](https://user-images.githubusercontent.com/6458876/76982264-dfb98900-6950-11ea-85c7-2ca008e2d3a6.png)

**Comment by Aezaeo** [comment]
I have no idea if there are any conflicts, I can test, disable  a few other tab managers I have. And yes, Firefox Options (about:preferences) shows FoxyTab.

**Comment by erosman** [comment]
Try going to `about:debugging` and then FoxyTab
Click on `Inspect` to pen the console

See if there are any errors there.

**Comment by Aezaeo** [comment]
this is what I found under console,  https://i.imgur.com/AQbPk0C.png

**Comment by erosman** [comment]
There is no issues there.

Have you set up container patterns?
Can you delete them and see if there are any issues in the patterns that you are using?

**Comment by Aezaeo** [comment]
I haven't set any container patterns, did a reinstall of the addon and its fresh with all default settings.

**Comment by erosman** [comment]
Was it working before? Or are you new to FoxyTab?

The context-menu is a Tab context-menu which means right-click on the tab.

**Comment by Aezaeo** [comment]
I see. I'm new to FoxyTab. I thought right clicking on a page would bring up the FoxyTab context Menu. The Context Menu is there >.< doh. 

My question now is, "Does it find "All" duplicate tabs?" Or does it only look for a duplicate tab based off the tab u selected?

**Comment by erosman** [comment]
You are welcome :)
