### ISSUE TITLE
[Text MultiCopy] - custom date format

### ISSUE THREAD

**Issue by smaragdus** [erosman/support#162]
I really like [Text MultiCopy](https://addons.mozilla.org/en-US/firefox/addon/text-multicopy/) very much. I use `Custom Copy` with the following format:

```
{text}
{title} 
{url}
{date} {time}
```

The only thing that is not very convenient for me is the date format, in stead of:

`Fri Mar 20 2020 05:50:25`

I prefer:

`2020-03-20 05:50:25`

So I would appreciate if there is an option to specify the date format.

**Comment by erosman** [comment]
There are many standard date formats.

```
standard            Wed Oct 05 2011 16:48:00 GMT+0200 (CEST)
ISO                 2011-10-05T14:48:00.000Z
UTC                 Fri, 02 Feb 1996 03:04:05 GMT
Local               3/20/2020
```

There is also the issue of American date format vs others (i.e mm/dd/yyy vs dd/mm/yyy).

I can maybe add `{yyyy} {mm} {dd}` parameters which means a custom copy like this: :thinking: 

```
{text}
{title} 
{url}
{yyyy}-{mm}-{dd} {time}
```

**Comment by smaragdus** [comment]
@erosman 

Thanks for the quick and detailed response. Indeed `{yyyy}-{mm}-{dd} {time}` will be perfect for me.

Regards

**Comment by erosman** [comment]
I have added the code for that and it will be in the next upgrade.

**Comment by smaragdus** [comment]
@erosman 

You are really fast, thank you!

Take care and good luck!

**Comment by erosman** [comment]
v2.9 Uploaded

> Added new Custom Copy parameters {yyyy} {mm} {dd}
> Minimum version increased to Firefox 63 (released 2018-10-23)
> Added Options to the contextmenu to open the Options page

**Comment by smaragdus** [comment]
@erosman 

Many thanks! With version 2.9 using this Custom Copy format:

```
{text}
{title} 
{url}
{yyyy}-{mm}-{dd} {time}
```
I get exactly what I want. I wish more developers were as helpful, responsive and quick as you! I may suggest one more feature.

Best regards
