### ISSUE TITLE
FoxyTab compatibility with Sidebery

### ISSUE THREAD

**Issue by grahamperrin** [erosman/support#163]
### Steps

1. Install @erosman [FoxyTab](https://addons.mozilla.org/addon/foxytab/) and @mbnuqw [Sidebery](https://addons.mozilla.org/addon/sidebery/)
2. Sidebery ▶ Settings ▶ Menu ▶ Use native context menu
3. add two panels
4. have three windows
5. in the third window, have tabs in each of the three panels
6. in the third panel of the third window, use FoxyTab to sort by title

### Expected

* tabs within the third panel, sorted

### Actual result

* all tabs from the second and third panels move to the first panel

– and tabs within the first panel are not sorted. 

Please, can the two extensions be made compatible with each other?

**Comment by erosman** [comment]
Extensions that create tabs in the side-bar create something the resembles a tab. They are not actual tabs.

FoxyTab deals with actual Firefox tabs which are on top.

Have you tried [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/). How does it work there?

**Comment by grahamperrin** [comment]
> Have you tried Tree Style Tab. 

Yes, thanks, but need something to succeed legacy [Tab Groups](https://web.archive.org/web/20171101234857/https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) and the grouping (panelling) within Sidebery is the closest thing that I have found, so far. 

([Simple Tab Groups](https://addons.mozilla.org/addon/simple-tab-groups/) is nice, but https://github.com/Drive4ik/simple-tab-groups/issues/319#issuecomment-520751523 Firefox Quantum does not allow the GUI that I require.)

**Comment by grahamperrin** [comment]
> … need something to succeed legacy Tab Groups and the grouping (panelling) within Sidebery is the closest thing that I have found, so far. …

Since discovering the sidebar of Simple Tab Groups: I can prefer Tree Style Tab to Sidebery, and so on. 

----

@erosman from https://github.com/erosman/support/issues/163#issuecomment-602026857 I assume that you can do nothing to enhance compatibility with Sidebery so I'm closing this issue. 

Thanks again 👍

**Comment by erosman** [comment]
> @erosman from #163 (comment) I assume that you can do nothing to enhance compatibility with Sidebery so I'm closing this issue.

Sadly, that is correct. However, if Sidebery points out something that I can improve in FoxyTab to help out with the issue, I will do so.
