### ISSUE TITLE
context menu is not coming in Foxy tab

### ISSUE THREAD

**Issue by gsrao7** [erosman/support#165]
I am not sure why I am not getting context menu of Foxy tab at all.
Is there anything else I can do
I am using windows 7, 64 bit, latest firefox

**Comment by erosman** [comment]
Are you right-clicking on the tab? (not the page)

**Comment by gsrao7** [comment]
Thank you. I got it. It is working on tab. I was checking on the page.

Sorry for the inconvenience, I missed that detail somewhere, somehow.

Have a great weekend.

Warm regards

gsrao

**Comment by erosman** [comment]
No problem :+1:
