### ISSUE TITLE
[Text MultiCopy] - shortcuts & {domain}

### ISSUE THREAD

**Issue by thedivclass** [erosman/support#168]
Hey, big fan - few feature requests though: 

1. keyboard shortcut for 'copy saved to clipboard' - context menu item 
    - Additionally, if possible, a shortcut to copy the custom text formatting directly to the clipboard for the current (single) text selection.
2. '{domain}' parameter
    - additional copy format parameter to show the webpage domain (source).
        - e.g. for any [medium.com](http://medium.com) article, {domain} would return 'medium'.
3. multiple custom copy formats
    - allow different copy formats and trigger them with unique keyboard shortcuts
    - one keyboard shortcut would add the text selection with the default copy format, whilst another would generate copy with a different custom format - if specified.
4. Remove UTM tags from URLs by default

many thanks

**Comment by erosman** [comment]
> keyboard shortcut for 'copy saved to clipboard' - context menu item 

 keyboard shortcut is a troublesome issue. Firefox already has occupied most of them and other extension do the rest. If there is conflict, it is pot-luck which extension would get it.
The ones that are available are mostly 3 key combinations that are less desirable, especially for operations that are not performed frequently.
While the "Save Selection" is done frequently, the other operations are not as much. It is easy enough to define another keyboard shortcut in manifest, but what shall it be?!

> {domain}' parameter 

It is possible. Usually the domain would include TLD e.g. `example.com` or `www.example.com`.
(ref: [https://developer.mozilla.org/en-US/docs/Web/API/Location/hostname](https://developer.mozilla.org/en-US/docs/Web/API/Location/hostname))

> multiple custom copy formats 

There has be a demand for it. As mentioned above more shortcuts are hard to find. Adding multiple menus is possible.

Another option is to utilise  "Ctrl", "Alt", "Shift" etc modifiers when doing "Save Selection" e.g.

"Ctrl" + "Save Selection"  => Custom Ctrl
"Alt" + "Save Selection"  => Custom Alt
"Shift" + "Save Selection"  => Custom Shift
... etc

> Remove UTM tags from URLs by default

Maybe some basic ones can be removed!!? Unfortunately, there are many variations of them.

**Comment by thedivclass** [comment]
> Keyboard shortcut is a congested issue. Firefox already has occupied most of them and other extension do the rest. If there is conflict, it is pot-luck which extension would get it.

> As mentioned above, more shortcuts are hard to find. Adding multiple menus is possible.

Can the functionality not exist without a default shortcut? If no key combination were offered by default, then providing the user valued the added functionality sufficiently, it would be on them to create one without conflict.  

> Usually the domain would include TLD

The inclusion of the TLD would be absolutely fine. The concept was more about removing the protocol, path and parameters (I.e. everything else).

thanks again!

**Comment by erosman** [comment]
I am working on [FoxyTab](https://addons.mozilla.org/firefox/addon/foxytab/) which has a **Custom Copy** feature similar to [Text MultiCopy](https://addons.mozilla.org/firefox/addon/text-multicopy/). I have added a clean URL feature to remove some tracking strings automatically.

I will add the same feature to Text MultiCopy in the next update.

So far ........ It is removing `fbclid=...` & `utm_ ...`

Let me know if there are other strings that need cleaning.

**Comment by erosman** [comment]
Clean URL is done and will be in the next update.

**Comment by thedivclass** [comment]
Awesome work, thank you! 

> Can the functionality not exist without a default shortcut?

Any additional thoughts on an **optional** 'copy saved to clipboard' shortcut which offers no preset key combination as to avoid any potential conflicts? 

> Let me know if there are other strings that need cleaning.

I have previously used [LinkClean](https://github.com/vitorgalvao/alfred-workflows/tree/master/LinkClean), an Alfred Workflow which removes "_'m.' 'mobile.' 'touch.', anything after and including '?', 'ref=' and amazon_". [Rationalising](https://www.alfredforum.com/topic/4179-linkclean-%E2%80%94-removes-extraneous-information-from-urls/?do=findComment&comment=52668) that, "_there are legitimate uses for ? that change the page without being useless, but it seems like that maybe the minority._"

That being said, I can appreciate the desire to target specific parameters instead. 

Either way, I am greatly looking forward to making use of this additional functionality!

Thanks again!

**Comment by erosman** [comment]
> Any additional thoughts on an optional 'copy saved to clipboard' shortcut which offers no preset key combination as to avoid any potential conflicts?

Do you mean multiple custom format?
I haven't examined the possibilities ... yet.

**Comment by thedivclass** [comment]
> Do you mean multiple custom format?

Although I am very interested in the possibility for multiple custom formats, I was actually referring to item 1 in my [original post](https://github.com/erosman/support/issues/168#issue-596007781), namely; a keyboard shortcut for 'copy saved to clipboard', presently only accessible via the context menu. 

In response, you mentioned that "_It is easy enough to define another keyboard shortcut in manifest, but what shall it be?!_". While I understand the concern of possible conflicting key combinations, especially for operations less commonly used, is it not possible to make the shortcut optional, whereby the key combination is left blank by default? 

This way, the concern of conflicting extension shortcuts would be on the user not you. If they did not value the operation sufficiently, they could leave it blank (the default). If they deemed it worthwhile they would be responsible for assigning a key combination which did not conflict with any of their pre-existing extensions. 

Personally, I would find this specific shortcut extremely valuable.

**Comment by erosman** [comment]
> is it not possible to make the shortcut optional, whereby the key combination is left blank by default?

Sadly no ... keyboard shortcuts (commands) MUST be set in `manifest.json` (hardcoded) first. 
The option exist only to alter above but not create new ones.

**Comment by thedivclass** [comment]
argh, shame!

I thought it might be possible as several of my extensions appear to show empty states for optional shortcuts. 

For example, as seen via '_about:addons > Settings (cog) > Manage Extension Shortcuts_', uBlock Origin seems to offer such functionality. 


![image](https://user-images.githubusercontent.com/26438389/84811200-6a6b5c00-b004-11ea-88e5-eb1d68611e8f.png)


I apologise if this is not an equivalent or suitable comparison

**Comment by erosman** [comment]
I see..... you are right.

It doesn't appear to be documented on MDN but it seems it is possible to set keyboard shortcut ([commands](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)) with no `default` value as they have done in **uBlock Origin**.

```js
  "commands": {
    "_execute_browser_action": {},
    "launch-element-picker": {
      "description": "__MSG_popupTipPicker__"
    },
    "launch-element-zapper": {
      "description": "__MSG_popupTipZapper__"
    },
    "launch-logger": {
      "description": "__MSG_popupTipLog__"
    },
    "open-dashboard": {
      "description": "__MSG_popupTipDashboard__"
    },
    "relax-blocking-mode": {
      "description": "__MSG_relaxBlockingMode__"
    }
  },
```

In that case ..... then I can work on the feature.

**Comment by erosman** [comment]
Keyboard Shortcuts are done and will be in v2.10

Second Keyboard Shortcut for save is removed as well as Options Settings. All will be done from Firefox. 

![Keyboard Shortcut](https://user-images.githubusercontent.com/6458876/84894461-1caf2c00-b0b6-11ea-9119-8dae2e80b363.jpg)

**Comment by thedivclass** [comment]
Legendary, thank you!

**Comment by atomGit** [comment]
> Remove UTM tags from URLs by default

IMHO this is not a job for MultiCopy - since @erosman already added it apparently, i'm not asking it be removed, but i think this just ads unnecessary bulk to the ext. - do one thing, do it well - for URL cleaning i might suggest [ClearURLs](https://addons.mozilla.org/en-US/firefox/addon/clearurls/)

don't mean to offend anyone

**Comment by erosman** [comment]
v2.10 released

- Added new Custom Copy parameters {hostname}
- Added Clean URL feature to remove tracking strings from copied Tab URLs
- Removed "Custom Keyboard Shortcut" setting since Firefox (66+) also provides the feature
- Added all actions to extension shortcuts
- Removed second save extension shortcuts
- Disable Notification option (default false) changed to Notification (default true)
- OOP Code Improvement
