### ISSUE TITLE
What means option "Enable Storage Sync"?

### ISSUE THREAD

**Issue by pstein** [erosman/support#169]
In FireMonkey options there is a checkbox "Enable Storage Sync".
What does this option mean?

Whats the (dis)advantage?

Peter

**Comment by erosman** [comment]
For people who use multiple Firefox browsers at different location, Firefox has a sync option which requires login in [Firefox Account](https://www.mozilla.org/firefox/accounts/).

The benefit is that a user who uses FireMonkey in more than one location, and has a Firefox Account, can sync the stored data & scripts between them.

The drawbacks are that:

- Only useful for users that FireMonkey at multiple locations
- it requires Firefox Account & login
- Privacy considerations when data is also stored remotely
- Firefox Sync has a limit of 100kb which would be enough for normal extensions but in case of FireMonkey, it is only usable if user has a few small scripts
