### ISSUE TITLE
[FoxyTab] Color of opened tabs changed in FF63

### ISSUE THREAD

**Issue by modem** [erosman/support#17]
Hi
After the upgrade to FF63, the color of the opened tabs in the FoxyTab icon changed from white to black.

![image](https://user-images.githubusercontent.com/62859/47614768-e7973580-da9c-11e8-8ee1-312a45cb27be.png)

I have FoxyTab v2.11.
If possible to fix...

Thank you

**Comment by erosman** [comment]
Hi

I know. It is done by Firefox 63+. They automatically sets black for light backgrounds and white for dark ones. I preferred the white too. 

> [Extensions in Firefox 63](https://blog.mozilla.org/addons/2018/08/31/extensions-in-firefox-63/)
> Browser actions will set the badge text color automatically to maximize contrast 

The new version of FoxyTab already has the option to change it (FF63+)
