### ISSUE TITLE
Dragging multiple *.user.js files not working; Direct install by copying?

### ISSUE THREAD

**Issue by pstein** [erosman/support#172]
Assume I setup a new (portable) Firefox installation.

In order to "initialize" this FF with all my (~20) *.user.js scripts I have to drag them individually step by step onto the Firefox window. This works.

Marking all the 20 files in WindowsExplorer and drag them in one step opens 20 tabs but installs only the first *.user,js script.

Is there no way to install multiple *.user.js scripts together in ONE step?

Maybe by copying these files (in WinExplorer) in a certain (sub)directory of Firefox and (re)start Firefox.
Does FF recognize these new script files and prompt for installation?

Or is there alternatively a way to install a *.user.js script from cmdline similar to

firefox.exe -addon=FireMonkey -install=D:\temp\myscript.user.js

Firefox could popup a confirmation prompt "as usual" for every passed file and obey security considerations this way.

Peter

**Comment by erosman** [comment]
Is there no way to install multiple *.user.js scripts together in ONE step?

yes ... Import 
FireMonkey -> Option Page -> At bottom left 
Click and select as many scripts as you wish


> Maybe by copying these files (in WinExplorer) in a certain (sub)directory of Firefox and (re)start Firefox.
> Does FF recognize these new script files and prompt for installation?

As explained in #170 extensions do not have access to user file system.
