### ISSUE TITLE
[Firemonkey] This script wont install for reason unknown

### ISSUE THREAD

**Issue by MikeZeDev** [erosman/support#173]
https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites

I have still a couple of scripts that arent working (even after Mozilla extend the wildcard tld api) but at least i've had no problem to install them, they are just disabled. 

For some reason i cant install this one i can't even save a new script and paste this code. The script is just not listed.

**Comment by erosman** [comment]
> even after Mozilla extend the wildcard tld api

Do you mean the TLD feature I added to FireMonkey?
Mozilla Match Pattern doesn't support TLD. 

> I have still a couple of scripts that arent working 
> https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites


Oops ......... sorry 
There is a typo in the code dealing with `@resource` :facepalm: 

I have fixed it and will release an update.
That you for reporting it. :+1:

**Comment by erosman** [comment]
**Note:**

After fixing above, script installs but fails to be enabled due to problem with `@include` patterns that cant be automatically converted to `@match`

The following are converted to @match automatically
```
// @include     http*://startpage.com/*
// @include     http*://*.startpage.com/*
// @exclude     https://www.startpage.com/*/ads?*

// @include     http*://duckduckgo.com/*
// @include     http*://start.duckduckgo.com/*
// @include     http*://safe.duckduckgo.com/*

// @include     http*://3g2upl4pq6kufc4m.onion/*
// @include     http*://www.bing.com/*
// @include     http*://*search.yahoo.com/*
// @include     http*://search.yahoo.co.jp/*
// @include     http*://www.yandex.com/*
// @include     http*://yandex.com/*
// @include     http*://searx.*/*
// @include     http*://www.qwant.com/*
// @include     http*://www.qwantjunior.com/*
// @include     http*://www.baidu.com/*
// @include     https://www.ecosia.org/search*
```

This one fails automatic conversion:
```
// @include     http*://www.google.co*.*/*
```
However, bearing in mind the following from above `http*://www.google.co*.*/*` isn't really needed
```
// @include     http*://www.google.*/*                // matches ALL www.google.*
// @exclude     http*://www.google.com/recaptcha/*    // not needed as it is a subset of the 1st one
// @include     http*://www.google.co*.*/*            // not needed as it ends up as a subset of the 1st one (depending on the regex of script-manager)
// @include     http*://news.google.*/*
// @include     http*://encrypted.google.*/*
```


I am going to update FireMonkey to look for '.co*.' as well. It will be in the next upgrade.

**Comment by MikeZeDev** [comment]
> Mozilla Match Pattern doesn't support TLD.

Ah you did it yourself. Thanks a lot !

I see those domains are not really need , yes. I am not the author btw :D

Anyway, thanks again for this addon and bug fixing.

**Comment by erosman** [comment]
v1.35 uploaded
Let me know if there are any issues.
