### ISSUE TITLE
Allow update of script with the SAME version number?

### ISSUE THREAD

**Issue by pstein** [erosman/support#175]
When I drag a changed *.user.js script file onto Firefox then the old, existing *.user.js is only replaced when the new *.user.js script contains a version number greater than the old one.

Thats bad.

Assume I have a working *.user.js script with version number 1.17

Now (after some weeks) I want to try out some modifications. I edit the *.user.js file in WinExplorer and (Notepad++ editor) outside of Firefox. I changed the version to v1.18 and dragged the new file onto Firefox.
The modifications are accepted by FireMonkey.

Now it occurs oftentimes that my modifications are not successful or I want to add some other modifications as well. So for each new, next change in *.user.js file in Windows Explorer I have to increase the version number again and again. This is uncomfortable. I want to keep the current version number until the modifications are final (for the current day).

So how can I force FireMonkey to accept *.user.js scripts even when the version number remains unchanged (or is even lower)?

Peter

**Comment by erosman** [comment]
OK.. I can make the changes.

> So how can I force FireMonkey to accept *.user.js scripts even when the version number remains unchanged (or is even lower)?

Copy the script from Notepad++ editor and paste it in the FireMonkey editor, then click Save.
That is how I do it myself as I do all my editing in a proper editor.

**Comment by erosman** [comment]
It is done and will be in the next update.
