### ISSUE TITLE
X-Ray vision problems

### ISSUE THREAD

**Issue by robertmaxton42** [erosman/support#176]
I'm attempting to write what in concept is a dirt-simple script, that essentially acts as an extension to the function of an existing web app. The app in question (Rolz) in fact already has an API for just this sort of thing; I just have to add my own subscriber to its event handlers...

... whiiiich of course, nowadays runs into the usual x-ray vision problems.

`unsafeWindow` on its own doesn't seem to do the trick anymore, giving me `Permission denied to access object` -- at a guess, using `unsafeWindow` bypasses GM4's "firewall" but not Firefox's own. Unfortunately, `exportFunction` doesn't seem to work either, and calling it just results in the script hanging indefinitely:

```
/*
==UserScript==
@name exportFunction Bug Repro
@include https://www.google.com
@version        1.0
==/UserScript==
*/

console.log("The script starts...");

function doomed() {
  console.log("Lorem ipsum");
}

exportFunction(doomed, window, {defineAs: "doomed"});
//It's arguable that I should be using unsafeWindow here, instead of window, but it's moot;
//at this point the script hangs.

console.log("... but this never prints.");
```

Unfortunately, it doesn't seem like I can easily work around this with, say, inserting a `script` tag, because I need access to the notifications API, either through Firefox or through GM. It'd be nice if we could use the native functions intended to cross the content/page script "firewall"; barring that, suggestions are solicited.

Thanks for all your work!

**Comment by erosman** [comment]
User-Scripts in FireMonkey are subject to more restrictions than other user-script mangers that don't use the dedicated userScript API.

`exportFunction()` is not implemented in FireMonkey as a function.

Have you tried the examples given in FireMonkey **Help** under **unsafeWindow**?

**Comment by robertmaxton42** [comment]
I have indeed; that's what's giving me `Permission denied to access object`.

For example:

```
/*
==UserScript==
@name Restricted { }
@include https://www.google.com
@version        1.0
==/UserScript==
*/

unsafeWindow.document.onFakeEvent = function () { alert(); };
```

I don't have a complete reproduction this time, but if you use the above script and then manually ask the console what `document.onFakeEvent`, it'll just give you `Restricted { }`, and calling it gives `Permission denied...`; the same behavior does occur when a page script tries to call the restricted function.

**Comment by erosman** [comment]
There is not enough information here to know what is happing and to advise correctly.

>  then manually ask the console 

`console` has a different scope and not the place to test this.

**Comment by robertmaxton42** [comment]
Mmm...

Well, as a side note, `@matchAboutBlank true` does not appear to make the script run on about:blank, which makes finding a good site to test this one a bit difficult.

Well, I suppose I can just use my actual use-case. If you go to https://rolz.org/dr?room=Sandboxtest, then the following:

```
/*
==UserScript==
@name Restricted
@match *://rolz.org/dr?room=*
@version        1.0
==/UserScript==
*/

unsafeWindow.document.onNotify = function(msg) {
  alert();
};
```

will produce the appropriate console spam every time you send a message.

**Comment by erosman** [comment]
>  as a side note, @matchAboutBlank true does not appear to make the script run on about:blank,

Please note:

> ref: [content_scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts)
> Insert the content scripts into pages whose URL is "about:blank" or "about:srcdoc", if the URL of the page that opened or created this page matches the patterns specified in the rest of the content_scripts key.
> 
> This is especially useful to run scripts in empty iframes , whose URL is "about:blank". To do this you should also set the all_frames key.

**Comment by erosman** [comment]
`document.onNotify` is not defined when I try it.

```
 chatNotify : function(msg) {
    if(document.onNotify && msg.type != 'keep-alive') document.onNotify(msg);
  },
```

**Comment by robertmaxton42** [comment]
Yup, that's as intended. Like I said, Rolz is expressly defined to be easy to extend with userscripts. `document.onNotify` doesn't actually exist in the native code, but you can define it with a userscript (or at least, you could when the API was designed before X-ray problems...) and it will respond to that.

And yeah, I've heard the story about `unsafeWindow`, but my actual intent is pretty much exactly what the X-ray paradigm is supposed to prevent: make page code call an extension-privileged function, in this case `GM.notification`. I'm working on a workaround with `postMessage`, but honestly `unsafeWindow`/`exportFunction` is pretty much exactly what I need here...

**Comment by erosman** [comment]
> Yup, that's as intended. Like I said, Rolz is expressly defined to be easy to extend with userscripts. document.onNotify doesn't actually exist in the native code, but you can define it with a userscript

I see ..... Here it is:

```js
/*
==UserScript==
@name          Rolz
@match         https://rolz.org/dr?room=Sandboxtest
@version       1.0
==/UserScript==
*/
 
unsafeWindow.document.onNotify = function(msg) { alert(msg); };
```

From console
![image](https://user-images.githubusercontent.com/6458876/79093954-1d9ca800-7d6b-11ea-85f0-8ba6e5e87962.png)

**Comment by erosman** [comment]
OK... here is a working script using Web API. 

```js
/*
==UserScript==
@name          Rolz
@match         https://rolz.org/dr?room=Sandboxtest
@author        erosman
@version       1.0
==/UserScript==
*/

console.log('Rolz started');

const script = document.createElement('script');
script.textContent = `(() => {

if (Notification.permission === 'granted') {
  document.onNotify = onNotify;
}
else if (Notification.permission !== 'denied') {

  Notification.requestPermission().then(permission => {
    // If the user accepts
    if (permission === 'granted') {
      document.onNotify = onNotify;
    }
  });
}

function onNotify(msg) {
  console.log(msg);
  new Notification('Hi there!');
}
console.log('script injected');
})();`;
document.body.appendChild(script);
script.remove();
```

It is only for testing and I have not removed the debugging `console.logs()`.
You would also need to **Allow Notification** as it uses the [Notification](https://developer.mozilla.org/docs/Web/API/notification) Web API.

The message is an object that can be used to create a proper Notification.

```js
{
  "type": "txtmsg",
  "from": "ImpossibleArchitect",
  "text": "blah",
  "key": "50111613",
  "h_time": "2020-04-12 08:05 UTC",
  "time": "1586678702",
  "room_id": "71107945"
}
```

**Comment by Sxderp** [comment]
The problem is the site in question performs a `document.onNotify()` rather than using native event passing systems. What you need to do is convert their manual method call into an actual event.

```javascript
/*
==UserScript==
@name Restricted
@match *://rolz.org/dr?room=*
@version        1.0
==/UserScript==
*/

function myNotify(event) {
  console.log('This is a userscript notify', event);
  console.log('The passed details are', event.detail);
  console.log(GM.notification)
}
document.addEventListener('mynotify', myNotify)


window.eval(`
window.document.onNotify = function (event) {
  console.log('Notify in eval', event)
  window.document.dispatchEvent(new CustomEvent('mynotify', { detail: event }))
  console.log('dispatched')
}
`)
```

**Comment by robertmaxton42** [comment]
After kitbashing the above solutions together, I found that recent Firefox versions actually disallow asking for Notifications permission except in a direct response to user action. 

It seems to me that the most intuitive way of complying with that requirement is to add the prompt as a menu command to the userscript, rather than, say, inserting a button somewhere on the page. (An alert box might work as well, but I'd prefer something a little less disruptive.)

Unfortunately, this doesn't seem to work -- Firefox doesn't count clicking on a menu command as "user action", despite it being precisely that. I'm not sure that this is something you can fix, but I thought I'd raise the subject.

For now, I think I will have to resort to the alert box...

**Comment by erosman** [comment]
> After kitbashing the above solutions together, I found that recent Firefox versions actually disallow asking for Notifications permission except in a direct response to user action.

When I was testing, although the prompt did not come up, all I had to do was to manually allow notification from the address-bar.

Script can popup a notification and remind users to do so.

The `CustomEvent` solution by @Sxderp is also quite good. If you don't want to use `window.eval()` you can inject the script using `<script>` tag. This method does not require any additional permission.

However ................... :thinking: 

During testing, I noticed that I don't get the detail form `new CustomEvent('build', { detail: 'time' });`
Event is received by the user-script but `detail: null`

![image](https://user-images.githubusercontent.com/6458876/79225198-a140bc80-7e71-11ea-83bf-32813e1b7fa9.png)


I am checking with Firefox userScript API developers to see if it is due to API.

Other script managers should not be affected by this as they don't use the Firefox userScript API.

**Comment by robertmaxton42** [comment]
Huh. 

This version of the script seems to get valid events...?

```
/*
==UserScript==
@name Rolz Notifications
@match http://rolz.org/dr?room=*
@match https://rolz.org/dr?room=*
@version        1.0
@require https://code.jquery.com/jquery-3.*.*.slim.min.js
==/UserScript==
*/

function subscribeNotifications() {
    const script = document.createElement('script');
    script.textContent = `document.onNotify = (msg) => {
      document.dispatchEvent(new CustomEvent('GM_notify', {detail:msg}));
    };`
    document.head.appendChild(script);
    console.log('script injected');
    script.remove();
}

console.log('test');
if (Notification.permission !== 'granted') {

  function requestNotifications() {
    Notification.requestPermission().then(permission => {
      if (permission === 'granted') {
        subscribeNotifications();
        icon.remove();
      }
    }, (reason) => {console.log(reason)});
  };

  const icon = document.createElement('span');
  icon.className = "fa fa-exclamation-circle";
  icon.style = "margin: 6px";
  icon.addEventListener('click', requestNotifications);

  console.log(icon);
  document.getElementById("dr-title").appendChild(icon);
} else {
  subscribeNotifications();
}

function notify(event) {
  console.log('received event');
  const msg = event.detail;
  console.log(msg);
}

document.addEventListener('GM_notify', notify);
```

**Comment by erosman** [comment]
> This version of the script seems to get valid events...?

There is not a problem  with getting the event. The issue is that the details that are sent are stripped by X-ray Vision.

**Comment by robertmaxton42** [comment]
Right, but that's what I'm saying -- I just print my `event.details`, and I get my full message object. Unless that's not what you're saying...?


Also, it may be worth mentioning somewhere in the Help files that `GM.notification` does not support the newer object-based format (or adding support instead.) That is, 
`GM.notification(text, title, ...)` works fine but
`GM.notification({text: ..., title: ...})` does not.

**Comment by erosman** [comment]
> Also, it may be worth mentioning somewhere in the Help files that GM.notification does not support the newer object-based format (or adding support instead.) 

The help says:

> GM.notification(text)
> GM_notification(text)

It only supports single text for plain notification.

**Comment by robertmaxton42** [comment]
Ah... while that is *true*, it is also not very *clear*; it could easily be shorthand, or a simply incomplete entry. Especially since in almost every other case, Firemonkey faithfully replicates the functions of the other *monkey extensions. Explicitly stating that the rest of the features of `GM.notification` are not yet supported would be helpful.

**Comment by erosman** [comment]
OK.. I will update the Help and maybe add object parsing for error avoidance.

**Comment by robertmaxton42** [comment]
Excellent, I'm glad to hear it :p.


> onclick: Firefox doesn't support notifications.onButtonClicked so the notifications.onClicked would be clicking anywhere on the notification which is not very useful, People often click the notification to close it and firing an event there is not desirable.

By the way -- actually, in my experience, the idiomatic thing to do when clicking the notification is to take you to whatever's being notified about. Push events already do this (if you get a Discord push, clicking it will open Discord), but also forums that implement notifications will usually take you to the tab (and in fact the specific message it's notifying you about), or open a new one if none are currently open. It'd be cool to replicate this, though I suppose in my case it's less necessary as people aren't likely to have more than a single Rolz chatroom open at a time.

**Comment by erosman** [comment]
Let.s see ...
Firefox currently only supports "basic" type notification and then without buttons.
It would have be very useful to the extensions as well if buttons were supported.

If `onclick` is added what happens when user wants to close the notification and not do whatever the `onclick `is set to do?

However, if there is a popular demand, then I will see what can be done.

**Comment by robertmaxton42** [comment]
![image](https://user-images.githubusercontent.com/13130661/79244989-1c3bb000-7e3d-11ea-9984-befb283a6d88.png)

Well, it does have an explicit "close" button, at least. So unless clicking the close button triggers the `onclick` (which would be perverse enough to be worth a ticket at bugzilla), that's probably good enough for a user that just wants to ignore it, I think?

**Comment by erosman** [comment]
:information_source:  I have added an example code based on this discussion to the FireMonkey Help.

**Comment by erosman** [comment]
Added **image** support to GM notification (v1.36)

AFA **onclick**, I am still looking for an efficient way.
