### ISSUE TITLE
new command not recognized

### ISSUE THREAD

**Issue by pstein** [erosman/support#177]
I edited an existing *.user.js script inside FF v75 through FireMonkey.

I added a new GM_addStyle() command with some additional CSS instructions (see attached snapshot).

The command text however switches not "as usual" to a black+light grey+colored syntax highlighting but remains completely in black.

Furthermore the new CSS is not applied to the reloaded webpage.
Yes, I saved the script. And I tried exit + restart FF.
The new command remains unusual in full black text.
All other instructions work.

So I guess the command is somehow not recognized by FireMonkey.

Whats wrong? 

Peter

![not recognized](https://user-images.githubusercontent.com/2775875/79094609-639c4080-7d58-11ea-92ea-60cfc8f55373.png)

If I prepend the line with  comment slashes // then not the whole line is turned to green but only a  part of it.
I guess this is a bug as well:

![wrong comment](https://user-images.githubusercontent.com/2775875/79095025-909d2300-7d59-11ea-9956-284352578f79.png)

**Comment by erosman** [comment]
Although it is fine, it is more efficient to add all styles together. i.e.:

```js
const css = `
  ...........
  ...........
  ...........
`;

GM_addStyle(css);
```

If you give a site to test it, I will check it out.
