### ISSUE TITLE
Pre-define/remember import+export directory?

### ISSUE THREAD

**Issue by pstein** [erosman/support#179]
Whenever I want to import some *.user.js scriptsand click on IMPORT iI have to click through the directory tree to get to the source directory.

Is it possible to add en entry field to pre-define an import folder and to jump to this custom import directory?

Alternatively FireMonkey should remember the last import directory beyond exit+restart.

Furthermore an Export directory cannot be selected. Its always automatically the system download directory PLUS "FireMonkey" subdirectory.

Is it possible to similarly define an export directory (with no auto-creation of subfolder)?

Peter

**Comment by erosman** [comment]
Since Firefox 57 it is no longer possible for extensions to have access to user HD/file system (for security).

Extensions can ONLY save-to/open from the location defined in:
Firefox -> Options -> General -> Files & Application -> Downlands -> Save files to

**Comment by erosman** [comment]
**Update:**
Firefox has updated the API and as of Firefox 78, the last download location will be remembered by Firefox.

> [Extensions in Firefox 78](https://blog.mozilla.org/addons/2020/06/29/extensions-in-firefox-78/)
> 
> When using `downloads.download` with the `saveAs` option set to `true`, the recently used directory is now remembered on a per-extension basis. For example, a user of a video downloader would benefit from not having to navigate to their videos folder every time the extension offers a file to download.
