### ISSUE TITLE
[FoxyTab] Support: FoxyTab context menu does not appear

### ISSUE THREAD

**Issue by craiglreid** [erosman/support#181]
Hi,

My FoxyTab context menu is entirely missing. FoxyTab is installed and the tab counter is working. I have disabled and reenabled FoxyTab, removed and readded FoxyTab, restarted Firefox, and restarted MasOS. None of these have fixed this issue, and my research hasn't turned up a solution. I'd greatly appreciate any help you can offer to fix this issue.

I'm running FF 75.0 on MacOS 10.15.4

Thanks,
Craig

**Comment by erosman** [comment]
Hi Craig

Please note that the FoxyTab context-menu belongs to the Tab which means you have to right-click the Tab on top.

**Comment by craiglreid** [comment]
Well, that explains it. I apologize for failing to understand this. Thank
you so much for the info and for the quick reply!

I’m using an extension named Tab Center Redux that puts my tabs in the
sidebar along with with thumbnails. That extension has its own right click
menu, which must be overriding FoxyTab. I’ve been using left side thumbnail
tabs for 15+ years going back to the old OmniWeb browser.

Tab Center Redux has a small user base, but the over 200,000 Tree Style Tab
users might value having FoxyTab’s context menu appear as an expandable
menu from the webpage context menu. I know for sure that I would as you’ve
built a very cool extension.

Thanks again,
Craig

____________________________________
Craig L. Reid
512.632.2124

From: erosman <notifications@github.com> <notifications@github.com>
Reply: erosman/support
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 4, 2020 at 10:43:48 AM
To: erosman/support <support@noreply.github.com>
<support@noreply.github.com>
Cc: craiglreid <craiglreid@gmail.com> <craiglreid@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [erosman/support] [FoxyTab] Support: FoxyTab context menu
does not appear (#181)

Hi Craig

Please note that the FoxyTab context-menu belongs to the Tab which means
you have to right-click the Tab on top.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/erosman/support/issues/181#issuecomment-623541763>, or
unsubscribe

**Comment by erosman** [comment]
Thank you for your kind words.

**Tree Style Tab** screenshot shows **FoxyTab** which would seem that it works there.

![image](https://user-images.githubusercontent.com/6458876/80995356-61a73800-8e53-11ea-97bc-61383838d5e6.png)
