### ISSUE TITLE
[FoxyTab] Not working upon installation 

### ISSUE THREAD

**Issue by dtsechen** [erosman/support#182]
Installed foxytab 2.15 on FF 76.01 but it's not appearing in the context menu. I tried to turn it off and on and again, and reloading the browser but no dice. The foxytab icon also doesn't show anything (no time, date, or country). It only has the Options and Recount buttons.

**Comment by erosman** [comment]
**Context-menu**
Please note that the FoxyTab context-menu belongs to the Tab which means you have to right-click the Tab on top (not the page).

**Time & Date**
They should be set in the Options first.
