### ISSUE TITLE
[Firemonkey] Export does not export all

### ISSUE THREAD

**Issue by Tharn** [erosman/support#184]
Hi there,

After having loaded 6 userscripts into FireMonkey, when I click on 'export' I see a little '6' appear above the  export button. However, in the created FireMonkey export folder I only find 4 scripts. This happens every time.

Possible cause: Non-NTFS letters in the userscript name, such as : " etc.

**Comment by erosman** [comment]
> Possible cause: Non-NTFS letters in the userscript name, such as : " etc.

That probably is the reason as the API that saves the script fails if filename has disallowed characters.

In my other addons, I remove disallowed characters when saving things but in case of script names that may result in confusion.

However, let me think more about the best approach.

**Comment by Tharn** [comment]
I think removing disallowed characters would still be the right way to go. When the user exports scripts, I am assuming he cares most that he actually gets all his scripts. Names are cosmetic at this point.

A warning popup in case of bad letters should clear up the confusion.

AFAIK, exact script titles are not necessary for working script updates or for operation. It's just a cosmetic thing. Worst case being that a user may have duplicate scripts because not all letters match.

**Comment by erosman** [comment]
It is done and will be in the next update.
