### ISSUE TITLE
[FireMonkey] Use CodeMirror or something equivalent?

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#185]
The addon itself functions as expected, which is nice. However, the syntax-enabled editor is very buggy and unusable. Every time I press backspace on an empty line, it only removes the line number. The second time backspace actually removes the line. Ctrl+Z does nothing. Copy pasting lines would insert additional newlines. Indent is not working, and can't be configured. There are so many more problems with it.

Why not use some mature js-based editor such as CodeMirror instead? It supports [hundreds of configurations](https://codemirror.net/doc/manual.html#config) out of the box. Violentmonkey uses it and works fine. Or something from [the list](https://en.wikipedia.org/wiki/Comparison_of_JavaScript-based_source_code_editors). Anything is better than the hand-crafted editor FireMonkey got.

**Comment by erosman** [comment]
CodeMirror is very good but it is also huge and resource intensive. As explained in the Help, FireMonkey intends to be slim.

I wrote the syntax highligting myself and it is very basic and mostly good for reading and very basic editing.

Proper editing should be done with a proper editor.

**Comment by CrendKing** [comment]
Can you explain slim in what aspect? In term of packaged size? Runtime cost? Memory cost? Maintenance cost?

If it is packaged size, the minified codemirror.js is around 200kb, which is compressed again in xpi.

If it is runtime or memory cost you concern, the editor would not be active during page injection. It is only loaded when the user is editing the script/CSS. Most of the users would simply install scripts from sharing sites anyway. They wouldn't even notice a change in the editor.

If it is the maintenance cost, I would agree with you if the "syntax" editor does not exist at all. The moment you add the syntax one, you have to keep it up with the constant changing Javascript standard, dealing with all the bugs and weirdness. Comparing to that, adopting CodeMirror only requires you to sync version from time to time.

If you are true to the slimness and "proper editing should be done with a proper editor", the logic action is completely remove the syntax editor. No one that writes scripts themselves would actually use it and it is actually wasting resource.

**Comment by erosman** [comment]
> Can you elaborate slim in what aspect? In term of packaged size? Runtime cost? Memory cost? Maintenance cost?

All above.

**Script Manger**

- GM XPI is 530kb
- VM 430kb
- TM 1.31mb

**Style Manger**

- Stylish 1.85mb 
- Stylus 1.39mb
- xStyle 953kb

FM is 62KB (without the JQuery etc libs) and handles both user-script and user-css.

Majority of user-script or user-style users are not programmers and only download and use them verbatim and do not edit the script/CSS.

Minority programmers who can write their own code, would already have a stand-alone program for writing the code. 

Personally speaking, in over a decade of writing user-scripts, I never use the script manger to write code.

AFA shortcoming of the editor in FM, it is possible to turn off the syntax highlighting and edit as plain text without any of the issues that were mentioned.

**Comment by CrendKing** [comment]
Fair enough. Thanks for the explanation. Feel free to close the ticket.

**Comment by erosman** [comment]
> I just find the instant preview feature in Stylus/Stylish being convenient. Surely more user friendly than requiring copy paste from external editor all time.

That is true and as I have said, CodeMirror is great. Even Firefox uses CodeMirror for its syntax highlighting.

In FM, I have concentrated on script management and not script editing.

However, FM will improve further over time.

**Comment by erosman** [comment]
I decided to use CodeMirror. It will be in v1.48
