### ISSUE TITLE
[Firemonkey] Feature suggestion: Hide number on icon

### ISSUE THREAD

**Issue by Tharn** [erosman/support#186]
As the title says, it'd be nice to have an option to toggle the number on the toolbar icon on and off. A lot of extensions do this, including the various *Monkeys.

**Comment by erosman** [comment]
TBH, it would be less work for FM if it didn't have to produce the number of active users.

GM doesn't have a feature to turn it off/on.

Do other script manager have it?

Let's see how popular the feature is.

**Comment by Tharn** [comment]
You're right, I thought it had it. Tampermonkey and Violentmonkey have it, anyway.

**Comment by erosman** [comment]
I have written the code for it and after testing, it will be in the next update.
