### ISSUE TITLE
[FireMonkey] 1.36 regression - empty FM window on every 2nd click

### ISSUE THREAD

**Issue by Tharn** [erosman/support#189]
Like so:

![Untitled](https://user-images.githubusercontent.com/13466852/82831616-32677200-9eb9-11ea-9600-d4a2c1aa15df.png)

**Comment by erosman** [comment]
Are you on a Nightly?

**Comment by Tharn** [comment]
No, I'm on FF 76.0.1 x64, and the 1.36 FM update is from today.

**Comment by erosman** [comment]
Actually, I see it happening here and there with all extensions (not only FM). I am on nightly which updates regularly and the situation goes away by itself, often after a restart.

**Comment by Tharn** [comment]
Okay, no point investigating then. Cheers!
