### ISSUE TITLE
Duplicate tabs features

### ISSUE THREAD

**Issue by mzguy** [erosman/support#191]
Is Foxytab's duplicate tab feature different from the Firefox native one, and how so? If not, why is it included?

I see that the Close Duplicates feature ignores location.hash. If I understand this correctly, this only will result in closing a duplicate tab if the duplicate tab hasn't navigated away to a new URL. However, I don't see under what circumstances this would close any tabs at all, since presumably the point of duplicating a tab is to use it as a starting point to navigate elsewhere. Am I missing something?

**Comment by erosman** [comment]
> Is Foxytab's duplicate tab feature different from the Firefox native one, and how so?

No.. it is the same.

>  If not, why is it included?

When I included the Duplicate Tab feature, Firefox didn't have it.
After Firefox added the Duplicate Tab, I removed it in FoxyTab v2.12
It was requested  by users to re-add it and it was re-added in v2.14 (ref #25).
In my opinion also, it is not necessary. 


> I see that the Close Duplicates feature ignores location.hash. If I understand this correctly, this only will result in closing a duplicate tab if the duplicate tab hasn't navigated away to a new URL. However, I don't see under what circumstances this would close any tabs at all, since presumably the point of duplicating a tab is to use it as a starting point to navigate elsewhere. Am I missing something?

[Location: hash #](https://developer.mozilla.org/en-US/docs/Web/API/Location/hash) in URL refers to a location inside the page. Therefore, the following links are the same page. In the one with the hash, it has scrolled to that section.

```
https://developer.mozilla.org/en-US/docs/Web/API/Element
https://developer.mozilla.org/en-US/docs/Web/API/Element#Properties
https://developer.mozilla.org/en-US/docs/Web/API/Element#Methods
https://developer.mozilla.org/en-US/docs/Web/API/Element#Events
https://developer.mozilla.org/en-US/docs/Web/API/Element#Specifications
https://developer.mozilla.org/en-US/docs/Web/API/Element#Browser_compatibility
```

All above are the same page and all but one will be removed in **Close Duplicate Tabs**, starting from the right to left.


**Close Duplicate Tabs** checks and compares the URLs of all tabs, at the time of execution. Whatever the URL was before the current one, is not relevant.

**Comment by erosman** [comment]
As in v2.16
- Removed "Duplicate Tab" as it is built-in since Firefox 57
