### ISSUE TITLE
Go Back to first opened page in current tab

### ISSUE THREAD

**Issue by Robbie711** [erosman/support#192]
This was a way cool extension. Any chance you can integrate it into Foxy Tab? Thx!

Go back to the very first page that was opened in the current tab. 
https://addons.mozilla.org/en-US/firefox/addon/snap-back-button/

**Comment by erosman** [comment]
Above extension uses a Web API (runs JavaScript inside the web page) and goes through the history one by one to get to the end (not an efficient method).

Problem with above is that:

- That history can be overwritten by JavaScript on the page which makes it unreliable
- FoxyTab doesn't deal with web page content

There is a Firefox API to go back  [tabs.goBack()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/goBack) but it goes back one by one which means it has to cycle through them to reach the end (inefficient when there are many previous pages in the tab history) which usually is `about:blank` i.e. a blank page.

I will see if there are other/better ways to do it.

**Comment by Robbie711** [comment]
> TBH, Right Clicking on the Back Button would be easy enough to go to the desired previous page.

Agree, this would do it. But real coolness is a one button solution. 

Seriously, this probably isn't worth the research and development time.

**Comment by erosman** [comment]
Furthermore, there are more steps in the second method. There isn't a ONE click method like that add-on which only has ONE function.

Right Click Back Button -> Click the URL
.......... vs ..........
Right Click Tab -> Click FoxyTab to open menu -> Click submenu

**Comment by Robbie711** [comment]
You're absolutely right.
