### ISSUE TITLE
Copy PlainText no bind cmd+c

### ISSUE THREAD

**Issue by deevroman** [erosman/support#194]
Changed the keyboard combination to cmd+c, but it doesn't work.
mac os, Firefox 78

**Comment by erosman** [comment]
Keyboard shortcuts are a congested area in the modern browsers.

Firefox has its own keyboard shortcuts.
Add-ons can add keyboard shortcuts.

If Firefox already has a keyboard shortcut combination, then it will IGNORE shortcuts set by an add-on.

In case of add-ons, each time, the first one that loads, gets the keyboard shortcut and others if they use the same keyboard shortcut, will be ignored. 

Firefox already has a `cmd +c` keyboard shortcut. AFAIK, it is not possible to re-assign it.
