### ISSUE TITLE
Avoid double empty lines when copying script code from FM to text editor?

### ISSUE THREAD

**Issue by pstein** [erosman/support#195]
Assume I changed the script code for a script in a Firemonkey tab .

I pressed "Save".

Now I want to copy the current code to a text file outside of Firefox. This should be done NOT by export but through clipboard.

So I hit at first Ctrl+A to mark the whole script code. Then right click with the mouse and select "copy" from context menu.
Finally I open a new text file (e.g. in well known Notepad++ editor) and paste the just copied code here.

Unfortunately every single empty line in original script code is doubled.

How can I avoid this?

Peter

**Comment by erosman** [comment]
That does not happen when I try it NOW.

But ..... I have seen it too.

There has been a few changes (for improvement) made to the Syntax Highlight code (mainly in v1.31 & v1.34) which resulted in layout inconsistency. Script that were saved before or during those changes might have ended up with hidden new lines that doesn't show in editor but come up when copy-pasting to another document.

Try making a small change (not space) to the script and save it and then revet the change and save it again and see.
Alternatively, export them all and check which one has this issue and import again.

The problem should not happen again in future. 

Sorry about that ....

**Comment by pstein** [comment]
> Try making a small change (not space) to the script and save it and then revet the change and save it again and see.

Ok, this works.
Thank you
