### ISSUE TITLE
Copy Plain Text Swedish translation

### ISSUE THREAD

**Issue by Gummigutta** [erosman/support#196]
// version 1.10

{
  "extensionName": { "message": "Kopiera PlainText" },
  "extensionDescription": { "message": "Kopiera/Klistra in oformaterad text utan någon formatering" },

  "pastePlainText": { "message": "Klistra in PlainText" },
  "errorPaste": { "message": "Misslyckades med att klistra in" },

  "noIndent": { "message": "Ta bort indrag av raden" },
  "noIndentDescription": { "message": "Välj för att ta bort inledande blanksteg på varje rad" },

  "keyboardShortcut": { "message": "Tangentbordsgenväg" },
  "keyboardShortcutDescription": { "message": "Välj den önskade tangentbordsgenvägen" },

  "reset": { "message": "Återställ" },

  "errorClipboard": { "message": "Misslyckades med att spara till Urklipp" },

  "about": { "message": "Om" },
  "amo":  { "message": "Firefox begränsar vissa funktioner på vissa URL:er" },
  "error": { "message": "Ett fel uppstod med operationen" },
  "help": { "message": "Hjälp" },
  "options": { "message": "Alternativ" },
  "saveOptions": { "message": "Spara" },
  "settings": { "message": "Inställningar" }
}

[sv messages.zip](https://github.com/erosman/support/files/4740519/sv.messages.zip)

**Comment by erosman** [comment]
Thank you. I will add it to the next release.

**Comment by erosman** [comment]
v1.11 released with above
