### ISSUE TITLE
[FoxyTab] FoxyTab: Move to Private Window but keep original window

### ISSUE THREAD

**Issue by Bamajon1974** [erosman/support#199]
Feature Request for FoxyTab, when moving a window to private window, please add an option to retain the original window, or "copy to private window" in addition to "move to private window". 

Thanks!

**Comment by erosman** [comment]
Normally, when you have tabs in one window and choose to move tab/tabs to a private window, those tabs are closed and same URL is opened in a private window.
The original window remains open as long as there are still tabs.

Do you mean to have the same page in both private and non-private windows?

**Comment by Bamajon1974** [comment]
Correct. Sorry if I was not clear. It would be useful to include options to open a tab (left and/or right tabs) in a private window while either retaining the original tab or closing the original tab. 

Does that make sense? Is that an easy addition to add?

**Comment by erosman** [comment]
At the moment there are these options to move all the tabs on the left of clicked tab and the right of the clicked tab to a private window.

Is it something else that you want?

screen from the next version 2.16 (to be released)
![foxytab 2 16](https://user-images.githubusercontent.com/6458876/84806770-744c8980-b01b-11ea-95f5-5fce9344d614.jpg)

**Comment by Bamajon1974** [comment]
Yes. To support the functionality I want, I can envision two options: 

(1) to the Move menu, below the existing "To Private Window, To Left of Private Window, To Right of Private Window", create a new group reading "To Private Window (retain original window), To Left of Private Window (retain original window) and To Right of Private Window (retain original window)". Change retain to keep or whatever is meaningful.

or 

(2) In the Copy menu, create a new group called "to private window, to left of private window, to right of private window". You don't need to add a (retain original window) phrase because the function in implied in the menu (copy, not move). 

I personally think that option two, add to copy menu, because rather than moving the window, you are making a copy in a new private window. 

Does that make sense? 

Thanks!

**Comment by erosman** [comment]
I am unclear about what you mean by "retain original window"

Do you want to have the same tab/s open in both a private window and a normal window?


> I personally think that option two, add to copy menu, because rather than moving the window, you are making a copy in a new private window.

It is actually not a copy or duplicate. A new tab is created which has different settings (cookies. storage, history etc) due to the private nature than the original ones.

**Comment by Bamajon1974** [comment]
> Do you want to have the same tab/s open in both a private window and a normal window?

Correct. This requested functionality in addition to the existing functionality.

**Comment by erosman** [comment]
I understand now.

Let's see if there is more demand for this feature.

**Comment by Bamajon1974** [comment]
Thank you!

**Comment by Bamajon1974** [comment]
Oh I forgot to ask...what features/changes are being made to the new version of FoxyTab?

**Comment by erosman** [comment]
So far .....

**2.16**
    FoxyTab will not remove Hidden tabs in 'Close Tabs to the Left' any more, unless 'Ctrl' is pressed
    Added Custom Copy All, Left, Right
    Adding new context-menu will retain the disabled items but not the order
    Private Tabs will merge into a private window
    Added Bookmark All Tabs
    Highlighted Tabs will be actioned if there are highlighted tabs
    Added Zodiac Sign to toolbar pop-up
    Minimum version increased to Firefox 63 (released 2018-10-23)
    Added new Custom Copy parameters {yyyy} {mm} {dd} {hostname}
    Added marker to reloading tabs
    New IP database source IP2Location
    Added IPv6 processing
    Updated IP database to 31-Mar-2020
    New flags & icons in page action title
    New flags & icons in browser action title
    Updated Theme section with all available parameters
    Migrated Theme data from IndexedDB to Storage
    Added Tabs Hide Tab, All, Left, Right
    Added Tabs Show All, Left, Right
    Added Tabs Discard Tab, All, Left, Right
    Added Tabs Pin All, Left, Right
    Added Tab Print
    Added Tab Capture
    Added Host Reload
    Added Help Button to pop-up
    Added Clean URL Option to remove tracking strings from Tab URLs (default is true)
    Added Clean URL feature to remove tracking strings from copied Tab URLs
    OOP Code Improvement

**Comment by Bamajon1974** [comment]
Nice. When do you expect to release the new version? Are you planning on updating FoxyImage and FoxyLinks as well?

**Comment by erosman** [comment]
Al the coding is done but not tested. There are a LOT of new code so all functions must be tested individually again (in case of bugs) and that is what is left to do.

**Comment by Bamajon1974** [comment]
Have you considered porting your extensions to Chrome or Edge/Chrome? Although I use Firefox primarily at home, I use Chrome at work. I like how you have condensed many additional browser functions into single add-ons which reduces clutter. Chrome and Edge Chrome could definitely use ChromeyTabs, etc.

**Comment by erosman** [comment]
I don't use Chrome (or other browsers) so there is no point for me.

More importantly, the 'tab' context (to show tab context menu) is not supported by Chrome. There are many of other API that are not supported by Chrome as well.

**Comment by erosman** [comment]
In v2.16

- Added Keyboard 'Alt' option to keep the original tabs when moving to Private Window

**Comment by Bamajon1974** [comment]
Awesome. Is a new version of FoxyTab ready to release yet?

**Comment by erosman** [comment]
I am hoping to release it in a few days.
I am sorry for the long delay as I got busy with other addons but I have been working non-stop on FoxyTab to finish it (and close the open feature requests).

**Comment by Bamajon1974** [comment]
That is great news! I completely forgot that I submitted the in-private tab request. Please keep me posted!
