### ISSUE TITLE
Custom section does not work

### ISSUE THREAD

**Issue by gordhub** [erosman/support#2]
Hi, I've just started using this add-on, and it's working very nicely for the tags it implements.

I wanted to add the `<pre>` tag as a custom tag, since it does a better job than `<code>` of presenting code etc., but the "Custom" section of the sidebar doesn't appear to have any controls to allow the definition of a new tag. 

See the following screen shot:
![firefox_edit_addon_custom_section](https://user-images.githubusercontent.com/25326671/45044194-6a6fb700-b03d-11e8-8ab1-58a1cbad824b.png)

**Comment by erosman** [comment]
The customs tags are added via the option page.

**Comment by gordhub** [comment]
Thanks, that works.
