### ISSUE TITLE
Foxytab thinks I am in Greenwich Time Zone

### ISSUE THREAD

**Issue by TecMunky** [erosman/support#20]
My system clock is in UTC, but I am not in that time zone.  Every other application on my system understands the difference.  But when I click on the FoxyTab icon it shows my location as London.

**Comment by erosman** [comment]
In order to be able to cover all time zones (and not only the local/system time), the time is not set to the local time. It can show multiple time zones so there isn't a default local time zone. You need to set it to the location that you prefer.

**Comment by TecMunky** [comment]
OK - I didn't see a method of changing the time zone before - and even when
I did see it, it was hard to change it.  I had to add a time zone, and then
delete the one for London.  very strange.  anyway - some instructions on
how to do this would be nice - unless i just missed it.

**Comment by erosman** [comment]
In the version with Time/Date, I included the default London Time in the preferences to show the new feature. I subsequently removed it and left it without any.

As you have mentioned, the process is to delete the unwanted one and add a new one. I thought it was understood (by the Bin image) but I can add some notes to the Help to make it clearer.
