### ISSUE TITLE
[FoxyTab] won't reload tabs with dev tools open

### ISSUE THREAD

**Issue by timprint** [erosman/support#201]
Reload all doesn't seem to work for tabs with the web dev inspector open. This has recently stopped working for another add-on so maybe something in Firefox has changed.

**Comment by erosman** [comment]
Thank you for letting me know. I am working on the next update and will test it out.

**Comment by erosman** [comment]
I tested on Nightly and the reload works with open Extension Toolbox, or Developer Tools.

Let me know if you are still experiencing issues.
