### ISSUE TITLE
[FoxyTab] Create Desktop Shortcut fails when site title includes certain characters

### ISSUE THREAD

**Issue by patrickburk1988** [erosman/support#202]
The following characters appear to break the functionality of the Create Desktop Shortcut function whenever they appear in the title of the site:
- `|`
- `<` and/or `>`

For example: Selecting Create Desktop Shortcut for a tab with the site title `My Website - Home` works as expected, bringing up the option to save the shortcut to the desktop. Selecting Create Desktop Shortcut for a tab with the site title `My Website | Home`, however, does nothing.

A couple of real-life examples where Create Desktop Shortcut doesn't work:
- [HCPL | Home](https://hcplky.org/)
- [`<div>`: The Content Division element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div)

I at first thought this might be related to Windows forbidding certain characters (i.e. \ / : * ? " < > | ) in file and directory names, but sites with question marks and colons appear to work fine.

Running Windows 10, Firefox 77.0.1 (64-bit), FoxyTab 2.15.

**Comment by erosman** [comment]
I tested both above links in Windows 7 and there was no problem.
Could it be something to do with Win 10!!??

**Comment by patrickburk1988** [comment]
It very well could be! I'll see if I can find a Windows 7 machine and test it.

I'm almost certain it's the pipe and less- and greater-than symbols at the root of it, though; I can reproduce the bug with any site that has them in the title. And for what it's worth, I tried to create shortcuts for the following:
- [Question mark (?), plus sign (+), asterisk (*)](https://support.google.com/analytics/answer/1034330)
- [Dot (.) and backslash (\)](https://support.google.com/analytics/answer/1034332)

Both the asterisk and backslash seem to work fine with Create Desktop Shortcut.

**Comment by erosman** [comment]
> I'm almost certain it's the pipe and less- and greater-than symbols at the root of it

FoxyTab removes those when making the Desktop Shortcut. Above 2 are saved as:

- HCPL  Home
- div The Content Division element - HTML Hypertext Markup Language  MDN

**Comment by patrickburk1988** [comment]
I'm on a Windows 7 machine now, and the `HCPL | HOME` and `<div>: The Content Division element` sites still aren't functioning with Create Desktop Shortcut.

I'm using a fresh Firefox install with no other extensions or add-ons. Firefox 77.0.1 (64-bit).

**Comment by erosman** [comment]
Are you saving them to a folder?
What is the value in the following? 

**about:preferences#general -> Files and Applications -> Save files to**

**Comment by patrickburk1988** [comment]
I had it set to `Always ask you where to save files`, but the default save location was `Desktop`.

I've done a fresh Windows 10 install and this appears to have fixed the problem; Create Desktop Shortcut strips the Windows-reserved characters as intended. No idea what changed, but hey, I'll take it! 🤔

Thanks again for looking into this!
