### ISSUE TITLE
[FoxyTab] Feature request: Close Tabs to the Right and Close Other Tabs

### ISSUE THREAD

**Issue by constructor-s** [erosman/support#205]
I know this is a duplicate of #54 but the situation has changed. In Firefox 78, the two actions (Close Tabs to the Right and Close Other Tabs) are moved into a submenu: https://www.ghacks.net/2020/06/05/firefox-78-close-multiple-tabs-options-moved-to-submenu/

![Image of the submenu](https://user-images.githubusercontent.com/10003477/86371379-ceba2c80-bc4e-11ea-8167-39fdbb71be13.png)

In my opinion, now if I have to use a submenu, I'd rather train myself the muscle memory to use the FoxyTab submenu. 

Would like to hear your thoughts and whether you will consider adding these two options into FoxyTab now. Thank you!

**Comment by erosman** [comment]
If that is added to FoxyTab, it will be 2 level deep instead of 1 level in Firefox

Close Multiple Tabs -> Close Tabs to the Right
FoxyTab -> Parent-group (close- left-right) -> Close Tabs to the Right

Another issue is duplicating standard Firefox menus. Some users like it and some hate it.

**Comment by constructor-s** [comment]
I see. And I totally agree with the comment regarding duplicating functions, though I don't mind duplicates.

**Comment by blueray453** [comment]
I hope there was a option to remove `Close Multiple Tabs` and `Move Tab` from Firefox. These incomplete features are at this moment is coming in the way of the UX.

We have to remember which menu to use when using `Close Tabs To The Right` (Because `Close Tabs To The Right` comes with Firefox and  `Close Tabs To The Left` comes with other extensions including FoxyTab). This is a major inconvenience. We can disable `Close Tabs To The Right` if we do not want it in FoxyTab. So, it does not hurt to have this option. On that note, please also add `Move To New Window` in FoxyTab.

This way we will not have to wonder around different places for different menu items.

**Comment by erosman** [comment]
> also add Move To New Window in FoxyTab.

Do you mean move tabs on the right/left to a new window?

It is already done for the next version.

**Comment by blueray453** [comment]
@erosman I meant move selected tab to new window. Firefox has this option. You have to right click on a tab, then go to `Move Tab` then `Move To New Window`.

**Comment by blueray453** [comment]
I have `To The Left To New Window` and `To The Right To New Window` in FoxyTab. In my machine both of these behave like I dragged out the tab to create new window. So, this is what I am asking as `Move To New Window`.

What does  `To The Left To New Window` and `To The Right To New Window` suppose to do? What does `New Window` mean in this context?

**Comment by erosman** [comment]
> What does To The Left To New Window and To The Right To New Window suppose to do? What does New Window mean in this context?

They will be closed in the current window and re-opened in a new window.

**Comment by blueray453** [comment]
@erosman sorry, I just checked.

 `To The Left To New Window` moves all the tabs left to selected tab to a new window.
 `To The Right To New Window` moves all the tabs right to selected tab to a new window.

I was requesting for `Move To New Window` that will move selected tab to a new window. (I know Firefox has this feature but I am habituated to search for everything tab inside FoxyTab. Having `Close Tabs to the Right` and `Move To New Window` within FoxyTab will hopefully greatly reduce my cognitive load. I am going to use `userChrome.css` or something to remove 'Move Tab' & `Close Multiple Tabs` from Firefox).

**Comment by erosman** [comment]
I see ... OK.. lets see what can be done in the next upgrade.

**Comment by blueray453** [comment]
@erosman thank you very much.

**Comment by erosman** [comment]
@blueray453 The selected/highlighted parameter is already implemented in the **next version** which means:

### Single, All, Left, Right & Highlighted


- Single actions relate to the right-clicked tab
- All actions relate to the every tab in active window
- Left|Right actions relate to the tab to the left or right of the right-clicked tab
- Highlighted tabs takes priority in 'All' actions which means if there are highlighted tabs (besides the active tab), the action will apply to the highlighted tabs

**Comment by erosman** [comment]
As in v2.16
- Removed "Close Tabs to Left" as is built-in since Firefox 88
