### ISSUE TITLE
please make firemonkey compatible with Firefox for Android 

### ISSUE THREAD

**Issue by ale82to** [erosman/support#206]
i installed firemonkey forcing desktop user agent but in Firefox for Android is not working at all.
(old Firefox version 68.10 not fenix).

**Comment by erosman** [comment]
TBH, I haven't worked on Firefox for Android for any of my extension (as I dont use it myself). Many APIs are not available on Firefox for Android. I have to see if it is possible.

**Comment by ale82to** [comment]
thank you very much!

**Comment by erosman** [comment]
Use #238 for further discussion
