### ISSUE TITLE
Text MultiCopy: bug and missing features

### ISSUE THREAD

**Issue by Vagmer** [erosman/support#21]
Hey. Good extension idea!

I just installed it on Firefox on Windows 10 and noticed an apparent bug: although the default divider is
`[newline] ----------------------------------------[newline][newline]`

Upon copying a bunch of text blocks from the same page, I get the the result with only the dashes as the separator, so the different blocks I'd copied are dumped on same lines. So basically, newlines within the divider seem to be ignored. I tried to change each [newline] to a double one ([newline][newline]), which made no difference.

On another note, there should probably really be features for clearing the current saved text (should probably ask for a confirmation for that one, by default) and viewing it (without modifying the clipboard) in a modifiable text field dialog (where you can edit and save if you want). Viewing/editing having an optional hotkey would be useful too.

**Comment by erosman** [comment]
The issue you are referring to is the system newline. On browsers and in textarea (the divider box) \n is used for newline.

```
Windows: "\r\n", 
 Mac: "\n", 
 Linux: "\n"
```

If you open the saved text in an application that is aware of this (most editors like Notepad++, etc), they will show as newline but MS Notepad isn't aware of it. If you open the saved document with Wordpad or MS word, it will show the \n as newline.


As far viewing, editing, that is a possibility and not a bad idea.  I will consider it for the next upgrade.

**Comment by Vagmer** [comment]
Thanks for the (blazingly fast!) reply. ):

Ah, I see, yeah, that is the case, and I was testing in Notepad. Surely, there is a way to do it right globally and include an actual newline, though. At worst it seems as easy as running a find&replace on the text in the divider box for "\n" and [newline], after reading it. Copied newlines in the actual selected text blocks are already received with no issue in Notepad.

Oh, I guess it would also be useful to have an option not to auto-clear the extension's saved text upon copying. Leaves it there as a kind of backup, and there would also be a separate clear menu. You could even optionally keep a saved text history, though that may be extraneous.

**Comment by erosman** [comment]
Keeping an archive gets complicated as they are appended together and can get very large.

I will see what improvements I can make on the newline for the next version.

You can open it in Wordpad and save it. It will change the newlines to Windows newline.

**Comment by Vagmer** [comment]
Thanks.

> Keeping an archive gets complicated as they are appended together and can get very large.

Yeah, that one is a bit less practical and probably not really worth the effort.

**Comment by erosman** [comment]
I added the option to view and delete saved data. It will be in the next upgrade.

**Comment by erosman** [comment]
Just to let you know, a lot of new features are coming to v2.8
Custom Copy, Check & Edit Saved Data, Export Saved Data as file

I have already added them to the add-on description
https://addons.mozilla.org/en-US/firefox/addon/text-multicopy/
