### ISSUE TITLE
[FoxyTab] Feature request: Sort by time.

### ISSUE THREAD

**Issue by bobmcn** [erosman/support#211]
It would be great to be able to sort tabs by whatever timestamps are available, such as when they were first opened, when they were last accessed, or when they were last reloaded.

Thanks.

**Comment by erosman** [comment]
That should be possible. One concern with any new feature request is the number of menus.

FoxyTab has many already and there are more coming in the next upgrade (#199).

Let's see if there is a popular demand for this feature.

**Comment by erosman** [comment]
The only timestamp that is available directly is `lastAccessed: 1649436196798`.

I can add the **Sort by last Accessed**, but how much demand is for that?

**Comment by bobmcn** [comment]
I could see that being useful for cleaning up old tabs.
