### ISSUE TITLE
contextual menu shortcuts enhancement

### ISSUE THREAD

**Issue by foxfoxgo** [erosman/support#212]
Hi,

first thank you for this very useful and friendly add-on!

I would like to know if it is possible to move at least one of the FoxyTab contextual menu shortcut in the main page contextual menu?

FoxyTab options appear when we click on a tab plus they are all organised in a menu folder; what I would need is one of these shortcuts to appear in the main Firefox contextual menu when I right-click anywhere on a page. Maybe it's already possible or maybe this will never happen due to FF new webext restrictions...

Another possibility : 

I also read in an other post that you feel that defining a 3-key keyboard shortcut for a task would not be enough user-friendly. Maybe for one or two tasks we use very frequently that will still be very useful. (plus, as for me but I'm sure I'm not the only one, except for one or two FF shortcuts I mainly use none of those predefined.)

For example, the shortcut I'm using the most is 'send shortcut to desktop' and I very feel that pressing ctrl+alt+s, for example, is way more friendly and faster than right-click/move to foxytab folder/move to send shortcut and click...

Anyway, looking forward for your feelings and keep the good job!

**Comment by erosman** [comment]
> I would like to know if it is possible to move at least one of the FoxyTab contextual menu shortcut in the main page contextual menu?

That is not possible. Firefox restricts each extension to a single menu item.

> I also read in an other post that you feel that defining a 3-key keyboard shortcut for a task would not be enough user-friendly. Maybe for one or two tasks we use very frequently that will still be very useful.

It is possible to add keyboard shortcuts to FoxyTab. However, there are many functions and not practical to assign a keyboard shortcut for all of them, and each user may have different favourite functions.

**Comment by erosman** [comment]
In v2.16

- Added Context-menu to Toolbar Icon
- Added Keyboard Shortcuts option
