### ISSUE TITLE
[Copy PlainText] not working with some style

### ISSUE THREAD

**Issue by Barticf** [erosman/support#213]
Hi, sometimes it's not working with some kind of style. Still copy bold text etc.

sample:
https://www.facebook.com/scantraxx/photos/a.443855053130/10157573765083131/ - problem with ‘𝗟𝗶𝘃𝗲 𝗧𝗵𝗲 𝗠𝗼𝗺𝗲𝗻𝘁’ & ‘𝗠𝗮𝗸𝗶𝗻𝗴 𝗠𝗲𝗺𝗼𝗿𝗶𝗲𝘀’

https://www.facebook.com/officialdjstephanie/photos/a.10151879712552146/10158221094677146/ - entire text

**Comment by erosman** [comment]
Facebook JavaScript is notorious and overrides a lot of functions. It is strange but I will do more testing to see what can be done.

**Comment by erosman** [comment]
I am working on the next upgrade (v1.14) of the extension.
I am looking int this issue.

**Comment by erosman** [comment]
I am working on the next upgrade (v1.14) of the extension.

After a closer look, the text on that post is not a normal formatted text.
They are Unicode characters and that is how they look unformatted.

> 𝑫𝒆𝒂𝒓 𝒇𝒓𝒊𝒆𝒏𝒅𝒔 𝒇𝒓𝒐𝒎 𝒕𝒉𝒆 𝒉𝒂𝒓𝒅𝒔𝒕𝒚𝒍𝒆 𝒇𝒂𝒎𝒊𝒍𝒚,
𝑰'𝒎 𝒑𝒓𝒐𝒖𝒅 𝒕𝒐 𝒂𝒏𝒏𝒐𝒖𝒏𝒄𝒆 𝒕𝒉𝒂𝒕 𝒐𝒏 8𝒕𝒉 𝑴𝒂𝒓𝒄𝒉, 𝑰𝒏𝒕𝒆𝒓𝒏𝒂𝒕𝒊𝒐𝒏𝒂𝒍 𝑾𝒐𝒎𝒆𝒏'𝒔 𝑫𝒂𝒚, 𝑰'𝒗𝒆 𝒅𝒆𝒄𝒊𝒅𝒆𝒅 𝒕𝒐 𝒍𝒂𝒖𝒏𝒄𝒉 𝒂𝒏 𝒂𝒍𝒍-𝒇𝒆𝒎𝒂𝒍𝒆 𝑬𝑷.


You can find sites that make such texts, by searching Google for "Unicode bold italic text".
