### ISSUE TITLE
"@match" requires first char to be duplicated

### ISSUE THREAD

**Issue by hunkjazz** [erosman/support#217]
**actual behavior**
`@match example.com` ---- _translates to_ ----> ` *://xample.com`

**expected behavior**
`@match example.com` ---- _translates to_ ----> ` *://example.com`

**hacky solution**
`@match eexample.com` ---- _translates to_ ----> ` *://example.com`

**Comment by erosman** [comment]
Thank you. I will fix it.

**Comment by erosman** [comment]
Please note that `@match                 example.com` is not a valid `@match`.
FireMonkey attempts to fix some invalid `@match`.

- [Metadata Block](https://wiki.greasespot.net/Metadata_Block#.40match)
- [Match Patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/match_patterns)
- [Match Patterns](https://developer.chrome.com/extensions/match_patterns)

**Comment by hunkjazz** [comment]
I guess I missed the scheme part, right?

`*://*.example.com/*`

**Comment by erosman** [comment]
> I guess I missed the scheme part, right?

Correct, valid `@match` must have scheme.
