### ISSUE TITLE
FireMonkey question

### ISSUE THREAD

**Issue by EstherMoellman** [erosman/support#218]
Hi @erosman ,

Please, can you confirm me if this small script attached below is compatible with FireMonkey and if it'll work?

Thanks in advance and big hug! : )

PS: Some info about the script:
Copyright © 2016–2017 Daniel Aleksandersen
SPDX-License-Identifier: GPL-3.0
License-Filename: LICENSE
Tell websites that you prefer to save data and costs. At websites’ discretion, you may see lower quality images and fewer media elements as webpages adjust to reduce data downloads.
The script works by sending the Save-Data: on HTTP header with every request.

```js
/*
==UserScript==
@name Save-Data: on
@match         *://*/*
@description Automatically enable data-savings mode at compatible websites.
@version        1.0
@run-at         document-start
==/UserScript==
*/

// Mozilla WebExtension or Chromium Extension
if (typeof browser === 'undefined' && typeof chrome !== 'undefined') {
  browser = chrome;
}

browser.webRequest.onBeforeSendHeaders.addListener(
  function(details) {
    var headers = details.requestHeaders;
    
    // Check if browser or another extension has already enabled the header
    for (var index = 0; index < headers.length; ++index) {
      if ('name' in headers[index] &&
          headers[index].name.toLowerCase().indexOf('save-data') >= 0) {

        // Return the original headers
        return {
          requestHeaders: details.requestHeaders
    } } };

    // Append the actual header
    headers.push({
      'name': 'Save-Data',
      'value': 'on'
    });

    return {
      requestHeaders: details.requestHeaders
    };
  }, {
    urls: ["<all_urls>"]
  }, [
    "blocking",
    "requestHeaders"
  ]
);
```

**Comment by erosman** [comment]
This code will not work as user-script in any script manager.

That code belongs to an extension. The APIs used are only available to extensions and not available to user-scripts e.g. 
`browser`, `chrome`, `browser.webRequest.onBeforeSendHeaders.addListener()`
