### ISSUE TITLE
Default profile/container is malfunctioning. How do I reset that container?

### ISSUE THREAD

**Issue by fishcymbal** [erosman/support#219]
I have a couple websites that I visit frequently that just don't work when I open them with the default profile/container. They DO work fine if I open the same site under a different container. How do I figure out which files to clear out and start again? Or, can I make one of the other containers the default?

**Comment by erosman** [comment]
Everything about the Containers (e.g. name, order etc) are handled by Firefox.
FoxyTab adds a feature to enable you to set domain rules for them.

There is no default container per se. 
If you want to reset them, just delete the domains that you have added and then click **SAVE**.

My guess is that there is a rule that catches the domains that you don't want.
If you post the entries in the Container section of FoxyTab, I can check to see if there are any problems.
