### ISSUE TITLE
FoxyTab: extension's submenu missing under tab right-click context menu

### ISSUE THREAD

**Issue by Vagmer** [erosman/support#22]
I'm guessing this started for me after the latest Firefox update, or another one. Basically I don't see the FoxyTab context menu submenu anymore, even though I haven't changed my settings and all the context menu items are still enabled (not sure if you can even disable the whole submenu itself).
![image](https://user-images.githubusercontent.com/12949474/47956251-34ea3a00-dfaa-11e8-8b16-a3a5512b1389.png)

**Comment by erosman** [comment]
That is strange. Is **FoxyTab** still in `about:addons` and enabled?

**Comment by Vagmer** [comment]
It's there and enabled. The options page works, and for what it's worth so does the tab recount on the FoxyTab icon (visible in my screenshot).
I'll maybe try disabling (or uninstalling) then restarting Firefox and enabling again later, might fix a transient issue. I just kinda have a ton of tabs and windows open right now.

**Comment by Vagmer** [comment]
Okaaayy... disabling and reenabling fixed it in 3 seconds flat with no restarting needed. Whoops? Maybe you'd have wanted to try debugging it, but it's the problem seems to be gone for me for now. Could just be a Firefox quirk.

**Comment by erosman** [comment]
Good... I was going to suggest disable/enable  which you did anyway.

**Comment by erosman** [comment]
Oops .... I found the problem ... uploading v2.13
