### ISSUE TITLE
[FoxyTab] Feature Request: Option to prevent the Sort feature from sorting pinned tabs

### ISSUE THREAD

**Issue by lazuratus** [erosman/support#220]
I don't want my pinned tabs to be sorted... would it be possible to get an option to prevent the **Sort** feature from sorting pinned tabs?

**Comment by erosman** [comment]
OK... I will work on it.

**Comment by erosman** [comment]
In v2.16

- Added Keyboard 'Alt' option to prevent sorting of pinned tabs
