### ISSUE TITLE
[FoxyTab] Feature Request: Option to make tab count specific per window

### ISSUE THREAD

**Issue by SomewhatOrangish** [erosman/support#222]
Please give us the ability to make the tab counter display tab count on a window by window basis. 
Thanks!

**Comment by erosman** [comment]
OK... I will work on it

**Comment by SomewhatOrangish** [comment]
> 
> 
> OK... I will work on it

Thank you!

**Comment by erosman** [comment]
It is done and will be in the next update (when it comes out).

**Comment by erosman** [comment]
In v2.16

- Updated Tab count to show per window

**Comment by SomewhatOrangish** [comment]
> In v2.16
> 
>     * Updated Tab count to show per window

Thank you! This is perfect!

**Comment by the456gamer** [comment]
how can i revert this to previous behaviour?
I cannot find the option described in the original issue

thanks

**Comment by erosman** [comment]
> how can i revert this to previous behaviour?
> I cannot find the option described in the original issue

There is no option for it at the moment. If there is a popular demand, I will see what can be done.

**Comment by erosman** [comment]
In v2.20
- Added All Windows option to Tab Counter
