### ISSUE TITLE
Replace-Addon: How to automate?

### ISSUE THREAD

**Issue by imperatom** [erosman/support#223]
I'd like to change texts automatically in websites. So I'd like to store some text phrases and their replacements in my addon to let them be searched and replaced in every website I visit automatically.

Is there any chance for that?

**Comment by erosman** [comment]
TBH, I wrote replace upon a request by a user. I have not worked on it for a long time.

It is possible to add such a feature if there is popular demand for it.
I will see when I try to update Replace next.

**Comment by erosman** [comment]
BTW, the same can be done with a user-script.

**Comment by imperatom** [comment]
> BTW, the same can be done with a user-script.

In tampermonkeye e.g.?
Unfortunately I don't have the skills to write one.

**Comment by erosman** [comment]
> In tampermonkeye e.g.?

GreaseMonkey, ViolentMoneky, TamperMoneky or my own [FireMonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/).

> Unfortunately I don't have the skills to write one.

There should be some user-scripts available already on [GreasyFork](https://greasyfork.org/).
It is a simple job and doesn't need a big script.
