### ISSUE TITLE
FoxyTab: feature suggestion: Reverse Tab Order

### ISSUE THREAD

**Issue by gthb1** [erosman/support#224]
Hi!
FoxyTab has so many wonderfully-useful features!

But I miss this one a lot:
Reverse Tab Order of all open tabs (tab1, tab2, tab3...tab9997, tab9998, tab9999 hence becomes now tab9999, tab9998, tab9997...tab3, tab2, tab1).
Further nuances of this feature could have the 'before' / 'after' 'current tab' variations, etc.

Thank you very much for your kind consideration!
:)

**Comment by erosman** [comment]
That is possible and depends on popular demand.

I am working on many new features and therefore there will be many new menus (#199).

**Comment by erosman** [comment]
Done in v2.16
