### ISSUE TITLE
No Tab Reload with Firefox

### ISSUE THREAD

**Issue by ggikthuo** [erosman/support#225]
Hi,

tried FoxyTab to reload tabs while I'm busy and page has timeout. Hope I got it right, that FoxyTab function works like this. I logon to a webpage, rightclick on a tab and select **reload every 3 minutes**.
But when I come back to the page after timeout, I have been logged off.
What do I understand wrong? What settings do I need for firefox 78.2.0esr (Windows 10 pro 64bit)?
I tried with FoxyTab as the only active addon. 
Have you any idea?

**Comment by erosman** [comment]
First, can you check if the tab reloads?
Set it to one minute or shorter and then watch it to see if it reloads.

If it reloads, then there is no issue with **FoxyTab** and the issue is with the page logging you off for some reason.

**Comment by ggikthuo** [comment]
Thanks for your immediate response. I did what you recommended and FoxyTab works! Nevertheless I was logged off from some webpages. So they seem to work around the reload trick, narrow-minded, they'l never learn.
So unfortunately FoxyTab is not what solves my problems, but it's not an behalf of FoxyTab.
One hint I have anyway: It would be helpful, if you could show up which page has which reload option set.
Thanks for your help.
