### ISSUE TITLE
Bug: Importing changed scripts via Options not possible (only by drag & drop)?

### ISSUE THREAD

**Issue by clsven** [erosman/support#226]
I observed that I cannot import any more *.user.js script(s) through the "Import" button in Options pane of FireMonkey.
Neither a single nor multiple files at once.

The only way of updating is through drag & drop.

I tried it on two different computer with 64bit Firefox 80.0.1 on 64bit Win7

Possibly Mozilla changed the API?

Can I verify that?

Claudia

**Comment by erosman** [comment]
Oops.. sorry, there is an error in the code.

I have fixed it and I will upload a new version shortly.

Thank you for reporting it. :+1:

**Comment by erosman** [comment]
v1.38 uploaded
