### ISSUE TITLE
[FoxyTab] Feature Request: close tabs from duplicate second-level domain

### ISSUE THREAD

**Issue by sallzt** [erosman/support#227]
Hi! I love FoxyTab, but there's one feature I'd use all the time if it were implemented, and that's an extension of the 'Close Duplicate Tabs' feature. Specifically, an option to close all tabs from the same second-level domain (e.g. startpage.com) would be so useful! I often leave a lot of search result tabs open, mixed about among all my other tabs, and managing them gets to be quite the pain, even with the wonderful sorting options afforded by this extension.

Another possibility to consider would be extending Sort to group tabs of the same second-level domain together at the end, you could then reuse the existing Close Multiple Tabs functionality to the same end.

**Comment by erosman** [comment]
> Specifically, an option to close all tabs from the same second-level domain (e.g. startpage.com) would be so useful! 

There is the option under **Host** menu which you can close all, keep all (and close others), keep one and close other from the same host, and reload
However, the Host means the hostname so `www.example.com` is not the same as `example.com`


> Another possibility to consider would be extending Sort to group tabs of the same second-level domain together at the end, you could then reuse the existing Close Multiple Tabs functionality to the same end.

There is a practical problem with that sort.

For example ie domains were A, B, C... and same domain tabs were A1, B1, etc


The current tabs :

A B C A1 B1 B2 A2 C1 C2 B3

If we want to sort B, where to put them after they are sorted? At the start, at the end,.... it will inevitably reorder other tabs.

PS. Please note there will also be a lot of new features in the next version (info #199)

**Comment by sallzt** [comment]
that's so cool! 
I guess I didn't read the documentation thoroughly enough, that feature is exactly what I wanted
