### ISSUE TITLE
[FireMonkey] Stylus .json Import Missing

### ISSUE THREAD

**Issue by eberhardweber** [erosman/support#228]
The navigation button for "Import from Stylus" seems to be missing on FireMonkey 1.38 - I only see "Import" and "Export" at the bottom left of the options column. The help file mentions the "Import from Stylus" together with the aforementioned so I assume it should be adjacent.

I tried using the available "Import" button and changing the filetype to "All" to bring in the exported .json file but that doesn't work. Is this feature supposed to be in the current build?

**Comment by erosman** [comment]
> The navigation button for "Import from Stylus" seems to be missing on FireMonkey 1.38

There is no extra navigation button. **Import** can import `js/css` and `json`.

> I tried using the available "Import" button and changing the filetype to "All" to bring in the exported .json file

That is correct

> but that doesn't work.

If it doesn't work, then there could be an issue. I wrote the import based on the export of Stylus back in 2017.
They may have changed their export format, or there might be some other issue.

I can test it and fix any issues, if you can get me a sample file to test.

**Comment by linsui** [comment]
Hi, when I try to import a Stylus file, I found that the import function only support .js and .css. Then I do the same thing as

> I tried using the available "Import" button and changing the filetype to "All" to bring in the exported .json file

But nothing happened. Here is an example

```
{
	{
		"enabled": true,
		"updateUrl": null,
		"md5Url": null,
		"url": null,
		"originalMd5": null,
		"installDate": 1594467081400,
		"name": "duckduckgo.com",
		"sections": [
			{
				"code": ".is-not-mobile-device .site-wrapper,\n.is-not-mobile-device .serp__results,\n.is-not-mobile-device body,\n.is-not-mobile-device {\n    min-width: 0;\n}",
				"domains": [
					"duckduckgo.com"
				]
			}
		],
		"updateDate": 1594467683900,
		"_id": "e30d37eb-fa92-43e9-95c9-7ab78c82766a",
		"_rev": 1594469006100,
		"id": 37
	}
}
```

**Comment by erosman** [comment]
> I wrote the import based on the export of Stylus back in 2017.
> They may have changed their export format, or there might be some other issue.
> 
> I can test it and fix any issues, if you can get me a sample file to test.

I need a sample json from Stylus to test it.

**Comment by linsui** [comment]
Hi, I have paste a sample json with one style exported from Stylus above. Could you please also fix the supported file type issue? Thanks!

**Comment by erosman** [comment]
I will test it and get back to you.

**Comment by erosman** [comment]
Is the above sample accurate?

Sections used to have "urls", "urlPrefixes", "domains", "regexps".

From 2017 Stylus export

```js
    "sections": [
      {
        "code": "/* Bigger Textarea */\ntextarea { height: 100px !important; }",
        "urls": [],
        "urlPrefixes": [
          "http://www.glitter-graphics.net/graphics/"
        ],
        "domains": [],
        "regexps": []
      }
    ],
```

But above example does have all of them

```js
    "sections": [
      {
        "code": ".is-not-mobile-device .site-wrapper,\n.is-not-mobile-device .serp__results,\n.is-not-mobile-device body,\n.is-not-mobile-device {\n    min-width: 0;\n}",
        "domains": [
          "duckduckgo.com"
        ]
      }
    ],
```

**Comment by linsui** [comment]
Yes, only one of them is included. If I change to match with url prefix then only urlPrefixes is included.

**Comment by erosman** [comment]
Before the `json` for each `sections` included all parameters, even if they were empty array e.g. `[]`

Now they dont!?
Stylus `json` only includes the ones that have something, correct?

I have already updated the FireMonkey code.
If you confirm that and then I will upload a new version.

**Comment by linsui** [comment]
Yes, I can confirm it! Thanks!

**Comment by erosman** [comment]
v1.41 uploaded
Let me know if there are any issues.

**Comment by linsui** [comment]
It works well. Thanks!
