### ISSUE TITLE
[Copy PlainText] "Windows" key for shortcuts

### ISSUE THREAD

**Issue by pcarrillo-dev** [erosman/support#229]
Please, include "Windows" key as an option for keyboard shortcuts.

**Comment by erosman** [comment]
Unfortunately, Firefox wont allow it.
[Shortcut values](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values)

**Comment by pcarrillo-dev** [comment]
What a pity. Thanks for the info.
