### ISSUE TITLE
After upgrading FoxyTab to 2.12 disappeared Context Menu.

### ISSUE THREAD

**Issue by FoxyTabuser** [erosman/support#23]
Hello!
Thanks for the extension, but after upgrading FoxyTab to 2.12 disappeared Context Menu. Firefox 63.0.1 64-bit, Windows 7 64-bit.
![2018-11-04_031106](https://user-images.githubusercontent.com/44734953/47957451-41898500-dfe0-11e8-8175-764774483156.jpg). Restore Defaults in Context Menu does not help.

**Comment by erosman** [comment]
Someone else also complained about the same. Disable/Enable FoxyTab from `about:addons` and it will come back.

I have no idea why that is happening.

**Comment by FoxyTabuser** [comment]
Thanks for the fast response - in version 2.13 everything works.
Muchas gracias, erosman!

**Comment by erosman** [comment]
> Using 2.14.1 and FF Nightly 66.0a1 (2019-01-14) (64-bit) on Mac. Same issue.

Is anyone else having this issue?
I am on 66.0a1 (2019-01-14) (64-bit) Windows and no problem.

You can try Exporting Preferences, disable/enable FoxyTab, or finally uninstall/reinstall to see what happens.
Check if there are any errors logged to the console. when enabling.

**Comment by jpinnix** [comment]
Interesting. Upon disable/enable this warning came up in the console: "Warning: attempting to write 4300 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes."

I tried exporting prefs, disable/enable, and uninstall/reinstall before posting the comment above.

**Comment by erosman** [comment]
That warning is general and happens when extension n have large amount of user data.

Lets see what happens with the next Nightly. I don't use Mac to see what is going on :(
