### ISSUE TITLE
FoxyTab: Trigger Action

### ISSUE THREAD

**Issue by ThomasSeeker** [erosman/support#230]
I am looking for a way to trigger the "Reload Tabs To the Left"-Action  via a toolbar-button and without needing to go through the menu.

A keyboard-shortcut or some command from an external script would work, I guess. Can you help here?

Thank you for the Addon!

**Comment by erosman** [comment]
> I am looking for a way to trigger the "Reload Tabs To the Left"-Action via a toolbar-button and without needing to go through the menu.

Sadly, Firefox only allows ONE menu item so everything has to come under one menu as a sub-menu.

> A keyboard-shortcut or some command from an external script would work,

That is possible in principle. However, FoxyTab has many actions (more coming in the next update) and it is not feasible to have a keyboard-shortcut for all of them and everyone has a different favourite action.

Once I am done with the current update, I can look into maybe setting a **selectable action** for **keyboard-shortcut**.

**Comment by ThomasSeeker** [comment]
"Once I am done with the current update, I can look into maybe setting a selectable action for keyboard-shortcut."

This would be wonderful!

Is there a way to get notice, when the time comes?

**Comment by erosman** [comment]
To be very honest, with the current pandemic climate, the development has become rather slow and there are a lot of new function (some info #199) . :facepalm:

**Comment by ThomasSeeker** [comment]
Ok, thank!
I keep my fingers crossed! ;-)

**Comment by erosman** [comment]
Previously #212 

In v2.16

- Added Context-menu to Toolbar Icon
- Added Keyboard Shortcuts option

**Comment by ThomasSeeker** [comment]
Thank you very much! 
:-)
