### ISSUE TITLE
FoxyTab: Context Menu 

### ISSUE THREAD

**Issue by blueray453** [erosman/support#231]
I am using FoxyTab with firefox.

Please add option to rename context menu elements.

For example, Copy has options:
```
URLs All
URLs to the Left
URLs to the Right
```
If I move them up one level then I no longer know what I am doing with the URLs. I would like to rename them to
```
Copy URLs All
Copy URLs to the Left
Copy URLs to the Right
```
Another thing. All submenu items (Copy, Bookmark, Sort...)  are under FoxyTab menu. It will be great if we could place the menu items in top level (In parallel to FoxyTab menu, So that we do not frequently have to enter FoxyTab menu).

**Comment by erosman** [comment]
> Please add option to rename context menu elements.

Names come from the language local for each language.

Some of the names will get very long if everything from parent menu is added to submenu.

Let's see what can be done .....

> Another thing. All submenu items (Copy, Bookmark, Sort...) are under FoxyTab menu. It will be great if we could place the menu items in top level (In parallel to FoxyTab menu, So that we do not frequently have to enter FoxyTab menu).

That is not possible. Firefox only allows ONE menu for each extension and everything has to come under it.

**Comment by blueray453** [comment]
If you can give us the option then I will rename within the given length.

**Comment by erosman** [comment]
Next version will have the word copy in the sub-menus eg

```
Copy URLs All
Copy URLs to the Left
Copy URLs to the Right
```
