### ISSUE TITLE
FireMonkey as WebExtension for Chrome?

### ISSUE THREAD

**Issue by clsven** [erosman/support#232]
Are there any plans to develop a Chrome(ium) compatible FireMonkey WebExtension?

If not:

Is there a Chrome Extension which is fully compatible with Firemonkey *.user.js scripts?

E.g. GM_addStyle() function is not working with Tampermonkey

**Comment by erosman** [comment]
> Are there any plans to develop a Chrome(ium) compatible FireMonkey WebExtension?

No. FireMonkey uses a dedicated secure Firefox API which is not available in Chrome or others.

> Is there a Chrome Extension which is fully compatible with Firemonkey *.user.js scripts?

Any user-script manger should work.

> E.g. GM_addStyle() function is not working with Tampermonkey

[TamperMonkey documentation](https://www.tampermonkey.net/documentation.php) says it is supported.
