### ISSUE TITLE
How to find bad CSS and javascript statements within Firefox?

### ISSUE THREAD

**Issue by pstein** [erosman/support#233]
It happens sometimes that I wrote and apply buggy CSS & Javascript/jQuery scripts into a webpage.

An errorneous CSS rule could be

`.myclassname { width: 1024kk !important; }};`

or a javascript

`var pane = document.getElementsByClassName("page-header-meta")[0];`

which does not find at least 1 instance of the class.

So the remaining statements of such a scripts are not executed.

How can I find out (in Firefox) which statement is causing the trouble?

Keep in mind that "normal" online CSS verifier services like 
https://jigsaw.w3.org/css-validator/ 
do not find errors in GM_addStyle() statements like:

`GM_addStyle(" myclassname{ padding-top: 0ppp; !important; }")};`

since they do not understand GM_addStyle() function.

So I need the error statement resultuing from execution in Firefox.

The webdeveloper pane at the bottom of Firefox is not really useful.

I have problems finding in it errors or warnings which come from my focussed *.css or *.user.js script (errors from other *.css and *.user.js) should be excluded.

How can I achieve a better/faster error search?

Peter

**Comment by erosman** [comment]
JavaScript compile errors in the user-script usually appear in  Browser Console (`Ctrl + Shift +J`) with a line number and a clickable link to the blob (with some string name)

Example   
(The first line is an error in user-script line 30)

![firemonkey-script-error](https://user-images.githubusercontent.com/6458876/93611927-2497a880-f9e4-11ea-83fc-297695f17c08.jpg)


The CSS error can be checked in Developer Tool (`F12`) for the page that the CSS is injected into.
You can check **Style Editor** tab and the injected CSS shows as `<inline style sheet #...>`
