### ISSUE TITLE
FireMonkey: Cannot save template when syntax highlighting is disabled

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#235]
As we [discussed before](https://github.com/erosman/support/issues/185), I disabled syntax highlighting. When I try to save a template, I got a popup saying "Meta Data Error". I debugged a bit and found the error comes from `Script.saveTemplate()` in options.js:
```
    const box = this.box;

    const metaData = box.textContent.match(Meta.regEx);
>   if (!metaData) { Util.notify(chrome.i18n.getMessage('errorMeta')); return; }
```
The reason is that `box.textContent` is `null`, and because `box` is pointing to the `pre.box`, which only has content when syntax highlighting is enabled. When disabled, it is the `<textarea>` next to it that has the text.

**Comment by erosman** [comment]
You are right. I will fix that.

Thank you for reporting it.

**Comment by erosman** [comment]
Fixed in v1.39 ... I will upload it soon.

**Comment by CrendKing** [comment]
Thank you so much for also "Saving Template will only trim the start" :-) I was wondering if I should bring this up but hesitated if that's too trivial to bother you.

**Comment by erosman** [comment]
Feel free to make any suggestions, big or small. :)

**Comment by erosman** [comment]
I decided to use CodeMirror. It will be in v1.48

**Comment by CrendKing** [comment]
holy moly! It would worth a v2.0 release 😉

**Comment by erosman** [comment]
Indeed... I changed it to 2.0
Ref #258
