### ISSUE TITLE
FireMonkey: Export in compatible format for other managers

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#236]
Well, I got [your message](https://github.com/erosman/support/issues/235#issuecomment-702709665), so here's a suggestion. I think FireMonkey is easily the best user script and CSS manger in Firefox by miles, but unfortunately it is not available in Chrome (I think it is because Chrome lacks the necessary API, right?) For people who have to use Chrome for various reasons, and writes their own scripts, syncing updates between the browsers is tedious. I think implementing a full scale cloud syncing mechanism between Firefox and Chrome for this is overkill, but can you at least export the scripts in a compatible format?

All other user script managers pack all the scripts as .js files in zip file, along with some addon-specific setting files. They can also import the zip exported by other addons (ignoring the setting files). When I export in FireMonkey, it just dumps all files on my desktop without even asking for a path (because the `saveAs` parameter is always false in `exportAllScript()`).

In order to import user scripts in other managers, I need to first make sure the metadata block are using `//` instead of `/* */` (which is exclusive in FireMonkey). Then zip all .js files. It is tedious, but still doable.

In order to import user CSS in Stylus or Stylish, I need to put all the content of .css files into a JSON, which is pretty much not doable. Manually copy paste would be easier. But it is relatively easy from FireMonkey since you got all the metadata in structured objects.

Also, since all other managers can only handle either scripts or CSS, it might be a good idea to export script and CSS separately.

So what do you think?

**Comment by erosman** [comment]
> unfortunately it is not available in Chrome (I think it is because Chrome lacks the necessary API, right?) 

Correct.. there is no [userScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts) API in Chrome. I personally asked for a secure API and it was developed by Mozilla engineers.


> can you at least export the scripts in a compatible format?

You can export scripts in normal `.user.js` script and then import them but it is tedious.

> All other user script managers pack all the scripts as .js files in zip file

It requires additional zip library and then the export/import functions are not universal in verious script-managers.

> When I export in FireMonkey, it just dumps all files on my desktop without even asking for a path (because the saveAs parameter is always false in exportAllScript()).

The alternative is a nightmare, when exporting 20+ files and getting 20+ pop-up dialogue. It is not possible to maintain the last used folder for the subsequent saveAs.

> I need to first make sure the metadata block are using `//` instead of `/*    */` (which is exclusive in FireMonkey). 

For scripts many still use `//` all the time for compatibility.
For CSS you have to use `/*    */`


> In order to import user CSS in Stylus or Stylish...

Sadly, they are incompatibility issues.

> Also, since all other managers can only handle either scripts or CSS, it might be a good idea to export script and CSS separately.

Ooops.... I just noticed a problem with export... I will fix it now

**Comment by CrendKing** [comment]
> It requires additional zip library and then the export/import functions are not universal in verious script-managers.

I tested Greasemonkey, ViolentMonkey and TamperMonkey. They all accept zip file with those .user.js stuffed in it. I know it's not standard, but probably covers 99% of non-FireMonkey world. I don't know how big zip library is. But shouldn't Firefox provide some zipping API?

> The alternative is a nightmare, when exporting 20+ files and getting 20+ pop-up dialogue. It is not possible to maintain the last used folder for the subsequent saveAs.

Of course, if there is only one zip file to download ... ;-)

> Sadly, they are incompatibility issues.

I know they don't accept the UserCSS metadata. What I meant is if you can parse the text, extract the metadata, convert to their format, then write as JSON. Hmmm, thinking about, it's probably some good amount of work...

**Comment by CrendKing** [comment]
> Ooops.... I just noticed a problem with export... I will fix it now

Oh, now they are cleanly organized in one directory. Thanks.

**Comment by erosman** [comment]
> How did no one report these problems before? No one ever export scripts besides me?

Initially, they would go into a folder, then ....

In v1.36 **Remove disallowed characters from file-names when saving**

However, I forgot about folder so `FireMonkey/abc.user.js` will become `FireMonkeyabc.user.js`
Therefore the issues has been there since v1.36 :hushed:

**Comment by CrendKing** [comment]
That's where the weird prefix comes from.

Back to the issue. If there reason for not export zip is extra library, and not export CSS is incompatibility, then so be it. I guess most users just download scripts from share sites. So I just have to do the chore.

Feel free to close.
