### ISSUE TITLE
[FoxyTab] sort tabs by first opened/accessed

### ISSUE THREAD

**Issue by KamelittaOida** [erosman/support#241]
is it possible to implement this?

@PKxk8J has it but it's bugged a little cause it's not sorting it properly by date first opened
https://addons.mozilla.org/en-US/firefox/addon/clicktabsort/

![Clipboard01dfvf](https://user-images.githubusercontent.com/29007971/95467120-61b8e000-097d-11eb-85d3-145f7470c9a2.png)

**Comment by erosman** [comment]
Firefox API [tabs.Tab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) does not provide opened time but has a `lastAccessed` data so it is possible to sort according to `lastAccessed`, if there is a popular demand for the feature.

**Comment by Kamelitta** [comment]
f@#$ing firefox
is last access being changed even if = browser.sessionstore.restore_on_demand = true . ?
does it get changed by simply loading, or only if enter/f5 ?

**Comment by erosman** [comment]
> can you not take the date from "most recent visit" in history? that's the one I'm referring to

History search is very resource intensive and slow.

**Comment by Kamelitta** [comment]
same here. what time frame are we talking about? let's say I were to sort 250 tabs. one minute?
let me ask you this. has firefox history API the ability to differentiate between first opened and "Most recent visit"?

**Comment by erosman** [comment]
> same here. what time frame are we talking about? let's say I were to sort 250 tabs. one minute?

That depends on CPU and what the tabs are doing but it can halt some tab operations. Such actions will cause red-flag and add-ons that slow down Firefox are sanctioned by Mozilla.
Furthermore, there is no reliable data to get when a tab was first opened. The history only shows when tab URL was accessed last. The `lastAccessed` data is available from another API without using the slow History search.

> let me ask you this. has firefox history API the ability to differentiate between first opened and "Most recent visit"?

AFAIK, there is no 'first opened' data. The History API data is similar to what you see when opening the History widows (Ctrl + Shift + H)

**Comment by Kamelitta** [comment]
alright thank you. RIP firefox

**Comment by erosman** [comment]
Previously: #211

**Comment by erosman** [comment]
In v2.16

- Added Sort Sort by Last Accessed Ascending/Descending

**Comment by KamelittaOida** [comment]
:O :O dont believe it. I've gotta try it. thanks
