### ISSUE TITLE
How to overwrite a CSS rule with class/label "lg\:max-w-lg"?

### ISSUE THREAD

**Issue by pstein** [erosman/support#243]
Assume some elements from a web page refer to a class "lg:max-w-lg" which in turn has a corresponding CSS rule like: (shown in Firefox)

```
<div class="aaaclass foobarclass lg:max-w-lg:">....</div>

.lg\:max-w-lg {
    max-width: 1012px;
}
```
As you can see the classname in CSS is partially masked by a backslash.

How can I overwrite from Firemonkey *.user.js script this CSS rule with a width of e.g. 98%?

The following does NOT work:

`GM_addStyle(".lg\:max-w-lg {  max-width: 98% !important; }");`
or
`GM_addStyle(".lg:max-w-lg {  max-width: 98% !important; }");`

Related question:

How can I delete this class from all \<div\> elements from Firemonkey *.user.js script (jQuery is possible)?

the following does NOT work:

`$("div").removeClass("lg:max-w-lg");`

**Comment by erosman** [comment]
If you are only interested in CSS changes without any JS, it is a lot more efficient to use userCSS.

The following in a test page, does not work in Firefox. Is it standard CSS? (there are other non-standard CSS which are possible with some extra libraries)

```css
.lg\:max-w-lg {
    max-width: 1012px;
}
```
> How can I delete this class from all <div> elements from Firemonkey *.user.js script (jQuery is possible)?

For example to remove class `'abcd'`,  you can use these selectors
- find all elements with above class `'.abcd`'
- find all DIV with above class `'div.abcd'`
- find all DIV  `'div'`

**Standard JavaScript**
```js
document.querySelectorAll('.abcd').forEach(item => item.classList.remove('abcd'));
```

**jQuery**
```js
$('.abcd').removeClass('abcd');
```

**Comment by erosman** [comment]
Further Info:

From: [CSS Quick Tip: The Valid Characters in a Custom CSS Selector](https://pineco.de/css-quick-tip-the-valid-characters-in-a-custom-css-selector/)


> If you know the [Tailwind CSS project](https://tailwindcss.com/), you can see escaped CSS selectors. In Tailwind the naming syntax often contains a colon:
> 
> ```html
> <div class="sm:flex sm:items-center px-6 py-4">
> ```
> 
> To select `sm:flex` class in CSS we need to escape the `:` character: 
> 
> ```css
> .sm\:flex { ... }
> ```
> It is unusual for our eyes but the Tailwind is a utility based library, and the class names are more important in the HTML than the selector in the CSS.

**Comment by pstein** [comment]
> The following in a test page, does not work in Firefox.

Sorry to say: This is wrong.

Ok, lets go into more detail and have a look at a real world example (german online magazine):

https://www.manager-magazin.de/unternehmen/lufthansa-noch-immer-warten-650-000-kunden-auf-ihr-geld-a-c86bcbd6-9bfb-41ba-bcb0-a6ef39d3f63a

I loaded the web page in Firefox, right-click on the initial paragraph and select "Inspect element".
Then I can  change (increase) the value for the class .lg:mb-32 
and it becomes immediately effective in Firefox browser. So it works in Firefox!

Have a look at the attached snapshot .

So again: My problem is how to access (=modifiy the corresponding CSS or delete the class).
Therefore I setup the following test *.user.js (see bottom of this posting) and applied it to the web page above:

As you can see:

1. The margin-bottom is not changed and has still the original value of 2rem
2. the class .lg:mb32 is still existing for the element

It seems that backslashes in classes are very special.
Any idea how to get it working with Firemonkey?


changetest.user.js:


// ==UserScript== 
// @name            ChangeSlashClass
// @namespace       nsChangeSlashClass
// @description     Change Layout SlashClass
// @include         http*://*.manager-magazin.de/*
// @version         1.0.0
// @grant           GM_addStyle
// @require         http://code.jquery.com/jquery-latest.js
// ==/UserScript== 

GM_addStyle(".lg\:mb-32 { margin-bottom: 35rem !important; }");
GM_addStyle(".lg:mb-32 { margin-bottom: 35rem !important; }");
document.querySelectorAll('.lg:mb-32').forEach(item => item.classList.remove('lg:mb-32'));
$('.lg:mb-32').removeClass('lg:mb-32');


![sample slash class](https://user-images.githubusercontent.com/2775875/96444356-6c416800-120e-11eb-8bc9-b3feb33ee5eb.png)

**Comment by erosman** [comment]
> Sorry to say: This is wrong.

Sorry, you are right ... due to the typo in your example (as updated above) I got the wrong result.

**Note:**
It is more efficient to run `GM_addStyle()` **once** for all the CSS instead of running for each line.

It has to be double escaped when using `GM_addStyle()` 


Here is an example:
```js
// ==UserScript==
// @name            ChangeSlashClass
// @namespace       nsChangeSlashClass
// @description     Change Layout SlashClass
// @match           *://*.manager-magazin.de/*
// @Version         1.0.0
// ==/UserScript==


const css = `
.lg\\:mb-32 {
  border: 1px solid red;
}
`;

GM_addStyle(css);
```

Or simply as a userCSS

```css
/*
==UserCSS==
@name           ChangeSlashClass CSS
@match          *://*.manager-magazin.de/*
@version        1.0
@run-at         document-start
==/UserCSS==
*/

.lg\:mb-32 {
  border: 1px solid blue;
}
```
