### ISSUE TITLE
[FireMonkey] Imgur Direct Script

### ISSUE THREAD

**Issue by WonderfulSpivey** [erosman/support#244]
Currently the Imgur Direct script is not compatible with FireMonkey, is it possible to fix this? https://greasyfork.org/en/scripts/413400-imgur-direct

**Comment by erosman** [comment]
The issue is `/^https://imgur\.com/.[a-zA-Z0-9]{5,8}$/` and the nearest would be `https://imgur.com/*`, although it catches more pages.
It is possible to further fine tune it (with more `@exclude`), if you run into problems.

Try:

```
// ==UserScript==
//
// @name           Imgur Direct
// @version        1.1
// @namespace      https://greasyfork.org/en/users/667743-catspinner
// @description    See Imgur images & videos directly.
// @icon           https://imgur.com/favicon.ico
// @license        Beerware
//
// @include        https://imgur.com/*
// @exclude        https://imgur.com/gallery
// @exclude        https://imgur.com/upload
//
// @run-at         document-start
//
// ==/UserScript==
```

**Comment by WonderfulSpivey** [comment]
That did the trick, thank you!
