### ISSUE TITLE
[FireMonkey] [Feature Request] Make scripts and CSS working in the sidebar

### ISSUE THREAD

**Issue by ddesch** [erosman/support#245]
I'm using https://addons.mozilla.org/de/firefox/addon/open-link-in-sidebar/ to load some sites in the sidebar and with https://addons.mozilla.org/de/firefox/addon/styl-us/ I'm able to use UserStyles for sites loaded there, but it seems that FireMonkey doesn't work with sites which are loaded in the sidebar. Could you make that also possible in FireMonkey?

**Comment by erosman** [comment]
I installed and tested [Open in Sidebar](https://addons.mozilla.org/en-US/firefox/addon/open-link-in-sidebar/) and both the FireMonkey userScript & userCSS work fine in sidebar.

**Comment by ddesch** [comment]
🙈 Yes, it's working 👍 
Sorry, my fault.
