### ISSUE TITLE
[FireMonkey] window.location does not work

### ISSUE THREAD

**Issue by Jinkiesz** [erosman/support#246]
Any attempts to change the url of a site doesn't work in firemonkey

codes like these doesn't work:
window.location.href = url;
window.location = url;
window.location.replace()

Anyways I would like to thank you for your work on this extension author :) the extension bundled with custom user.css is really useful as an alternative to laggy stylus

**Comment by erosman** [comment]
> Anyways I would like to thank you for your work on this extension author :)

Thank you for your kind comment :+1:

> Any attempts to change the url of a site doesn't work in firemonkey

It works. You can use or omit `window` here, example:

```js
location.href.replace(location.search, '')
location.replace(location.href.slice(0, -1));
location.href = 'https://www.example.com'; 
location.replace('https://www.example.com/page.html');
location.replace(location.href.replace(/\/[\w-]+\//, '/en-US/'));
location.search = '';
```

What is the code you are trying?
Please note that these are part of page JavaScript and some pages may include methods to block some actions.

**Comment by Jinkiesz** [comment]
Sorry it was my mistake, it works now. Thanks for the feedback and the omitting tips too :)
