### ISSUE TITLE
Duplicate tab menu item not appearing

### ISSUE THREAD

**Issue by rayman89** [erosman/support#25]
I have changed the menu order and items a lot but recently I noticed that duplicate tab menu item does not show anymore. I tried disabling it and enabling it again changing it's order removing other items and nothing worked.

![image](https://user-images.githubusercontent.com/5449042/48225366-2f9e3e00-e362-11e8-8514-f4727779450e.png)

**Comment by erosman** [comment]
Which version of Firefox are you using?

FoxyTab doesn't have a **Close** menu !! (the one on top) and it would appear where it is shown.

Duplicate Tab context-menu was added by Firefox in version 57 to its own menu so FoxyTab checks if the version is 57+, it removes its own Duplicate Tab context-menu.

**Comment by rayman89** [comment]
I'm using firefox 64 The "close" is for close all of the same host. Idk why you changed the names to only make sense when they are under a category I just put it out of host to have it more at hand. 

Could you not auto hide it please? People can choose to hide it if they want to in the options why force it?

**Comment by rayman89** [comment]
I changed the menu using userChrome.css I can change it to make firefox's duplicate tab appear again but I would prefer to have it in the Foxy tab menu. Could you not auto hide it please? People can choose to hide it if they want to in the options why force it?

**Comment by erosman** [comment]
> Could you not auto hide it please? 

Sure.. that is possible

> People can choose to hide it if they want to in the options why force it?

I had just the opposite request. Users asked why FoxyTab has menus that Firefox has by default.

I will see what can be done for the next upgrade. Maybe hide it but make it possible to unhide it!!?

**Comment by erosman** [comment]
It is re-added in v2.14

**Comment by rayman89** [comment]
Thank you It's all working properly you can close this if needed.
