### ISSUE TITLE
[FoxyTab] Feature Request: Suspend tab

### ISSUE THREAD

**Issue by dbbgba** [erosman/support#250]
Right now I'm using another addon called "Tab Suspender". I think the same feature would be a perfect fit for FoxyTab (and allow me to have one less addon :P)

Basically I like to have something that would suspend tabs if they are unused for a long period of time (freeing up memory) and allow me to suspend tabs by right-clicking on it.

**Comment by erosman** [comment]
I have to check on this.... [tabs.discard()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard) appears unsupported.

In any case, keeping track of each tab, when they open and how long they have been opened, is resource intensive.

**Comment by dbbgba** [comment]
Well already having it as a right-click option would be great :D

**Comment by erosman** [comment]
Previously: #79

In 2.16

- Added Discard Tab, All, Left, Right
