### ISSUE TITLE
[FireMonkey] GM_getValue/GM_setValue does not work right on >=1.45

### ISSUE THREAD

**Issue by benoit-pierre** [erosman/support#255]
Steps:

- `GM_getValue('setting')` => `undefined`
- `GM_setValue('setting', 42)`
- reload page
- `GM_getValue('setting')` => `undefined`

**Comment by erosman** [comment]
Can you show me the code?

Before  1.45 `GM_getValue() = GM.getValue()`
They both returned a `Promise` so you had to use `await`

Since 1.45, `GM_getValue()` is sync and `GM.getValue()` is async promise.
```js
const value = GM_getValue(key, default);
const value = await GM.getValue(key, default);
```

**Comment by erosman** [comment]
There seems to be an issue... I will fix it and upload a new version.

**Comment by erosman** [comment]
Actually, the sync `GM_getValues` is broken. I have to revert back to the old set-up for now. :(

**Comment by benoit-pierre** [comment]
Does that mean that using `GM.getValue/GM.setValue` on 1.46 should work? Because I reverted to my old async code and still get the issue.

**Comment by erosman** [comment]
>Does that mean that using GM.getValue/GM.setValue on 1.46 should work? Because I reverted to my old async code and still get the issue.

The whole process was changed and it resulted in error. I have disabled v1.45-1.46 so  you can revert back to 1.44

**Comment by benoit-pierre** [comment]
OK, thanks.

**Comment by erosman** [comment]
v1.47 uploaded .. let me know if there are problem
