### ISSUE TITLE
[FireMonkey] fetch http resource not work in HTTPS-only mode

### ISSUE THREAD

**Issue by linsui** [erosman/support#259]
I have a user script for a http site. I fetch a http resource which works without HTTPS-only mode enabling. But when I enable the HOM, it doesn't work anymore. GM.fetch doesn't work, either. Could you help me please? Thanks!

**Comment by erosman** [comment]
Does the resource also serve as HTTPS?

HTTPS-only mode converts HTTP to HTTPS. If a target site does not serve HTTPS then the connection fails.
That is the same case when visiting HTTP sites (that don't have a HTTPS version) when in HTTPS-only mode.

**Comment by linsui** [comment]
No., it's an http resource. When an http site is added to exception, it can fetch other http resource, so the same script can run in the cosole. But I guess user scripts are run in a different context so that it's not allowed? Is that possible to add user scripts to exception?

**Comment by erosman** [comment]
I will investigate it and get back to you.

**Comment by linsui** [comment]
Thanks!

**Comment by erosman** [comment]
I have done some testing....

When **HTTPS-Only Mode** is enabled

- Network connections to HTTPS goes through normally
- Network connections to HTTP will be forward to HTTPS
  - If site has both HTTP & HTTPS support, then the network connection goes through
  - If site doesn't have HTTPS support, then the network connection fails
`TypeError: NetworkError when attempting to fetch resource.`
- When opening a web page which doesn't support HTTPS, Firefox gives you TEMPORARY option to open the page in the browser. This setting does not affect network connections not made from a Tab i.e. in other background processes.

There isn't a way to bypass **HTTPS-Only Mode** by extensions and there shouldn't be as it violates users' choice of security.

**Comment by linsui** [comment]
Thanks for you help!
