### ISSUE TITLE
FoxyTab Feature Request: Menu Option - Open New Tab 

### ISSUE THREAD

**Issue by tmountney** [erosman/support#26]
FoxyTab
First, thank you for a nice, very useful addon.

RE: open new blank tab to immediate right of current viewed/opened tab

One issue with FF is that a new tab opens the tab at the end of current tabs. I'm a heavy tab user and this is annoying, and inconvient, because if I open a new tab I want it to open to the immediate right of the tab that I have open/am viewing. 

Tab Mix Plus had this feature and it was quite handy and very convenient...
Thank you for considering this feature...
Tom

**Comment by erosman** [comment]
Sure... I will add the option

**Comment by erosman** [comment]
Firefox has added the feature.
The Firefox context-menu "New Tab" opens next to the click tab.
