### ISSUE TITLE
Cannot make location.reload work

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#260]
I cannot make a simple page auto-reload script work. Tried all different ways, the page does not reload. Here are some setTimeout variants that I tried, one at a time. Nothing works. What am I missing?

```
var minutes = 1;
// window.setTimeout(window.location.reload.bind(window.location), minutes*60000);
// window.setTimeout(function(){ window.location.reload(); }, minutes*60000);
window.setTimeout("document.location.reload();", minutes*60000);
```

**Comment by rubaboo** [comment]
Actually, I think the bank is somehow defeating the script. I got this working on another banking site, but it still does not reload the page on the first site. Here is the full script, I only changed the domain names.

Do you have any idea how can I possibly try and make it work on the site that is apparently blocking it somehow? The icon shows the script activated, so my match pattern is ok.

```
/*
==UserScript==
@name             AutoRefresh
@match            https://www.bank1notworking.com/Secure#/*
@match            https://secure.bank2ok.com/*
@version          1.0
==/UserScript==
*/

const refreshRate = 10000;                      // Refreshes every 10s
window.setTimeout(window.location.reload.bind(window.location), refreshRate);
```

**Comment by erosman** [comment]
I have to test it ... but .... I have heard many sites interfere with location.reload e.g. some game sites, banks.

If there is no workaround, I can consider adding a GM API.

**Comment by sn260591** [comment]
Site scripts can override standard methods. But you can execute a userscript at the start of the page load and save a link to the required method.

**Comment by rubaboo** [comment]
Can't give you a site to test, LOL. The timeout is only when signed in. No way I'm giving you my online banking credentials.

**Comment by erosman** [comment]
> Can't give you a site to test, LOL. The timeout is only when signed in. No way I'm giving you my online banking credentials.

Understandable ...

If you find any other testable example that doesn't require login, let me know.
