### ISSUE TITLE
[FireMonkey] unsafeWindow stopped working

### ISSUE THREAD

**Issue by kekkc** [erosman/support#262]
Hi Erosman,

since a few versions, I realized that unsafeWindow no longer works ("without error messages"). 

As a workaround I replaced 
`let confirm = new window.Function('return true');`
`unsafeWindow.confirm = confirm;`
with 
`let confirm = new window.Function('return true');`
`window.wrappedJSObject.confirm = confirm;`

Which is still working. Do you know if this is related to FF changes (I initially preferred unsafeWindow because of script "compatibility with other script managers)?

**Comment by erosman** [comment]
You are right.
Sorry... that is due to changes in v1.45 which broke `unsafeWindow` (made it one way).
I fixed it now and will be in v2.0 (with a whole lot of other things).

I will release v2.0 very soon if you can wait a little bit.

**Comment by erosman** [comment]
v2.0 released... fingers crossed ;)

**Comment by kekkc** [comment]
As usual, a "little bit" was blazingly fast. Many thanks for the super fast fix ;)
