### ISSUE TITLE
Support for regexp matching in @include

### ISSUE THREAD

**Issue by eberhardweber** [erosman/support#263]
Fairly self-explanatory: There's a large amount of scripts out there that take advantage of regular expressions to match domains. Currently these do not work in FireMonkey. 

Especially Amazon-related (url shortening, smile redirection, etc.) scripts are currently largely unusable in FireMonkey due to lack of support. Here are a few examples of such scripts:

https://greasyfork.org/en/scripts/410767-amazon-smile-redirect
https://greasyfork.org/en/scripts/33227-amazon-short-url
https://greasyfork.org/en/scripts/39709-smile-amazon

I'm sure Amazon isn't the only usercase with the large variety of different domains, but it's probably the biggest one. You can see how complex the matching has to be in some of these.

**Comment by erosman** [comment]
FireMonkey uses Firefox built-in API. That means, all scripts are passed to Firefox for insertion which is more efficient than the extension handling the script injection manually.

The limitation is that Firefox API only accepts match pattern.

Few of the easy regex are converted in FireMonkey to match pattern.

Others have to be manually converted. Please also note that regex include has its own shortcomings.

### [Amazon Smile Redirect](https://greasyfork.org/en/scripts/410767-amazon-smile-redirect)
```
// @include         /.*(www.|http.?:\/\/|smile.)amazon\.(de|com|co.uk).*$
// @exclude         /(.*=.*amazon|.*amazon.*\/signin.*).*$
```

Above will also match the following and many more
```
http://some-spam-site.com/?url=http://smail.amazon.com/#some-other-trackign-parameter
```

Match Pattern in general is more robust and without accidental matching. Here is an example for above:
```
// @match           *://*.smile.amazon.de/*
// @match           *://*.smile.amazon.com/*
// @match           *://*.smile.amazon.co.uk/*
// @match           *://*.smile.amazon.com/*
// @exclude=match   *://*.amazon.de/signin*
// @exclude=match   *://*.amazon.com/signin*
// @exclude=match   *://*.amazonco.uk/signin*
```


### [Amazon short URL](https://greasyfork.org/en/scripts/33227-amazon-short-url)
```
// @include        /^https?:\/\/(www|smile)\.amazon\.(cn|in|co\.jp|sg|ae|fr|de|it|nl|es|co\.uk|ca|com(\.(mx|au|br|tr))?)\/.*(dp|gp\/(product|video)|exec\/obidos\/ASIN|o\/ASIN)\/.*$/
```

Change to: 
Note TLD is FireMonkey only feature
```
// @match           *://*.smile.amazon.TLD/*dp/*
// @match           *://*.smile.amazon.TLD/*gp/product*
// @match           *://*.smile.amazon.TLD/*gp/video*
// @match           *://*.smile.amazon.TLD/*exec/obidos/ASIN/*
// @match           *://*.smile.amazon.TLD/*o/ASIN/*
```

### [Smile@Amazon](https://greasyfork.org/en/scripts/39709-smile-amazon)
```
// @include        /^https\:\/\/www\.amazon\.(com|co\.uk|de)\/.*$/
```

Change to:
```
// @match           *://*.smile.amazon.de/*
// @match           *://*.smile.amazon.com/*
// @match           *://*.smile.amazon.co.uk/*
```

**Comment by erosman** [comment]
I am working on a possible workaround ... let's see if it works out.

**Comment by erosman** [comment]
## version 2.5
**Experimental** Regular Expression support has been implemented for `@include`/`@exclude `.

### &#x1f4ca; URL Matching Performance
The performance from top (best) to bottom (worst):
  
1. match & exclude-match
2. includeGlob & excludeGlob
3. include & exclude
4. include & exclude with regular expresion

**Comment by erosman** [comment]
v2.5 uploaded.
