### ISSUE TITLE
Historia: Open Options: should go directly to the /content/options.html view of preferences

### ISSUE THREAD

**Issue by grahamperrin** [erosman/support#264]
Expected (ideal): 

![image](https://user-images.githubusercontent.com/192271/101850288-68b4c800-3b51-11eb-9657-95e30a0e1c05.png)

Actual result (of the _Open Options_ menu option): 

![image](https://user-images.githubusercontent.com/192271/101850428-a1ed3800-3b51-11eb-96e7-8574013f7767.png)

Please, is it possible to open the preferences page?

(If the about:addons page is required, the toolbar button context menu can be used.)

Thanks

**Comment by erosman** [comment]
> Please, is it possible to open the preferences page?

Do you mean the toolbar popup "Open Options"?
For me it goes to the option page.
Are you using it in a private window?

**Comment by grahamperrin** [comment]
> Do you mean the toolbar popup "Open Options"?

Yes.

> Are you using it in a private window?

No.

I discovered a factor: `extensions.htmlaboutaddons.inline-options.enabled` `false`. 

For test purposes, with about:addons already open I temporarily made it `true`, then retried _Open Options_. Still no view of preferences, so I reloaded about:addons then preferences appeared. 

Please, can you make the extension open `options.html` in a separate tab?

From source code for an extension that does so: does https://github.com/VerifiedJoseph/Save-to-the-Wayback-Machine/blob/ac05a7bd4b9e8a650e8f12dc300f0ef7a963ddcb/src/javascript/pages/popup.js#L266 help?

Thanks

**Comment by erosman** [comment]
> Please, can you make the extension open options.html in a separate tab?

Yes... In all new upgrades of my extensions, I moved the Options page to a new tab. It will be done when I next work on Historia. (ATM all my time is spent on working on FireMonkey)

**Comment by erosman** [comment]
I have uploaded v1.4 which opens the Options in a new tab.

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2020. dec. 13. 09:43 CET](https://github.com/erosman/support/issues/264#issuecomment-743974487 "2020-12-13T08:43:26Z - Replied by Github Reply Comments"):
> I have uploaded v1.4 which opens the Options in a new tab.

Cool. Thanks!

**Comment by grahamperrin** [comment]
Thanks for the very speedy fix!
