### ISSUE TITLE
[FireMonkey] In editor, a long line can't be displayed completely

### ISSUE THREAD

**Issue by linsui** [erosman/support#265]
![sshot-029](https://user-images.githubusercontent.com/36977733/102012941-f6a4d480-3d44-11eb-80e9-51330007a66a.png)

I set `.CodeMirror { overflow: unset; }` to display it completely.

**Comment by erosman** [comment]
It displays fine for me... there is horizontal scrollbar.

Example:

![image](https://user-images.githubusercontent.com/6458876/102014886-8eb6b400-3d6d-11eb-8b46-07c4b60d2eb4.png)

**Comment by linsui** [comment]
I scroll the line to the rightest but still can't see the tailer.

`.CodeMirror { overflow: hidden; }`
![sshot-030](https://user-images.githubusercontent.com/36977733/102015628-a6ce0980-3d54-11eb-8fac-6e1d2a0ba325.png)

`.CodeMirror { overflow: unset; }`
![sshot-031](https://user-images.githubusercontent.com/36977733/102015745-47bcc480-3d55-11eb-9305-84bfa1ef5eaa.png)

**Comment by erosman** [comment]
I see... let me see how to fix it.. without it getting additional horizontal scrolls.

**Comment by erosman** [comment]
I got it fixed.. it will be in v2.5

**Comment by linsui** [comment]
Thanks!

**Comment by erosman** [comment]
v2.5 uploaded. Let me know if there are any issues.

**Comment by linsui** [comment]
It works well! Thanks!
