### ISSUE TITLE
Bug!? Matching *.user.js scripts do not appear in upper pane "Tab Scripts & CSS" any more?

### ISSUE THREAD

**Issue by pstein** [erosman/support#266]
When I load webpages into my Firefox v84 (64bit on windows) then some of them are matched by previously imported *.user.js scripts.

And yes, statements inside (e.g. Font size modifications) are applied just as desired.

What I miss is the corresponding entry of the match script in the upper pane (after click on toolbar icon) of Firemonkey.
It is labelled "Tab Scripts & CSS" and is empty.

In order to disable the script I have (in the lower pane) to scroll down my 40 scripts and to toggle the script checkbox.

As far as I remember from the past the matching *.user.js script appeared in the upper pane.
So I had always easy+fast access to the checkbox.

Is this a change in recent versions of Firemonkey or in recent versions of Firefox?

If possible I would like to have it back in the upper pane.

Thank you

**Comment by erosman** [comment]
> As far as I remember from the past the matching *.user.js script appeared in the upper pane.

That is still the case. I have 122 Scripts & CSS and the applicable ones appear on the top panel.

> Is this a change in recent versions of Firemonkey or in recent versions of Firefox?

I don't think there is anything to do with Firefox... BUT ... there are some major changes in v2.5 mainly dealing with `include/exclude`. _(info in the Help)_

Before v2.5, `include/exclude` were converted to `match/exclude-match` by FireMonkey. The result was that some would fail to convert and script wouldn't run.

In v2.5 the processing is changed to allow `include/exclude` to run as they are. Additionally, regex `include/exclude` patterns are now supported. However, they should still show up in the top panel.

**Please note that `match/exclude-match` performs far better.**

If you give me a test script, I will check if there are any problems and fix it.

**Comment by pstein** [comment]
Ok, here is a simplified sample (for a german news webpage):

https://www.welt.de/vermischtes/article222523568/Corona-Zahlen-Erstmals-ueber-30-000-Corona-Neuinfektionen-binnen-24-Stunden-gemeldet.html

The simplified script welt.user.js is as follows:

```
// ==UserScript==
// @name            ChangeWelt
// @namespace       nsChangeWelt
// @description     Change welt.de
// @include         https://*.welt.de/*
// @exclude         https://www.welt.de/
// @exclude         https://www.welt.de/icon/*
// @version         1.5.0
// @grant           GM_addStyle
// @require         http://code.jquery.com/jquery-latest.js
// ==/UserScript==

GM_addStyle(".c-article-text > p { font-size: 25px !important; line-height: 25px !important; font-family: Verdana !important; }");

```

As you can see the font-size is adjusted but the upper pane is empty. And no "1" is shown in the upper right corner of Firemonkeys toolbar icon

**Comment by erosman** [comment]
You are right. :+1: 

I will find out what is going on and fix it.

If this is your own script, in the meanwhile, please note that `@match/@exclude-match` is the recommended method which is more robust. Wildcard type `include/exclude` can have unexpected matching.
 `@match` is supported by all script managers but `@exclude-match` only by FM & VM.

In FireMoneky, `@match/@exclude-match` performs far better.

> [Violentmonkey Matching](https://violentmonkey.github.io/api/matching/)
> It is recommended to use `@match` / `@exclude-match` rather than `@include` / `@exclude` because the match rules are safer and more strict.


> [Greasemonkey Matching](https://wiki.greasespot.net/Metadata_Block#.40match)
> The `@match` metadata imperative is very similar to `@include`, however it is safer. It sets more strict rules on what the * character means.


Your patterns in your example are actually Match Patterns.
```
// @match           https://*.welt.de/*
// @exclude-match   https://www.welt.de/
// @exclude-match   https://www.welt.de/icon/*
```

**Comment by erosman** [comment]
Fixed .. it will be in v2.7

**Comment by pstein** [comment]
Seems to work now.
Thank you
