### ISSUE TITLE
[FireMonkey] Can't fit the window in the Overflow Menu

### ISSUE THREAD

**Issue by linsui** [erosman/support#270]
When open FireMonkey in the Overflow Menu, it can't fit the window well.

![sshot-034](https://user-images.githubusercontent.com/36977733/103499911-a69bc800-4e41-11eb-9408-c9f80810e422.png)

Thanks!

**Comment by erosman** [comment]
Oh ... I never used the overflow menu. I have to check why that happens.

**Comment by erosman** [comment]
Fixed for v2.8

**Comment by linsui** [comment]
Thanks!
