### ISSUE TITLE
[FireMonkey] Script not compatible?

### ISSUE THREAD

**Issue by WonderfulSpivey** [erosman/support#273]
I used a script with Tampermonkey to bulk activate Steams Keys that is not working with FireMonkey, is it possible to adjust this script to make it compatible? 

https://cdn.jsdelivr.net/gh/LiteOnE/Steam-Scripts@master/Batch-Keys-Activator/Batch-Keys-Activator.user.js

**Comment by erosman** [comment]
I am guessing it is to do with injection time, since the script uses JQuery `.ready()` (line 455)

TamperMOnkey documentation is rather unclear.

> [TamperMonkey @run-at](https://www.tampermonkey.net/documentation.php#_run_at)
> 
> `// @run-at document-end`
> The script will be injected when or after the DOMContentLoaded event was dispatched.
> 
> `// @run-at document-idle`
> The script will be injected after the DOMContentLoaded event was dispatched. This is the default value if no @run-at tag is given. 

MDN & Chrome documentation states:

> document_end
>     Corresponds to interactive. The DOM has finished loading, but resources such as scripts and images may still be loading.
> document_idle
>     Corresponds to complete. The document and all its resources have finished loading.

Anyway, try injecting it earlier since the default FireMonkey is `document-idle` which menas JQuery `.ready()` probably would not fire.

Try adding `@run-at   document-end` e.g.
```
// @run-at       document-end
// ==/UserScript==
```

**Comment by WonderfulSpivey** [comment]
Thank you for the quick response, unfortunately that did not fix the issue. The script gets hung up on "Processing Given Keys" and never processes them.

**Comment by erosman** [comment]
Can you give me a web page that doesn't require login to test it?

**Comment by WonderfulSpivey** [comment]
The script allows you to activate multiple steam game keys at the same time rather than 1 by 1. I believe a login would always be required to test it as you need to be logged into a steam account: https://store.steampowered.com/account/registerkey?

Tested in GM & VM and it did not work in either, still works in TamperMonkey though.

**Comment by erosman** [comment]
> Tested in GM & VM and it did not work in either, still works in TamperMonkey though.

Then, it must be something specific to TM. TM code is not available to see what they are doing which is different. 
You can also ask the script developer who might know.

I will look again to see if I can find the reason.

**Comment by erosman** [comment]
Looking at [Steam Community :: Guide :: Activate Multiple Keys at Once](https://steamcommunity.com/sharedfiles/filedetails/?id=1369737759) it seems only TamperMonkey is working with it.

**Comment by erosman** [comment]
You can also try asking [GM](https://github.com/greasemonkey/greasemonkey/issues) and [VM](https://github.com/violentmonkey/violentmonkey/issues) about above userscript.

They may know why it doesn't work on GM|VM but works on TM.

**Comment by erosman** [comment]
I had another look at the code..

After `Processing given keys...` (line 587) the script sends `activateKey` to `https://store.steampowered.com/account/ajaxregisterkey/` (line 215).
It is possible that the (login) credential are not sent since the userscript is sandboxed in its own scope and the code is using the userscript scope to POST XHR (not GM function).

Try testing it by...
- Go to the page
- Open Developer Tools `F12`
- Go to Network tab (select `All` to show everything)
- Do the registering
- Watch the Network tab and see what happens when there us a POST to above URL

There might be some useful details there.

**Comment by erosman** [comment]
> [Greasemonkey throws “DOMException ...](https://stackoverflow.com/questions/65749354/greasemonkey-throws-domexception-the-operation-is-insecure-on-document-imple)
> 
> **comment:**
> Tampermonkey runs in page context whereas GM4 runs in a true sandbox.


If that is the case, then it can explain why script works in TM and not in FM|GM|VM.

TM runs in page content without a sandbox which helps above script but opens up all sort of security issues.
FM|GM|VM run in sandbox

**Comment by erosman** [comment]
You can try the same solution as #277 

> [Tampermonkey • Documentation](https://www.tampermonkey.net/documentation.php)
> 
> If @grant is followed by 'none' the sandbox is disabled and the script will run directly at the page context. In this mode no GM_* function but the GM_info property will be available.

As I suspected, the script in TM runs in page context (which has security concerns).

**Comment by erosman** [comment]
New feature in  the next update will support this type of injection.

**Comment by erosman** [comment]
v2.13 with `@inject-into` support uploaded.

Try the script with it and let me know.

```
// @require      https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
// @inject-into  page
// ==/UserScript==
```

**Comment by WonderfulSpivey** [comment]
Still getting the same result, stuck on processing keys.

**Comment by erosman** [comment]
Did you try it with `// @inject-into  page`?

Check the result in the Developer Tools as shown in #277

**Comment by WonderfulSpivey** [comment]
This is what I have at the beginning of the script: 
![firemonkey](https://user-images.githubusercontent.com/73183603/105544540-f1c23180-5caf-11eb-8936-3980e96a98b3.png)
Below is what shows in Developer Tools
![console](https://user-images.githubusercontent.com/73183603/105544687-18806800-5cb0-11eb-803f-5d3d805d7b08.png)

**Comment by erosman** [comment]
> This is what I have at the beginning of the script:

No.. not the beginning, it was the end part ... in the metadata block eg:

```
// ==UserScript==
// @name         Batch Keys Activator
// @icon         https://store.steampowered.com/favicon.ico
// @namespace    top_xex
// @version      2.5.2
// @description  Activate a bunch of keys at once. Many thanks to Delite for helping with some css stuff, motivation and testing
// @author       Lite_OnE
// @match        https://store.steampowered.com/account/registerkey*
// @match        https://www.indiegala.com/profile?user_id=*
// @match        https://www.indiegala.com/gift?gift_id=*
// @match        https://www.gogobundle.com/latest/bundles/order/show/cid-*
// @match        https://www.gogobundle.com/account/order/show/cid-*
// @match        https://otakubundle.com/latest/bundles/order/show/cid-*
// @match        https://otakubundle.com/account/order/show/cid-*
// @match        https://www.fanatical.com/*/orders/*
// @match        https://www.humblebundle.com/downloads?key=*
// @match        https://groupbundl.es/buy/*
// @homepageURL  https://xeox.xyz
// @supportURL   https://github.com/LiteOnE/Steam-Scripts/issues
// @updateURL    https://github.com/LiteOnE/Steam-Scripts/raw/master/Batch-Keys-Activator/Batch-Keys-Activator.meta.js
// @downloadURL  https://github.com/LiteOnE/Steam-Scripts/raw/master/Batch-Keys-Activator/Batch-Keys-Activator.user.js
// @require      https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js
// @inject-into  page
// ==/UserScript==
```

**Comment by WonderfulSpivey** [comment]
That fixed it, thanks!
