### ISSUE TITLE
[FireMonkey] Stop throwing error when regex doesn't match

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#274]
Apparently, FireMonkey throws error for each script that has @include with regex that doesn't match.

For example, an UserScript whose @include regex only matches Google pages throws `uncaught exception: {name} regex not match` for every non-Google loaded page.

This is not an error, so it shouldn't throw anything. Not even should log, unless FireMonkey supports enabling debug mode.

Edit: I think I got it... its intentional. Scripts with only regex @include runs on *every* page and the `throw` is a way to abort if regex doesn't match. Wouldn't it be possible to test regex before injecting the script?

**Comment by pintassilgo** [comment]
So the problem is that WebExts' userScripts API doesn't support regex. FireMonkey adds match `*://*/*`, the script is loaded on every page and aborted at start if regex fails.

There's no perfect solution, but maybe we can improve the current workaround. It would be possible to use an intermediary wrapper? For every UserScript with one or more regex we'll register a very simple UserScript with match `*://*/*` and excludes (if any). But the code would be only the regex check. If it passes, then it will call the real UserScript code. It's possible for one UserScript to access another? Or anything like that, it's just to avoid trying to load the entire code before testing regex.

**Comment by erosman** [comment]
> Edit: I think I got it... its intentional. Scripts with only regex @include runs on every page and the throw is a way to abort if regex doesn't match. Wouldn't it be possible to test regex before injecting the script?

Correct.
As indicated in the Help under `include` & `exclude`, since version 2.5 full support of `include` & `exclude` was added based on the Firefox/Chrome `ncludeGlobs/excludeGlobs` API.
Before v2.5 `include` & `exclude` were converted to match pattern which was not possible in all situations.

The API was created just for this purpose by Chrome (and followed by Firefox).

The way the API works is that there MUST be a `@match` which will be checked fist and then `includeGlobs/excludeGlobs`.

> So the problem is that WebExts' userScripts API doesn't support regex. FireMonkey adds match *://*/*, the script is loaded on every page and aborted at start if regex fails.

Exactly. :+1: 
The only way FM could support regex was to check it at the time of injection since API does not support regex. Other userscript managers also do the same before injection but since their injection is manual, you don't see it.

I originally wanted to abort inject in `onBeforeScript` but sadly that does not work. I have discussed it in length with the userScripts API developer.

Therefore, I came up with this method.

> It's possible for one UserScript to access another? Or anything like that, it's just to avoid the waste of loading the entire code on unwanted pages, besides avoiding that ugly error throwing.

The script is not injected.

The way it is working now is that , it injects the regex match check first, if it fails, then actual script is not injected. That is why there is a `throw` error, to **abort** with `throw`. There is no other way to abort.

I could have used `throw` without any text (`xyz regex not match') but I added the text to show where it is coming from.

The `throw` only happens for scripts that have regex `include/exclude`.

Finally, as mentioned in the Help under **URL Matching Performance**, the best method is to use `match` & `exclude-match`.

**Comment by pintassilgo** [comment]
> The script is not injected.
> 
> The way it is working now is that , it injects the regex match check first, if it fails, then actual script is not injected. That is why there is a `throw` error, to **abort** with `throw`. ATM, there is no other way to abort.

OK, that's better than I thought. So it's only the annoying console flooding, not about bad performance of unnecessarily loading scripts on every page.

**Comment by pintassilgo** [comment]
What do you thing about using the "legacy" injection mode (ie not using UserScripts API) when the script uses regex (non trivially convertible into match patterns)? I think it would be the best way to handle this.

**Comment by erosman** [comment]
> What do you thing about using the "legacy" injection mode (ie not using UserScripts API) when the script uses regex (non trivially convertible into match patterns)? I think it would be the best way to handle this.

This is the method used by GM|TM|VM & Stylish|Stylus|xStyle

- Add a listener to all HTTP requests
- Loop through all scripts on every request to check if the there are scripts that match
- If matches are found, process the scripts and inject the scripts
- All injections are handled manually by the extension
- Script injection is made into privileged & unsecure `content` context (or `page` context in cases in TM|VM)

This is the method used by FireMonkey
- All scripts are prepared and passed to Firefox native engine at start-up
- From then, FireMonkey does nothing and all is handled by the Firefox natively
- Script injection is made into secure `userScript` context


Besides the security features of the dedicated userScript API, the performance difference is immense.
The cost of `throw` in regex `include` is nothing compared with above.

In any case, the use of regex `include` is not recommended and not widely present. It is only implemented for convenience of the users.
Using `match|exclude-match` is the most effective way and has the best performance.

**Comment by pintassilgo** [comment]
> the performance difference is immense
> The cost of `throw` in regex include is nothing compared with above.

That's why I would like to migrate from VM to FM.
But do you have numbers of that difference? I guess UserScripts API tends to perform better, but I'm not sure if there's a practical difference, mainly about the speed to check matches/includes. uBO does everything you said and many more and it's **super** efficient.

> In any case, the use of regex include is not recommended and not widely present. It is only implemented for convenience of the users.

That's why I think that what I suggested wouldn't affect the better performance of FM. Just those rare scripts using regex `include` would need to be injected with *the old way*. All other would still use userScripts API.

**Comment by erosman** [comment]
> uBO does everything you said and many more and it's super efficient.

uBO blocks the connection. Userscript manger, in addition to check, has to wait for the tab, inject the script, and perform other associated processes.

No matter how efficient uBO is, having 2 uBO run at the same time would not be as efficient as one uBO, It all adds up.

> That's why I think that what I suggested wouldn't affect the better performance of FM. Just those rare scripts using regex include would need to be injected with the old way. All other would still use userScripts API.

There is a lot more involved. Many extra listeners have to be started and be ready just to process those few regex `include`. It can become bloated.

**Comment by pintassilgo** [comment]
> uBO blocks the connection. Userscript manger, in addition to check, has to wait for the tab, inject the script, and perform other associated processes.

uBO does a lot more than blocking requests. [It also inject scripts](https://github.com/gorhill/uBlock/blob/master/assets/resources/scriptlets.js). In fact, it attached parts of the code of the defunct and once popular UserScript AdsBypasser. So it checks thousands of filters to every request, and if it matches it injects script. Just like a basic userScript manager.

> There is a lot more involved. Many extra listeners have to be started and be ready just to process those few regex `include`. It can become bloated.

I know, I just don't think this has any practical effect, like I said when asking if you have any numbers about the better performance of userScripts API. I guess it's much more irrelevant than you think.

Firefox listens to every event anyway (`http-on-modify-request`, `http-on-examine-response` etc), the cost it's more about the code added by each listener. And checking a couple of regex against each `nsIURI.spec` is cheap...

**Comment by erosman** [comment]
`throw` is used by many add-ons and Firefox. It is standard JavaScript.

For example:

FM uses `throw` in 1 file & only once

GM uses `throw` in 20 files (one or more in each)
https://github.com/greasemonkey/greasemonkey/search?p=2&q=throw&type=code

VM uses `throw` in 25 files (one or more in each)
https://github.com/violentmonkey/violentmonkey/search?q=throw

TM uses `throw` in 13 files (one or more in each)

uBO uses `throw` in 12 files (one or more in each)
https://github.com/gorhill/uBlock/search?q=throw
