### ISSUE TITLE
[FireMonkey] Option to switch between contentScript and userScript

### ISSUE THREAD

**Issue by linsui** [erosman/support#276]
Sometimes it's convient to run userscript as contentScript. E.g., the contentScript won't be blocked by HTTPS-only-mode on a http website. Could you please add a user option to insert some scripts as contentScript? Thanks!

**Comment by erosman** [comment]
> Could you please add a user option to insert some scripts as contentScript?

contentScripts API is meant for the addon's own code. It has far more privileges.

> [WebExtension APIs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis)
> 
> In addition to the standard DOM APIs, content scripts can use the following WebExtension APIs:
> 
> From extension:
> - getURL()
> - inIncognitoContext
> 
> From runtime:
> - connect()
> - getManifest()
> - getURL()
> - onConnect
> - onMessage
> - sendMessage()
> 
> From i18n:
> - getMessage()
> - getAcceptLanguages()
> - getUILanguage()
> - detectLanguage()
> 
> From menus:
> - getTargetElement
> 
> Everything from:
> - storage 


userScripts API was especially created to block user-script access to higher browser APIs. User-scripts in FireMonkey do not have access to any of the above browser API, thus the enhance security which is a feature of FireMonkey.

It would create a security issue where malware or badly written scripts can cause real problems. For example, a malware can re-write all scripts the user has, add scripts, delete scripts, change preferences, change update URLs etc, all with access to extension storage API.

> the contentScript won't be blocked by HTTPS-only-mode on a http website

userScritps API was made from (fork of) contentScripts API and the only difference is the access to browser API. **HTTPS-only-mode** should affect both of them the same way.

If that is not the case, then there might be a bug in Firefox and/or an issue with the user-script itself.

**Comment by linsui** [comment]
I have a user script for a http site and need to fetch a http resource. When Hom is enabled it failed but it works well in the scratchpad. There is a difference that in userscript I use `GM.fetch` but in scratchpad I use `fetch`. I guess that maybe they run in different context and the userScript doesn't inherit the Hom setting.
I thought that it would be enough to  show a warning before switch a script to contentScript and maybe disable the option for webinstalled script..  Thanks!

**Comment by erosman** [comment]
> When Hom is enabled it failed but it works well in the scratchpad.

scratchpad context is different.

> There is a difference that in userscript I use GM.fetch but in scratchpad I use fetch.

In scratchpad, it uses the same HTTP for the `fetch` since it comes from the DOM.

`GM.fetch` is from background script and it only attempts HTTPS if HOM is enabled.

I recall others having issues with HOM. I will ask around.

**Comment by linsui** [comment]
> In scratchpad, it uses the same HTTP for the fetch since it comes from the DOM.

> GM.fetch is from background script and it only attempts HTTPS if HOM is enabled.

Sometimes `fetch` doesn't works because of CORR, I guess. So I have to use `GM.fetch`.

> I recall others having issues with HOM.

Maybe it's me :joy:. https://github.com/erosman/support/issues/259

**Comment by erosman** [comment]
Bugzilla discussion
[Cannot download HTTP resources in background script in HTTPS-Only Mode](https://bugzilla.mozilla.org/show_bug.cgi?id=1685862)
