### ISSUE TITLE
Text MultiCopy - Disable Notifications

### ISSUE THREAD

**Issue by Sopor** [erosman/support#28]
Even if i have enabled `Disable Notifications` it will show this message:

![image](https://user-images.githubusercontent.com/5789283/48651558-adfe7e00-e9fb-11e8-8ee1-09c761b84353.png)

**Comment by erosman** [comment]
From **Help**:

> Disable Notifications
> Select to disable Information Notifications (error messages are not disabled).

That is an error message. Without it, when user tries to paste/copy and storage is empty, nothing happens and user doesn't know why it is not doing anything.
