### ISSUE TITLE
Container settings not applied on reload

### ISSUE THREAD

**Issue by FearNaBoinne** [erosman/support#280]
Whenever I restart my PC, I have to go back in to FoxyTab's settings - Container and click 'save', before the automatic container function works.

For instance, I have a facebook container with these settings:
*.facebook.com
*.fbcdn.net
*.messenger.com
facebook.com
fbcdn.net
messenger.com

When I start FireFox fresh, and open FaceBook or Messenger, it opens in a normal tab, without being logged in. If I then go in to FT settings and press 'Save' in Container, and then return to the tab and refresh, it re-opens in a container tab, as expected...

I have observed this on 2 separate computers

**Comment by Originalme** [comment]
I have noticed this too, and can recreate it on demand if I can provide anything to assist.

**Comment by erosman** [comment]
Subsequent to #349, have you installed and enabled **Firefox Multi-Account Containers**?

Another post, claimed that saving values in the FoxyTab container enables **Firefox Multi-Account Containers**, if it was not enabled.

If that is the case, could it be that in a new install of Firefox, **Firefox Multi-Account Containers** is not enabled by default?
_Note: I use Nightly where it is always enabled._

To test, first check if **Firefox Multi-Account Containers** is enabled and working by right-clicking on the add Tab + (it show show container options).

**Comment by Originalme** [comment]
I have confirmed this is installed and enabled on my browser.

![image](https://user-images.githubusercontent.com/132492/127345829-5e6495ca-9b54-4629-baac-9c03d983f6e0.png)

The full settings page is below.

![image](https://user-images.githubusercontent.com/132492/127346065-0125c024-090a-4bec-802c-4bd10ccc5134.png)

I removed all the rules directly from the **Firefox Multi-Account Containers** extension, but I do have the **Facebook Contain** extension installed. I will go ahead and disable that to see if it helps and report my findings back in after work today or tomorrow.

**Comment by Originalme** [comment]
OK, got busy with work. I was able to test this again with the changes mentioned, but still having the same problem.

**Comment by erosman** [comment]
I will try to see what can be done.

**Comment by Originalme** [comment]
No worries, if there is anything else I can supply, let me know. I try to check this account at least once a week on github.

Also, I am on Fedora 34 for my operating system, not sure if that would make a difference for FF extensions.

**Comment by erosman** [comment]
Let me know if there are still any issues.
