### ISSUE TITLE
FM: deleting scripts not possible

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#281]
Deleting a script seems to be broken. The script does not get deleted, only the textarea goes blank and stays blank even after navigating to other scripts. Gave me a bit of a scare. Reopening the FM tab fixes the empty textarea problem, but the script I want to delete is still there.

**Comment by erosman** [comment]
You are right. I will fix it.

**Comment by erosman** [comment]
Fixed.. v2.16 uploaded
