### ISSUE TITLE
[Historia] Filter Patterns Help

### ISSUE THREAD

**Issue by tiniestkid** [erosman/support#283]
What are the formatting rules for Filter Patterns? Can you include AND OR statements? Is there any syntax? I'm specifically trying to create an AND statement so that if a URL matches two things like "apple.com" and "product-page" it'll get removed, but a formatting guide in general would be really helpful as I couldn't find one for Filter Patterns. I tried using the Match Patterns guide for Filter Patterns but it didn't work so I'm guessing that they're different.

**Comment by erosman** [comment]
Patterns are based on Glob or RegEx patterns.

AND|OR are logical expressions however you can incorporate a similar pattern using RegEx.

> I'm specifically trying to create an AND statement so that if a URL matches two things like "apple.com" and "product-page" 

For example the following matches above two in that order

`/^https:\/\/apple\.com\/.+product-page.+/`

**Comment by grahamperrin** [comment]
### Excluding Google search URLs from history

I had this: 

`^https://www.google.com/search.*$`

– but continued to find entries such as this in history: 

https://www.google.com/search?q=%22State+Partitioning%22+dFPI&tbs=li%3A1#unfucked

----

Please, what am I missing? 

Might this be any better?

`^https:\/\/www.google.com\/search.*$`

**Comment by erosman** [comment]
There are 2 types pattern in Historia:
- Glob type simplified pattern
- Normal Regular Expression


Glob type example: `^https://www.google.com/search`
It means whatever starts with `https://www.google.com/search`

Normal Regular Expression example: `/^https\:/\/www\.google\.com\/search.*/`
It means whatever starts with `https://www.google.com/search` and may have more after it.
Regular Expression must start and end with `/` e.g. `/.................../`

You may find the first type easier to use.
Often there is no need to use the ends with `$` character unless it is specific e.g. `^https://www.example.com/*.jpg$`.
It means whatever starts with `https://www.example.com/` AND ends with `.jpg`

**Comment by grahamperrin** [comment]
Thank you!

`^https://www.google.com/search` 

– works as expected. A visit to the linked search page causes the page to appear momentarily in, then disappear from, history.
