### ISSUE TITLE
[FoxyTab] Enable/Disable toggle for country flags/server location

### ISSUE THREAD

**Issue by GreatestFool** [erosman/support#284]
There is not a lot too this issue, as the title explains, simply that it'd be highly preferable to be able to disable the country flags/server location flags in the url field. For example, I already have FlagFox installed, so I end up with this:

![image](https://user-images.githubusercontent.com/3003484/107549647-5c400080-6bd0-11eb-8a52-7284c4352998.png)

**Comment by erosman** [comment]
If you **disable** the **Copy Tab IP**, it will not process country flag any more.

**FoxyTab -> Options -> Context Menu -> Copy Tab IP**

**Comment by GreatestFool** [comment]
Thank you, that worked :)

Kind of weird that it is not a separate option though, just in case you still want to still be able to copy the ip or something.

Oh well, my issue is solved so I'll just close this issue.

**Comment by erosman** [comment]
> Kind of weird that it is not a separate option though, just in case you still want to still be able to copy the ip or something.

The  processing will be disabled completely once the menu is disabled. It is designed for people who are using alternative add-on for this purpose so there was no need to duplicate the function.

**Comment by GreatestFool** [comment]
Ah, true I suppose. Forgot to consider that. Thanks for the explanation :)

**Comment by arandorion** [comment]
Just a suggestion. I spent an hour trying to figure out how to get rid of the flag in the address bar. I never would have figured out to disable "Copy IP" to get rid of the flag. From a user perspective, it is not intuitive at all. A user who doesn't know the inner workings of the extension would first have to figure out it had anything to do with a menu item. Then they would have to disable and re-enable *every* menu item until they figured out which one it was. Most will just remove the extension.

You may want to make it more clear or just disable the "feature" by default.

**Comment by erosman** [comment]
There is a Help document that explains it.

I will see what can be done for the next upgrade.

**Comment by erosman** [comment]
I have been thinking about this and there are considerations ...

Adding a separate Option to enable/disable flag display
- Disable the associated processes
  - What to do with the menu?
    - Keep menu: then users will ask why the menu or custom copy `{ip}` doesn't work
    - Remove the menu: then users will ask where is the Copy IP menu
- Keep the associated processes
  - Extra processing to get IP, Country which may not be used by the user since most will have another addon for that (hence the desire to disable the flag

**Comment by arandorion** [comment]
Thanks for looking into this!
