### ISSUE TITLE
[FireMonkey] Possible to disable linting?

### ISSUE THREAD

**Issue by mal** [erosman/support#285]
First, thanks for FireMonkey, been using it for years and really appreciate it's minimalistic approach. 😁

Unfortunately my preferred style of JS conflicts pretty heavily with CodeMirror's somewhat opinionated stance (not terminating lines with semi-colons, not using braces for one liners, etc). Is there a way to disable linting, or hint the linting gutter somehow? I had a look through the options exposed by CodeMirror and there doesn't seem to be any way to alter the linting rules to match (or at least not whine about) what is, after all, still valid syntax. Disabling CodeMirror completely even including highlighting wouldn't be ideal, but it doesn't seem like that's possible anyway, as the `"mode": "null"` option doesn't get saved in FireMonkey options either.

Thanks for you consideration!

**Comment by mal** [comment]
Naturally, no sooner had I written up this issue, I realised I could (kind of) do with with the CSS customisation by hiding the lint information:
```css
.CodeMirror-lint-markers, .CodeMirror-lint-marker {
  display: none
}
```

It's perhaps not ideal, but it does solve my issue. I'll leave this open in case a less hacky or more user-friendly solution is something you'd like to consider, but if not this can be closed. Thanks again for all your work on this project!

**Comment by erosman** [comment]
> First, thanks for FireMonkey, been using it for years and really appreciate it's minimalistic approach. grin

My pleasure :+1: 

> Disabling CodeMirror completely even including highlighting wouldn't be ideal, but it doesn't seem like that's possible anyway,

True as FM now gets data from CodeMirror output when editing.

> ... CodeMirror's somewhat opinionated stance ....

TBH, it is not CodeMirror. The Lint process is provided by JSHint.
It was also me who set a fairly strict JSHint options. 

However ................ you can change that completely to suit your preference. Check **JSHint Options** in FireMonkey help under **CodeMirror (advanced users)**.

> **CodeMirror** _(advanced users)_
> 
> Customize CodeMirror Configuration & JSHint Options with a valid JSON. JSHint is set to ECMAScript 2019 ES10 & fairly strict guidelines for coding excellence.

Previously: #258

**Comment by mal** [comment]
Oh wow, I can't believe I managed to miss that! 🤦

Thanks for the pointer, everything's now working great. 😀
