### ISSUE TITLE
[Firemonkey] using @match *://*/* shows error and breaks highlighting.

### ISSUE THREAD

**Issue by ryanmk54** [erosman/support#286]
using `@match *://*/*` shows an error and breaks highlighting. This initially made me think it was invalid. The */ makes codemirror think that is the end of the block comment. Full metadata block is below.
```
/*
==UserCSS==
@name ReactQueryDevtools
@match *://*/*
@version          1.0
@run-at document-idle
@inject-into        page
==/UserCSS==
*/
```

The error is
```
Expected LBRACE at line 5, col1.
Unknown @ rule: @version
```

**Comment by erosman** [comment]
TBH, the CSSLint error is correct AFA normal CSS is concerned.

This is how the CSS works out normally.

Start of the comment `/*`

```
/*
==UserCSS==
@name ReactQueryDevtools
@match *://*/
```
end of comment `*/`

start of the rest
```
*
@version          1.0
@run-at document-idle
@inject-into        page
==/UserCSS==
*/
```

FireMonkey. alters the userCSS metadata block `*://*/*`  at the time of injection to ensure correct behaviour of the CSS.

The error can be ignored. I will see if I can suppress that error.

**Comment by ryanmk54** [comment]
Thank you for the clarification and for creating the addon.

**Comment by erosman** [comment]
CodeMirror and CSSLint UserCSS Metadata Block with `*/` error suppressed in v2.31
