### ISSUE TITLE
How to add <style>.....</style> with GM_addStyle()?

### ISSUE THREAD

**Issue by tobwz** [erosman/support#288]
Assume I want to add a <style>.....</style> Element to an existing webpage.
If possible after &lt;head&gt;.......&lt;/head&gt; element.

How can I achieve this with GM_addStyle() command?

`GM_addStyle("<style> body {  max-width: 1024px !important; } </style>" );`

seems not to work. 

Keep in mind that this is a simplified scenario.
I don't want a solution like

`GM_addStyle("body {  max-width: 1024px !important; }" );`

The <style>....</style> tags must appear.

**Comment by erosman** [comment]
`GM.addStyle` | `GM_addStyle` in FireMonkey adds style via `<style>....</style>`.

Therefore, `GM_addStyle("body { max-width: 1024px !important; }" );` will result in:

```html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title> ... </title>
    ...
    ...
    ...
    <style data-src="scriptname.user.js">body { max-width: 1024px !important; }</style>
  </head>
  <body>
  ...
```

**Comment by tobwz** [comment]
> `Style is added to the end of `<head>` normally, and if not available to the end of `<body>`.

Thats exactly the problem.
Assume the <script>...</script> contains not a CSS but a javascript command.
Then it matters if the command is execute BEFORE or AFTER the webpage is loaded.

Can I somehow direct FireMonkey to put a <script> at the END of <body>?

**Comment by erosman** [comment]
> Assume the `<script>...</script>` contains not a CSS but a javascript command.

Injecting script is handled differently. Your question was about injecting CSS.

> Can I somehow direct FireMonkey to put a `<script>` at the END of <body>?

Again, the question was about `<style>.....</style>` injection via `GM_addStyle()`

You can always manually inject `<script>` at the END of `<body>` if you want. Read Help under: **Injecting code into page context**

```js
const script = document.createElement('script');
script.textContent = `... code ...`;
document.body.appendChild(script);
script.remove();
```

If you explain the situation more clearly, I will answer accordingly.
