### ISSUE TITLE
Text MultiCopy - adjustable notification time

### ISSUE THREAD

**Issue by Sopor** [erosman/support#29]
There should be an adjustable time to set how long the notifications should be visible (default seems to be 20 seconds).

**Comment by erosman** [comment]
The notification time is set by Firefox (not the extension) and it is not possible to change it.

It is possible to manually close it from the extension but that would mean adding a timer and ID to each and every notification and then run another process to manually close it. That is a lot of more processing (means more memory and CPU usage) for a little gain.

However, if there is a popular  demand for it, I can work on it.
