### ISSUE TITLE
[FireMonkey] How a page with CSP could access objects set by script?

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#292]
For example, let's say I want to intercept any setTimeout call made by the page. I could use Proxy. But in userScript context this would break everything, as any setTimeout access made by the page would be blocked as "restricted". So I need to set `@inject-into page` OR use `eval` in the code. Either way it wouldn't work in page with CSP (like GitHub). So unless I'm missing something there's no solution. FireMonkey needs to support exportFunction and cloneInto.

**Comment by erosman** [comment]
There have been discussions about page CSP & extension contentScript & userScript context.

- [[meta] Page CSP should not apply to content inserted by content scripts (V2 issue)](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027)
- [Investigate what CSP should be applied to userScripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1587494)
- [Websites can observe CSP violations from content scripts](https://bugzilla.mozilla.org/show_bug.cgi?id=1588957)

Unless Firefox implement some changes, the page CSP will prevent certain actions and `exportFunction()` and `cloneInto()` would not make any difference.

There is a hack that some extensions use, which is to alter the page CSP header, but that creates security issues and not possible for userScripts.

**Comment by pintassilgo** [comment]
It's true, TM rewrites CSP header. But GM doesn't, yet it can run userScripts that share objects with the page without affecting CSP. Maybe the answer is `exportFunction()` and `cloneInto()`...

If you try this code in a UserScript matching GitHub (as an example of page using CSP):
```
let obj = { a: 2 };
unsafeWindow.pageObj = cloneInto(obj, unsafeWindow);
```

If you paste `pageObj` in console, you'll see that the object is exposed to the page.
And CSP is till applied, as you can see by pasting the following code in console:

```
script = document.createElement('script');
script.innerText = 'console.log(1)';
document.body.appendChild(script);
```

**Comment by erosman** [comment]
> Did you mean script.textContent = 'console.log(pageObj);';, right? 

Yes... sorry... corrected.


AFA the rest, we discussed `exportFunction()` and `cloneInto()` with Mozilla engineers and it was not possible in userScripts API due to X-ray vision.

GM doesn't use userScripts API.

**Comment by pintassilgo** [comment]
Sorry for totally unrelated comment, but I don't know a better place to post it, since I don't think it's worthy a new issue: Greasemonkey doesn't support `GM.addStyle` (to fix in API table chart).

FM Help page is excellent, you should publish it elsewhere, it's the best available UserScript documentation.

**Comment by erosman** [comment]
> Sorry for totally unrelated comment, but I don't know a better place to post it, since I don't think it's worthy a new issue: Greasemonkey doesn't support GM.addStyle (to fix in API table chart).

Thank you. I will update the Help. :+1: 

> FM Help page is excellent, you should publish it elsewhere, it's the best available UserScript documentation.

Thank you for your kind comment.

**Comment by pintassilgo** [comment]
Another thing: you should use *static* links as references for GitHub code. For example, in "Context Comparison", you included this link:
https://github.com/violentmonkey/violentmonkey/blob/master/src/background/utils/preinject.js#L176
But the line is wrong because the file was modified recently. You should use something like
https://github.com/violentmonkey/violentmonkey/blob/59b5aa4814204d08e66dfc92c4023ab79edf0178/src/background/utils/preinject.js#L189

**Comment by pintassilgo** [comment]
> Unless Firefox implement some changes, the page CSP will prevent certain actions and exportFunction() and cloneInto() would not make any difference.

I just found out that this is not true. You could easily expose `exportFunction()` and `cloneInto()` to userScripts just like  `GM.*` and `GM_*` functions and this would fix everything. See here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1516356#c1

I just tried the attached extension (` user-script-register-example-v2-with-exportFunction.xpi `), registered the `setTimeout` example code I posted above and it worked perfectly in GitHub (page with CSP).

**Comment by erosman** [comment]
@pintassilgo Let me ask Luca and get back to you.

**Comment by pintassilgo** [comment]
I just added these two lines in FM's `api.js`, inside `script.defineGlobals`:
```
    exportFunction,
    cloneInto
```

And it works!

I see no reason to not implement this, as `exportFunction`|`cloneInto` only serves to do what UserScripts always did with just `unsafeWindow`.

With that, maybe I can finally migrate to FM. About the other remaining issue (regex includes throwing errors to console) I'm concluding that UserScripts simply shouldn't use regex.

**Comment by erosman** [comment]
> I just added these two lines in FM's api.js, inside script.defineGlobals:

Only that, without actually defining the function so it refers to same name function?

**Comment by pintassilgo** [comment]
> Only that, without actually defining the function so it refers to same name function?

Yes, only that, it's not needed to do something like `exportFunction: exportFunction` or
```
    exportFunction(fn, global) {
      return exportFunction(fn, global);
    }
```

`exportFunction` and `cloneInto` are already defined in the scope, you just need to expose them to UserScripts.

**Comment by erosman** [comment]
Good.. I had a chat a Luca and decided to add `exportFunction()` and `cloneInto()` in the next release v2.19

**Comment by erosman** [comment]
> With that, maybe I can finally migrate to FM. About the other remaining issue (regex includes throwing errors to console) I'm concluding that UserScripts simply shouldn't use regex.

userScripts API will be updated for manifest v3 and I have already asked for a method to abort so that I wont have to use `throw` (ref [Bug 1516478 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1516478#c5).

However, please note that the userscript with regex has the least efficient performance. Using `@match` is the best option.
