### ISSUE TITLE
[FireMonkey] options.html is reverting changes made in popup

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#294]
Steps to reproduce:
1. Click to Edit a script.
2. Click FM's toolbar button and toggle the enabled status of another script.
3. Click to Save the script loaded in Editor.

The enabled/disabled state of all scripts will revert to the state when options.html was opened.

Saving a script in editor shouldn't affect other scripts.

**Comment by pintassilgo** [comment]
A minor thing, not worthy a new issue: new scripts/styles created using the editor should be `[×] Enabled` by default. Just like scripts installed by links are enabled by default.

**Comment by erosman** [comment]
> Saving a script in editor shouldn't affect other scripts.

That is possible to do, but adds more processing to listen to & process changes made to enable/disable in popup.
Let me see how it is.

> A minor thing, not worthy a new issue: new scripts/styles created using the editor should be [×] Enabled by default. Just like scripts installed by links are enabled by default.

The reason is ....

- Scripts installed complete are meant to be used, therefore they are enabled by default
- New Scripts/CSS are meant to be edited and usually takes some edits before they are complete
- Enable button is LIVE which means clicking it toggles the script/CSS without needing to SAVE. Enabling it by default will start to inject an incomplete script/CSS which will run into error. Enable button can also be used to enable/disable multiple scripts at the same time by selecting them in the left panel list.

**Comment by pintassilgo** [comment]
>  That is possible to do, but adds more processing to listen to & process changes made to enable/disable in popup.

I guess it's not that hard or expensive, is it? While options.html is open (infrequent), create a listener between the page, background and popup...


> New Scripts/CSS are meant to be edited and usually takes some edits before they are complete

I respectfully disagree, I still think that the expected default is to set as enabled. Also, as a new manager expecting to get users, many like me come from other addons and need to migrate the scripts. Since FM can't import form other managers, I needed to manually paste the codes, so it was't exactly a new script from scratch. Not everyone shares UserScripts/styles as installable links, it's common to install by manually copy/pasting the code and it's expected the newly created style to be enabled.

> Enable button can also be used to enable/disable multiple scripts at the same time by selecting them in the left panel list.

So I just discovered the left panel. I thought there wasn't a scripts list in options page. IMHO, this panel should be visible and pinned by default or at least its menubutton should have a proper and clear name instead of the three vertical dots.

I couldn't select multiple scripts at the same time. Also don't think all of this is intuitive, to multi enable/disable by clicking a button above the editor with a single script code below. Next to the `Enable` button is `Save`, what it's supposed to do if you click it when multiple scripts are selected?

Suggestion: add titles to filter buttons in left panel list

**Comment by pintassilgo** [comment]
> Enabling it by default will start to inject an incomplete script/CSS which will run into error.

So, what I propose: enable by default when you first save a new script/style. Enable will be disabled until you do the first saving.

**Comment by erosman** [comment]
> So I just discovered the left panel. I thought there wasn't a scripts list in options page. IMHO, this panel should be visible and pinned by default or at least its menubutton should have a proper and clear name instead of the three vertical dots.

It was like that previously. I was changed recently to prepare FM for FF on Android (on popular demand)

> I couldn't select multiple scripts at the same time.

It is in the Help ... highlight multiple with mouse, like selecting text.

> [ ] Enable will be disabled until you do the first saving.

What if the user doesn't want to enable it?
I have may script/CSS that are not enabled. Some of them I only enable some times, not all the time.

**Comment by pintassilgo** [comment]
> It is in the Help ... highlight multiple with mouse, like selecting text.

Didn't work for me. 😕

> What if the user doesn't want to enable it?
> I have many script/CSS that are not enabled. Some of them I only enable sometimes, not all the time.

Me too. But when installing, do you have any doubt that at least 90% of time time people want the script to be enabled? at least for test it. Disabling is (almost) always done later. Also, if you're creating by typing/pasting the code, you're right on the screen to click disable if you're part of the <10%. The default, at least for **the first saving of a new script**, should be enabled. For sure. But this is a very minor thing.

**Comment by erosman** [comment]
> Didn't work for me. :confused: 

Let me check and if there is an issue, fix it.

AFA enable, let's see if there is a popular demand for it.

**Comment by erosman** [comment]
> new scripts/styles created using the editor should be [×] Enabled by default.

Done for v2.19
