### ISSUE TITLE
[FireMonkey] CodeMirror: highlight every instance of the selected word

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#298]
It's common for code editors to highlight all instances of the selected word. It's an useful feature. This can be easily added to CM by including the [match-highlighter.js](https://codemirror.net/addon/search/match-highlighter.js) module and setting `"highlightSelectionMatches": true` in CM config if you choose not to enable it by default (but I think you should).

Also, I'm probably missing something, but which config should I use to append two spaces instead of tab when I press Tab? When I implement CodeMirror for something I use
```json
{
  extraKeys: {
    Tab: (cm) => cm.execCommand('indentMore'),
    'Shift-Tab': (cm) => cm.execCommand('indentLess'),
  }
}
```
for that, but of course I can't paste this in FM's CodeMirror config because `JSON.parse()` fails.

**Comment by erosman** [comment]
> ... including the match-highlighter.js module  ...

That is possible .... let me try and see

> ... which config should I use to append two spaces instead of tab when I press Tab? ...

Personally, I prefer 2 spaces as well. At first I did set it that way but it runs into a problem.

- FM already sets the tab size to 2 Instead of default 4) in `tabSize: 2,` 
- To replace tab with space `Tab: (cm) => cm.replaceSelection('  '),` BUT it conflicted with multi-line selection indenting (select a few line user tab or Shift+Tab to increase/decrease indent. I haven't tried `indentMore` & `indentMore`. Nonetheless, some people prefer tabs to spaces.
- In order to set `extraKeys` ATM you have set & replace the entire `extraKeys` but that fails as valid JSON e.g.
```js
{
  "extraKeys": {
    "Ctrl-Q": "toggleComment",
    "Ctrl-Space": "autocomplete",
    "Alt-F": "findPersistent",
    "Tab": (cm) => cm.replaceSelection("  "), // conflict with multi-line selection
    "F11": (cm) => cm.setOption("fullScreen", !cm.getOption("fullScreen")),
    "Esc": (cm) => cm.getOption("fullScreen") && cm.setOption("fullScreen", false)
  }
}
```

> for that, but of course I can't paste this in FM's CodeMirror config because JSON.parse() fails.

True...

There is also the **➜ Tab to Spaces** from 3-dot menu.

**Comment by pintassilgo** [comment]
> I haven't tried indentMore & indentMore. Nonetheless, some people prefer tabs to spaces.

You should try, I think it has no issues and doesn't affect those who prefer `Tab` over spaces. `indentMore` and `indentLess` just follows `indentWithTabs` and make things more coherent.

Currently, FM editor defaults to `indentWithTabs = false`, so even if you press `Enter` in a block indented with `Tab`, the new line will be indented with spaces, respecting your `indentWithTabs` config. But if you press `Tab`, `Tab` will be inserted. I think this is not right. In a code editor, you only press `Tab` to indent, so `Tab` key should follow `indentWithTabs`. And that's exactly what the keys I posted fix.

**Comment by pintassilgo** [comment]
> In order to set extraKeys ATM you have set & replace the entire extraKeys but that fails as valid JSON e.g.

I'll wait for the fix, cause I want autocomplete, but `Ctrl-Space` is filled for years to quick search among open tabs. When I implement CodeMirror I use `Ctrl+Q` to autocomplete, this shortcut defaults to close Firefox but I've always disabled it.

**Comment by erosman** [comment]
> I'll wait for the fix,

I will work on it

> I think it has no issues and doesn't affect those who prefer Tab over spaces. 

There are many who prefer tabs and not spaces. Channing it may become unwelcomed. 
More feedback on this is needed.

Maybe it can have a custom setting to turn it off/on :thinking:

**Comment by pintassilgo** [comment]
> I will work on it

Thanks.

> There are many who prefer tabs and not spaces. Channing it may become unwelcomed.

Why? I don't think you understood what I said. The `extraKeys` from my first comment **doesn't affect** those who use `indentWithTabs: true`.

- Current FM default: indent with spaces, but pressing Tab insert Tab. This is not coherent.
- Current FM for a user who prefer Tab over spaces: he will set `indentWithTabs: true`, then will indent with Tab and pressing Tab will insert Tab. Right.
- If you add the suggested `extraKeys`: indent with spaces, Tab insert spaces. Coherent.
- If you add the suggested `extraKeys`, for a user who prefer Tabs over spaces: he will set `indentWithTabs: true`, then will indent with Tabs and pressing Tab will insert Tab. Right.

Now you understood? It won't change **anything** for who prefer `Tab`. It will just fix something that is currently wrong for those who prefer spaces.

**Comment by erosman** [comment]
What will happen when user presses TAB?
`indentWithTabs` should affect the start of the line and not the elsewhere e.g. in the middle of a line.

**Comment by pintassilgo** [comment]
Do you know a code editor that prints different char for Tab key depending on the position of the cursor? I use the popular Notepad++ and the only option about that is if Tab key will print tab or spaces (and I can define the number of spaces of course). There's nothing like "spaces for the beginning of the line and tab for other positions", it would confuse users. I never saw anything like that and even if it exists it's for sure very very unusual. And you like to say about "popular demand"... 🤷‍♂️

**Comment by erosman** [comment]
I tested with:
```
  Tab: (cm) => cm.execCommand('indentMore'),
  'Shift-Tab': (cm) => cm.execCommand('indentLess'),
```
The behaviour is odd since pressing tab **anywhere** on a line with cause indentation of the whole line.
It makes it impossible to use tab in insert 2 or 4 space anywhere other than start of the line.
This behaviour is totally against the way code editors behave.

Even making it optional, would break default `indentWithTabs: false`.

**Default Behaviour**
- indent with spaces
- Tab inserts `\t` anywhere

**With tab-to-space functions & `indentWithTabs: false`**
- indent with spaces
- Tab indents anywhere

**With tab-to-space functions & `indentWithTabs: true`**
- indents with tab
- Tab indents anywhere

**Comment by erosman** [comment]
**v2.19**
- Added option to add custom `extraKeys` to CodeMirror editor

**Comment by erosman** [comment]
I guess all the issues here are done. You can re-open it if there is anything else.

**Comment by pintassilgo** [comment]
> v2.19 ...

Thanks.

About `indentMore` and `indentLess`, I even removed my last comment when I found out what you said (pressing tab anywhere on a line with cause indentation of the whole line). This is really wrong, so I dismissed it. So far, the best I've got for `Tab` pressing is
```js
Tab: (cm) => cm.somethingSelected() ? cm.execCommand('indentMore') : cm.getOption('indentWithTabs') ? cm.execCommand('insertTab') : cm.execCommand('insertSoftTab')
```
That way, it seems to work as I thought it would work with `indentMore`/`indentLess`, with the only change from current FM default being that it will print the indent unit (defined in `indentWithTabs`) when you press `Tab`, while in FM there is no way to print spaces instead of tab.

The only thing I would improve from here is that pressing Tab when even a single char is selected is indenting the line. In this case, it should instead replace the selected char with Tab/spaces. It should only append a indent unit in the line if the entire text of the line is selected (ignoring indentation, so it's not needed the ENTIRE line to be selected, just the useful part).

**Comment by erosman** [comment]
ATM, the Tab situation is left to users and the custom settings JSON. It is not possible to add the function in that JSON.

**Comment by pintassilgo** [comment]
For the record, I guess I perfected the `extraKeys` `Tab` for what I wanted:
```js
Tab: (cm) => {
  function insertTabOrSpaces() {
    if (cm.getOption('indentWithTabs')) {
      cm.execCommand('insertTab')
    } else {
      cm.execCommand('insertSoftTab');
    }
  }
  if (cm.somethingSelected()) {
    function trim (str) {
      return str.replace(/^\s+(\S)|\s+(\n|$)/gm, '$1$2');
    }
    let indent;
    let sels = cm.listSelections();
    for (let i = 0; i < sels.length; i++) {
      let sel = sels[i];
      let fullLines = sel.anchor.line <= sel.head.line ?
                        editor.getRange({line: sel.anchor.line, ch: 0}, {line: sel.head.line}) :
                        editor.getRange({line: sel.head.line, ch: 0}, {line: sel.anchor.line});
      if (trim(fullLines) != trim(cm.getSelections()[i])) {
        cm.replaceSelection('');
        insertTabOrSpaces();
        return;
      }
    }
    cm.execCommand('indentMore');
  } else {
    insertTabOrSpaces();
  }
}
```
Results:
- it follows what `indentWithTabs` defines (if `Tab` key should print tab or spaces).
- If entire line(s) is selected (or at least the useful - trimmed - part), `Tab` will indent the line(s).
- If the selection doesn't match the entire line(s) (like if a single word is selected), then the selected string will be replaced by tab or spaces.

On how to add it on `Customize CodeMirror`, currently I can only think of using `eval()` instead of `JSON.parse()`, so you get the true object the user intended to write in textarea. But `eval()` isn't safe, it would probably be rejected by AMO.
