### ISSUE TITLE
Any way to import scripts from greasemonkey, other than doing it by hand, one-by-one?

### ISSUE THREAD

**Issue by mzso** [erosman/support#299]
I have a lot, and not much free time to go through all of them, or install them.

**Comment by erosman** [comment]
You can multi select with **import** button and import 100s together as long as they are in individual files.

- In GreaseMoneky ➜  Export a Buckup
- GreaseMoneky exports as ZIP
- Open the zip and take out all `***.user.js` and put them in one place
- In FireMonkey click **Import**
- `Ctrl` or `Shift` click all the files and they will be imported
- ATM, there is no process to import scripts' saved data e.g. `.gm.json` & `.stored.sjon`

**Comment by mzso** [comment]
@erosman 
Thanks. Though, still a lot of trouble. Not having the settings/data is a pain, but more of a problem is that I have a bunch of disabled scripts, with now way to distinguish them.

**Comment by erosman** [comment]
I understand.

The way GM creates backup, if FM was to read the zip, then it would also require a big zip library and if unpacked, due to storage data being based on folders, it is not possible to cursively open & read files.

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. márc. 17. 20:02 CET](https://github.com/erosman/support/issues/299#issuecomment-801335361 "2021-03-17T19:02:48Z - Replied by Github Reply Comments"):
> I understand.
> 
> The way GM creates backup, if FM was to read the zip, then it would also require a big zip library and if unpacked, due to storage data being based on folders, it is not possible to cursively open & read files.

Oh well.
Anyway, I ran into greater problems. I can't even find the import feature. I only see an import button on the options page, but that it seems to be for options.
But there's no import button on the scripts tab. Only an export button. I see no way to import anything. Is it broken or something?

**Comment by mzso** [comment]
![kép](https://user-images.githubusercontent.com/4479090/111525739-391fe800-875e-11eb-9a5a-798802f3e4b2.png)

**Comment by erosman** [comment]
Click on the 3-dot menu on the top left (next to Options). 

The import is there.

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. márc. 17. 20:42 CET](https://github.com/erosman/support/issues/299#issuecomment-801360907 "2021-03-17T19:42:04Z - Replied by Github Reply Comments"):
> Click on the 3-dot menu on the top left (next to Options).
> 
> The import is there.

Ah! So that's invisible when the dark theme is active. I only see it on hover.

Not sure if I would have found it, even if the button was visible. It's too well hidden. Plus having a "Script & CSS" tab that's not even usable for anything when opening options is more than a little confusing. Why even have it there when no script is loaded?

(Not sure if such feedback is desired, but in my opinion a script management page, or tab here in options would be better than this popup menu. More practical, and I wouldn't need to search for it.)

**Comment by erosman** [comment]
>So that's invisible when the dark theme is active.

Not for me  :shrug: 

![image](https://user-images.githubusercontent.com/6458876/111574470-c47e9500-87c1-11eb-9350-f38ef3b14398.png)

> Not sure if I would have found it, even if the button was visible. It's too well hidden. 

There is a Help which explains everything.

Initially, that 3-dot menu time was a left panel which was visible all the time. However that design does not work on Firefox for Android. The changes were made to make it compatible with Firefox for Android (although I don't use it myself).

I will see if I can improve it in the next upgrade by setting it default to pinned.

> Plus having a "Script & CSS" tab that's not even usable for anything when opening options is more than a little confusing. Why even have it there when no script is loaded?

You can change the theme from there without any script loaded. After scripts are loaded into editor, you can switch between the tabs, e.g. go to log or help tab and then back to "Script & CSS".

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. márc. 18. 05:59 CET](https://github.com/erosman/support/issues/299#issuecomment-801625690 "2021-03-18T04:59:16Z - Replied by Github Reply Comments"):

> **Update:** I think I know what has happen. Your `prefers-color-scheme` is dark but have not selected a dark theme in FireMonkey. Therefore some of the setting has not applied.

I guess that's something done by the browser? I only set the OS to dark.

I was just about to ask where is that option, es well as about blacklisting urls. I wouldn't have found them if the other three dot button on your screenshot doesn't catch my eye. This hiding stuff in not-really button looking buttons doesn't vibe to well with me.
You implied that the UI is like the way it is because of mobile. Couldn't the UI be different for android/desktop just like websites?  In my opinion it became a tad clunky for desktop. (On mobile everything is clunky. :) I only use a smartphone when a proper computer is not available.)

**Comment by erosman** [comment]
> You implied that the UI is like the way it is because of mobile. Couldn't the UI be different for android/desktop just like websites? In my opinion it became a tad clunky for desktop. (On mobile everything is clunky. :) I only use a smartphone when a proper computer is not available.)

I am the same.. I dont use mobile for browsing at all.
I have **Changed default Pin Menu to pinned** in the new upgrade so the panel is visible all the time, unless changed.
I have also changed the setting for when OS is set to dark to apply to the missing elements like the 3-dot menu, in the next upgrade v2.19.

FireMonkey continues to develop based on user feedback. The 3-dot menu was based on another user feedback.

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. márc. 18. 18:16 CET](https://github.com/erosman/support/issues/299#issuecomment-802138052 "2021-03-18T17:16:38Z - Replied by Github Reply Comments"):
>  in the next upgrade v2.19.

Cool. When is that due?

>  The 3-dot menu was based on another user feedback

I guess something is needed for mobile screens. It's just that using the same UI on both doesn't seem to work that well. For desktop especially.

**Comment by erosman** [comment]
> When is that due?

I will release it soon. 

> It's just that using the same UI on both doesn't seem to work that well.

I will continue to work on it until it gets optimal.
