### ISSUE TITLE
[FoxyTab] tab reloading--i don't want it

### ISSUE THREAD

**Issue by gitrdn** [erosman/support#3]
before i installed your foxytab, all my tabs would go idle and unload after a period of time except for  my google/twitter/etc tabs that actively reload automatically and provide a notification dot on the tab when there are new messages.  i like it that way because having the bulk of my tabs unloaded lightens the load on my system on the many tabs that may sit a while before i need them again, and yet i don't miss out on my messages.

i noticed on the options of your add-on that the tab reload interval does not go below 6 or higher than 30, and the default is 10, which would suggest that foxytab will not let tabs naturally unload and stay unloaded. is that correct? how can i ensure the loading states of my tabs remain the same as before foxytab? thanks.

**Comment by erosman** [comment]
The Tab Reload function of FoxyTab, doesn't do anything at all, until user activates it from the context-menu. It only start when user decides to start "Reload Tab Every" on a specific Tab and runs until it is stopped or tab closed.

Therefore it does not interfere with any other functions of the Firefox.

In fact, all FoxyTab context-menu functions are like that. None of them run automatically and they only run once when user selects the menu.

**Comment by gitrdn** [comment]
Thanks! I only wanted FoxyTab for copying URLs and moving tabs to the end, but they'll be handy when I need them and I appreciate your efforts.
