### ISSUE TITLE
Why is there still a space gap at the top?

### ISSUE THREAD

**Issue by pstein** [erosman/support#300]
I have a serious problem with settings up a working *.user.js script

Lets have a look at a - simplified - example:

The webpage:
https://www.thewindowsclub.com/flameshot-is-a-powerful-yet-simple-to-use-screenshot-software-for-pc

The *.user.js script:

```
// ==UserScript== 
// @name            ChangeLayoutTheWindowsClub
// @namespace       nsChangeLayoutTheWindowsClub
// @description     Change Layout TheWindowsClub
// @match           https://www.thewindowsclub.com/*
// @version         1.0.0
// @grant           GM_addStyle
// @require         http://code.jquery.com/jquery-latest.js
// ==/UserScript== 

$(".site-header").remove();

GM_addStyle(".site-inner { margin: 0 !important;  padding: 0px 10px 0 !important;  }");

```

As you can see after loading of the web page the article title touches almost the top border of the browser window (Firefox).

Now when I print this page (into PDF) there is surprisingly a huge space gap between top page border and the article title.

Why?

I cannot find any responsible CSS which is creating it.
As far as I can see there is no "@media print" CSS section.
So the title should touch the top pdf border as well - similar to the visual browser version.

But this is not the case

**Comment by erosman** [comment]
It is a quirk of Firefox Save as PDF.

I tried it even on this page and use `display: none` for part of the page and then generated the PDF but it had a big gap where the hidden element was.

Take a Screenshot works fine though.

**Comment by pstein** [comment]
Thank you for your comment.

However I am confused.

You said its a quirk of Firefox "Save as PDF".
You mean probably the new print function of Firefox v85ff

But when I disable this new Save function in config and use the old "Print...."  sub menu from "File" menu
then the (bad) result is the same.

You said: "I tried it even on this page and use display: none"
Onto which element did you apply this CSS instruction?

Furthermore I wonder why this gap appears only on the https://www.thewindowsclub.com" pages and not others.

So it must be something special.

Do you have an idea which CSS instruction the problem?

Thank you for commenting
Peter

**Comment by erosman** [comment]
> Do you have an idea which CSS instruction the problem?

I dont think the problem is the CSS.

I think the issue is Firefox and how it gets the data that it is going to process.

Try to hide somehting usig the F12 Developer Tools -> Inspector -> click on an element and use `display: none;`

```css
element {
}
```
to

```css
element {
  display: none;
}
```

Then Save as PDF or Print etc and see the result is the same with a gap where the original time should have been. 
In that case, you can file a bug in Bugzilla.

**Comment by pstein** [comment]
I have got it!

In a linked CSS stylesheet:
https://www.thewindowsclub.com/wp-content/themes/the-windows-club/style.css?ver=1.0.0
there is a special print definition for media printing:

@media print {
....
	@page {
		margin: 2cm 0.5cm;
	}
...
}

When I overwrite it in a Firemonkey script with

GM_addStyle("@media print { @page { margin: 0 !important; } }");

no more gap is visible.

I hate such guys which try to "optimize" the print layout independent from visual screen layout.

**Comment by erosman** [comment]
Good job finding the cause. :+1:
