### ISSUE TITLE
[FireMonkey] Allow user to set @run-at per script

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#301]
As you wrote in Help, each manager uses a different default for `@run-at`. FM's default `document-idle` is the safest for most cases, but also the *slowest* to run. This may reduce user experience in pages with significant delay between `document_end` and `document_idle`. I noticed that in my scripts. I'm former Violentmonkey user, which uses `document-end` by default, but in FM some scripts run a couple seconds later than they could, worsening the UX. So I edited the script defining `@run-at document-end` and things went back to normal, much better.

If you're not the original writer of an userScript and don't want to fork it, editing the code should be avoided at all costs, that's why every manager allows user settings like includes and excludes. Given the inconsistency of `@run-at` among managers, I think FM should provide a per-script `@run-at` option if the metadata is not set in the script.

Tampermonkey, the only other manager using `document-idle` by default, supports this feature (user defined `@run-at` per script).

**Comment by erosman** [comment]
Let's see how much demand there is for such feature.

**Comment by pintassilgo** [comment]
> Tampermonkey, the only other manager using document-idle by default, supports this feature (user defined @run-at per script).

Just to say that Violentmonkey also has this feature.
![image](https://user-images.githubusercontent.com/5483864/111892518-eacb4d00-89da-11eb-9f8a-93341323b4a5.png)

**Comment by erosman** [comment]
`@run-at` must be set by the userscript developer (not the user) since it affects how and if the script runs.

Any userscript developer that wants the script to be compatible with all mangers, would include the correct `@run-at`.

Including `@run-at` does not have any negative impact on the script at all.

Therefore, this issue should be left to userscript developers and not the userscript managers.

**Comment by pintassilgo** [comment]
We have a problem of **@run-at** behaving different on each manager. In my opinion, each extension having a different default value is reason enough to implement this minor and simple feature. But it goes further: as you know, each manager injects scripts differently, so even the same value for **@run-at** isn't enough to ensure the script will run at the right time. FM is maybe the only one to have real `document-start`. `document-idle` is also different for each one, from my experience VM runs earlier than others.

Sometimes the script needs to run at a specific time, but for the vast majority the code can be executed anytime after `DOMContentLoaded`. Given that both `document-idle` and `document-end` (the two defaults) run after `DOMContentLoaded`, authors don't usually bother to set **@run-at** because the script works anyway. The point is: if the script can run on `document-end`, that should be preferable because it runs earlier than `document-idle`, so it provides a better experience for the user.

Of course, in an ideal world, authors should always set **@run-at** with the best value. But they don't, and managers always allowed that, as it was never required to set **@run-at**. This is far from being the only "tolerance to not optimal" from managers. As you know, authors should always use **@match** instead of **@include**, but yet **@include** is still universally supported. And there are probably more examples like this.

I don't understand, what's the problem of implementing this easy (right?) feature that will not add complexity on the code nor cause any performance regression? I guess I made it clear the use case, on how it can be useful.

Someone may share it's personal scripts, but not bother to provide any compatibility shims because ultimately it's for personal use. So an author using GM or TM may release a script without defining **@run-at**, but expecting it to run at `document-end`. In TM, the manager which uses `document-idle` by default, users can set per-script custom **@run-at**. So can VM users.

If I'm FM user, I install a script without **@run-at** and I notice this script would run better at `document-end`, but I don't want to lose the ability of receive updates from the original script. So I set custom **@run-at**, if FM allows to. Why not?

**Comment by erosman** [comment]
While extra features are good, there is also the consideration of not becoming a bloatware.
There is no end to the number of things that can be set per-script.
Should UI be created to set all metadata block entries per-script?

- TM has per script settings for: 
auto-update, run-at, noframes, updateURL, include, exclude, match, user include, user exclude, user match, whitelist, temporary whitelist, user whitelist blacklist, require

- VM has per script settings for: 
auto-update, run-at, homepage, updateURL, downloadURL, user include, user exclude, user match, user exclude-match

- GM has per script settings for: 
auto-update, user include, user exclude, user match

**Comment by pintassilgo** [comment]
> While extra features are good, there is also the consideration of not becoming a bloatware.

Right, but:
- The requested feature doesn't help FM to become bloatware because it's a very simple thing that wouldn't have any impact. It wouldn't make the code more difficult for you to maintain/read/write, it wouldn't increase memory/CPU usage...
- Given the current UI, this feature wouldn't even pollute the options page, as user custom settings are already pretty hidden.
- I hope I got to show you how this feature can be useful and how is something almost without workaround, it's not pointless.

> Should UI be created to set all metadata block entries per-script?

No. My opinion:
Auto-update (which is not a metadata block), match, exclude-match (I understand FM needs to support include and exclude, but it shouldn't endorse them by allowing customs), run-at, downloadURL and noframes.

I only included downloadURL because unlike other managers FM doesn't treat the source URL as the downloadURL when the script doesn't have one.

**Comment by erosman** [comment]
OK... added custom per script `run-at`


> I have only included downloadURL because unlike other managers FM doesn't treat the source URL as the downloadURL when the script doesn't have one.

FM treats the source URL as updateURL if it is from greasyfork.org, sleazyfork.org, openuserjs.org, userstyles.org

**Comment by pintassilgo** [comment]
Thank you.

As the issue was solved, you can close this one.

> FM treats the source URL as updateURL if it is from greasyfork.org, sleazyfork.org, openuserjs.org, userstyles.org

I suggest you to include github.com. Example:
https://github.com/Infocatcher/UserScripts/blob/master/Direct_Images/direct_images.user.js

**Comment by erosman** [comment]
github was not added since it was treated as a basic tab loaded script but I will work out something for that too.

**Comment by erosman** [comment]
v2.20 is out. Let me know if there are any issues to reopen this topic.
