### ISSUE TITLE
FireMonkey: it may not be necessary to push *://*/* in scripts with @include or @exclude

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#304]
I know that regex in \@include and \@exclude makes FM to push `*://*/*` because userScripts API doesn't support regex. I also know these metadata support less strict rules for host. But I guess it's kinda easy to detect which metadata can be directly treated as \@match or **@exclude-match**. If there is no nonconvertible \@include and \@exclude, there is no need to push `*://*/*` and `file:///*`.

**Comment by erosman** [comment]
Originally (before v2.5), FM used to convert `@include` and `@exclude` to `@match` & `@exclude-match` with some conversion patterns and left the rest which would cause an error when registering the script.

From v2.5, FM doesnt try to convert them and leaves them to the new process.

Problem is that it is not possible test if a pattern is a valid match-pattern or not. Therefore, something like the following cant be converted
```
@include          *://*.example.com/*
@include          *://*.google.*/*
```

You would also be surprised at some overlapping `@include` in some user-scripts (and also extension `manifest.json`).

```
// @match       http://*.nexcess.net/*
// @exclude     http://*.nexcess.net*
// @match       https://pizzaonline.dominos.co.in/*
// @exclude     https://pizzaonline.dominos.co.in*
// @exclude     https://www.google.*
// @exclude     https://mega.io/
// @exclude     https://www.express-scripts.com/*
// @exclude     https://www.sous-titres.eu/*
// @include     http://*
// @include     https://*
// @include     file:///*
```

**Comment by pintassilgo** [comment]
> Problem is that it is not possible test if a pattern is a valid match-pattern or not.

From what I read, I thought it was. Do you have an example? 

> `@include          *://*.example.com/*`

What about the following?
```
@match           *://*.example.com/*
@exclude-match   *://example.com/*
```

> `// @exclude     https://pizzaonline.dominos.co.in*`

Since this one have wildcard in host, it should be considered as nonconvertible just like regex.

What I'm saying is for trivial convertible patterns like this:
`// @exclude		https://radikal.ru/video/*`

FM don't need to change anything here, just treat it as **@exclude-match**.

**Comment by erosman** [comment]
> From what I read, I thought it was. Do you have an example?

Where did you read it?
At the moment, there is no API to test is a pattern is valid. There used to be one in the legacy Firefox.
Otherwise, the whole process of deconstruction a match-pattern has to be performed (as in `MatchPattern.cpp`) to check it.

I made a basic one to test some common issues but it is not 100% of the issues.

> FM don't need to change anything here, just treat it as @exclude-match.

The problems in my example were missed...

```
because of these @include
// @include     http://*
// @include     https://*
// @include     file:///*

these @match are meaningless
// @match       http://*.nexcess.net/*
// @match       https://pizzaonline.dominos.co.in/*


this @exclude will also match the @match so the @match is meaningless
// @exclude     https://pizzaonline.dominos.co.in*
// @match       https://pizzaonline.dominos.co.in/*
```

**Comment by pintassilgo** [comment]
> At the moment, there is no API to test is a pattern is valid.

I wasn't thinking about an API, but in something implemented by FM. From what I read, I guess it's not that hard to check if a pattern can be convertible to match patterns. Given that this would only run on script install/update, it's not something to throw away because of performance.

> The problems in my example were missed...

Right, people are really bad at writing patterns. But I don't think this is an argument against what I proposed.

**Comment by erosman** [comment]
Let me see how it will work out

**Comment by erosman** [comment]
> I know that regex in @include and @exclude makes FM to push *://*/* because userScripts API doesn't support regex. 

If there is no regex, the normal `@include` and `@exclude` converted to `Glob` doesn't perform too badly. It is not as robust as `@match` & `@exclude-match` but that shouldn't be a major problem.

When there is a regex, it involves a workaround that affect the performance.

**Comment by pintassilgo** [comment]
Initial thinking about this, for `@include`/`@exclude` patterns:

- If it has no `*`, FM can safely treat it as `@match`/`@exclude-match`
- If it has complete domain followed by slash, FM can safely treat it as `@match`/`@exclude-match`, no matter what comes after (example: `https://www.example.com/search*aetaet*eataet`)

I think that just these two rules can cover the vast majority of `@include` and `@exclude`, preventing the unnecessary pushing of `*://*/*` in most existing scripts. At first sight I guess they are enough, there's no need to do nothing more complex.

Note: TLD list is **very** incomplete. For instance, here in Brazil the most popular TLD by far is `.com.br` which doesn't exist in FM list. [Here](https://publicsuffix.org/list/public_suffix_list.dat) is the full list, used by Violentmonkey, Mozilla etc.

**Comment by erosman** [comment]
> TLD list is very incomplete. For instance, here in Brazil the most popular TLD by far is .com.br which doesn't exist in FM list. Here is the full list (and here as JSON), used by Violentmonkey, Mozilla etc.

True.. bit that was made as a helper to cover most common case, not all case.

> Initial thinking about this, for @include/@exclude patterns:

Userscript developers could consider using `@match/@exclude-match`. It is easier for them to do it.

There are also many errors in many userscripts such as overlapping rules which causes complications when trying to convert `@include` to `@match`.

With **User Metadata** in 2.35 users can improve userscript matching performance with their own rules.

Let me see what can be done about auto-converting some rules.

**Comment by erosman** [comment]
v2.35
Added limited <code>@include/@exclude</code> to <code>@match/@exclude-match</code> auto-conversion
