### ISSUE TITLE
[Firemonkey] Immediately apply changes when toggling stylesheets on or off

### ISSUE THREAD

**Issue by Markussss** [erosman/support#305]
I have a few userstyles that are intended to only be turned on a few times here and there, not for any single site or page. An example is a userstyle for flipping all videos on a page horizontally, for example, in case I come across a video that has been mirrored and want to watch it un-mirrored. With other userstyle managers, toggling the userstyle on or off will immediately apply the CSS to the view, but in Firemonkey, the CSS is only applied after a reload. I want the userstyle to be enabled or disabled immediately when I toggle its state.

**Comment by erosman** [comment]
As already discussed in #295 Style manager use a manual injection method (extension matching URL of each tab to available style and then injecting) while FireMonkey uses an automatic injection (all are set at start and pass to Firefox to inject natively when tab refreshes).

It is not possible with the current API to add/remove styles without refreshing the tab.

However.... the FireMonkey scratch pad can manually inject and remove.
I will see if the scratchpad function can be extended to include installed scripts :thinking:

**Comment by erosman** [comment]
I have thought of a feature which can help with your request.

**New feature can:**
- temporary inject any listed userCSS (enabled or not) as long as it is not already injected in the tab with API
- remove above temporary userCSS

**New feature can not:**
- Remove userCSS injected automatically with API (e.g. enabled userCSS that applies to a page)

If it works out, it will be in next v2.20

**Comment by Markussss** [comment]
Thank you for getting back to me so quickly! Great response.

> temporary inject any listed userCSS (enabled or not) as long as it is not already injected in the tab with API

This would be a good solution for my use, although it would be even better to never have to reload the tab in order to add the style.

**Comment by erosman** [comment]
v2.20 is out. Let me know if there are any issues to reopen this topic.
