### ISSUE TITLE
[FireMonkey] If you rename an UserScript, all previous data is erased

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#309]
This is a critical bug. FM must just rename the key in storage to match the new name.

FM must know the difference between create, rename and delete. If I'm editing and I click to save, anything other than updating code/metadata is unwanted.

**Comment by erosman** [comment]
> FM must just rename the key in storage to match the new name.

It does.... option.js line 1000-1014

>  If I'm editing and I click to save, anything other than updating code/metadata is unwanted.

Please explain more.

**Comment by pintassilgo** [comment]
It's not working. I lost all data from one script because I renamed it.

**Comment by pintassilgo** [comment]
Created the script with `await GM.setValue('test', 'ok')`, loaded once, looked at storage:
![image](https://user-images.githubusercontent.com/5483864/113498695-d456e280-94fe-11eb-8073-2edcb05820a7.png)

Replaced the code by `await GM.setValue('test2', 'ok2')`, renamed, reloaded about:devtools-toolbox. Nothing has changed, but `_bug309` should have been renamed to `_bug309 - renamed` (the new name). So I loaded a page where the scripts applies, then looked again to storage:
![image](https://user-images.githubusercontent.com/5483864/113498764-6b239f00-94ff-11eb-8704-cc1ce1ac762b.png)

It should be:
`key = _bug309 - renamed`

`value = {"test":"ok"},{"test2":"ok2}`

**Comment by pintassilgo** [comment]
So you just need to add

`await browser.storage.local.set({['_' + data.name]: pref['_' + data.name]});`

next to

`await browser.storage.local.remove('_' + oldName);`

But there's another issue, that may have caused my data loss: data is not sync'ed in options tab. Steps to reproduce:

1. Create an script with `GM.setValue('test', 'ok')` and load it once.
2. You'll have `{"test": "ok"}`.
3. But you still havent closed options.html since the creation of the script, and options.html still has storage empty for the new script.
4. So you rename the script and save, after the fix I proposed.
5. Storage is erased because it saves the cached storage from when options.html was loaded.

**Comment by pintassilgo** [comment]
For the issue described in last comment, just add

```js
browser.storage.onChanged.addListener((changes, area) => {
  Object.keys(changes).forEach(item => pref[item] = changes[item].newValue);
});
```

**Comment by erosman** [comment]
I know what happened.... :man_facepalming: 

Originally the code was ...
```js
pref['_' + data.name] = pref['_' + oldName];
await browser.storage.local.remove('_' + oldName);
...
....

browser.storage.local.set(pref);     // update saved pref
```

Above would update the entire `pref`, including `['_' + data.name]`

Later, I changed it to the following for better performance BUT forgot to update the `['_' + data.name]`
```js
browser.storage.local.set({content: pref.content});
```

I will fix it.. thank you :+1:

**Comment by pintassilgo** [comment]
Thanks. You may also want to fix this in `processResponse` (if script is renamed on update).

**Comment by erosman** [comment]
> You may also want to fix this in processResponse (if script is renamed on remote update).

Fixed ... both in manual update and auto-update

**Comment by erosman** [comment]
v2.23 uploaded ... let me know if there are any issues
