### ISSUE TITLE
[FireMonkey] Import is not retrieving GM* values

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#310]
I exported my settings, the generated JSON has GM* values from scripts. But there's something wrong with importing. Settings, scripts and styles are imported, but stored values are not.

**Comment by pintassilgo** [comment]
Also, you may consider the possibility of adding support for individual export to include storage, not just the script/style source as it is currently.

**Comment by pintassilgo** [comment]
I also just noticed that importing removes every existing script/style. I think there should be an option about this, people may lose everything when they just wanted to import a single script.

**Comment by erosman** [comment]
> I exported my settings, the generated JSON has GM* values from scripts. But there's something wrong with importing. Settings, scripts and styles are imported, but stored values are not.

Previously #299

> Also, you may consider the possibility of adding support for individual export to include storage, not just the script/style source as it is currently.

Export is meant for **export** script/css and not custom or stored data.
Options export will export all data, to be imported into another FireMonkey instance or as back-up.

> I also just noticed that importing removes every existing script/style. I think there should be an option about this, people may lose everything when they just wanted to import a single script. I know there's another Import on the left for this, but the UI is not clear.

Which importing are you referring to?

- Options -> Import
  for all data
- Script list -> Import
  for one or more individual userscript/userCSS OR Stylus import

**Comment by pintassilgo** [comment]
> Previously #299

It's not the same, I'm importing from FM to FM, #299 is about GM → FM.

> Options export will export all data, to be imported into another FireMonkey instance or as back-up.

The problem is, despite stored script data (GM* values) is exported, it's not imported.

---

FM UI should be more clear about the differences between every import/export button.

And I think "options import" shouldn't remove existing data data isn't included in the imported file.

- Settings: obviously must be replaced.
- Scripts/styles:
  - if already exists, replace
  - if it's new, add
  - don't remove existing script not being replaced by the imported file.

**Comment by erosman** [comment]
> It's not the same, I'm importing from FM to FM, #299 is about GM → FM.

I explained in that topic why it is not possible since it GM exports as zip and then it is in directory based JSON and it is not possible to recursively traverse local file system.

FireMonkey at the moment only has **Stylus import** feature.

"options import" is meant to replace ALL extension data, not to concatenate data. That is how all extension imports would work. It is a back-up data.

**Comment by pintassilgo** [comment]
> I explained in that topic why it is not possible since it GM exports as zip and then it is in directory based JSON and it is not possible to recursively traverse local file system.

I'm not talking about GM, I don't use GM, I use FM.

I was doing tests in FM in a test profile, so I exported the data from my main profile.  The exported JSON includes scripts stored data, but it isn't parsed on import. So what's the point of exporting stored data if it's skipped on importing? That's a bug.

> no other direct import from other managers

I'm not importing from other managers, I'm importing from FM.

> "options import" is meant to replace ALL extension data, not to concatenate data. That is how all extension imports would work. It is a back-up data.

GM disagrees
![image](https://user-images.githubusercontent.com/5483864/113610313-74665600-963c-11eb-9b3b-a6778255dfc6.png)

VM also disagrees, did a test here and installed script weren't removed when I imported others. Only scripts with the same name were overwritten.

The same for TM.

So FM is the only exception.

I know that Imagus also does importing without removing existing data first and probably there are many others.

**Comment by pintassilgo** [comment]
Maybe you got confused because I said "GM* values". This is not related to Greasemonkey extension. Scripts can only store data through GM.setValue/GM_setValue. That's what I meant.

**Comment by erosman** [comment]
> I was doing tests in FM in a test profile, so I exported the data from my main profile. The exported JSON includes scripts stored data, but it isn't parsed on import. So what's the point of exporting stored data if it's skipped on importing? That's a bug.

I see... it should .. I will test it and get back to you.

> GM disagrees ...... VM also disagrees

The normal import in FM, tries to rename and `throw` error if it cant.

The extension back-up import/export is meant to restore the entire extension data to a previous state. It replaces everything. That is how restore back-up, or move/copy extension data to another FM instance work. This process should not be mistaken with importing scripts.

FM at the moment does not have a partial import/export that imports/export part of its data e.g. some script with stored userscript data.
It can be considered as a new feature if there is a popular demand for it.

**Comment by erosman** [comment]
> The exported JSON includes scripts stored data, but it isn't parsed on import.

You are right :+1:  .... I will fix it

**Comment by erosman** [comment]
> FM at the moment does not have a partial import/export that imports/export part of its data e.g. some script with stored userscript data.
> It can be considered as a new feature if there is a popular demand for it.

Looking at GM|TM|VM ...
- GM exports directory based `name.user.js` `.gm.json` `.files.jso`
- TM exports `name.user.js` `name.options.json` `name.storage.json`
- VM exports `name.user.js` `violentmonkey` (JSON of options & script storage)

I have to see what would be the best format. :thinking:

**Comment by erosman** [comment]
v2.24 uploaded

**Comment by pintassilgo** [comment]
Tested and it's working, thanks.
