### ISSUE TITLE
[FireMonkey] Clicking "Edit" in popup doesn't work if current tab is a container tab

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#311]
1. Click FM toolbar button;
2. Click a script;
3. Click Edit
4. Expected: editor opens for clicked script.

This works if active tab when you clicked FM button was a normal tab (default container). But if the tab was from non-default container (Work, Personal, whatever), clicking Edit just opens options.html page in "Options" view, not in Editor view for the clicked script.

**Comment by erosman** [comment]
It works for me testing on Nightly on container tabs.

It doesnt work when in Private window.

**Comment by pintassilgo** [comment]
After your comment, I just tested on latest Nightly (20210408215439): created a fresh new profile. installed FM, installed a script, clicked to edit in normal tab: it works. Opened a container tab (Personal), tried again, doesn't work. So it's like as I said in first comment.

**Comment by erosman** [comment]
I tried again...

- Opened new container tab (Personal)
- Opened google
- FM tool bar -> popup -> info -> edit
- Opens the selected script/CSS

Even switching scripts works fine for me i.e. FM options is open with a script and click edit another script in popup.

Can someone else check this too?

**Comment by pintassilgo** [comment]
Just commenting to confirm that this works as expected. Because the usual is for the options tab to open in default container. I was using something that forces FM options to open in a container tab. Thus, `localStorage` is empty and there's no action to perform, so no script is selected for editing.

FM shouldn't handle this edge case. Firefox tries is to always open options tab in default container and I was *hacking* that, so this issue can be considered as invalid, so it's right it's closed.
