### ISSUE TITLE
[foxy tab] [feature request] move all of domain to new window

### ISSUE THREAD

**Issue by nerdCopter** [erosman/support#312]
Foxy Tab
Feature Request

Option to move all tabs of current-tab domain to New Window.

e.g.  50 open tabs, 22 are youtube.  Right click tab>Move>"This Domain to new Window".

ty! <3

**Comment by erosman** [comment]
OK ... I will work on it

**Comment by erosman** [comment]
Host Move to New Window was added in v2.16
