### ISSUE TITLE
[FireMonkey] Beta Testing

### ISSUE THREAD

**Issue by erosman** [erosman/support#313]
I am currently working on a major restructuring of the FireMonkey data storage in v2.25. Once the code is done, if there is an interest, I can post the new version for beta testing.

Please note that the changes will break previous versions therefore, beta testers must backup (export) options before testing (so that they can import after reinstalling v2.24).

**Comment by pintassilgo** [comment]
OK, I can test.

**Comment by erosman** [comment]
Thank you. I will post it as soon as I am finished with initial tests.

**Comment by erosman** [comment]
Here is v2,25beta

- Export Options first (for back-up)
- it is better if there are saved sciprt storage e.g. GM_setValue to test the DB migration
- Please test create/rename/delete etc

Let me know if there are issues.

[firemonkey.2.25beta.zip](https://github.com/erosman/support/files/6330548/firemonkey.2.25beta.zip)

**Comment by erosman** [comment]
Here is updated v2.25beta

[firemonkey.2.25beta.zip](https://github.com/erosman/support/files/6336123/firemonkey.2.25beta.zip)

**Comment by erosman** [comment]
Here is updated v2.25beta2

[firemonkey2.25beta2.zip](https://github.com/erosman/support/files/6338286/firemonkey2.25beta2.zip)

**Comment by pintassilgo** [comment]
Sorry for my late response, but only now I had time to test a little. Updated to v2.25b2, apparently everything is working fine.

But then I tried to test something I wouldn't do normally: while already with v2.25b2, I exported FM data then I imported it in a new profile after installing v2.25b2. 

Apparently everything was imported, but an error was thrown to console right after the many "register" and "unregister" logs:
> can't access property "enabled", oldValue is undefined options.js:235
>    Script moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/options.js:235
>    forEach self-hosted:206
>    Script moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/options.js:225
>    apply self-hosted:2644
>    raw resource://gre/modules/ExtensionCommon.jsm:2423
>    onChanged chrome://extensions/content/child/ext-storage.js:329
>    apply self-hosted:2644
>    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:616
>    fire resource://gre/modules/ExtensionChild.jsm:806
>    recvRunListener resource://gre/modules/ExtensionChild.jsm:810
>    recvRunListener self-hosted:1161
>    _recv resource://gre/modules/ConduitsChild.jsm:78
>    receiveMessage resource://gre/modules/ConduitsChild.jsm:184
>    (Async: JSActor query)
>    _send resource://gre/modules/ConduitsChild.jsm:61
>    _send resource://gre/modules/ConduitsParent.jsm:228
>    _send self-hosted:1265
>    listener resource://gre/modules/ExtensionParent.jsm:1001
>    apply self-hosted:2644
>    raw resource://gre/modules/ExtensionCommon.jsm:2423
>    listenerLocal chrome://extensions/content/parent/ext-storage.js:193
>    notifyListeners resource://gre/modules/ExtensionStorageIDB.jsm:860
>    receiveMessage chrome://extensions/content/parent/ext-storage.js:81
>    (Async: MessageListener.receiveMessage)
>    <anonymous> chrome://extensions/content/parent/ext-storage.js:61
>    asyncGetAPI resource://gre/modules/ExtensionCommon.jsm:1615
>    AsyncFunctionNext self-hosted:674
>    (Async: async)
>    asyncLoadAPI resource://gre/modules/ExtensionCommon.jsm:1228
>    asyncFindAPIPath resource://gre/modules/ExtensionCommon.jsm:1309
>    recvAddListener resource://gre/modules/ExtensionParent.jsm:1024
>    recvAddListener self-hosted:1161
>    _recv resource://gre/modules/ConduitsChild.jsm:78
>    receiveMessage resource://gre/modules/ConduitsParent.jsm:371
>    (Async: JSActor query)
>    _send resource://gre/modules/ConduitsChild.jsm:63
>    _send resource://gre/modules/ConduitsChild.jsm:111
>    _send self-hosted:1265
>    addListener resource://gre/modules/ExtensionChild.jsm:642
>    addListener resource://gre/modules/ExtensionChild.jsm:885
>    register chrome://extensions/content/child/ext-storage.js:335
>    addListener resource://gre/modules/ExtensionCommon.jsm:2487
>    addListener resource://gre/modules/ExtensionCommon.jsm:2552
>    addListener resource://gre/modules/ExtensionCommon.jsm:1106
>    addStub resource://gre/modules/Schemas.jsm:2795
>    process moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/background.js:278
>    AsyncFunctionNext self-hosted:674
>    (Async: async)
>    ProcessPref moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/background.js:262
>    <anonymous> moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/background.js:257
>    (Async: promise callback)
>    <anonymous> moz-extension://96e5f13d-f79c-4e1b-bb1c-c174ed5b11f5/content/background.js:257
>    InnerModuleEvaluation self-hosted:2346
>    evaluation self-hosted:2317

The real problem is: I noticed that one script was being loaded twice in every matched page. Maybe this is the case for every script, but that one was noticeably because it creates an element, and two identical elements were being created. I reloaded the page a couple of times and always the script runs twice.

After restarting Fx, things went back to normal, with scripts loading a single time. No data was lost in the process afaik, script storage is OK.

**Comment by pintassilgo** [comment]
Easy test-case:
1. Install v2.25beta2.
2. Create this script:
```

// ==UserScript==
// @name             Tst
// @match            https://example.com/
// @version          1.0
// ==/UserScript==

document.body.innerHTML += 'tst ';
```

3. Open https://example.com/ and you'll see "tst " at the bottom of the page.
4. Open FM settings and export everything.
5. Delete FM and restart Fx.
6. Install v2.25beta2 again.
7. Import the data exported in step 4.
8. Reload https://example.com/ and you'll see "tst tst " at the bottom of the page. You can refresh the page if you want, the script always loads twice.
9. Restart Firefox and load the page again, now things went back to normal with just a single "tst ".

**Comment by erosman** [comment]
As mentioned in the Help. the Import in v2.55 is different in  this way that it merged old data with new data.

- old options will be replaced with the imported
- old scripts with the same name will be replaced with the imported
- old scripts not present in the import will remain

AFA the bug, I will investigate and fix it and post an updated beta.


> You can see an error being reported in Browser Console, "can't access property "enabled", oldValue is undefined".

That is from `storage.onChanged.addListener` ... I will fix that

> Reload https://example.com/ and you'll see "tst tst " at the bottom of the page. You can refresh the page if you want, the script always loads twice.

That shouldn't happen ... Can you export the data again and see if there are 2 scripts in it?

**Comment by pintassilgo** [comment]
The new exported data is exactly the same as the previous, no duplicates.

**Comment by erosman** [comment]
Here is updated v2.25beta3

[firemonkey.2.25beta3.zip](https://github.com/erosman/support/files/6369045/firemonkey.2.25beta3.zip)

**Comment by pintassilgo** [comment]
Thanks. The two reported issues were fixed.

**Comment by erosman** [comment]
Thank you. Please let me know if you find any other issues.

**Comment by erosman** [comment]
There is an error in the new code when updating script... I will fix it and release.

**Comment by erosman** [comment]
Here is updated v2.25beta4

[firemonkey..2.25beta4.zip](https://github.com/erosman/support/files/6369068/firemonkey.2.25beta4.zip)

**Comment by erosman** [comment]
@pintassilgo Did you try the latest beta?

**Comment by pintassilgo** [comment]
Tested a little back then and found no other issue. But just for testing, it's not in my main profile (cause as you know I use a forked version and I'll wait the release to merge).
