### ISSUE TITLE
[FireMonkey] New JS and CSS icons

### ISSUE THREAD

**Issue by StoyanDimitrov** [erosman/support#316]
Here are new JS and CSS icons. Made with the same font  and letter size and overall the same appearance. Copyleft.

In a [zip](https://github.com/erosman/support/files/6330027/js-and-css-icons.zip) because GitHub does not allow me to attach SVG files directly.

**Comment by erosman** [comment]
Thank you.... I will try them out. :+1:

**Comment by erosman** [comment]
Should I add the credit?

**Comment by StoyanDimitrov** [comment]
No need to.
