### ISSUE TITLE
[Edit] [Suggestions] Add markdown syntax support

### ISSUE THREAD

**Issue by Korb** [erosman/support#319]
At the moment, there is no add-on for Mozilla Firefox that would provide the user with the ability to quickly format text with markdown syntax rules.

[Basic syntax](https://www.markdownguide.org/basic-syntax/), [extended syntax](https://www.markdownguide.org/extended-syntax/).

**Comment by erosman** [comment]
I will work on it.

**Comment by erosman** [comment]
I have been thinking about **Edit** and I am considering a rework of the addon.

- remove sidebar interface
- move all formatting to context-menu
- move find/replace to toolbar icon
- include HTML | BBcode | Markdown submenus


If there are any other requests ... let me know.

**Comment by Korb** [comment]
> I have been thinking about **Edit** and I am considering a rework of the addon.
>     * remove sidebar interface
>     * move all formatting to context-menu

Then how will your add-on differ from bbCodeWebex?

**Comment by erosman** [comment]
> Then how will your add-on differ from bbCodeWebex?

**bbCodeWebex** was first released Mar 5, 2019 Size 185.82 KB
**Edit** was first released Sep 29, 2019 Size 73.45 KB

I am working on the next release and re-adding the sidebar.

**Comment by rubaboo** [comment]
What flavor of Markdown does **Edit** support?

**Comment by erosman** [comment]
> What flavor of Markdown does **Edit** support?

A few basic Markdown tags as can be seem in the context menu.

**Comment by Korb** [comment]
> A few basic Markdown tags as can be seem in the context menu.

@rubaboo probably meant - which flavor is used to generate the list of tags in the context menu? CommonMark, GFM, Extra, Multi or R?

**Comment by erosman** [comment]
It is based on Github's Markdown.

**Comment by Korb** [comment]
@erosman, I suggest moving this question and your answer to [🙏 Q&A](https://github.com/erosman/support/discussions/categories/q-a).
