### ISSUE TITLE
[FoxyTab] Container Control does not indicate which one is currently edited

### ISSUE THREAD

**Issue by dg-wfk** [erosman/support#32]
It would be helpful if the currently edited container would be highlighted somehow, i.e. with a different background colour.

**Comment by erosman** [comment]
Do you mean the menu on the left on Options -> Container?

Sure... I will add it to the next upgrade.

**Comment by dg-wfk** [comment]
Yes, I mean the icon and name of the currently edited container in the 2nd level menu "Options -> Container" right under the caption "Container" and sub-caption "Container Control".
