### ISSUE TITLE
[Firemonkey] Installing scripts on android doesn't seem to work.

### ISSUE THREAD

**Issue by mzso** [erosman/support#327]
Hi!

The other day I remembered that Firemonkey works on Android as well. So I installed it on Firefox 68.11.0.

The addon installed fine. The UI appeared, but when I tried to install a script, by clicking the install button [here](https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments), I only got the source code shown, but no installation prompt.

(The version is 68.11, because I got fed up how incredibly botched the newer variant is...)

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. máj. 8. 19:53 CEST](https://github.com/erosman/support/issues/327#issuecomment-835447871 "2021-05-08T17:53:58Z - Replied by Github Reply Comments"):
> To start with, I don't use Firefox on Android so my testing is very limited and based on user feedback.  
> The compatibility with Android is experimental ATM.
> 
> Unfortunately, the `extraParameters` in Firefox [tabs.onUpdated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onUpdated) API to grab URLs ending with `.user.js` & `.user.css`, is not supported on Firefox for Android. So the process is disabled on Android.

Oh well, I tried copy/pasting the script, but the arrow doesn't seem to appear anyway.

**Comment by erosman** [comment]
Which arrow?

After copy/paste and save, was there any problems?

Note: The script seens to be wrriten for TamperMoney with `@grant       none` which means it will be injected into `page` context.

In FireMonkey, you need to add the following for the script to be injected into the `page` context.
```
// @inject-into   page
```

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. máj. 8. 20:14 CEST](https://github.com/erosman/support/issues/327#issuecomment-835456250 "2021-05-08T18:14:51Z - Replied by Github Reply Comments"):
> Which arrow?
> 

The arrow the script provides to reply/quote to a github comment, which I used for this comment as well.
![kép](https://user-images.githubusercontent.com/4479090/117549858-0c40d080-b03d-11eb-944f-7fb4f77d575e.png)


> After copy/paste and save, was there any problems?
> 

Other than the script not working I didn't see any.

> Note: The script seems to be written for TamperMonkey with `@grant none` which means it will be injected into `page` context.
> 
> In FireMonkey, you need to add the following for the script to be injected into the `page` context.
> 
> ```
> // @inject-into   page
> ```

I added that extra line. But it still didn't work. Oh well...

**Comment by erosman** [comment]
TBH, someone has to test it. I will fix it if there are issues but I cant test it on Android to find out what is the problem. :(

BTW, does the script work on desktop FireMonkey?

**Comment by erosman** [comment]
BTW, I updated the code so hopefully the direct install will work on Android too in the next upgrade v2.26.

**Comment by mzso** [comment]
[**@erosman**](https://github.com/erosman) commented on [2021. máj. 8. 21:07 CEST](https://github.com/erosman/support/issues/327#issuecomment-835475643 "2021-05-08T19:07:10Z - Replied by Github Reply Comments"):
> TBH, someone has to test it. I will fix it if there are issues but I cant test it on Android to find out what is the problem. :(
> 
> Does the script work on desktop FireMonkey?

It does. Though you can try it yourself as well.  I often have to refresh the page, but I guess that's probably a script issue.


[**@erosman**](https://github.com/erosman) commented on [2021. máj. 9. 15:55 CEST](https://github.com/erosman/support/issues/327#issuecomment-835812604 "2021-05-09T13:55:46Z - Replied by Github Reply Comments"):
> BTW, I updated the code so hopefully the direct install will work on Android too in the next upgrade v2.26.

I'll try it when I can.

**Comment by erosman** [comment]
> It does. Though you can try it yourself as well.

I tried it and it works fine without `// @inject-into   page` so the problem must be somewhere else.

I am looking for a basic Android emulator for Windows to be able to to test on Android.

**Comment by erosman** [comment]
> Installing scripts on android doesn't seem to work.

Updated the Android code in v2.26
