### ISSUE TITLE
[FireMonkey] Broken style after error on updating

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#329]
I'm still using v2.24 so I'm not sure it happens in v2.25, but release notes don't say nothing in this regard, so I think this bug applies to v2.25 too.

I don't know if you're aware, but UserStyles.org server is unstable.

I just noticed that one of the styles I use stopped working. So I opened its code and after the metadata there's only this:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```

So FM cleared the entire code, replacing it with the message of the server error.

FM should be capable of not messing things if server returns error, in my opinion it should try again once and if it still fails FM should just ignore until the next day (when it will check again for updates).

**Comment by erosman** [comment]
> I don't know if you're aware, but UserStyles.org server is unstable.

I am and also noted in the Help 👇

> Please note that <i>userstyles.org</i> is sometimes slow and may time out.

I will see how the process can be improved.

**Comment by erosman** [comment]
Was this through auto-update or manual update?

**Comment by pintassilgo** [comment]
Auto-update.

**Comment by erosman** [comment]
Was there metadata block? (and the html under it)

**Comment by pintassilgo** [comment]
Old styles from USO don't have metadata block, the metadata block is generated by FM. So after the failed auto-update the auto-generated metadata remained intact (increasing the version number of course) and below it was just the error message instead of the actual code.

**Comment by erosman** [comment]
That is what I meant... so the metadata block was created by FM.

I have added a check (for HTML) which hopefully should be enough. I tried a few times to generate the timeout to test but couldn't now.

**app.js**
```js
fetch(item.updateURL)
.then(response => response.text())
.then(text => !text.trim().startsWith('<') && this.callback(metaData + '\n\n' + text, item.name, item.updateURL)) // userstyles.org serves HTML timeout page
.catch(error => App.log(item.name, `getStylish ${item.updateURL} ➜ ${error.message}`, 'error'));
```

**Comment by erosman** [comment]
v2.27 uploaded
