### ISSUE TITLE
Settings Problems

### ISSUE THREAD

**Issue by nollinvoyd** [erosman/support#33]
Firefos 64, Windows 10 Pro

When I import my settings, none of the context menu customizations were recorded.

After I re-customzed the context menu, the whole page is now blank

![foxy 1](https://user-images.githubusercontent.com/20844322/50111505-c677d900-01f1-11e9-8955-2f40db8c680e.png)

The Foxytab sub menu is also offset

![foxy 2](https://user-images.githubusercontent.com/20844322/50111572-e9a28880-01f1-11e9-91b6-020341df86fe.png)

**Comment by erosman** [comment]
That seems strange. The extension can not move its main menu to the submenu. I suspect it might be a bug with Firefox on Windows 10.

If you have saved your preferences, then try disabling & enabling FoxyTab and if that didn't work try uninstalling and reinstalling it.

Finally, you can try reinstalling Firefox and/or upgrading it to refresh it.

**Comment by erosman** [comment]
Is the problem with separators or the entire context-menu customisation is lost?

**Comment by nollinvoyd** [comment]
The context menu customizations maintain themselves after they are set in the current profile.  

The problem is they don't "register" when they are exported.  When you import the settings, the first page of settings is properly adjusted to the saved settings (except for the time zone, which always reverts back to the default, even after it is manually changed), but the context menu settings fully revert to the default, regardless of how they were changed when they were saved.

This has been verified thru the many new profiles recently created.

The only reason I mentioned the term "separators" is that was the only term I could think of to describe those multiple lines you see in the image I posted of the context menu.

**Comment by erosman** [comment]
The lines are actually called "separators" :)

So the problem is that:
- You export the current Preferences
- Then import that file (same place or on another computer)
- The result is not the same as when it was exported

Is that current?
I will do some testing to see what is happening.

**Comment by nollinvoyd** [comment]
> 
> So the problem is that:
> 
>     * You export the current Preferences
> 
>     * Then import that file (same place or on another computer)
> 
>     * The result is not the same as when it was exported
> 
> 
> Is that current?

Yes to all
> I will do some testing to see what is happening.

**Comment by nollinvoyd** [comment]
I'm back to report that at least  in part, this problem has not been solved.

On the "settings" page, most of the the customizations are retrievable.  The only one that does not work is the time zone.  It's stuck on London | Edinburgh

The context menu settings are the real problem.  None of those custom settings import.  It remains at default. 

It would be one thing if this was a tool with one or two available settings changes.  But considering all the variations FoxyTab has to offer,  it's a real chore each time they must be fully adjusted.

thanks

**Comment by erosman** [comment]
Can you check the data on **Export preferences**?
Are they there?

**Comment by nollinvoyd** [comment]
This is the content from the latest backup

`{
  "menus": [
    {
      "id": "createShortcut",
      "icons": {
        "16": "image/shortcut.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "copy",
      "icons": {
        "16": "image/copy.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyTitle",
      "icons": {
        "16": "image/title.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyUrl",
      "icons": {
        "16": "image/link.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrl",
      "icons": {
        "16": "image/tab.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyIP",
      "icons": {
        "16": "image/ip.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "customCopy",
      "icons": {
        "16": "image/copy.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyUrlAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyUrlLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyUrlRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "merge",
      "icons": {
        "16": "image/new-window.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "closeLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "saveAsPDF",
      "icons": {
        "16": "image/pdf.svg"
      },
      "disabled": false
    },
    {
      "id": "closeDuplicate",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": true
    },
    {
      "id": "closeOtherWindows",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "duplicate",
      "icons": {
        "16": "image/duplicate.svg"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "bookmark",
      "icons": {
        "16": "image/library.svg"
      },
      "disabled": true
    },
    {
      "parentId": "bookmark",
      "id": "bookmarkLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "bookmark",
      "id": "bookmarkRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "host",
      "icons": {
        "16": "image/host.svg"
      },
      "disabled": true
    },
    {
      "parentId": "host",
      "id": "hostKeep",
      "icons": {
        "16": "image/check.svg"
      },
      "disabled": true
    },
    {
      "parentId": "host",
      "id": "hostClose",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": true
    },
    {
      "parentId": "host",
      "id": "hostCloseOther",
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "sort",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": true
    },
    {
      "parentId": "sort",
      "id": "sortURLAsce",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": true
    },
    {
      "parentId": "sort",
      "id": "sortURLDesc",
      "icons": {
        "16": "image/sort_descend16.png"
      },
      "disabled": true
    },
    {
      "parentId": "sort",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "sort",
      "id": "sortTitleAsce",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": true
    },
    {
      "parentId": "sort",
      "id": "sortTitleDesc",
      "icons": {
        "16": "image/sort_descend16.png"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "move",
      "icons": {
        "16": "image/move.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "moveStart",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "moveEnd",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "moveNewWinLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "moveNewWinRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "movePrivate",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "movePrivateLeft",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": true
    },
    {
      "parentId": "move",
      "id": "movePrivateRight",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": true
    },
    {
      "id": "reload",
      "icons": {
        "16": "image/reload.svg"
      },
      "disabled": true
    },
    {
      "parentId": "reload",
      "id": "reloadAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": true
    },
    {
      "parentId": "reload",
      "id": "reloadLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "reload",
      "id": "reloadRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "parentId": "reload",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "reload",
      "id": "reloadTab",
      "icons": {
        "16": "image/history.svg"
      },
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "reload60",
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "reload120",
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "reload180",
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "reload240",
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "reload300",
      "disabled": true
    },
    {
      "parentId": "reloadTab",
      "id": "customReload",
      "disabled": true
    },
    {
      "parentId": "reload",
      "id": "reloadStop",
      "icons": {
        "16": "image/disable.svg"
      },
      "disabled": true
    }
  ],
  "tabCounter": true,
  "badgeBGColor": "#000000",
  "badgeTextColor": "#ffffff",
  "customCopy": "{Title}_{Domain}_{Date}",
  "customReload": "10",
  "date": [
    "en-GB"
  ],
  "clock": [],
  "hour12": true,
  "weekday": "short",
  "month": "short",
  "menuChanged": true,
  "container": [
    "",
    "",
    ""
  ],
  "theme": null
}`

**Comment by erosman** [comment]
They are not saved.... did you click SAVE after adding new clock & date and before exporting?
```
    "date": ["en-GB"],
    "clock": [],
    "hour12": true,
    "weekday": "short",
    "month": "short",
```

**Comment by nollinvoyd** [comment]
I've tried it numerous times in the past, and I tried it again just now, using Fx 69.

I checked to see if my customized settings were in place.  They were.  I went to both the settings page and the context menu page, and "saved' on both pages.

I exported from "both" pages in the off chance that both pages settings needed to be saved and restored separately.

I uninstalled and reinstalled FoxyTab.  I imported both backup settings.  

The context menu settings remained at default.

> They are not saved.... did you click SAVE after adding new clock & date and before exporting?

I already mentioned that the time zone (Edinburgh) cannot be changed, but I also just discovered that when I select Copy > Custom Copy, what i get is "{Title}_{Domain}_{Date}", literally, not the current page title, domain, and date you would expect.

**Comment by erosman** [comment]
1- Save & Import/Export are the static in those pages (same button. the content above t change)
2- The default has no clock. so the clock seems to have been saved
3- Have you done any changes to the `about:config` ?
I recall some changes affect the operation of extensions (like when Web API copy) is used.
4- As you are the only person mentioning this issue, the problem is not universal.

Please do the following:
1- make changes & Save
2- Export Preferences
3- Check the JSON file to see if those changes are reflected

let me know ...

**Comment by nollinvoyd** [comment]
> As you are the only person mentioning this issue, the problem is not universal.

I don't know what to say.  I don't have this problem with any other addon.

I routinely tweak about:config in my complete profiles.  Hypothetically, It is reasonable to assume that an about:config alteration could have caused a conflict.  
 
So, I just now did as you instructed.  Using Fx 69, I opened a fresh profile.  No about:config tweaks, or other alterations of any kind.  Installed FoxyTab.  Disabled "copy" in the context menu settings.  Exported the settings.  Restored defaults.  Imported the settings.  The default settings were "not" altered by importing the custom settings. 

If I am reading the FoxyTab_2019-09-18.json correctly, the exported settings show "copy" is disabled.

`{
  "menus": [
    {
      "id": "duplicate",
      "icons": {
        "16": "image/duplicate.svg"
      },
      "disabled": false
    },
    {
      "id": "closeDuplicate",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "closeLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "merge",
      "icons": {
        "16": "image/new-window.svg"
      },
      "disabled": false
    },
    {
      "id": "closeOtherWindows",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "saveAsPDF",
      "icons": {
        "16": "image/pdf.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "createShortcut",
      "icons": {
        "16": "image/shortcut.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "copy",
      "icons": {
        "16": "image/copy.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyTitle",
      "icons": {
        "16": "image/title.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyUrl",
      "icons": {
        "16": "image/link.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrl",
      "icons": {
        "16": "image/tab.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyIP",
      "icons": {
        "16": "image/ip.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "customCopy",
      "icons": {
        "16": "image/copy.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyUrlAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyUrlLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyUrlRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "type": "separator",
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": true
    },
    {
      "parentId": "copy",
      "id": "copyTitleUrlRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": true
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "bookmark",
      "icons": {
        "16": "image/library.svg"
      },
      "disabled": false
    },
    {
      "parentId": "bookmark",
      "id": "bookmarkLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "bookmark",
      "id": "bookmarkRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "host",
      "icons": {
        "16": "image/host.svg"
      },
      "disabled": false
    },
    {
      "parentId": "host",
      "id": "hostKeep",
      "icons": {
        "16": "image/check.svg"
      },
      "disabled": false
    },
    {
      "parentId": "host",
      "id": "hostClose",
      "icons": {
        "16": "image/close.svg"
      },
      "disabled": false
    },
    {
      "parentId": "host",
      "id": "hostCloseOther",
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "sort",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": false
    },
    {
      "parentId": "sort",
      "id": "sortURLAsce",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": false
    },
    {
      "parentId": "sort",
      "id": "sortURLDesc",
      "icons": {
        "16": "image/sort_descend16.png"
      },
      "disabled": false
    },
    {
      "parentId": "sort",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "sort",
      "id": "sortTitleAsce",
      "icons": {
        "16": "image/sort_ascend16.png"
      },
      "disabled": false
    },
    {
      "parentId": "sort",
      "id": "sortTitleDesc",
      "icons": {
        "16": "image/sort_descend16.png"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "move",
      "icons": {
        "16": "image/move.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "moveStart",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "moveEnd",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "moveNewWinLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "moveNewWinRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "movePrivate",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "movePrivateLeft",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": false
    },
    {
      "parentId": "move",
      "id": "movePrivateRight",
      "icons": {
        "16": "image/private-browsing.svg"
      },
      "disabled": false
    },
    {
      "type": "separator",
      "disabled": false
    },
    {
      "id": "reload",
      "icons": {
        "16": "image/reload.svg"
      },
      "disabled": false
    },
    {
      "parentId": "reload",
      "id": "reloadAll",
      "icons": {
        "16": "image/left-right.svg"
      },
      "disabled": false
    },
    {
      "parentId": "reload",
      "id": "reloadLeft",
      "icons": {
        "16": "image/back.svg"
      },
      "disabled": false
    },
    {
      "parentId": "reload",
      "id": "reloadRight",
      "icons": {
        "16": "image/forward.svg"
      },
      "disabled": false
    },
    {
      "parentId": "reload",
      "type": "separator",
      "disabled": false
    },
    {
      "parentId": "reload",
      "id": "reloadTab",
      "icons": {
        "16": "image/history.svg"
      },
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "reload60",
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "reload120",
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "reload180",
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "reload240",
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "reload300",
      "disabled": false
    },
    {
      "parentId": "reloadTab",
      "id": "customReload",
      "disabled": false
    },
    {
      "parentId": "reload",
      "id": "reloadStop",
      "icons": {
        "16": "image/disable.svg"
      },
      "disabled": false
    }
  ],
  "tabCounter": true,
  "badgeBGColor": "#ff7700",
  "badgeTextColor": "#ffffff",
  "customCopy": "",
  "customReload": "10",
  "date": [],
  "clock": [],
  "hour12": false,
  "weekday": "long",
  "month": "long",
  "menuChanged": true,
  "container": [
    ""
  ],
  "theme": null
}`

BTW, can you please tell me why my code displays like that.  What am I doing wrong there?

thanks

**Comment by erosman** [comment]
The Copy appears disabled. I will test them and let you know.

Th clock and date are not set. Please work on testing the Clock & date since that was your initial concern.

After Importing Preferences, did you SAVE?

The markdown for inline code is ` 
The markdown for block code is ``` (or use the <> button)

**Comment by nollinvoyd** [comment]
The custom copy format is working properly.  I cant say what happened before with that, tho I'd like to suggest doing something similar to what nimbus screen capture does for the "save as" template to avoid any typos

![nimbus](https://user-images.githubusercontent.com/20844322/65265354-95e90680-dac5-11e9-9ec3-edcd6a3d5b89.png)

The time is correct for my time zone (PST), even tho it is still stuck on Edinburgh, but I won't be able to tell if the 24 hour format is intact until this afternoon.

> After Importing Preferences, did you SAVE?

Yes.

**Comment by erosman** [comment]
Try adding few clocks & dates, just to test, and then SAVE and Export Preferences to see if they are saved.

**Comment by nollinvoyd** [comment]
As far as I can see, the clocks and dates re ok.  The 12 hours time format works, and every customs setting on the settings page is restored.  

I cannot say the same for the context menu settings.

**Comment by erosman** [comment]
So the Clocks & Dates that weren't working/saving before are now working, right?

The context-menu settings is a bit complicated. Are they reflected in the JSON when you export?

**Comment by nollinvoyd** [comment]
> So the Clocks & Dates that weren't working/saving before are now working, right?

There are no problems with the clocks, dates, etc.  I don't know what went wrong before with this, but there is no issue now.

> The context-menu settings is a bit complicated. Are they reflected in the JSON when you export?

The last code I posted was the JSON of the customized exported settings, as you previously requested.
