### ISSUE TITLE
foxytab: using close duplicare closes urls with #post-number of the same page but different html location

### ISSUE THREAD

**Issue by rezad1393** [erosman/support#330]
when I open a rss feed for a forum that I follow the post are the same main url but different post location that is indicated by /#post-number  at the end of url , like /#post-244 .
can you make it so that these be considered not the duplicate?

**Comment by erosman** [comment]
Some sites has started using [Location: hash](https://developer.mozilla.org/en-US/docs/Web/API/Location/hash) in their URL incorrectly. Hash `#` in URL means anchor to a location within the same page.

> The hash property of the Location interface returns a USVString containing a '#' followed by the fragment identifier of the URL — the ID on the page that the URL is trying to target.

Therefore, the following are all the same page ...

```
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#syntax
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#examples
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#specifications
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#browser_compatibility
```

Previously #191

**Comment by rezad1393** [comment]
I completely understand.
and I said that in the first post too.
I am asking for them to be NOT considered the same URL, so that they dont get closed.

**Comment by erosman** [comment]
They are the same URL.

[What is a URL?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL)
![image](https://user-images.githubusercontent.com/6458876/118800107-c72a6300-b8b4-11eb-8653-37e7a4c6f3c4.png)

> I am asking for them to be NOT considered the same URL, so that they dont get closed.

Considering the hash to be a different URL, besides being incorrect, would break 'close duplicate' for other anchors. e.g.

```
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#syntax
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#examples
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#specifications
https://developer.mozilla.org/en-US/docs/Web/API/Location/hash#browser_compatibility

vs

https://www.example.com/#post-244
https://www.example.com/#post-240
https://www.example.com/#post-227
https://www.example.com/#post-105
```

**Comment by rezad1393** [comment]
ok nevermind
