### ISSUE TITLE
[FireMonkey] Add global variables shows error but works

### ISSUE THREAD

**Issue by IvoryJam** [erosman/support#331]
Using the recommended way to [CSS custom properties from MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) works great, the editor says it's not correct though.
**Expected RBRACE at line 10, col3.**

```
==UserCSS==
@name test1
@match https://website.com/*
@version          1.0
==/UserCSS==
*/

:root {
  --main_color: #545864;
}


.sidebar {
    background: var(--main_color);
}
```
![image](https://user-images.githubusercontent.com/35709713/118923349-a257df00-b8f8-11eb-8380-2d6026871a9f.png)

**Comment by erosman** [comment]
The warning is generated by [CSSLint](https://github.com/CSSLint/csslint) v1.0.3 Latest 20 Sep 2016.

The warning on the editor does not affect the actual injection of the script or CSS and as long as they are valid JS/CSS, they will work fine.

There is an issue already on the subject [CSS4 custom properties ](https://github.com/CSSLint/csslint/issues/682) from 27 Oct 2016 but it does not appear that an update is due.

I will see, if I can manually suppress the error.

**Comment by erosman** [comment]
It is done and will be in v2.27.
