### ISSUE TITLE
[FireMonkey] Sync Storage won't delete

### ISSUE THREAD

**Issue by IvoryJam** [erosman/support#332]
With Sync Storage enabled, I cannot delete scripts or css that I wrote, it says it deletes them, but I refresh and they're still there.

To remove them I have to turn off Sync Storage, disable/enable the extension (for some reason, not sure why), then delete the unwanted files.

If I enabled Sync Storage and refresh, it brings back the ones I deleted.

**Comment by erosman** [comment]
You are right... 
It was an oversight when database was migrated in v2.25  :man_facepalming: 

I will fix it and release a new version.

**Comment by erosman** [comment]
It is done and will be in v2.27

**Comment by IvoryJam** [comment]
Issue isn't resolved in version 2.27, I also have another machine where they aren't syncing between the two, just the same two scripts I try to delete that come back after syncing. If it helps the Firefox versions are 89 and the other on 88

**Comment by erosman** [comment]
I will investigate it again.

TBH, the sync is only used by a limited few since the sync limit is 100kb and only few users will have a storage of less than 100kb. Some user-scripts are 2.5+mb.

Personally, I don't use sync since my storage is over 1mb and I only use Firefox on one machine. Therefore I cant test the result.

ATM, the sync is set to merge with current running storage, The reason is that if there is a error in the sync, it wont wipe everything off. That might be the reason the deleted script comes back. :thinking:

**Comment by IvoryJam** [comment]
Alright so I did some more digging, I'm a moron and realized you had a logs tab in there.
The error is 
```
QuotaExceededError: storage.sync API call exceeded its quota limitations.
```
I'm not much a a JavaScript guy, but I think I got where it's saying that, **line 340 to 343** in `background.js`
I checked my `prefs` size and it's 40189 so it's well below that storage limit, so I'm wondering if it's either the api responding with a limit to calls? I don't know, I'm not a js guy.

`deleted` is undefined on line 341 in `background.js`, I fixed this by moving **line 307** to the first line in `processPrefUpdate` since const is block defined it doesn't get out of that else statement (to my understanding)

Lastly I did have to add `const obj = {};` as it's own line on `options.js` **line 1091** so that fixes uploading user.js and user.css files (in bulk)

Again I'm not a JS guy, so I could be speaking totally out of my ass, I could definitely be wrong.

**Comment by IvoryJam** [comment]
I do want to thank you for your efforts with this whole thing too, no other extension (in Firefox or even Chrome) accomplishes what you did in this one, with user scripts and user css together as one in a decent UI. 

Seriously amazing work, great job.

**Comment by erosman** [comment]
Thank you for your kind words. :+1: 

> QuotaExceededError: storage.sync API call exceeded its quota limitations.

That is the error from Firefox API (`catch()` of the promise) showing [Storage quotas for sync data](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data).
There are multiple limits:
- Maximum total size 102400 (100kb)
- Maximum item size 8192 (8kb)
- Maximum number of items 512

> deleted is undefined on line 341 in background.js, I fixed this by moving line 307 to the first line in processPrefUpdate since const is block restricted it doesn't get out of that else statement (to my understanding) 

You are correct and that was my oversight. I will fix it for the next update, although the code may change as I am still working on the code to avoid getting a loop when sync is updated remotely (sync -> local -> sync .....).
As I mentioned before, I did not concentrate on Sync feature before (only added it on request) as it has limited users.
However, I am working on fixing the issues.

> Lastly I did have to add const obj = {}; as it's own line on options.js line 1091 so that fixes uploading user.js and user.css files (in bulk)

Bulk importing of `user,js` and `user.css` is already available by multi-selecting items.

**Comment by IvoryJam** [comment]
I found that since obj isn't defined like that, I can't upload at all, when I unpack the extension, update that, the load it unpacked, I can successfully upload

**Comment by erosman** [comment]
> I found that since obj isn't defined like that, I can't upload at all, when I unpack the extension, update that, the load it unpacked, I can successfully upload

I found out what you mean. In a quick look, it seem the problem is `obj[id] = pref[id];` which should be `this.obj[id] = pref[id];` but I have to check it.

This is again some leftover from the database migration of 2.25 :man_facepalming: 
I am going to re-check and fix that section of the code.

**Comment by IvoryJam** [comment]
Aaah yeah okay that makes sense

**Comment by erosman** [comment]
I have uploaded v2.28

Please check and see if the sync is working better. As I mentioned, I only use one Firefox so I cant test the sync when I change the code.

**Comment by IvoryJam** [comment]
Upload and sync work!
I did find one script that breaks the sync though, https://greasyfork.org/en/scripts/375467-enhance-twitch, having that installed, not even enabled causes this error **QuotaExceededError: storage.sync API call exceeded its quota limitations.**

When I checked my prefs size, that script was included in that, so it's still below the limit Firefox sets for sync

**Comment by IvoryJam** [comment]
Sorry, for clarification, it won't sync that specific script. Any changes or new/deleted scripts do sync!

Would love to see that fixed, but it's a small price to pay. Again, great work, this is my new favorite extension.

**Comment by erosman** [comment]
As mentioned earlier ....

> That is the error from Firefox API (`catch()` of the promise) showing [Storage quotas for sync data](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync#storage_quotas_for_sync_data).
> There are multiple limits:
> - Maximum total size 102400 (100kb)
> - Maximum item size 8192 (8kb)
> - Maximum number of items 512

Each script will have a single entry in FireMonkey which is the script itself plus all associated data.

[Enhance twitch](https://greasyfork.org/en/scripts/375467-enhance-twitch/) is **25.6KB** plus the associated data (around 1-2 KB more).
The maximum allowed by Firefox Sync is **8KB** for each item. In other words, scripts should be smaller than 6-7KB in order to sync.

This is the impracticality of using Firefox Sync in script or style mangers. It will only work when user has a few small scripts.

**Comment by IvoryJam** [comment]
Ooooh I didn't notice that item size limit, I usually have a few small scripts so that sync is amazing for me, that twitch script is the only one I copied over.

We're good then! Thank you for your work!

**Comment by IvoryJam** [comment]
So you know, I can't see the file size at the bottom because it's having me scroll down on Firefox 89. 89 is still in beta so that may be why? But it's going to stable on the 1st of June. I can open up a new issue if you'd like though

**Comment by erosman** [comment]
Oh ... that shouldn't be.. I am on Nightly 90.0a1 and it shows

![image](https://user-images.githubusercontent.com/6458876/120091499-ddd88180-c120-11eb-973f-b866f50ab42d.png)

**Comment by IvoryJam** [comment]
So I can see it, but I have to scroll down on the page, so if I have a long script, I got two scroll bars, that might be a Linux thing though for some reason.
![image](https://user-images.githubusercontent.com/35709713/120091578-97a40380-c0c9-11eb-9183-1e8f22a0495f.png)
that's on the same nightly with 69 lines (no pun intended I swear hahaha)

If I change the CSS for fieldset to `calc(100% - 5em)` it does fix it, but adds a little more space on 79
![image](https://user-images.githubusercontent.com/35709713/120091597-da65db80-c0c9-11eb-8a88-d32aa6ae95dc.png)

**Comment by erosman** [comment]
What about `calc(100% - 4.5em)`?

**Comment by IvoryJam** [comment]
4.5 shows it, still causes the overflow though, this is it scrolled up all the way
![image](https://user-images.githubusercontent.com/35709713/120091680-aa6b0800-c0ca-11eb-9253-3d42adc29072.png)

**Comment by erosman** [comment]
hm ..... let me think about what to do... as the display doesn't seem to be the same on different OS. :thinking:

**Comment by erosman** [comment]
Since you can edit and test .......  can you move the `footer` to inside the `fieldset` in `options.html` and set the `calc(100% - 4em)` e.g. `options.html` line 313

```html
          <fieldset>
            <legend class="js" data-i18n="script"></legend>
            <input type="color" style="display: none;">
            <textarea class="box" data-type="css" spellcheck="false" autocomplete="off" disabled></textarea>
            <footer></footer>
          </fieldset>
```

**Comment by IvoryJam** [comment]
You bet, I updated that and didn't seem to have any effect, if it helps Firefox says the things causing the overflow are the l`div` for the line numbers and the `footer`

**Comment by erosman** [comment]
`div` for line numbers are generated by CodeMirror for the editor.

Let me think ... if I move the footer data somewhere else.. where could that be?!!

**Comment by IvoryJam** [comment]
After playing around a bit, I've come up with some ideas that may be completely worthless, I'm not a web dev in any sense of the words. 

So I found specifically the report button also causes it, if I make the padding 0.3em, it does fix it, BUT on nightly it doesn't do anything.

So there's that, or maybe making the menu 1em smaller somehow?

**Comment by IvoryJam** [comment]
Sorry, 0.3em in `.menu summary`

**Comment by erosman** [comment]
OK .... can you keep everything as the original and try this `options.css` for me please?

[options.zip](https://github.com/erosman/support/files/6566206/options.zip)

**Comment by IvoryJam** [comment]
Yep that fixed it for me, I tested on Firefox Beta v89.0 and on Nightly v90.0a1

**Comment by erosman** [comment]
Ah ... good .... it will be in the next update then.

**Comment by IvoryJam** [comment]
Great! Thank you for your help!

**Comment by erosman** [comment]
Thank you for taking the time to test it.
