### ISSUE TITLE
FoxyTabs Bug Report

### ISSUE THREAD

**Issue by pie-faced** [erosman/support#335]
Firefox 89b15 on Windows 10. FoxyTabs at startup changes the theme setting from a dark theme to all white background and black foreground (no theme). Chosen theme loads before FoxyTabs loads and then apparently gets broken when FoxyTabs loads. The Themes window of the Addons Manager still shows the theme as enabled; enabling a different one then changing back again restores normal functionality for the rest of the current session. Not related probably, I have noticed if you apply a theme that changes the background color to black for internal pages like Settings, Advanced Settings, Addons Manager, and if you're lucky the Firefox Start Page, that black background will persist with all dark themes, even the ones that don't normally affect those pages. Another issue: When you open a new window and try to open a url that was already open even in the other browser window instead of opening a new instance of that page it returns focus to the tab it's already open in. Okay, this happens even when FoxyTabs is disabled. Also I turned off all but three of FoxyTabs menu-items and I wonder if that affected the code.

**Comment by erosman** [comment]
I will check these out.

PS. I am working on the next update and a lot of the code is changed in the new version.

**Comment by erosman** [comment]
Let me know if there are still any issues.
