### ISSUE TITLE
[FireMonkey] [Suggestion] disable / allow disabling the "save" animation

### ISSUE THREAD

**Issue by afontenot** [erosman/support#338]
Personal opinion: I don't like the current save animation, which sends a slow animated progress bar across the top of the screen.

Saving any reasonably sized Javascript file should be \~instantaneous, and the slow progress bar makes it *look* slow. Some indication of the save status *is* a good idea, but something like adding an asterisk `*` before the title of the script and making the title *italicized* is a pretty universal way of indicating that a script hasn't been saved since the last change, and then you can just remove the asterisk and go back to normal text as soon as the document is saved. Lots of programs do it more or less like this, in my experience.

At any rate, a way to easily disable the animation in the settings would be appreciated.

**Comment by erosman** [comment]
It was actually added on request (one my other addons) because people wanted a visual indication that the save process is running.

If there is a popular demand, I can change it and/or add a preference option for it.

**Comment by afontenot** [comment]
I agree, not having any indication that a file has been successfully saved would be annoying. As currently implemented, it has two downsides: 

1. The animation is too slow, taking multiple seconds when presumably the actual save process happens in milliseconds.

2. There's no indication that the file is currently unsaved. You simply don't know, unless you try to click away to a different script. Closing the browser tab actually appears to lose any unsaved changes you've made, which is doubly bad on top of not having an indicator. I think you should catch the window close event and block it if there's unsaved data.

I find the following a pretty acceptable way of indicating save status:

Unsaved:
![unsaved](https://user-images.githubusercontent.com/3870410/121007047-7638bc80-c746-11eb-8be5-0afd8bbb534e.png)

Saved:
![saved](https://user-images.githubusercontent.com/3870410/121007085-80f35180-c746-11eb-92c7-ac93fdfc6aa4.png)

That's what my normal, offline text editor does. By all means, get feedback from others though before you decide. Thanks for considering the idea!

**Comment by erosman** [comment]
Let's see if there is a popular demand for a change and I will change it.

TBH, FM is continually being improved and I may change that anyway in future updates.
