### ISSUE TITLE
XSS vector in foxytab

### ISSUE THREAD

**Issue by DanielHeath** [erosman/support#34]
In `background.js` line 494, a code string is constructed via:

```
`confirm(\`${chrome.i18n.getMessage('textConfirmCloseLeft', rem.length)}\`)`;
```

If javascript content is set into `textConfirmCloseLeft` with a closing backtick, it'll allow arbitrary code execution in the context of `content/helper.html` - which (I think) has 'read and write all data' permissins.

**Comment by DanielHeath** [comment]
On the bright side, I've read every line of code in the extension and this was the riskiest thing I found, so well done :)

**Comment by erosman** [comment]
Thank you for checking.

chrome.i18n.getMessage getsa static string from `/_locales/en/`
`"textConfirmCloseLeft": { "message": "You are about to close $1 tabs. Are you sure you want to continue?" },`

There isn't any remote content that could cause an XSS.

**Comment by DanielHeath** [comment]
Makes sense. 

Is there no other source of locale information / translations? No way to override them? 

If not, that's great; if so, it's a way to pivot from lesser credentials to greater ones. I'm not familiar enough with the APIs to know.
