### ISSUE TITLE
[FireMonkey] [Bug] All cross-origin XMLHttpRequest fail, even if not blocked by CORS

### ISSUE THREAD

**Issue by afontenot** [erosman/support#340]
This report isn't about `GM.xmlHttpRequest`, it's about the native `XMLHttpRequest`. 

On [this previous bug report](https://github.com/erosman/support/issues/337#issuecomment-855857124), you indicated that `userScript` context scripts behave the same with respect to CORS and CSP as `content` context scripts. Either this isn't the case, or FM has a bug in how it handles `XMLHttpRequest`.

The following script, which violates CORS, works fine in Greasemonkey because `content` scripts are not subject to CORS:

```
// ==UserScript==
// @name     CORS test
// @version  1
// @grant    none
// @match    https://example.org/*
// ==/UserScript==

function reqListener () {
  console.log("response received");
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "https://www.imdb.com/name/nm0432380/bio");
oReq.send();
```

The following script doesn't violate CORS (because the domain has `Access-Control-Allow-Origin: *`) and also works fine in Greasemonkey.

```
// ==UserScript==
// @name     XMLHttpRequest test
// @version  1
// @grant    none
// @match    https://example.org/*
// ==/UserScript==

function reqListener () {
  console.log("response received");
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "https://httpbin.org/status/200");
oReq.send();
```

However, to my surprise, *neither* script works in FireMonkey due to what seems to be CORS related errors. For the latter I see the following error (in the browser console, not the dev tools / web console):

On Firefox 89 on Windows:

> Cross-Origin Request Blocked: ... (Reason: CORS header 'Origin' cannot be added)

Note that if `userScript` actually behaves like `content`, you would expect to see both requests succeed. Perhaps this is a bug in Firefox?

**Comment by erosman** [comment]
> On this previous bug report, you indicated that userScript context scripts behave the same with respect to CORS and CSP as content context scripts.

What I said was:

> Both content injected user-scripts (GM|TM|VM) & userScript injected user-scripts (FM) **are subject to** the page CSP and CORS,

CSP applies to the current page while CORS to the target and depends on `Access-Control-Allow-Origin` header. (more at the end of this post)

>  Either this isn't the case, or FM has a bug in how it handles XMLHttpRequest.

FM does not handle `XMLHttpRequest`. All standard JavaScript code is handled by Firefox. FM only handles GM APIs.

> Note that if `userScript` actually behaves like `content`,....

`userScript` does **NOT** behave like `content`. They are totally different contexts. `userScripta` API is based on `contentScripts` API but with **additional** restrictions.

`content` context is meant to be used by extension's **own privileged code**. It was not designed to be used for 3rd party code like user-scripts.
`userScript` context is designed to be used for 3rd party code like user-scripts.

📌 `content` context has a higher privilege comparing to `userScript` context.

**Comment by afontenot** [comment]
I'm well aware of everything you said here, but none of it addresses the bug I'm reporting here.

> CSP applies to the current page while CORS to the target and depends on Access-Control-Allow-Origin header. (more at the end of this post)

I know that. But Firefox will inject content scripts without respecting the page's CSP settings, and it will accept `XMLHttpRequest` cross-origin that would normally violate CORS. This is what I mean by saying that content injected user scripts **are not subject to** the page CSP and CORS. If you mean something else by "subject to", I haven't been able to figure out what it is.

In any case, the bug as reported stands. If you're maintaining that *unlike* content injected userscripts, `userScript` context user scripts **are** subject to CORS in the sense that I mean (see above), then we can dismiss one aspect of it. However, it's still the case that cross-origin XMLHttpRequests are failing when they should not be. Can you please see if you can replicate that with this code?

```
// ==UserScript==
// @name     XMLHttpRequest test
// @version  1
// @grant    none
// @match    https://example.org/*
// ==/UserScript==

function reqListener () {
  console.log("response received");
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "https://httpbin.org/status/200");
oReq.send();
```

> FM does not handle XMLHttpRequest. All standard JavaScript code is handled by Firefox.

I'm aware of this too. As I suggested in the report, this may be a bug in Firefox if cross origin requests aren't working in the `userScript` context. I'd like to verify that with your help.

**Comment by afontenot** [comment]
Not to be rude, but are you reading my comments fully? This is not a CORS issue, as I've repeatedly said. As the unedited title reads, this issue occurs **even if not blocked by CORS**.

The point is that this trivial script does not work in FireMonkey, as tested by me on multiple computers:

```
// ==UserScript==
// @name     XMLHttpRequest test
// @version  1
// @grant    none
// @match    https://example.org/*
// ==/UserScript==

function reqListener () {
  console.log("response received");
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "https://httpbin.org/status/200");
oReq.send();
```

It works on Greasemonkey. CORS should *not* be causing any problem here, because as I said originally, and you have repeated, httpbin has `Access-Control-Allow-Origin: *` in the response headers. Despite this, I do see a CORS related error in the browser console.

Can you copy/paste the code into a new script and try it? You should find that it doesn't work. I'm perfectly willing to accept that this is Mozilla's fault, if it turns out that there's a bug in Firefox we can report it upstream.

Again, let me emphasize that I'm **not** saying that this has anything to do with CORS. This is about a trivial cross-domain request failing in FireMonkey for as-yet unknown reasons.

**Comment by erosman** [comment]
As I mentioned before, `userScript` context is a heavily restricted sandboxed context and has a strict X-ray vision. The X-ray vision restricts many functions (read the relevant information on X-ray vision).

Any comparison with what GM does in `content` context is irrelevant.

Any discussion regarding the reason `XMLHttpRequest` results in error in `userScript` context should be forwarded to Mozilla as it is not handled by or related to FireMonkey.

**Comment by afontenot** [comment]
I suppose I was thinking your approach to this userscript manager was something like that of other people who have made userscript managers. You seem to be thinking of your extension as a thin shell around abilities that the browser natively provides and expecting any users who have problems to go directly to Mozilla, instead of handling broken features yourself. That's fine, if I decide to keep using this extension I'll go to Mozilla about it, but I don't think that's a particularly sustainable approach. Your extension is broken, regardless of whether it's caused by Mozilla or not. Mozilla does not surface `userScript` to end users, and I don't think they're anticipating doing support for people writing user scripts.

> Any comparison with what GM does in content context is irrelevant.

This is something that really shouldn't be context dependent, so I'm not comparing to GM "in content context", but just pointing out that the code obviously works in Greasemonkey in general (it also works in your "Scratchpad" feature, as I just discovered). Code in the page has the ability to do cross-site requests. Code in `content` has the ability to do cross-site requests. Background scripts running in extensions can do cross-site requests. Code in the console can do cross-site requests. If cross-site requests are broken in `userScript` context, that's really bad for your extension and anyone else using the `userScript` API, and so the reason I filed this bug was for help in determining whether your extension could be at fault here or whether you / I need to report this to Mozilla.

**Can you at least confirm that the code I posted doesn't work for you either?**

> The X-ray vision restricts many functions (read the relevant information on X-ray vision).

I have read both your documentation on Xray vision and the MDN documentation carefully, and don't see any relevancy to this issue. I'm not accessing any JS objects in the page. I'm just trying to do a cross-site `XMLHttpRequest`.

**Comment by erosman** [comment]
> I suppose I was thinking your approach to this userscript manager was something like that of other people who have made userscript managers.

Pleas read the implementation of user-scripts in FireMonkey. FireMonkey passes the user-scripts to Firefox to be handled by Firefox natively.
Other script managers handle the user-scripts manually. There is a considerable difference in concept and thus resource usage between these approaches.

> You seem to be thinking of your extension as a thin shell around abilities that the browser natively provides and expecting any users who have problems to go directly to Mozilla, instead of handling broken features yourself. 

When the issue is an API provided by Firefox, Mozilla or associated forums is the best authority for seeking information.

> instead of handling broken features yourself

Which feature that is related to the FireMonkey code is broken?
`userScripts` API does not belong to FireMonkey and the code is not written by me. 

Feature requests that can be accomplished by FireMonkey, will be considered. Feature requests that relate to Firefox API can not be expected of FM.


> This is something that really shouldn't be context dependent,  so I'm not comparing to GM "in content context",  but just pointing out that the code obviously works in Greasemonkey in general (it also works in your "Scratchpad" feature, as I just discovered). 

I seem to be repeating the same thing.

There is a **fundamental** difference in the context between FM & others.
What you mentioned that works in GM, works because the code runs in `content` context.
FireMonkey does NOT run in `content` context therefore, it is impossible to compare.

**It is impossible to make `userScript` context behave like `content` context (nor that it should). Therefore such demands are unrealistic.**

The security of `userScript` context is a feature of FireMonkey, albeit it may have some drawbacks in terms of accustomed practices. Users should weigh the advantages against the disadvantages to chose the most appropriate extension.

FireMonkey's scratchpad runs in `content` context as stated in the Help with a warning.

> I have read both your documentation on Xray vision and the MDN documentation carefully, and don't see any relevancy to this issue. I'm not accessing any JS objects in the page. I'm just trying to do a cross-site XMLHttpRequest.

There really is a need to fully understand the concept of context in Firefox.  The X-ray vision filters objects (the response from XHR is an object). All functions & objects are passed under strict rules in `userScript` context which are generally blocked unless allowed in `script.defineGlobals`.

The full discussion of how the Firefox API works, is beyond the scope of FireMonkey support.

> Can you at least confirm that the code I posted doesn't work for you either?

I get the same result as you got.

**Comment by afontenot** [comment]
> It is impossible to make userScript context behave like content context (nor that it should). Therefore such demands are unrealistic.

I'm not asking it to. As I pointed out,

> This is something that really shouldn't be context dependent, so I'm not comparing to GM "in content context", but just pointing out that the code obviously works in Greasemonkey in general (it also works in your "Scratchpad" feature, as I just discovered)

You seem to be under the impression that this is not a bug at all, that this is just an intended difference between the `content` context and the `userScript` context, but this is not the case, at least as far as I can find from any documentation. And indeed it would be astonishing if it were intended. This is something that anonymous functions running *in the page* can do.

If you open up the devtools console on a random domain, say example.org, and you run the following code in the console, it will work.

```
function reqListener () {
  console.log("response received");
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "https://httpbin.org/status/200");
oReq.send();
```

Please note that the dev console is subject to CORS, as you can verify by replacing the domain with one that implements CORS protections. This is *not* a CORS issue. If you put the Javascript in `<script>` tags in a perfectly ordinary web page, it will work. This has nothing to do with content scripts or CORS or any kind of comparison with what Greasemonkey does, or so on. The issue is that code running under `userScript` in FM can't do perfectly ordinary things that even page context scripts can do **and** that there is no obvious reason why Mozilla would have restricted this ability for userScript **and** that there is no documentation indicating that they (deliberately) did so.

> There really is a need to fully understand the concept of context in Firefox. The X-ray vision filters objects (the response from XHR is an object). All functions & objects are passed under strict rules in userScript context which are generally blocked unless allowed in script.defineGlobals.

Can you find any documentation at all indicating that this affects running `XMLHttpRequest` in the `userScript` context? Quoting from [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts):

> In Firefox, part of the isolation between content scripts and page scripts is implemented using a feature called "Xray vision". When a script in a more-privileged scope accesses an object that's defined in a less-privileged scope it sees only the "native version" of the object. Any expando properties are invisible, and if any properties of the object have been redefined, it sees the original implementation, not the redefined version.

Great. I'm familiar with this feature and behavior. But this is ... not what's happening here. I'm trying to use functions that are built in to the Javascript spec. I'm *not* accessing objects that are defined in less privileged scopes. If I was executing the `XMLHttpRequest` in the page and then trying to access the response object from `userScript`, you'd have a point. I'm not, so I can see no reason at all to believe that Xray applies here. We're only operating in one context, the `userScript` context.

**Comment by erosman** [comment]
> You seem to be under the impression that this is not a bug at all, that this is just an intended difference between the content context and the userScript context,

Indeed ..... FireMonkey does not handle `new XMLHttpRequest()` at all.
How `new XMLHttpRequest()` behaves in `userScript` context is not controlled by FireMonkey.
How can something which can not be controlled by FireMonkey be a bug of FireMonkey?

> Can you find any documentation at all indicating that this affects running XMLHttpRequest in the userScript context?
I don't know of any. You would need to look around. That was the reason I suggested asking Mozilla devs.

> [userScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts)
> 
> This API offers similar capabilities to [contentScripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) but with features suited to handling third-party scripts:
> 
> - execution is in an isolated sandbox: each user script is run in an isolated sandbox within the web content processes, preventing accidental or deliberate interference among scripts.
> - access to the window and document global values related to the webpage the user script is attached to.
> - no access to WebExtension APIs or associated permissions granted to the extension: the API script, which inherits the extension’s permissions, can provide packaged WebExtension APIs to registered user scripts. An API script is declared in the extension's manifest file using the "user_scripts" manifest key.


>  I'm trying to use functions that are built in to the Javascript spec.

When running the sample user-script I get the following error:

> Error: Got a request https://httpbin.org/status/200 without a browsingContextID set

Above error is not due to FireMonkey. It is a Firefox error. Therefore, only Firefox can answer and/or fix any issues that relates to the error.
I will ask them as well.

**Comment by afontenot** [comment]
I have filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1715249

Feel free to contribute there.

**Comment by erosman** [comment]
FYI ... I am talking with Mozilla engineers who developed userScripts API regarding this issue.

**Comment by afontenot** [comment]
For the record, I have a bit of advice. 

I created this issue in the hope of verifying that (a) I was not the only person experiencing the problem, (b) figuring out whether or not it was caused by the extension or by Firefox, so that it could be fixed or reported upstream. *I even suggested in the issue I filed that it was a Firefox bug.*

This was, apparently, quite easy. It's an issue with Firefox, and so it's been reported upstream. But I think you'll find other potential contributors are less inclined to waste five hours of their lives debating the nuances of an issue with you, only to have you insist that it's expected behavior, or that they don't understand the difference between userScript context and content context, or that they need to read up on Xray - *none* of which are relevant in this case, apparently. 

At the end of the day, from a user's point of view, if your extension doesn't work the way the spec says it should work, it's your bug, even if that's the result of you relying on upstream code. If Nvidia releases a driver that makes Windows bluescreen, Microsoft is the one that hears about it. 

I think you would be less likely to scare off contributors if you kept the focus on the actual issue, and not the misunderstandings you think the reporter has. You could have immediately replicated the issue with the code I provided in the initial report, said that it was definitely an upstream problem, and reported it or asked me to do so. I asked you directly god knows how many times to do that. Instead I got ... stuff like this:

> There is a fundamental difference in the context between FM & others. What you mentioned that works in GM, works because the code runs in content context. FireMonkey does NOT run in content context therefore, it is impossible to compare.

As it turns out, this issue is *not* caused by the `userScript` sandbox having different limitations than `content`. It appears to be a feature that's available in *every other context* being broken in `userScript` by a Mozilla bug. 

Sorry if I'm a bit steamed up about this. I simply find this approach to handling bug reports emotionally exhausting.

**Comment by erosman** [comment]
Thank you for the feedback.

As you have mentioned, the discussion got off-track due to comparison between user-script managers that work and behave differently.

A simple direct  "**XMLHttpRequest fails in userScripts**" without the side-tracking issues of CORS (not the issue here), how GM, TM, VM do things (not the issue here), could have got the results faster. 

Since `XMLHttpRequest()` is not controlled by FireMonkey, the immediate conclusion would have been a bug in Firefox API. Then, the issue would have been passed to Firefox engineers for investigation.

I do appreciate the time and effort that you have put in. Please also consider that FireMonkey and my other addons are also provided for free and without any gain for me. ;)

Nonetheless, it is now being handled by them and there should not be a need for further action at this point.

**Comment by erosman** [comment]
v2.53
Mapped `fetch` & `XMLHttpRequest` to page `window` as a workaround for  [Bug 1715249](https://bugzilla.mozilla.org/show_bug.cgi?id=1715249) until the bug is fixed.
