### ISSUE TITLE
[FireMonkey] allowSpecialHeaders doesn't work for multiple *special* headers

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#342]
`e.requestHeaders.splice(index, 1);` inside `forEach` is breaking things, because it removes the item from array, so what was `index + 1` becomes  just `index`, so it's skipped in the next iteration.

If you can't understand what I said, here's an example:

```js
let array = ['a','b','c','d'];
array.forEach((a, i) => {
  console.log(a);
  if (a == 'b') {
    array.push('b');
    array.splice(i, 1);
  }
});
```

Console logs `abdb`, `c` is skipped. Initially `c` had index = 2, but when the code removes `b`, `c` becomes index = 1, but this happens exactly after `forEach` processes the `index = 1`, that's why `c` is skipped.

**Comment by pintassilgo** [comment]
Why don't you use simply

```js
e.requestHeaders[index] = {name: item.name.substring(3), value: item.value};
```

instead of

```js
e.requestHeaders.push({name: item.name.substring(3), value: item.value});
e.requestHeaders.splice(index, 1);
```
?

**Comment by erosman** [comment]
I see .... I cant recall why I did that ... probably based on some example snippet :man_shrugging: 

sounds good.... :+1:

**Comment by pintassilgo** [comment]
> Have you tested it? Does it wok fine?

Yes. I was trying to set both `cookies` and `referer`, but `referer` was being sent as `FM-referer`. Applied the change I suggested and now both headers are being sent as intended.

**Comment by erosman** [comment]
Can you also test the 2nd part?

```js
      else if (item.name === 'Origin' && item.value.includes('moz-extension://')) {
        e.requestHeaders[index].value = 'null';
        found = true;
      }
```

**Comment by pintassilgo** [comment]
It's the exact same simple logic, so it works.

(I'm still lazy with my modded 2.24, but I guess 2.29 is the same)
