### ISSUE TITLE
[FireMonkey] [Bug] "Yandex Images" not loading with "RU AdList JS Fixes"

### ISSUE THREAD

**Issue by PoetAnderson1** [erosman/support#345]
When doing a search in "Yandex Images", the page seems to get stuck at the first 20 images:

![sshot-2021-07-06-22-30-00](https://user-images.githubusercontent.com/85243826/124687490-60382c00-deab-11eb-838d-ca8172ca1326.png)

Tapping on "More images" doesn't really do anything.

(doing a new search in the same page also seems to break things; nothing really loads):

![sshot-2021-07-06-22-32-44](https://user-images.githubusercontent.com/85243826/124688457-2b2cd900-dead-11eb-90d7-9e1f810772d7.png)

**Comment by erosman** [comment]
Only the userscript developer can debug the script, especially for large scripts like "RU AdList JS Fixes".
