### ISSUE TITLE
[REPLACE] Killer feature Replace with formula.

### ISSUE THREAD

**Issue by aranapatona** [erosman/support#346]
Today after trying this and other text replace addons that work more or less the same way, except for the Regex , I noticed I had the need to not only replace some text that came in foreign language, but I also needed to replace some quantities (measurement units) that came with the original page, so I figured it would be fantastic to add basic math support to this addon or even any supportd JS EVAL() operation.

Some work already done here:
https://greasyfork.org/en/scripts/370010-replace-numbers-on-webpages

**Comment by erosman** [comment]
>  I figured it would be fantastic to add basic math support to this addon

TBH, I only wrote that addon on request. If there are popular demands for features, I will work on it.

> even any supportd JS EVAL() operation.

`eval()` is not allowed in addons on AMO.

> Some work already done here:

Userscript managers would be more powerful for this purpose, for example my own [FireMonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/) which can handle both userscripts and userCSS.

**Comment by aranapatona** [comment]
> `eval()` is not allowed in addons on AMO.
> 
is window.Function() allowed?

I think that Converting units  would be a perfect use for an extension like this one.

**Comment by erosman** [comment]
> is window.Function() allowed?

It is the same as `eval()`. 

There are other methods that are allowed (_subject to the upcoming manifest v3 not disallowing them_), but as I said, a userscript manager specialises for that.

**Comment by aranapatona** [comment]
Yeah well userscripts are not as popular as extensions, you can do a lot of stuff but not many people even know how to use them or that they even exist. lol never would have imagined you were the author of firemonkey. I must admit its really good and we actually used it  for long, now I have it installed but currently disabled since I used it for a particular task that now we use an addon for (easier to configure, manage etc than a script) and I dont use any other scripts.

**Comment by erosman** [comment]
FireMonkey has scratchpad that users can paste and run code in it.

There is also the option to save a code and disable it and manually run it whenever user wants.

Replacing measurement requires an extended code, there are many measurements that can be replaced, there are many languages and formats.

The "Replace Numbers on Webpages" userscript can only replace digits with English words but that is not the only possibility, what about the dates, Chinese numbers, Roman numbers, etc etc. That is why a configurable script would be better.

However, as mentioned, if there are popular demands for features, I can work on it.
