### ISSUE TITLE
FoxyTab is Closing Tabs and Preventing Access to Container Listed Websites

### ISSUE THREAD

**Issue by tigersof** [erosman/support#349]
Hi,

I have just written about this issue and not realising that the GitHub website is included in my container list, the same thing happened - FoxyTab closed the tab, losing my draft post with it. This should not have happened.

I use FoxyTab for a lot of its features daily. The problem begins with needing to set Firefox up fresh due to an update and reinstall all the extensions, in this case, Firefox multi-containers and FoxyTab. In previous installations, they worked well together.

I have noticed that FoxyTab does not include the name of the container with its container list in the json file, and so container names must be added via Firefox multi-containers extension first. As I have about 28 different containers, this is not a trivial task to do manually. It is complicated by the fact that it is prone to errors, as I describe below, and some additional unwanted effects, which I will also describe. It has also consumed a lot of my time, and is not a sustainable exercise to keep repeating in future Firefox updates. 

### What I was trying to do (and has worked with fewer containers in the past):

1. Add each container name via Firefox multi-container settings one by one, careful to match same order as that in the json file.
2. Then import the json file via FoxyTab and save. Each container name should then be matched with its correct container list contents. 

### What Happened:

Attempt 1. container names and lists mismatched. 

Attempt 2. Tried to adjust multi-container names and then re-import json file, but still ended up with a mismatch.

Attempt 3. uninstalled both extensions and started over. This time container names are in correct order. 

  - However, after importing json file, all the container lists remained empty. 
  - Additionally, accessing websites included in my container lists (in new or existing tabs) now causes those tabs to be closed immediately. 
  - Unfortunately, this can also result in form data loss, as my last GitHub post demonstrates.
  - FoxyTab now behaves as a whitelist website blocker (!), rather than allowing me access to websites in my container list that I do want access to. 
  - FoxyTab does allow access to all other websites not included in my container lists.
  - Disabling FoxyTab stops the tab closing errors. 

Attempt 4. Uninstalled both extensions, restarted Firefox and tried again. Again, I have the same issues as Attempt 3.

For now, I have had to disable the extension again to be able to access websites, and cannot use FoxyTab's container lists, which are much more convenient and practical than Firefox multi-containers regarding efficient creation of long container lists. 

### Feature Request
If possible, please, export each container name along with its corresponding container list into the json file to improve efficiency and reliability, while reducing errors?

### Issue Fix
Failing that, I would like FoxyTab fixed to prevent the above issues occurring again.

As I rely on FoxyTab a lot, I would really appreciate some help with this. Thank you for making such a great extension. 

I am running the latest version of Firefox, 90.0.1.

**Comment by erosman** [comment]
> I have noticed that FoxyTab does not include the name of the container with its container list in the json file, and so container names must be added via Firefox multi-containers extension first.

Firefox multi-containers is a separate function which handles creation and management of the containers. FoxyTab utilises the existing containers to provide additional feature. Creation & Management of the containers are not part of FoxyTab's features.

> container names and lists mismatched

Please note that when navigating a tab, Firefox supplies `cookieStoreId` which relates to the containers. `cookieStoreId` data is in the format `firefox-container-n` where `n` is a digit. FoxyTab uses this digit (not container name) to handle the container. 

In FoxyTab options, the patterns for each container also follow above number in order, e.g.

```
1st pattern set for firefox-container-0
2nd pattern set for firefox-container-1
3rd pattern set for firefox-container-2
...

```

> Additionally, accessing websites included in my container lists (in new or existing tabs) now causes those tabs to be closed immediately.

The way the FoxyTab container feature works is that:

- On navigation, FoxyTab checks URL against the pattern sets in FoxyTab
- If there is match, it checks `cookieStoreId`
- If `cookieStoreId` doesn't match the digit of the order of matched container pattern set, it closes the tab and opens new one according the digit number

I am guessing that after deleting and renaming, the corresponding container might be missing e.g. you have pattern set 15 but there is no `firefox-container-14`.

📌 **If you are importing preferences of a previous FoxyTab into a new installation, your containers must be already set in Firefox Containers, before the import.**

If you wish to test, you can:

- Go to `about:debugging#/runtime/this-firefox`
- Find FoxyTab and click **Inspect**
- On the Toolbox, click **Console**
- Paste the following, click **Run** and see the result after editing containers
```js
browser.contextualIdentities.query({})
.then(contexts => console.log(contexts))
.catch(console.error);
```

**Comment by tigersof** [comment]
Hi

Thank you for your prompt response. 

> 📌 **If you are importing preferences of a previous FoxyTab into a new installation, your containers must be already set in Firefox Containers, before the import.**

This is the approach I was taking at the beginning, only it didn't work or I made errors. "" and null seem to be different, but I may have also missed the fact that they were separate container list lines when I created my containers, hence why I tried to reorganise the containers afterwards (a natural and intuitive response), which made things worse perhaps.

In the end, as uninstalling the extensions and restarting Firefox didn't seem to clear the problem, I could only solve this by doing the following:

1. Create a new Firefox profile (which I wanted to avoid doing)
2. Install Firefox multi-account containers to the new profile
3. Set up full list of containers, giving each a number 01..27 (including preinstalled ones)
4. Open the FoxyTab json file into notepad++
5. Extract the container list section only into a new Notepad++ tab, so that they line up with the line numbers 1..27
6. Use each line in Notepad++ container list to accurately modify Firefox multi-container names
7. Install FoxyTab
8. Then import the json file I referenced for the container names

It's a lot of effort, and as I said, difficult to do without error, especially if it needs to be done repeatedly, which seems likely given Firefox keeps forcing it via its updates every so often.  This is but just one extension though!

- **Is there not an easier way this could be done, by way of a feature request, please?** 


I'm not a coder, so some of what you said escapes me somewhat. 

- Is `cookieStoreId` user accessible, and if so, how?


> If you wish to test, you can:
> 
>     * Go to `about:debugging#/runtime/this-firefox`
> 
>     * Find FoxyTab and click **Inspect**
> 
>     * On the Toolbox, click **Console**
> 
>     * Paste the following, click **Run** and see the result after editing containers
> 
> 
> ```js
> browser.contextualIdentities.query({})
> .then(contexts => console.log(contexts))
> .catch(console.error);
> ```

I tried to follow this but I don't think it worked.

**Comment by erosman** [comment]
You shouldn't have to use a new profile, and custom containers should remain with extension & Firefox upgrade.
It could be worthwhile to post this particular issue to [**Firefox Multi-Account Containers** support](https://github.com/mozilla/multi-account-containers/issues).

TBH, **Firefox Multi-Account Containers** could do with an export/import function. :thinking: 

Once above is sorted, we can get to the FoxyTab part.

>  I tried to follow this but I don't think it worked.

In **multi-line editor mode (Ctrl + B)**

![foxytab-inspect1](https://user-images.githubusercontent.com/6458876/126737069-7db2d680-1930-4fed-8ea6-cab68d61c7f1.jpg)


In console mode, paste the code and hit **Enter**

![foxytab-inspect2](https://user-images.githubusercontent.com/6458876/126737110-08dcf527-cf51-4409-8590-1890a13e3bd0.jpg)

**Comment by tigersof** [comment]
Thank you, I go that to work this time.

I'll try posting on the link you provided. An interim/temporary solution would be welcome to output a line-delimted list of container names in listing order presented until then - would you be willing to do this for now, please?

Thanks for clarifying the above issues.

**Comment by erosman** [comment]
> An interim/temporary solution would be welcome to output a line-delimted list of container names in listing order until then - would you be willing to do this for now, please?

It wouldn't matter sice FoxyTab doesn't set containers.

As mentioned, in Foxy tab you can set patterns to open pages the in the 1st, 2nd, 3rd, 4th, ... container, whatever they might be.

**Comment by tigersof** [comment]
I meant as an aid memoire reference list in setting up the multi-account containers for the user (i.e. the next time I'm forced/need to start over). I do realise that FoxyTab can't set the container names up directly and I'm not requesting that. 

Some of my containers are specific to certain company domain sets, but many others are themed according to subject area (e.g. shopping). It can be challenging to work out some of the original container names looking at the FoxyTab json file, and any changes to the container list via multi-containers need to be recorded separately as I go along to manage this. Indeed, I was unable to identify several container names I had originally - I had spent a lot of time deciding what structure these containers should take in terms of how they would best suit my needs prior to gathering lists of domains to fill them. I find the multi-container method way too tedious and disruptive (as well as physically painful due to its buggy UI and limited voice accessibility), and this is also why FoxyTab really helps in that direction. 

This container name list creation feature for the purpose of the user manually recreating it more easily in multi-containers as and when needed would be useful and save me much of the effort and difficulties I experienced as described further above. Hopefully, such a list generating tool won't be needed long-term, assuming the multi-containers extension is updated to reflect this need directly and enable list import and export automatically.

Arguably, FoxyTab is already doing some of what multi-containers ought to be doing! You created a bonus add-on feature to multi-containers that improves its practicality, this request is just an additional slightly user-friendlier tweak until multi-containers catches up, which I hope it will do, since it is not ideal that component features relating to one extension are partially performed by another extension, and especially when the original extension could provide a much better fully integrated user experience. I’m very glad that FoxyTab includes the container domain list creation feature for now but do have a need for it to be extended to include a separate exportable-only container names reference list.

I plan to address all the issues I’ve described, including accessibility, with multi-containers directly with the extension makers in due course but that will take some time. If you’re able, and willing, I’d really appreciate this addition to FoxyTab until multi-containers evolves to negate the need for this, as a workaround to ease management of multi-containers, which is what I think FoxyTab aimed to do with the domain lists.

**Comment by erosman** [comment]
Let's see what can be done.

**Comment by tigersof** [comment]
Thank you, erosman, I hope you are able to do something.

**Comment by erosman** [comment]
I am updating Container code in v2.16.

The new code will tie container patterns to container IDs which should sort out the problem.

**Comment by tigersof** [comment]
Thank you for keeping me up to date, much appreciated. Will check this out a bit later.

**Comment by erosman** [comment]
Let me know if there are still any issues.

**Comment by tigersof** [comment]
Hi, 

Thank you for making this change. I had to edit my old FoxyTab json to get it to work since you've changed its structure a bit, but got there eventually. I think it achieves what you intended, which is great. 

Maybe worth including a note somewhere that within Firefox Multi-containers, both "Limit to designated sites" should be unchecked and the site lists should be empty, otherwise users can experience a very disruptive looping hell as FoxyTab and Firefox Multi-containers fight it out with each other!

Thank you again.

**Comment by erosman** [comment]
> Maybe worth including a note somewhere that within Firefox Multi-containers, both "Limit to designated sites" should be unchecked and the site lists should be empty, otherwise users can experience a very disruptive looping hell as FoxyTab and Firefox Multi-containers fight it out with each other!

I will... however, there shouldn't be any conflict if the same site is not entered in both.
