### ISSUE TITLE
Always turned on Proxy All option

### ISSUE THREAD

**Issue by val7000** [erosman/support#35]
I'm usind Windows 10, Firefox 64.0. 
Can't turn off Proxy All option. Clicking on it and nothing happens. 
On another desktop with the same OS it was the same, but then this bug disappeared.

**Comment by erosman** [comment]
Do you click the power button on toolbar popup? 
Does it change colour? 
Do you have multiple proxies set?
Do you have patterns set?

Export your preferences then disable/enable FoxyPAC and check it it makes any difference?
Next, uninstall and reinstall and import your preferences (in case Firefox had some issues in installation)

**Comment by val7000** [comment]
@erosman If I click power button on popup, it becomes always on (always letter A displayed). 
I can sitch off or on by clicking on main icon om toollbar. But patterns doesnt works. It is still Proxy All.
It changes the color.
I have one proxy set.
I have patterns.

Tried to export preferences, delete, reinstall plugin, then import prefs. There are any differences. 
As I said on another pc plugin mysteriously starts working.

I tried to remove code block in plugin where option All is turned on, but no effects yet.

**Comment by erosman** [comment]
There are TWO buttons on the popup
One big icon to turn FoxyPAC on/off
One power button next to Proxy ALL that is grey if it is off and blue if that is on

Are you turning Proxy All off by clicking the power button?

**Comment by val7000** [comment]
I know that. I'm using you plugin for a long time and found it very useful.
Option Proxy All turning on/off by clicking on label Proxy All. 
Big icon is turning off whole plugin.
The bug was that I cannot turn of ProxyAll option, letter A was hanging permanently.
I made a gif: https://i.imgur.com/q06nXl2.gifv

P.S. I found out that the reason was in cyrillic domain in patterns.

**Comment by erosman** [comment]
I see ... good that you found the reason

Did it put out any errors to the console?

**Comment by val7000** [comment]
Yes.
![error](https://i.imgur.com/022KYx8.png)

**Comment by erosman** [comment]
Have you tried the converted URLs? (copy them from address bar not text)

```
https://ru.wikipedia.org/wiki/Компью́тер
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80
```

**Comment by val7000** [comment]
I'll try, thanks.

**Comment by sergeevabc** [comment]
Is FoxyPAC broken under FF 70.0.1 x64?

**Comment by val7000** [comment]
Yes. It's always disabled.

**Comment by erosman** [comment]
> Is FoxyPAC broken under FF 70.0.1 x64?

@sergeevabc  I have been using it continuously and I am now on 72.0a1 (2019-12-01) (64-bit)

What is the problem?
Is there any error logged to the console?
Are you using the latest version?

**Comment by val7000** [comment]
In console: Unchecked lastError value: Error: proxy.settings requires private browsing permission.

**Comment by erosman** [comment]
@val7000 Have you disabled its private browsing permission?

Firefox now allows users to allow/disallow Extension to **Run in Private Windows**
Go to: 
Add-ons -> FoxyPAC (or any extension) -> Manage (or click on it) -> **Run in Private Windows** -> Allow

More Info: [Extensions in Private Browsing](https://support.mozilla.org/en-US/kb/extensions-private-browsing)

**Comment by val7000** [comment]
Ok, I found out that it conflicts with Windscribe VPN extension. I disabled Windscribe and FoxyPAC starts working.

**Comment by erosman** [comment]
> Ok, I found out that it conflicts with Windscribe VPN extension. I disabled Windscribe and FoxyPAC starts working.

Good .... Firefox only allows one extension to control **Network Settings** at a time.
