### ISSUE TITLE
[FireMonkey] [Question] Is this script compatible with "FireMonkey?

### ISSUE THREAD

**Issue by PoetAnderson1** [erosman/support#351]
for some reason, the "Alt-Click" behaviour of this script doesn't seem to work with Firefox.

https://greasyfork.org/en/scripts/12367-open-links-in-new-tab

is it just me?

I don't know what's wrong ;-;

**Comment by erosman** [comment]
Firefox uses `alt` key to display menu which conflicts with the userscript.

Furthermore, there is no uniformity in the `openInTab` options between userscript managers. The above userscript is written for Tampermonkey for Chrome.

The open-link in the new background tab part of the userscript works fine on Firefox & Chrome, and on all userscript managers but the **alt-click** part doesn't.



### `GM openInTab` Option
- [Greasemonkey](https://wiki.greasespot.net/GM.openInTab) supports `true/false` (_Greasemonkey 4 only supports `GM.openInTab`_)
- FireMonkey supports `true/false`
- [Violentmonkey](https://violentmonkey.github.io/api/gm/#gm_openintab) supports `true/false` and object (active, container, insert, pinned)
- [Tampermonkey](https://www.tampermonkey.net/documentation.php#GM_openInTab) supports `true/false` and object (active, insert, setParent, incognito)


### Built-in Firefox Click Options
- **Mouse-Middle-click** or **Ctrl-click** to open link in new tab in the background
- **Shift-click** to open link in new window

**Comment by PoetAnderson1** [comment]
is there a way to make it work with another key?

**Comment by erosman** [comment]
> is there a way to make it work with another key?

Sure .... you can try mentioning it to the developer.

**Comment by PoetAnderson1** [comment]
is it something that I can change on my own?

I've already tried replacing `e.altKey` with `e.cKey` (to make it work with the "C" key), but... that doesn't seem to work u.u

**Comment by erosman** [comment]
The available keys are `altKey`, `ctrlKey`, `metaKey` (on mac) & `shiftKey`, all of which are used by Firefox.

The userscript needs more changes to the way it is written.

**Comment by PoetAnderson1** [comment]
I found a tiny script that seems to overwrite the default behaviour of `ctrlKey`:

```
// ==UserScript==
// @name        Ctrl+click to Regular Click
// @namespace   YourNameHere
// @description Change ctrl+left click to regular click on all sites
// @include     *
// ==/UserScript==
function overrideCtrlClick(e){
  if (e.button == 0 && e.ctrlKey && e.target.nodeName == "A"){ // left button + ctrl key
    e.preventDefault();  // stop Firefox from processing 
    e.stopPropagation(); //   the user's Ctrl+click
    e.target.click();    // apply a regular click to the link
    return false;
  }
}
document.addEventListener("click", overrideCtrlClick);
```

I'm really sorry for asking, but... do you have any idea of how can I combine part of this code with the code from GreasyFork?

so I can use `ctrlKey` to do regular clicks?

**Comment by erosman** [comment]
Here is a script that should work with all userscript managers.

```js
// ==UserScript==
// @name          Open links in new Tab
// @description   Open links in new background tab but Alt-click opens in the same tab
// @match         *://*/*
// @author        erosman
// @version       1.0
// @grant         GM.openInTab
// @run-at        document-start
// ==/UserScript==

document.addEventListener('click', processClick);

function processClick(e){

  if (e.ctrlKey || e.metaKey || e.shiftKey || e.target.nodeName !== 'A') { return; }

  e.preventDefault();
  e.stopPropagation();
  e.altKey && e.target.nodeName === 'A' ? location.href = e.target.href : GM.openInTab(e.target.href, true);
}
```

**Comment by PoetAnderson1** [comment]
that works! :0

and, if I wanted to use "Ctrl" instead of "Alt", switching `e.ctrlKey` and `e.altKey` from places should not hurt the code, right?

**Comment by erosman** [comment]
> and, if I wanted to use "Ctrl" instead of "Alt", switching e.ctrlKey and e.altKey from places should not hurt the code, right?

Sure, that would work too.

**Comment by PoetAnderson1** [comment]
I'm.. sorry for bothering you again ;-; but, I just noticed that there are some type of links that completely ignore the script and never get opened in a new tab.

I noticed that in [Invidious](https://yewtu.be/) (open-source alternative Youtube front-end) and [Teddit](https://teddit.net/) (open-source alternative Reddit front-end).

maybe it's a missing line from the Greasy Fork script?

**Comment by erosman** [comment]
The script is meant to handle plain/standard links. 

Many sites, have their own JavaScript to handle link processing. For these sites, a more complex method of overwriting the site's JavaScript is needed which would often be different for each site.

**Comment by PoetAnderson1** [comment]
I feel like I'm taking too much of your time and that doesn't make me feel too good.

I'm sorry, I think I prefer to close this issue for now.

thank you for being so kind with me.

**Comment by KanadeTachibana2** [comment]
is there any way to implement what you did (override the shortcuts) on top of the other script?

**Comment by erosman** [comment]
> is there any way to implement what you did (override the shortcuts) on top of the other script?

Do you mean add it/combine it with another script?

If that is the case, then you can simply user `@require`. 
FireMonkey has a feature to `@require` another userscript that is already installed. (Read Help under **require**).

**Comment by KanadeTachibana2** [comment]
I mean to override the default Firefox keys in the following userscript:

https://greasyfork.org/en/scripts/12367-open-links-in-new-tab

**Comment by erosman** [comment]
hm ... try this and see how it works.

```js
// ==UserScript==
// @name          Open links in new Tab
// @description   Open links in new background tab but Alt-click opens in the same tab
// @match         *://*/*
// @author        erosman
// @version       1.0
// @grant         GM.openInTab
// @run-at        document-start
// ==/UserScript==

document.addEventListener('click', processClick);

function processClick(e){

  if (e.ctrlKey || e.metaKey || e.shiftKey || e.target.nodeName !== 'A') { return; }

  e.preventDefault();
  e.stopPropagation();
  e.altKey && e.target.nodeName === 'A' ? location.href = e.target.href : GM.openInTab(e.target.href, true);
}

window.addEventListener('auxclick', prevent);
function prevent(e) {
  
  e.preventDefault();
  e.stopPropagation();
  e.stopImmediatePropagation();
} 
```

**Comment by KanadeTachibana2** [comment]
the thing is that, just like before, some links that are handled by JS are completely ignored.

a part of the code of the other userscript seems to handle those links; that's why I wanted to know if it was possible to override the keys there?

**Comment by erosman** [comment]
> I mean to force the keys in the following userscript:
> 
> https://greasyfork.org/en/scripts/12367-open-links-in-new-tab
> 
> to... force them to work with Firefox?

You have to ask the author to fix it to work with Firefox. (https://greasyfork.org/en/scripts/12367-open-links-in-new-tab/feedback)
That userscript doesn't have any issues with FireMonkey.

**Comment by KanadeTachibana2** [comment]
I will.

thank you for taking your time to try to fix this, even thought I didn't deserve it... sorry.
