### ISSUE TITLE
[FireMonkey] CSS Live preview

### ISSUE THREAD

**Issue by kr4ssi** [erosman/support#357]
Just tried moving over from stylus again, but I miss the live preview. I have to reload the page to activate/deactivate a userstyle, I think no other userstylemanager needs a reload.

**Comment by erosman** [comment]
UserStyle managers manually inject CSS so they can also remove it.

FireMonkey uses Firefox API to inject and currently there is no live removal option in the Firefox API (there might be in future).

There is a considerable performance difference between manual injection and using the Firefox API.

Please refer to Help for more info.

You can manually inject and remove from FireMonkey toolbar icon popup Scratchpad or Info page.

>  I think no other userstylemanager needs a reload

True... but no other userstylemanager can also inject userScript ;)
