### ISSUE TITLE
[FireMonkey][CSS] Regular Expression is not supported 

### ISSUE THREAD

**Issue by kr4ssi** [erosman/support#358]
I can't run:
https://github.com/StylishThemes/Wikipedia-Dark
https://userstyles.org/styles/167419/google-darkest-fusion-1-2

**Comment by erosman** [comment]
> Regular Expression is not supported

The Firefox API does not support Regular Expression.

All such userStyles can be written without the use the Regular Expression, if developers decide to do it.
