### ISSUE TITLE
[FireMonkey][Android] Can't export

### ISSUE THREAD

**Issue by linsui** [erosman/support#359]
Nothing happens when I try to export.

**Comment by erosman** [comment]
[downloads.download()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) API that is used for export (save file) is not supported in Firefox for Android yet.

**Comment by linsui** [comment]
It seems uBO uses data url directly. See https://github.com/gorhill/uBlock/blob/79a2678f003bb0d19e1fed857c936a02be6e8dd9/src/js/settings.js#L109

**Comment by erosman** [comment]
How does it work on Android?
Have you tested it?

**Comment by linsui** [comment]
The uBO baxkup file is downloaded as other files on Android.

**Comment by erosman** [comment]
It will be in v2.31 (for testing).

**Comment by linsui** [comment]
Thanks!

**Comment by erosman** [comment]
BTW ...

- Export ALL (button at the bottom of the sidebar) will cause havoc on Android (i.e. as link), so I have disabled it
- Export Single (top men above scripts) is working but I am not sure if it is needed !!!?? :thinking: 
  - Export Single saves `.user.css` fine, but saves `.users.js` as `.users.js.txt` :man_shrugging:

**Comment by erosman** [comment]
v2.31 uploaded

**Comment by linsui** [comment]
It doesn't work for me. Do you need some log?

**Comment by erosman** [comment]
Ooops... I was testing on desktop Firefox and forgot to revert the test code.

I will release another shortly.

**Comment by linsui** [comment]
Thanks!
