### ISSUE TITLE
[Copy PlainText] change <hr> by custom separator

### ISSUE THREAD

**Issue by killero30** [erosman/support#36]
add an option so <hr> can be converted to a custom text
ex: I like to change <hr> with \n===\n

also would like to remove multiple lines when more than 2, but not when is less

**Comment by killero30** [comment]
also when copying from gmail for example, I'd like to remove:
[Quoted text hidden]
automatically from the pasted string

**Comment by killero30** [comment]
understood
I guess it couldn't copy a text or <img added with ::after or ::before either?

**Comment by killero30** [comment]
I see, do you have any recommendation?
the problem I'm having is that I'm copying from gmail print page, and the <hr is the separator used between mails in a thread, and when copying to text many emails becomes a little unreadable, that's why I wanted to convert <hr to a \n=======\n or something like that, that it could be chosen what to change it for

**Comment by erosman** [comment]
I rarely use gmail and then there are only few message there without replies so I cant test to see what is happening.

**Comment by erosman** [comment]
BTW, I have other addons (**Edit** & **Replace**) that you can use to replace text (not HTML) on web pages and then use **Copy PlainText** to copy.
