### ISSUE TITLE
[FireMonkey]Imported style doesn't work until saved again

### ISSUE THREAD

**Issue by linsui** [erosman/support#362]
Afther importing styles and scripts I have to save them again to enable it. Else it's enabled but doesn't work. Could you please take a look? Thanks!

**Comment by erosman** [comment]
How are importing?
Do you mean importing the entire Preferences? or individual import?

**Comment by linsui** [comment]
Importing the Preferences.

**Comment by erosman** [comment]
Only the styles don't work?
Scripts work?

**Comment by linsui** [comment]
No, script doesn't work either. All imported styles and scripts disapeared later.

**Comment by erosman** [comment]
> No, script doesn't work either. All imported styles and scripts disapeared later.

The Help that says:

> ### Preferences: Import/Export
> 
> You can import/export Preferences (for backup or share) from/to a local file on your computer.
> 
> 📌 **Import is non-destructive. Click save to apply the new settings.**

**Comment by linsui** [comment]
Thanks! I miss that.
