### ISSUE TITLE
[Copy PlainText] Shortcut "Ctrl+Shift+F7" not working

### ISSUE THREAD

**Issue by gt13013** [erosman/support#363]
Hello
I was using "Ctrl+Shift+F7" but it does not work anymore.
F7 is still working but I prefer "Ctrl+Shift+F7".
How can I retrieve the "Ctrl+Shift+F7" shortcut ?
Best regards
Gerard

**Comment by erosman** [comment]
**v1.12**
- Removed "Custom Keyboard Shortcut" setting since Firefox (66+) also provides the feature
- Removed second keyboard shortcut
- Added paste keyboard shortcut option

You can set any keyboard shortcut that you want. Please check the Help under **Keyboard Shortcut**.

> **Keyboard Shortcut**
> Setting was removed in v1.12 since the feature is available directly from Firefox (66+). Previous setting for first keyboard shortcut should remain but second one is removed.

**Comment by gt13013** [comment]
OK. It works!

Thanks for recalling me this operation that I had probably done some months before, and that I was not able to do again!
I have reset my Firefox profile and I have to configure everything again.

Best regards
Gerard
