### ISSUE TITLE
[Firemonkey] GM_fetch is broken

### ISSUE THREAD

**Issue by kr4ssi** [erosman/support#364]
Hello, I'm not sure if there are any technical issues hindering to make it compatible to
[fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), or [GM_fetch](https://github.com/rayfill/GM_fetch), but right now it's not even usable:

`GM_fetch('https://notexisting.host').then(console.log).catch(console.error)`
`GM_fetch(1).then(console.log).catch(console.error)`
`GM_fetch({}).then(console.log).catch(console.error)`
returns a Promise resolved to undefined
`GM_fetch([]).then(console.log).catch(console.error)`
Seems to fetch the current page?
`GM_fetch('https://existing.host/notexisting.path').then(console.log).catch(console.error)`
returns a Promise resolved to the HTML of the error-page

- There is no possibility to check for status-codes, like usually this would return a rejected promise with the statusCode which gets error-logged by the catch-handler.
```
GM_fetch('https://existing.host/notexisting.path').then(res => {
if (res.ok) return res.text()
else throw res.statusCode
}).then(console.log).catch(console.error)
```
- There is no type-checking for the URL
- It basically never returns a rejected Promise

**Comment by kr4ssi** [comment]
Nevermind the type-checking since original-fetch doesn't even have it too.

**Comment by kr4ssi** [comment]
`.catch(error => App.log(name, `${message.api} ${url} ➜ ${error.message}`, 'error'));`
This makes your promises always return resolved since [catch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) always returns resolved promises. This would return a rejected promise with the correct error.
`.catch(error => {
App.log(name, `${message.api} ${url} ➜ ${error.message}`, 'error')
throw error
});`

**Comment by erosman** [comment]
`G.fetch` is  JavaScript `fetch` run from background script.
`throw error` will cause the script to halt which is not desirable.

> There is no type-checking for the URL

It verifies the URL and uses `location.href `as base ( for relative URLS) in [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) i.e. `new URL(url, base)` (ref _background.js#803_).

**Comment by kr4ssi** [comment]
throw inside a promise won't cause the script to halt.

**Comment by erosman** [comment]
Looking at the [Using Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) it appears the promise rejection is handled somehow differently.

> The Promise returned from fetch() won’t reject on HTTP error status even if the response is an HTTP 404 or 500. Instead, as soon as the server responds with headers, the Promise will resolve normally (with the ok property of the response set to false if the response isn’t in the range 200–299), and it will only reject on network failure or if anything prevented the request from completing.

In `fetch` use examples, the code doesn't look for Promise rejection.

However, if there is popular demand for a change in the `GM.fetch` behaviour, I will look into it.

**Comment by kr4ssi** [comment]
There is no way to check if any request with your version of fetch was successful. It even returns a resolved promise on timeouts.

**Comment by erosman** [comment]
> There is no way to check if any request with your version of fetch was successful. It even returns a resolved promise on timeouts.

The result of `fetch` is usually checked e.g. if the text or json etc is returned by the promise, or not.

> [](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful)
> 
> **Checking that the fetch was successful**
> 
> A fetch() promise will reject with a TypeError when a network error is encountered or CORS is misconfigured on the server-side, although this usually means permission issues or similar — a 404 does not constitute a network error, for example. An accurate check for a successful fetch() would include checking that the promise resolved, then checking that the Response.ok property has a value of true.

**Comment by kr4ssi** [comment]
Your fetch doesn't resolve in a Response-object, so there is no way to check for the status.
It also doesn't reject if there was a network-error.

**Comment by kr4ssi** [comment]
background.js:
```
                return fetch(url, init)
                    .then(response => {

                        if (e.init.method === 'HEAD') {
                            const res = {
                                headers: {}
                            };
                            response.headers.forEach((value, name) => res.headers[name] = value);
                            ['ok', 'redirected', 'status', 'statusText', 'type', 'url'].forEach(item => res[item] = response[item]);
                            return res;
                        }

                        switch (e.init.responseType) {

                            case 'json':
                                return response.json();
                            case 'blob':
                                return response.blob();
                            case 'arrayBuffer':
                                return response.arrayBuffer();
                            case 'formData':
                                return response.formData();
                            default:
                                return response.text();
                        }
                    })
                    .catch(error => App.log(name, `${message.api} ${url} ➜ ${error.message}`, 'error'));
```
api.js:
```
        async fetch(url, init = {}) {

            const response = await browser.runtime.sendMessage({
                name,
                api: 'fetch',
                data: {
                    url,
                    init,
                    base: location.href
                }
            });

            // cloneInto() work around for https://bugzilla.mozilla.org/show_bug.cgi?id=1583159
            return response ? (typeof response === 'string' ? script.export(response) : cloneInto(response, window)) : null;
        }
```
There will never be an error. Just `response` will be undefined if there was an error.

**Comment by erosman** [comment]
> Your fetch doesn't resolve in a Response-object,

It is not possible to return the response object due to the X-ray vision. Therefore, the following had to be handled in the background script:
- response.json()
- response.blob()
- response.arrayBuffer()
- response.formData()
- response.text()


> There will never be an error. Just response will be undefined if there was an error.

That is how it can be checked.

```js
const response = await GM.fetch('https://example.com/etc');
if (response) {
 // successful 
}
else {
 // failed
}
```

**Comment by kr4ssi** [comment]
You still can't check for 404 this way.

It would be more useful just to include https://github.com/rayfill/GM_fetch

**Comment by erosman** [comment]
> It would be more useful just to include https://github.com/rayfill/GM_fetch

That does not appear to be `fetch`. It appears that their `GM_fetch` is a wrapper function for `GM_xmlhttpRequest` in a `new Promise`.

> You still can't check for 404 this way.

Passing additional values to the fetch response will break the current `Gm.fetch` specification in FireMonkey. Let's see if there is a popular demand for it.

**Comment by erosman** [comment]
I am working on updating `GM.fetch` ... let's see how it works out.

**Comment by erosman** [comment]
v2.33 
Updated GM fetch API to return an object (breaking change)
Check Help for more Info

**Comment by kr4ssi** [comment]
What if there's an json-error in the response?
