### ISSUE TITLE
[Firemonkey] Dollchan-compatibility

### ISSUE THREAD

**Issue by kr4ssi** [erosman/support#365]
Please make Firemonkey compatible to [Dollchan](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/). There already is an [issue](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1404) about it and the developer seems intrigued to work on it.

**Comment by erosman** [comment]
I had a quick look and it is a very large script (623kb, 18,914 lines). If the developers points out the issue, and it is possible to do, I will make the necessary changes.

**Comment by erosman** [comment]
FM v2.41
Since userscript has both GM_* & GM.* API, try `@disable-synchGM` in **User Metadata** and see if that helps

**Comment by erosman** [comment]
FM v2.42
Added experimental background `@grant` processing to auto-disable sync GM API if async GM API are supported (#408) (after save)
`@disable-synchGM` is removed
