### ISSUE TITLE
FoxyTabs Tab counter problem

### ISSUE THREAD

**Issue by Winter84** [erosman/support#366]
The Tab Counter seems to be unable to show a count of tabs of four digits under Firefox 92.0.1 (possibly also version 92.0). The display was fine with previous Firefox versions. I am running FoxyTabs 2.15. My OS is macOS 10.13.6.

**Comment by erosman** [comment]
Sadly, Firefox has reduced the width of the toolbar icon badges from 4 to 3 and even with recent release, it barely displays 3 characters properly.

ref: [BrowserAction Badge Text shows only 3 characters ](https://bugzilla.mozilla.org/show_bug.cgi?id=1602230)

**Comment by Winter84** [comment]
Would it be possible to show the count also on the Recount toolbar icon? Then the Firefox behaviour would only be mildly annoying. 😉

**Comment by erosman** [comment]
> Would it be possible to show the count also on the Recount toolbar icon?

Recount button is removed in the next version of the FoxyTab but if there is popular demand for it, I will see what can be done.

**Comment by Winter84** [comment]
> > Would it be possible to show the count also on the Recount toolbar icon?
> 
> Recount button is removed in the next version of the FoxyTab but if there is popular demand for it, I will see what can be done.

If the Recount button is removed after all, perhaps the count could be added to the Options page in the Tab Counter block.

**Comment by erosman** [comment]
> If the Recount button is removed after all ....

Recount was there since the number was cached which on occasion resulted in wrong count. The new process wont have that issue as it calculates live thus there is no need for a recount.

> perhaps the count could be added to the Options page in the Tab Counter block.

Do you mean opening the Option page to see the count value?

**Comment by Winter84** [comment]
> Do you mean opening the Option page to see the count value?
Only to confirm the count if the full number is not visible on the toolbar icon - not ideal, but I thought it might at least be feasible

**Comment by erosman** [comment]
Option page is not appropriate for this purpose. The toolbar icon popup would be better.
Let me see what can be done...

**Comment by Winter84** [comment]
> Let me see what can be done...

Thank you!

**Comment by erosman** [comment]
v2.16
Added Tab Count display to Toolbar popup 

It will show the tab count for that window in the popup header

![foxytab-counter](https://user-images.githubusercontent.com/6458876/161022622-4d3ebdb4-ee0c-450e-aa4b-a49842cfdfcf.jpg)

**Comment by erosman** [comment]
> I have Per Window disabled. I was expecting it to honor the setting but it seems like the popup always displays window count.

I will test it. 

_PS. I am traveling at the moment and not at my usual location._
