### ISSUE TITLE
Update from 2.32 to 2.33 breaks await

### ISSUE THREAD

**Issue by n-a-m-e** [erosman/support#368]
The latest update has stopped the await keyword from unwrapping promises. Please find below a test case that worked in 2.32 but not in 2.3.3
```
// ==UserScript==
// @name             testcase
// @match            https://www.google.com/
// @version          1.0
// ==/UserScript==
let result = GM.fetch("https://yahoo.com/");
async function run(){
  result = await result;
  console.log(result); //should print the HMTL string which is the promise.text value but returns promise object in version 2.33 instead
}
run();
```

**Comment by n-a-m-e** [comment]
just saw #364, i guess the change was intentional

**Comment by erosman** [comment]
I see.... you mean the result?
Yes.. there is a breaking change in v2.33 `GM.fetch` as per **About**.
It returns an object.

Please check and let me know if there are any issues.
