### ISSUE TITLE
[Foxytab] Development Status?

### ISSUE THREAD

**Issue by MintMain21** [erosman/support#369]
Browsing this Github page, I can see that a lot of development has occurred without a proper release. I have nothing but respect for you for working on this for so long and making sure it works as intended. Unfortunately, seeing the development screenshots that pop up here has only made me excited to try the updated features for myself. I will not demand a hard "release date", but I will say that if you wanted to introduce perfected features in incremental updates while you work on features that need more development I would welcome the change. If you would rather wait until the "full suite" is ready before unleashing it, I likewise understand. I am excited to eventually try for myself everything you have up your sleeve regardless. 

No real bug reports or feature requests for the time being. I'm more interested in trying out what you've been working on than I am pitching hypothetical features for future releases (not to mention the current version on the AMO is pretty rock solid stable as it is).

**Comment by erosman** [comment]
TBH, I have been working mostly on _FireMonkey_ which is a much more intensive project development.

AFA _FoxyTab_ ....

It has been rewritten and there are many new features and updates of old features.
It is working (I use all my addons myself and road-test them as I develop) BUT I haven't had the time to fully test all its functions for bugs, hence the delay. The development has been start & stop as I move to work on another add-on.

I am sorry for the time it has taken and I know I must finish it and I will try my best.

**Comment by keikoro** [comment]
Relatedly, Foxytab is not open source, is it? I was wondering about that with regards to the UI, but couldn't find a repo for it.

**Comment by erosman** [comment]
Open Source means the source is readily available and not obfuscated, hidden, minified, hard to read, or Proprietary License.
There is no requirement for an open source to be on a repo.
The source can be seen by opening the XPI.

**Comment by keikoro** [comment]
Well, this doesn't answer my question and offers a weirdly literal and incomplete definition of "open source". Since we're communicating on GitHub and I was specifically inquiring about a repository, I'd assumed it'd be clear I was talking about OS in the OSS development sense, i.e. collaborative work. Anyway, I'll translate this to "who knows" and "no". OK.

**Comment by erosman** [comment]
Here is the answer to your questions.

> Relatedly, Foxytab is not open source, is it?

FoxyTab is open source and released under [Mozilla Public License, version 2.0](http://www.mozilla.org/MPL/2.0/)

> I was wondering about that with regards to the UI, but couldn't find a repo for it.

FoxyTab is not on a repo.
