### ISSUE TITLE
Open Link In New Tab shows a blank screen untill i refresh the new tab

### ISSUE THREAD

**Issue by iaznaB** [erosman/support#372]
As per title, started happening today I believe.

Firefox 93.0 (64bit)
FoxyTab version 2.15
I have 74tabs open and I restarted my firefox (also closed more than 75% of tabs thinking that was the problem).

Problem is fixed when I disable foxytab.

Happens on youtube with night mode and reddit with RES installed and night mode on.

**Comment by DaSandman** [comment]
Indeed, I am seeing this behavior with, or without FoxyTab installed.
