### ISSUE TITLE
Why version 1.13 requires new permissions?

### ISSUE THREAD

**Issue by mrsarm** [erosman/support#374]
I have installed version 1.12 in Firefox 93.0, and today when I launched the browser it asked me to accept new permission requests from this plugin:

![Copy_Plain_Text_2021-10-18-fs8](https://user-images.githubusercontent.com/1608415/137730580-2b325ec0-d745-4f45-a0cc-61c84fa107aa.png)

Why such permissions are requested? I don't see the point of give the plugin download permissions to copy and paste text within the page, could you explain why?

I'm pretty sure there is a good reason, my recommendation for next release is to include in the release note a clarification of why a new permission is requested because it's the place when you usually check that.

**Comment by mrsarm** [comment]
Closing the question. IMHO, it's too much to allow the permission to just export preferences, I didn't update the plugin because I don't see the point of give up with more access to dangerous permissions to export how many preferences? 2.. 3..? how much time it takes to manually configure those options manually again?

**Comment by erosman** [comment]
### v1.15
- Changed <code>"&lt;all_urls&gt;"</code> and <code>"downloads"</code> to optional permissions
