### ISSUE TITLE
[NOT AN ISSUE] Request: Tab Navigation Buttons uc.js

### ISSUE THREAD

**Issue by EstherMoellman** [erosman/support#379]
Hi @erosman , how are you?

I'm really in need of a specific JS, and it would be great if you can help me. I'm using the latest version of Firefox Nightly + Windows 10 and, please, I need a JS (uc.js) where a mouse-hovered tab shows (below) the back - reload - forward buttons (inside a small tooltip or popup or container). If the mouse leaves the navigation buttons container or the tab, then the container disappears.

I'm sorry to bother you, but if by chance you can give me a hand... it'll be amazing!
Yeah, this is totally unrelated to FireMonkey, so if you don't want to or can't help me, no problem!, I understand, please forget my request.

Thank you in advance!
Big hug : )

**Comment by erosman** [comment]
Hi Esther

TBH, I have never attempted it so I am not experienced in it.

**Comment by EstherMoellman** [comment]
Thanks my friend for replaying me.
I'm closing the issue, but please, if you know someone who can help me, or you know a way to help me, please I count on you. Thank you very much again!
