### ISSUE TITLE
Turning Copy PlainText into Paste PlainText ?

### ISSUE THREAD

**Issue by antistress** [erosman/support#38]
Hi,

I like Copy PlainText thanks for that.

However sometimes I first "Copy" before releasing that I'd rather have "Copy PlainText". Then I have to copy again the selection, this time using the "Copy PlainText" entry.
What about allowing user to "Paste PlainText" ? That way, user would only have one copy option, and then the possibility to either "Paste" or "Paste PlainText" (which means no need to copy again if the 1st time I forgot to choose the "Copy PlainText" entry)

Summary : 
At present time : 2 entries for copying ("Copy" and "Copy PlainText") and 1 for pasting ("Paste")
Suggestion for the future : 1 entry for copying ("Copy") and 2 for pasting ("Paste" and "Paste PlainText")

Thanks !

**Comment by erosman** [comment]
**Paste Plain Text** has already been done and will be in the next upgrade.

**Comment by antistress** [comment]
Amazing !
Thanks

**Comment by erosman** [comment]
v1.9 uploaded with the **Paste Plain Text**
