### ISSUE TITLE
[FireMonkey] popup should close after clicking an UserScript command

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#382]
Example:

1. Install [MPIV](https://greasyfork.org/en/scripts/394820-mouseover-popup-image-viewer).
2. Open FM popup.
3. Click Script Commands.
4. Click MPIV: configure.

 MPIV settings appears, but it's behind FM popup that should have been closed when you clicked a command (in that case, "MPIV: configure").

**Comment by erosman** [comment]
hm ... Originally, I left it open so multiple actions can be performed.

OK .. done
