### ISSUE TITLE
[FireMonkey] allow to ignore original URL matching rules

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#383]
This just happened to me: I want to install and use a heavy script that is set to run on all pages, but I want it to run only on a specific page.

The script isn't mine and is updated regularly, so it's not convenient to manually edit the script all the time.

FM has User Matches, but they are useless in cases like the above.

Both VM and Tampermonkey support what I'm requesting (disabling original matching rules).

---
- Screenshot from VM:
![image](https://user-images.githubusercontent.com/5483864/140459497-bdf2b20b-d9a5-4cbb-aa95-bee2d566c7ad.png)

- Screenshot from TM:
![image](https://user-images.githubusercontent.com/5483864/140459542-3a5fc8d5-9259-4613-b5ad-eeb4be235b19.png)

---

FM should also have this feature.

FM has one extra reason to support it, because userScripts API handles URL rules differently and as you know there are ways much more performant than others. `@match` is better than `@include` and `@include` with regex is a disaster for FM. The user should be able to *fix* that without needing to fork the script or to rely on author good will about FM.

**Comment by erosman** [comment]
> FM has User Matches, but they are useless in cases like the above.

It should be possible with User Matches & Exclude Matches although it can become complicated to exclude due to the matching logic  (_match first then exclude_) :man_shrugging: initially set by Chrome and complied with by Firefox (read FM Help under **includeGlob & excludeGlob**).


FireMonkey has more matching parameters than others.
- match
- exclude-match
- include
- exclude
- includeGlob
- excludeGlob
- matchAboutBlank


I can add a single option to **ignore all matching rules** (except _matchAboutBlank_).

:thinking:

**Comment by pintassilgo** [comment]
> I can add a single option to ignore all matching rules (except matchAboutBlank).

For me that's fine, I think it's enough.

> It should be possible

I don't think it's possible at all.

**Comment by erosman** [comment]
> I don't think it's possible at all.

Write an exclude-match rule for each of the userscript includes :thinking:

**Comment by pintassilgo** [comment]
> Write an exclude-match rule for each of the userscript includes 🤔

The script is enabled for all pages.

`@include *`

**Comment by erosman** [comment]
That makes it very difficult.

_PS. All userscript mangers support the more robust `@match`. I am surprised that people still use `@include *`_

**Comment by pintassilgo** [comment]
> PS. All userscript mangers support the more robust @match. I am surprised that people still use @include *

The script I'm talking about is developed by the main person behind Violentmonkey in the last years. I guess they would use `@match` if it's not `@include *`.

**Comment by erosman** [comment]
Actually ....... I thought of a new idea....

It will take time to write, and it would need a database migrate... but I think it will be future-proof and awesome.

Remove  **User run-at**, **User matches**, **User Exclude matches** ... and instead add a user metadata block so users can set own rules.


**User Metadata**
```
// disable rules
@disable-match
@disable-exclude-match
@disable-include
@disable-exclude

// add/amend rules
@match
@exclude-match
@matchAboutBlank
@allFrames
@inject-into
@run-at
```
 :thinking:

**Comment by pintassilgo** [comment]
Thank you. Do you plan to release v2.35 soon? It seems that the code will change considerably.

**Comment by erosman** [comment]
As soon as I finalised the changes.

**Comment by erosman** [comment]
Updated **User Metadata** 

```
// Disable Rules
// without a value disables ALL original metadata rules of each entry
// with a value disables SINGLE original metadata rules of each entry
@disable-match
@disable-exclude-match
@disable-include
@disable-exclude

// Add/Amend Rules changes existing metadata rules
@match
@exclude-match
@matchAboutBlank
@allFrames
@inject-into
@run-at
```

**Comment by erosman** [comment]
It is done and will be in v2.35

**Comment by erosman** [comment]
v2.35 uploaded.

Note: Changes to script matching will happen when saving/importing/updating a script.

**Comment by erosman** [comment]
There is no entry on AMO page for cookies

![image](https://user-images.githubusercontent.com/6458876/140972738-4b8aab26-57da-4a41-a559-737b763c89fb.png)

**Comment by pintassilgo** [comment]
Weird... but also good. Less people to complain.

**Comment by pintassilgo** [comment]
It seems that autoconversion of `@include` to `@match` is kinda breaking this feature.

I set `@disable-include` to an UserScript that only has `@include *`, but still the script was being injected into every page. So I also added `@disable-exclude` and only then my disabling worked.

**Comment by erosman** [comment]
There are multiple features at work ... and the order is:

- process original Metadata
- auto-convert include/exclude to match/exclude-match
- process User Metadata
- process overlap rules

You can always check the result from the Info page of the toolbar popup. The page shows the the converted details.

Therefore:
1. original `@include *`
2. auto-converted to `@match <all_urls>`
3. User Metadata `@disable-match`
4. User Metadata add your new `@match`

**Comment by erosman** [comment]
> User metablock should be processed before auto conversion. In this case, after processing user metablock there would be nothing to convert, because there would be no @include since it was disabled by user metablock.

That is possible... Let em sort something out

**Comment by pintassilgo** [comment]
> That is possible... Let me sort something out

Yes, please. As you explained, ultimately it's working, but in a confusing way. I realized what happened because I'm related to FM development, but other users wouldn't understand why `@disable-include` isn't doing nothing even if the script uses `@include`.

**Comment by erosman** [comment]
OK.. fixed.. took a lot more code.
I will release 2.36 soon.

**Comment by pintassilgo** [comment]
Please, would it be possible to add this feature to UserStyles from `userstyles.org`?

I have a style using `@-moz-document domain("domain.com")`. I would like to disable this original match and to set my own `@match` rules.

**Comment by pintassilgo** [comment]
Actually my case is a little more complex.

I have always had this style enabled, but actually running via `@require` in another style (which I'd call a fork).

Now I want to disable my fork in a specific page (done with user metablock, easy) and to enable the original style on it.

So my plan is to enable the original style, but use user metadata to restrict it to the specific page I want.

But I want this original style to still fully work as `@require` on my fork, so user metadata on original style shouldn't apply to the `@require` on my fork.

**Comment by pintassilgo** [comment]
Detailed explanation:

- Original style uses `@-moz-document domain("example.com")`
- My fork `@require`s the original style and has `@match https://*.example.com/*`.
- Currently, original style is disabled, it only runs as an required style, not as an individual userstyle. This is important for my fork to always be processed **after** the original, so expressions from the fork always prevail over the original ones.

But now I want that the specific page `https://www.example.com/fire` should behave different: my fork should **not** work on it, but the original style should. So I should follow these steps:

1. Enable the original style.
2. In user metablock of the original style, set `@disable-match` and `@match https://www.example.com/fire`.
3. In my fork, add `@exclude-match https://www.example.com/fire`.


The problem is that step **2** doesn't owrk.

**Comment by erosman** [comment]
User metadata is complicated in userstyle since use metadata applies to whole script/CSS while userstyle rules are segmented.

```css
/*
==UserStyle==
@name           UserStyle
@description    UserStle Test
@author         erosman
@version        1.0
==/UserStyle==
*/

@-moz-document url('https://example.com/') {
  body { border: 2px solid red; }
}

@-moz-document url-prefix('https://one.com/') {
  body { border: 2px solid green; }
}

@-moz-document domain('two.org'), url-prefix('http://three.org') {
  body { border: 2px solid blue; }
}

@-moz-document regexp('https?:\/\/(www\.|old\.)?reddit.com.*') {
  body { border: 2px dotted purple; }
}
```

**Comment by pintassilgo** [comment]
Yes, in cases like that there's nothing to be done.

But just like we discussed in #304, I believe that the vast majority of styles using `@-moz-document` encapsulate the entire code in a single block. The one I use is an example. For these, I think it's doable.

Something like...
1. If the entire style is inside a single `@-moz-document` block and
2. The function is **not** `regexp()`
3. Then the userstyle can be autoconverted to `@match`es.

**Comment by pintassilgo** [comment]
This would also prevent from unnecessarily registering sheets globally.

**Comment by erosman** [comment]
I will have to see what can be done but the deprecated [@-moz-document](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)  method used in userstyles is not future-proof.

Imagine what a mess it would have been to have a similar system in userscripts. :man_facepalming:
