### ISSUE TITLE
maybe im a idiot .... but i can not figure out to use HISTORIA

### ISSUE THREAD

**Issue by FriedChicken** [erosman/support#385]
my first task is to remove translate.google pages from my firefox browser history , and i cant do it

**Comment by erosman** [comment]
Do you mean `https://translate.google.com/....`?

Do you want to add it to **Filter Patterns**?
Try:
`^https://translate.google.com/`

**Comment by FriedChicken** [comment]
![historia PATTERNS](https://user-images.githubusercontent.com/2156438/141017905-fe14d94e-4fe6-4614-9fc7-da0bd555e4a3.png)

i am on firefox - i went into extensions , then into HISTORIA options menu  - 
and pasted the text into the pattern box     -  i click on SAVE  and nothing seems to happen

**Comment by erosman** [comment]
Did you sort it out?

**Filter Patterns** removes new history items as soon as they are created. It doesn't delete old history items.
**Delete History** can be used to delete old history item
