### ISSUE TITLE
[FireMonkey] Updating script removes all related data

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#387]
I knew that an update was available for one UserScript I use. So I clicked the "Update" button. A dialog asked "*Do you want to discard the changes without saving?*" even that I didn't do any change since opening options page, so I confirmed.

The script was updated (minor changes), but all related data was lost. Both script settings (stored via `GM_setValue`) and my personal `User metadata` were erased.

**Comment by erosman** [comment]
I will check it out ....

**Comment by erosman** [comment]
I found it ... it was missing from options.js line 964
`storage` has been missing since 2.25 when database migrate :man_facepalming:
`userMeta` has been missing since 2.35

**Comment by pintassilgo** [comment]
`storage` is also missing in `readDataScript`.

**Comment by pintassilgo** [comment]
Sorry for totally off topic, but I wrote `pt_BR` localization, if you want to add it to FM:

**Comment by erosman** [comment]
Thank you . I will add it to the next release.

**Comment by pintassilgo** [comment]
Hi,

You forgot the "typo" commit, added in the previous comment:

https://github.com/pintassilgo/forked-firefox-extensions/commit/f616a2432e5e4a513121108ea077ca694d298784

**Comment by erosman** [comment]
OK... updated

**Comment by pintassilgo** [comment]
Instead of updating just the diff from the link I posted, you copied the entire file from my fork.

- Official FM uses `customCSS`. My fork renamed id to `optionsCustomCSS`.
- Official FM uses `customCSSDescription`. My fork: renamed it to `optionsCustomCSSDescription`.
- Exclusive ones from my fork*: `popupCustomCSS` and `popupCustomCSSDescription`.

So you should use this file:
https://github.com/pintassilgo/forked-firefox-extensions/blob/52b818efa0b9ab75f648790d0b5b30028c950424/firemonkey/_locales/pt_BR/messages.json

Plus these two typo fixes:
https://github.com/pintassilgo/forked-firefox-extensions/commit/f616a2432e5e4a513121108ea077ca694d298784

*: that's because you rejected my issue #302. I don't know why, because it doesn't change nothing for current users, it just adds a new option (default off, as I said it doesn't change nothing for current users). But of course I respect your decision.

FM only supports styling options page. My forked FM supports styling popup.
https://github.com/pintassilgo/forked-firefox-extensions/commit/39268ce9cb5b311935cea05039befd594730b683
https://github.com/pintassilgo/forked-firefox-extensions/commit/4cdb1ef6593fa36baaa11b24ee7576e5b3e7120c

**Comment by erosman** [comment]
If there is a popular demand for Custom CSS for the popup, I will add the feature.

**Comment by pintassilgo** [comment]
Right, this wasn't to bring back this matter, it's just that the pt_BR in v2.38 is wrong. I hope you understood what needs to be fixed.

**Comment by erosman** [comment]
> Right, this wasn't to bring back this matter, it's just that the pt_BR in v2.38 is wrong. I hope you understood what needs to be fixed.

Did you check v2.39?

**Comment by pintassilgo** [comment]
Yes, sorry, I meant v2.39.

What is wrong and need to be changed is [here](https://github.com/erosman/support/issues/387#issuecomment-975064784).

**Comment by erosman** [comment]
> What is wrong and need to be changed is here.

That one has extra entries.

**Comment by pintassilgo** [comment]
No, The file in your v2.39 has extra entries, that's why I'm saying to fix.

Again:

> So you should use this file:
https://github.com/pintassilgo/forked-firefox-extensions/blob/52b818efa0b9ab75f648790d0b5b30028c950424/firemonkey/_locales/pt_BR/messages.json
>
> Plus these two typo fixes:
pintassilgo/forked-firefox-extensions@f616a24

**Comment by erosman** [comment]
I fixed the typos ... for v2.40

**Comment by pintassilgo** [comment]
It happened again with user metadata. Today the script was updated for the first time in v2.42, previous time was a month ago in v2.40.

Data stored with `GM.setValue` (`storage`) was preserved intact, but user metadata (`userMeta`) was cleared, I needed to type everything again.

So the regression was at v2.41 **or** v2.42.

**Comment by erosman** [comment]
Is that auto-update or manual update?

**Comment by pintassilgo** [comment]
Auto-update. I noticed because as I already explained somewhere, this script uses `@include *` and I want it to run just in a single website, so I use `@disable-include` and a single `@match` in User Metadata.

Today I noticed the script was running in all websites, just checked the log and it was updated.

**Comment by erosman** [comment]
It should auto update :thinking: 

https://github.com/erosman/support/blob/9e0667ff03baf40e6ff29b8b75c4621d8f02f01c/content/app.js#L405-L410
