### ISSUE TITLE
[Firemonkey] CSS Issue?

### ISSUE THREAD

**Issue by hyperioo** [erosman/support#389]
Hello,

I wanted to use this script https://raw.githubusercontent.com/Rand0max/deboucled/master/deboucled.user.js that basically adds some buttons to a web forum to sort/hide topics based on my preferences.

After importing the script in Firemonkey, the scripts seems to run but the display is completely broken. Here is a view with maximum unzoom (there is a gigantic circle at the top of the page), the topic list (snapshot on the right) is also broken.

![image](https://user-images.githubusercontent.com/64754494/141693088-572860bf-5b87-442b-86e2-704414748415.png)

As these icons should be small, I was wondering if it could come from a CSS incompatibility issue (https://raw.githubusercontent.com/Rand0max/deboucled/master/deboucled.css). By looking into the script itself with Firemonkey editor, I'm seeing a lot of warning due to missing semicolons and a some red warnings I don't really understand as i'm not familiar with javascript. 

I was wondering if there was a quick way to tell if it was indeed an incompatibility issue.

The script is initially intended to be used with Tampermonkey but due to their data collection I wanted to avoid using it if possible.

Thank you in advance for your help, I would understand if you don't have much time to spend to help a single user.

**Comment by erosman** [comment]
re: https://github.com/Rand0max/deboucled

TBH, the best people to debug a userscript are their developers, especially for a large script.

I had a very quick look.

The script users synchronous `GM_getValue|GM_setValue` which may have issue in FireMonkey.

`GM_getResourceText` is `async` in FireMonkey so the CSS may not load in time.

**Comment by hyperioo** [comment]
@erosman Thank you for your answer. I might contact the developer or just resign myself to use tampermonkey.
