### ISSUE TITLE
[FireMonkey] Gmail's Google Keep side panel does not show my UserCSS's text-shadow

### ISSUE THREAD

**Issue by Fanolian** [erosman/support#390]
I have a UserCSS that applies text-shadow to (nearly) all text in all pages:

```css
/*
==UserCSS==
@name             TEST Text Shadow across whole Firefox
@match            <all_urls>
@version          1.0
==/UserCSS==
*/

* {
  text-shadow: 1px 1px 0px red;
}
```

For FireMonkey the text shadow does not show on the Google Keep panel in Gmail. In contrast, Stylus can apply it to the panel.

### Steps to reproduce
1. Have a Google account.
2. Add the above UserCSS to FireMonkey 2.37.
3. Log in to [Gmail](https://mail.google.com/). Turn on the Google Keep panel on the right. (Other panels exhibit the same issue)
4. Observe the text in the panel.

### Actual result
The text does not have a red text shadow:
![image](https://user-images.githubusercontent.com/771216/141964135-0deedfdb-f24e-486b-ae0a-640223e391fd.png)

I also tried to add another blue text-shadow CSS `*{text-shadow: -1px -1px 0px blue !important;}` using the Scratchpad (and press Run) but in vain:
![image](https://user-images.githubusercontent.com/771216/141964982-e4dd1ef6-1dbe-48b5-adc1-75b8225d5232.png)

With Stylus it looks like this (even without `!important`):
![image](https://user-images.githubusercontent.com/771216/141965643-238de074-7981-4edf-b2f7-cd768354d49e.png)

### Additional notes
1. The text shadow shows correctly if I open Google Keep in its own tab (https://keep.google.com/).
2. I see the issue in other side panels in Gmail, and also the side panels in Google Calendar.
3. I am still new to FireMonkey. Gmail is the first place I see such an issue.

I see that the Keep panel loads after others have been loaded. In FireMonkey's help it says:

>  ... CSS rules will apply to newly created elements in dynamically updated pages (e.g. on scroll) ...

So I guess the text in Keep panel should have text shadows too?
I understand that Stylus uses a different mechanism to inject CSS. Is this issue a limitation on how FireMonkey works? Or is it merely an issue with my UserCSS code?

### System info
Brand new profiles in Firefox 94.0.1 and currently Nightly (2021-11-15; 20211115215316)
FireMonkey 2.37

Thank you for your extension.

**Comment by erosman** [comment]
The standard behaviour of CSS is that its rules can override each other. There is also an order of importance.

To check what is going on...
- Go to `https://www.google.com/` (for example)
- Open **Developer Tools** (`F12`)
- Go to **Inspector** tab
- Find a relevant element
- On the right panel you should be able to see that the CSS has been applied
- It should also show if it has been overridden
- If it is missing, then the CSS has not been injected
![dev-tools2](https://user-images.githubusercontent.com/6458876/141974865-b2171f1e-1210-4960-b0b1-9cec869c287b.jpg)

**Comment by Fanolian** [comment]
> **Note:** If side-panels in Gmail's are in `iframe`, then that could be a reason and you should try adding `@allFrames true`

Thank you. It works.

For future reference, it is easier to reproduce it at the CSS Demo box (not the result part) at https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow
