### ISSUE TITLE
[FireMonkey] is returning error for valid match pattern

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#391]
I'm interested in testing [this](https://greasyfork.org/en/scripts/430593-recaptcha-solver-automatically-solves-recaptcha-in-browser/) script.

Recaptcha runs in iframe and FM is default off for frames, unlike the others engines. Usually I would suggest to follow other engines to improve compatibility, but in this case it's fine, I agree that default off is better and now we have user metablock to easily fix compatibility.

So I added `@allFrames true` to user metablock and clicked `Save`, but an error popped up saying `"*" in host must be the only character or be followed by "."`. This is a bug, because the pattern `*://*/recaptcha/api2/*` is valid.

**Comment by pintassilgo** [comment]
Another issue is that FM doesn't allow the valid `*://*/` pattern, saying that path can't be empty. The path [starts with `/`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns#path) so it's not empty.

**Comment by erosman** [comment]
> This is a bug, because the pattern *://*/recaptcha/api2/* is valid.

> FM doesn't allow the valid *://*/ pattern

I will fix that.

**Comment by erosman** [comment]
Fixed.. will be in 2.38
