### ISSUE TITLE
[NOT AN ISSUE] Simple question, you are not obliged to answer me

### ISSUE THREAD

**Issue by EstherMoellman** [erosman/support#392]
Hi @erosman my friend,

I'm going to ask you something about this [**TTBG**](https://addons.mozilla.org/en-US/firefox/addon/tabs-to-bookmark-groups) add-on.
It has nothing to do with you or your amazing add-ons, so please don't feel obliged to replay me.

I have been using **TTBG** for two years, IMHO it is an excellent add-on, I never had any problems. But recently in the Browser Console (CTRL + SHFT + J) some [errors in red](https://imgur.com/a/wz1kEiQ) have appeared. This is the [first screen](https://imgur.com/a/Lty18rT), and this is the [second](https://imgur.com/a/utObVFm).

**TTBG** has not had any updates for two years, and it is quiet normal that some errors may appear. But please what I want to ask you is about the second error, it is saying something about "message", "remoteproxyid", "could not establish connection" etc ... and although I have NO reasons to suspect anything, to my ignorant ears those things worry me a bit. Please @erosman, could you just tell me if that is normal?

I don't want to offend the Dev with my ignorant doubts, I trust you, so I prefer to ask you.

Thanks!
Big hug! :)

**Comment by erosman** [comment]
Hi Esther

The mentioned errors are not important.

JavaScript in Toolbar pop-up will be thrown away as soon pop-up is closed. When pop-up sends a message to background script, background script replies to that pop-up. If pop-up is closed in the meantime, you get an error.

[Proxy()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) is actually a name of a JavaScript API, and it is not the same as the proxy that is used in remote network connection.

**remote.js**
```js
export function registerRemoteHandler(handler, remoteProxyId = handler.constructor.name) {
    const listener = (message) => {
        if (!message || message.remoteProxyId !== remoteProxyId
            || !(message.name in handler))
            return undefined;
        return (async () => handler[message.name](...message.args))(); // Promise
    };
    browser.runtime.onMessage.addListener(listener);
    return { destroy() { browser.runtime.onMessage.removeListener(listener); } };
}
export function remoteProxy(remoteProxyId) {
    return new Proxy({}, {
        get(_target, name) {
            return (...args) => browser.runtime.sendMessage({
                remoteProxyId, name, args
            }).catch(e => {
                if (typeof e === 'object' && e.name === 'Error' && e.message ===
                    "Could not establish connection. Receiving end does not exist.")
                    return undefined;
                throw e;
            });
        }
    });
}
```

**Comment by EstherMoellman** [comment]
@erosman, you are an amazing person... THANK YOU!
