### ISSUE TITLE
[FireMonkey] Uncaught TypeError: importData.forEach is not a function

### ISSUE THREAD

**Issue by siamak2** [erosman/support#394]
when I try to import my scripts using the import button this error is displayed on console and nothing happens:
`Uncaught TypeError: importData.forEach is not a function`
![image](https://user-images.githubusercontent.com/20032689/142757657-36de12ee-9663-4a23-8884-1f72d0f70a52.png)

**Comment by erosman** [comment]
I tried import script and there was no problem.

`importData.forEach` is part of Stylus import. Are you trying to import a JSON?

**Comment by siamak2** [comment]
the import button from sidebar gives this error. I just realized that import/export on sidebar is different from import/export on main window.
I exported from main window and import it using the import button in main window and it doesn't give any error in console but nothing happens.
I just want to move all of my scripts to different profile. I have many scripts and don't want to do it one by one

**Comment by erosman** [comment]
In Options
- Export preferences
- Import into new FireMonkey

The Import/Export in Options is for importing/exporting everything.
The **Import** on the sidebar is for importing one/more scripts individually.

**Comment by siamak2** [comment]
import/export in Options doesn't import the scripts? in exported file I can see all of my scripts but when import it on new FireMonkey, only preferences are imported and script list is empty.

**Comment by erosman** [comment]
It should import everything. Let me test it to see if there are any issues.

**Comment by erosman** [comment]
You are right.. there is a bug

I have fixed it for v2.39 and will release it soon.

**Comment by erosman** [comment]
v2.39 is uploaded... try with v2.39 and let me know if there are any issues.

**Comment by siamak2** [comment]
it's working now. thanks
but it's important to click save to keep the scripts. perhaps you should add warning or something like that to remind the user to press save

**Comment by erosman** [comment]
> but it's important to click save to keep the scripts. perhaps you should add warning or something like that to remind the user to press save

It is already in the Help, under import.

I set it that way so if there are issues in the import, it wont wipe off everything and users wont loose their settings/scripts.
