### ISSUE TITLE
[FireMonkey] Script autoupdate disables user metablock

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#395]
As I already explained in other issues, I use a script that has `@include     *` , which I disable with `@disable-include` and then I set a single domain `@match` because I want the script to run in only one specific website.

Today, suddenly the script started to run on all websites. My user metablock was still correctly set. I clicked `Save` and the issue was gone.

Then I checked FM's log and realized that the bug happened because FM fetched the new version released by script's author. It was a minor update, the script still uses `@include     *`.

So, the issue is: script update turns user metablock useless. FM probably forgets to process user metablock after updating. The user metablock is **not** erased, it's still correct, but it's not processed.

**Comment by erosman** [comment]
It is fixed for v2.40
