### ISSUE TITLE
[Foxytabs] Feature Request: Operations with highlighted tabs

### ISSUE THREAD

**Issue by jedikalimero** [erosman/support#398]
Firefox allows the user to select several tabs using Shift or Ctrl keys in a similar way items are selected in an Explorer window. Thus allowing the user to make operations with the selected tabs such as close them, send to end/start, send to new window, bookmark, etc.

Ther are several functions in Foxytabs that can be executed on current tab,  all tabs, tabs to the left or tabs to the right.
Adding also Selected tabs to these four options would increase the versatility of the add-on greatly. In fact, this option can replace the "current tab" option since it would work as such if only one tab is selected (That is the case most of the time).

**Comment by jedikalimero** [comment]
Here is a list of all the features that would benefit from adding "selected tabs":

    Bookmark selected tabs
    Create Desktop Shortcuts for selected tabs
    Copy URLs with Titles from selected tabs
    Copy Tab Title from selected tabs
    Copy Tab Title & URL from selected tabs
    Copy Tabs URLs from selected tabs
    Duplicate selected tabs
    Sort selected tabs by URL or Title, Ascending or Descending
    Move selected tabs to the Start/End of tabs
    Move selected tabs to a New Window
    Move selected tabs to a New Private Window
    Reload selected tabs
    Copy selected tabs IP

Note: I think a few of these functions are already included with Firefox, but most of them not.

**Comment by erosman** [comment]
Selected tabs has already been added to the new release of FoxyTab.
Unfortunately, I haven't completed the new release of FoxyTab :man_facepalming:  as I have been working mostly on FireMonkey over the past 2 years.

**Comment by jedikalimero** [comment]
That's great news!
I will await impatiently the release of the new version! 😊
