### ISSUE TITLE
[Copy PlainText] Allow hidden context menu items

### ISSUE THREAD

**Issue by mantou132** [erosman/support#4]
I just want to use shortcuts without using context menu items. Thanks!

**Comment by erosman** [comment]
You can use the default keyboard shortcuts **F7** or **Ctrl+Shıft+F7**
You can also change the keyboard shortcuts.

At the moment, it is not possible to change to **Ctrl+c** or any shortcuts used by Firefox as Firefox ignores it.

There are talks to expand the API for shortcuts
https://bugzilla.mozilla.org/show_bug.cgi?id=1325692
