### ISSUE TITLE
Copy marked text and URL

### ISSUE THREAD

**Issue by JLRowe** [erosman/support#40]
I used an extension for years that allowed several options on copying the marked (selected) text and the URL. That extension is no longer compatible and is not being updated.

I used (in your style):
**{marked text}**
**{url}**

And possibly optionally add tab title to that combo.
Can you add this to FoxyTab or another, or just make an extension for this.

**Comment by erosman** [comment]
**FoxyTab** doesn't deal with page content (e.g. selected text on a page). It only deal with the Tab as a whole. 
My [Text MultiCopy](https://addons.mozilla.org/en-US/firefox/addon/text-multicopy/) has that function.
