### ISSUE TITLE
Are the scripts running under one of the Android browsers too?

### ISSUE THREAD

**Issue by pstein** [erosman/support#400]
Is there a browser (on ANDROID) which is capable to run the scripts too?

At least Firefox for Android cannot.

Maybe there is another browser?

**Comment by erosman** [comment]
I don't use Android for browsing but from what I have heard userscript managers work on Firefox for Android, although there might be some reduced functions.

FireMonkey also runs on Firefox for Android.

**Comment by pstein** [comment]
So in Edge browser it is not running?

**Comment by erosman** [comment]
I am not familiar with Edge to comment.
