### ISSUE TITLE
Request: Offer Pre-Release build of Foxytab on Github.

### ISSUE THREAD

**Issue by MintMain21** [erosman/support#401]
Not long ago I made an "issue" on here regarding the development status of Foxytab. The developer was kind enough to update me that he's been adding features, but unable to test/release them. 

Another extension who's development I follow, https://github.com/ssborbis/ContextSearch-web-ext, offers pre-release builds exclusively on Github, wherein people can report bugs before the final release on Mozilla Add-Ons Page. 

Since the developer is struggling to test the updated Foxytab himself, I propose he release the pre-build on Github so that we can test it, report bugs, etc.

**Comment by erosman** [comment]
That is possible. 
I once posted a pre-release/beta version of another addon for feedback but sadly it was not successful.
Furthermore, unsigned add-ons can only be installed in Nightly or Developer Edition of Firefox.

**Comment by erosman** [comment]
v2.16 will be released shortly.

**Comment by MintMain21** [comment]
Define "shortly".

**Comment by erosman** [comment]
Maybe tomorrow or within a coupe of days.
Unless I find something that needs doing (I added a new feature yesterday).

Then, as it is a recommended addon, it wont be available to download until it is reviewed by the Mozilla addon admin reviewers.

**Comment by erosman** [comment]
v2.16 Uploaded
Hopefully it will be reviewed soon and there are no issue/bugs.
