### ISSUE TITLE
[FireMonkey] v2.40 scrolls up on saving

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#403]
From v2.40 release notes:
> Added automatic Trim Trailing Spaces on SAVE

This is causing editor to scroll up and move cursor to the beginning of the code, that's annoying.

**Comment by erosman** [comment]
The reason is that the editor has to re-render the content.

Let me see what can be done.

**Comment by erosman** [comment]
OK... Removed editor update after save for v2.41
That means, trailing spaces are removed but the editor doesn't show it.
