### ISSUE TITLE
FireMonkey: setting User Agent

### ISSUE THREAD

**Issue by Iey4iej3** [erosman/support#406]
I am trying to understand how to set the UA in FireMonkey. Here is a simple piece of code:

``` javascript
// ==UserScript==
// @name Test
// @match *://*/*
// @version 1.0
// @run-at document-start
// ==/UserScript==

function ChangeUA(){
  Object.defineProperties(navigator,{
    userAgent:{value:"Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1"},
    platform:{value:'Mac'}
  });
}

ChangeUA();
```

This code works with TamperMonkey, and if `security.csp.enable` is set to be `false`, it also works with ViolentMonkey. I don't know how to make it work with FireMonkey. I tried to visit https://webbrowsertools.com/useragent/?method=normal&verbose=false but the default UA is untouched.

**Comment by erosman** [comment]
Above script defines that object in `userScript` context, not `page` context.
TM injects into `page` context when there is no grant.
TM injects into `page` context by default.

I have not tried it but have you tried using  `@inject-into page` or using `unsafeWindow` or `cloneInto()` to define it in page script?

Note: Changing the UA via userscripts will only affect the JS running in that page. Servers get the UA via headers. Page can have the real UA if it has access to server data.

**Comment by Iey4iej3** [comment]
Thanks. `@inject-into page` seems to work (when `security.csp.enable` is set to be `false`, otherwise there might be CSP errors). I am not sure how to use `unsafeWindow`, and you seem to say that it is deprecated in https://github.com/erosman/support/issues/343#issuecomment-870783391?

**Comment by erosman** [comment]
`unsafeWindow` is simply an alias for the `page` context `window`. Improper use of it can cause issues (linking userscript to page js & vice versa), but proper use of it can be useful.

TM alters CSP of the pages so it can inject userscripts everywhere (but that has security issues).
Other userscript mangers don't alter CSP of the pages so they cannot inject userscripts into pages with restrictive CSP.

**Comment by Iey4iej3** [comment]
I don't know whether the following code is OK? It seems working:

``` javascript
function ChangeUA(){
    Object.defineProperties(unsafeWindow.navigator,{
        userAgent:{value:"Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1"},
        platform:{value:'Mac'}
    });
}
```
Is there any benefit to use `cloneInfo()`?

**Comment by erosman** [comment]
`unsafeWindow` or `cloneInto()` are used to access `page` context from `content` (GM|TM|VM) or `userScript` context (FM), (i.e. when not using `@inject-into page` in FM).

If you use  `@inject-into page`, then the userscript is injected into `page` context, so there is no point.
