### ISSUE TITLE
FoxyTab sorting by URL should sort by top-level domain, then second-level, etc.

### ISSUE THREAD

**Issue by ejm554** [erosman/support#407]
When sorting my tabs by URL, I expected that all of my `acer.com` tabs would be grouped together and precede a group of `apple.com` tabs. 

Instead, they were sorted as follows:
```
https://service.acer.com/chat/support/...
https://support.apple.com/en-us/HT201...
https://support.apple.com/en-us/HT203...
https://www.acer.com/ac/en/US/content...
https://www.acer.com/ac/en/US/search...
```

I suspect that the sorting feature is looking at the URL as a regular string, rather than sorting according to the domain names, or maybe more precisely, according to the way the Domain Name System (DNS) is organized:

> A domain name consists of one or more parts, technically called _labels_. [...] The right-most label conveys the top-level domain; for example, the domain name www.example.com belongs to the top-level domain _com._ [...] The hierarchy of domains descends from right to left; each label to the left specifies a subdivision, or subdomain of the domain to the right. For example, the label _example_ specifies a subdomain of the _com_ domain, and _www_ is a subdomain of example.com. ([Wikipedia](https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_syntax,_internationalization))

Because of that, I expected the top-level domains (TLDs) of my tabs to be grouped together alphabetically, then, within that group, sorted/grouped by their [second-level domains (SLD or 2LD)](https://en.wikipedia.org/wiki/Second-level_domain), and so on.

I further wonder if the current sorting system also considers the protocol to be part of the sorting string. I tend to shy away from `http://` in favor of `https://`, so I couldn't test it. If it does, then all of the tabs in the first protocol might, respectively, precede those in the second, regardless of domain. For sake of sorting, this is the least important part of the URL, IMO.

**Anyhoo, I'd like to request that the sorting be smart enough to sort by the domain names in the standard DNS form, i.e., beginning with the right-most (top-level) domain label, then the second-level domain label, and so on.**

**Comment by erosman** [comment]
Separating subdomains from main domains is not straightforward without an additional library. ATM, the sort function is a plain text sorting of the URLs.

If there is a popular demand for the feature, I can look into what can be done.

**Comment by ejm554** [comment]
Oh, I didn't realize that. I figured it could be done using regular expressions or something.

**Comment by erosman** [comment]
Previously #317
