### ISSUE TITLE
[FireMonkey] "Meta Data Error" when UserScript is loaded in a background tab

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#409]
I'm getting `Meta Data Error` alert when opening a background tab with a valid UserScript.

https://github.com/erosman/support/blob/5291b3f6db8ae14881f45c271f282c26ff27cf22/content/background.js#L482-L490

The issue is in `browser.tabs.executeScript({code})`.

You should use `browser.tabs.executeScript(tabId, {code})` instead.

Without `tabId`, `executeScript` runs in active tab, which may not be the tab loading the .user.js file, like the case I experienced because I clicked to open the link in background tab.

**Comment by erosman** [comment]
Fixed in v2.41
