### ISSUE TITLE
'hljs' is not defined.

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#410]
Hi @erosman , any chance you could check why FM is showing the above warning when I'm trying to use this script: https://github.com/Wizmann/Utils/blob/master/UserScript/WorkflowyMd.js. The script is supposed to provide code highlighting among other things, but it doesn't. Thanks a lot!

**Comment by erosman** [comment]
Which line of which file generates the error?

Try adding `console.log(typeof hljs);` to see if it was defined.

`hljs` does not appear to be defined in `WorkflowyMd`.
`hljs` is defined as a property in `highlight.min.js` e.g. `t.hljs=e({}` and blocked in a function.


### Notes

`/highlight.min.js` is fetched at inserted into `userScript` context before userscript
```
// @require      https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js
```

Then ... `/highlight.min.js` is fetched by the web page and injected into webpage after userscript

```js
    var scriptElement = document.createElement( "script" );
    scriptElement.type = "text/javascript";
    scriptElement.src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js";
    document.body.appendChild( scriptElement );
```

Above does not serve any purpose. It would only be useful to webpage & `page` context. Userscript can only use it if it is injected into `page` context as well.


Also .... (just for info)
`GM_getResourceText/GM.getResourceText` in FM are `async` but should not be a problem for CSS.
As of FM 2.41 you can also `@require` CSS and FM does the rest.

e.g.
```
// @require     https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/monokai-sublime.min.css
```

**Comment by rubaboo** [comment]
> Which line of which file generates the error?

I was talking about `CodeMirror-lint-marker-warning` in the FM editor. I guess it was only a warning, and not the reason highlighting was broken. Anyways, just following your advice to

1. comment out the purposeless piece and
2. require css directly (so comment out GM_addStyle as well),

I got it to start highlighting. Also figured I could save a custom highlight.js as another userscript and require that instead of the cloudflare one that does not have the languages I need. Thank you so much! Case closed.

**Comment by erosman** [comment]
> I was talking about CodeMirror-lint-marker-warning in the FM editor.

I see .... that is because  `@require` code is not present in the editor, so that is understandable.

> Also figured I could save a custom highlight.js as another userscript and require that instead of the cloudflare one

Much better ... The same can be done with the `monokai-sublime.min.css` etc

TBH, for such a small main script, few small changes and jQuery would not be needed any more which would improve its performance.
