### ISSUE TITLE
[FoxyTab] Feature request - Adding Create Desktop Shortcut for All Selected Tabs instead of only the current tab.

### ISSUE THREAD

**Issue by Ced3k** [erosman/support#411]
Currently when we use the feature "Create Desktop Shortcut", it creates a shortcut only for the current tab.

I would like to create a shortcut for all the tabs in my browser's window.

Since we already can select all tabs at once, the idea is to create a shortcut for all the selected tabs instead of only the current tab.

It's a very small feature to add, but I need it.

Thanks.

**Comment by erosman** [comment]
I will work on ....

**Comment by erosman** [comment]
Done in v2.16
