### ISSUE TITLE
[FireMonkey] FR – ability to resize the two panes vertically…

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#413]
… by adding a drag handle to "Other Scripts & CSS" heading, or just making the whole heading draggable. Even if the position is not remembered, the feature would still be pretty handy.

A mock-up:
```
+---------------------------------+
| Other Scripts & CSS    ↕↕↕↕↕↕↕↕ |
+---------------------------------+
```

 As is, I can only see 6.5 lines in "Tab Scripts & CSS" section, which can be bothersome when I have 8-10 entries in there. I just like having the entire list visible, helps me think somehow, when I'm trying to remember where the part I want to change is.

**Comment by rubaboo** [comment]
Yup. I anticipated such a response so I tried to justify my request. I realize it's a bit irrational, but I don't think I'm alone in finding small windows aggravating. Whenever possible, I resize panes so that I can see as much of the entire thing as possible, even if I'm looking at it briefly. So, in the already not very big dropdown window, I'd appreciate the ability to expand either one of the 2 panes.

Feel free to close the request if you don't find it worthy.

**Comment by erosman** [comment]
OK ... let's see ...

Previous request for Custom popup CSS: #302

**Comment by rubaboo** [comment]
Ah, that guy! :) I guess custom popup CSS would satisfy us both.

**Comment by erosman** [comment]
Added to v2.42
