### ISSUE TITLE
[FireMonkey] Support different saveAs settings in GM.download()

### ISSUE THREAD

**Issue by xstnztk** [erosman/support#414]
Currently (version 2.41) FireMonkey always passes `saveAs: true` to `browser.downloads.download()` in background.js. As the [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) says:

> If both `filename` and `saveAs` are specified, the Save As dialog is displayed, populated with the filename.

In my use case I want to download several files at once, and I must pass a filename to `GM.download()` because I want to specify a different download directory (I do not really care about the filename itself). This means that Firefox will show a Save As dialog for every single file which I then have to confirm. This makes downloading many files quite tedious.

The Save As dialog is always displayed even if the Firefox setting for "Downloads" is _not_ set to "Always ask you where to save files".

It is not entirely clear to me from the MDN documentation linked above if there is a difference between setting `saveAs` to `false` and not including `saveAs` at all in the download options. The documentation could be understood that `saveAs: false` will _never_ show a Save As dialog, whereas omitting `saveAs` completely would show a dialog depending on the Firefox "Downloads" setting. IMHO it would therefore be best to support all three possibilities (true, false, absent).

As an additional benefit, this would also allow `GM.download()` to work on Firefox for Android. The MDN documentation says:
> Firefox for Android raises an error if `saveAs` is set to `true`. The parameter is ignored when `saveAs` is `false` or not included.

Thanks for considering this feature request. FireMonkey is extremely useful to me and it would be great if I could use it for all my needs.

**Comment by erosman** [comment]
The primary reason for `saveAs` in `GM.download()` is to notify user that the userscript is saving something. Without it, a userscript can save files in the background without the knowledge of the user.

The 2nd reason is to choose a location, as the API only saves to the **Download** location set in the _Firefox Settings_.
In case **Download** location is not set in the _Firefox Settings_, Firefox downland API will always show a `saveAs` popup.

How do other userscript managers behave in this regard?

> As an additional benefit, this would also allow GM.download() to work on Firefox for Android. 

ATM, that Firefox API is not available on Android as per [Browser compatibility](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download#browser_compatibility)

**Comment by xstnztk** [comment]
Thanks for the quick reply!

> The primary reason for `saveAs` in `GM.download()` is to notify user that the userscript is saving something. Without it, a userscript can save files in the background without the knowledge of the user.

I understand that you want to be careful and protect the user from malicious userscripts.

> The 2nd reason is to choose a location, as the API only saves to the **Download** location set in the _Firefox Settings_. In case **Download** location is not set in the _Firefox Settings_, Firefox downland API will always show a `saveAs` popup.

Hm, I am not sure if I understand you correctly but perhaps this is not necessary if the userscript explicitly passes a filename to `GM.download()`?

> How do other userscript managers behave in this regard?

Unfortunately I have not used any other userscript managers. Looking at the source code for ViolentMonkey, it seems to trigger the download by simulating a click on an anchor element instead of using the official WebExtension API.

> > As an additional benefit, this would also allow GM.download() to work on Firefox for Android.
> 
> ATM, that Firefox API is not available on Android as per [Browser compatibility](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download#browser_compatibility)

I understand this to mean that it did not support it up to version 79 (the current version is 96) but I am not sure. Using extensions on Android which are not approved by Mozilla is anyway a PITA. ;-)

Anyway, thanks again for considering it. I will rewrite my script as its own extension. A great opportunity to learn new stuff! :-)

**Comment by erosman** [comment]
> Hm, I am not sure if I understand you correctly but perhaps this is not necessary if the userscript explicitly passes a filename to GM.download()?

The purpose of **Save As** is to:
- Set a location to save to
- Set or change the filename


***Firefox ➜ Settings ➜ Files & Applications ➜ Downloads ➜ Save files to***

If above is not set in Firefox,  `downloads.download()` will always popup with **Save As**, regardless of whether `saveAs: true` is set or not.
The reason is that Firefox doesn't know where to save the file and has to ask user where to save it.
