### ISSUE TITLE
[FoxyTab] Move host tabs to this window

### ISSUE THREAD

**Issue by oddstr13** [erosman/support#416]
Similar to, but not the same as #75 

It would be nice to be able to move all tabs from a particular domain into the current window.
This way, you could consolidate all tabs from a particular webshop into a single window, then de-duplicate and sort there.

This would be kinda like merge all windows, except for a single host.

**Comment by erosman** [comment]
Let's see if there is a popular demand for it.

**Comment by erosman** [comment]
Done in v2.16

**Comment by erosman** [comment]
Previously: #312

**Comment by oddstr13** [comment]
The feature implemented in v2.16 and linking to this issue in the changelog, matches #75 but not this issue.
My suggested feature would allow moving, for example github tabs, from all other windows, into the current window.

I currently have 20 windows open, and merging them all first would be a bad option for me.
I would like to be able to move all open amazon tabs into one window, so that I can properly de-duplicate them.

I respectfully request that this feature request is re-opened and moved from the done state, so that it is visible for the future, when you have time and desire to look into this feature again :slightly_smiling_face:

**Comment by erosman** [comment]
Sorry.. you are right. It got missed up. I will work on this for the next update.

**Comment by erosman** [comment]
The code is done for v2.27

### Note
"Move Host to this Window"  will move hosts from the same type of window
- if current window is Private, only host tabs in other private windows will be moved
- if current window is normal, only host tabs in other normal windows will be moved

**Comment by oddstr13** [comment]
Awesome!
Thanks :smiley:

**Comment by WS-HS** [comment]
I Very need This!! 
i have use amazon too.
i open 8 window and have 17 YouTube tab in 5 window
and try [Move host to this window]
but not Nothing happened . why ... ?

**Comment by erosman** [comment]
Let me know if there are any issues.
