### ISSUE TITLE
All imported scripts and styles are disabled

### ISSUE THREAD

**Issue by ygoe** [erosman/support#418]
After selecting all files for import from a backup, I have to enable each one separately.

1. Why are imported items disabled? Wouldn't I import them to use them? They must be enabled for that.
2. (If 1 isn't possible or acceptable) Can there be an operation to enable/disable all scripts and styles at once?

**Comment by erosman** [comment]
Which file/how are you importing them?

**Comment by ygoe** [comment]
18 files, most of them styles (originally imported from Stylus)

I clicked the Import button, selected the directory and then all files with Ctrl+A

**Comment by erosman** [comment]
That is a manual method. It should set them as enabled. :thinking: 
Are there any errors logged in the Log tab?

FM has a method to import Stylus in one file.

From FM Help:

**Import from Stylus**
- Export styles from Stylus and Import the JSON (on pop-up change the file type selection to All Files), same name Script/CSS will be overwritten without warning

**Comment by ygoe** [comment]
You mean the Log tab on the settings page? Right now it's empty but I think I have restarted the browser since the import. Can I delete all scripts to retry? The settings page design looks a bit playful and is fairly limited. It doesn't stay with the usual GUI design guidelines which makes it hard to understand and use.

I imported them from Stylus *once* and then never again. The import isn't exactly nice, the formatting is strange (I manually fixed everything) and why should I import from Stylus when I have migrated to FireMonkey and exported from there? So Stylus was the original source of my scripts but is not relevant anymore now.

**Comment by erosman** [comment]
> You mean the Log tab on the settings page?

Yes

> Can I delete all scripts to retry?

Sure

> The settings page design looks a bit playful and is fairly limited. It doesn't stay with the usual GUI design guidelines which makes it hard to understand and use.

Suggestions are welcomed

**Comment by ygoe** [comment]
Ok so how can I delete all scripts without doing it 18 times individually? I can't find such a button.

**Comment by erosman** [comment]
You can select multiple scripts. Read Help under: **Multiple Enable/Disable, Delete & Export**

**Comment by ygoe** [comment]
Argh. Okay, here's some necessary UI feedback:

* The multi-selection works as expected but doesn't show. I expect selected items to have a clear representation, usually a blue background colour. There's a very light grey, almost unnoticeable. And that very thin and unclear orange border at the right edge. Also, when Shift-clicking items, for a brief moment, all text is selected as if the event wasn't handled properly. All of this led me to believe that multi-selection wasn't there. These are multiple UI failures. Suggestions: Use the `user-select` CSS property on every UI element where text selection isn't desired, like list controls. Use clear UI state presentation with visible colours, like in other applications.
* The Delete button is grey. Not orange like in the help image. That has two consequences: I didn't find it. When I found it, I believed it was disabled and unavailable. Until I hovered it and saw the expected colour. And only then dared to click on it. So the UI made me believe that function is unavailable. Suggestions: Don't use grey or light grey for icons that are not disabled. That colour has a meaning you didn't intend.

Now back to this issue: No, the log is empty.

Additional feedback: The Firefox window was unresponsive for 10 seconds (Windows told me so) while importing these 18 files. There was no feedback whatsoever that it's doing something. If this import process must be blocking for technical reasons I don't understand, it would be helpful to show a progress message at least. Like "Importing files, this might take a moment, please wait". Maybe even with a progress indicator (x of y files or x%).

Also, the top tab bar seems to be overlapped by the scripts list box. Its orange border at the bottom isn't completely visible.

**Comment by erosman** [comment]
> Suggestions: Use the user-select CSS property on every UI element where text selection isn't desired

OK, done.

> Suggestions: Don't use grey or light grey for icons that are not disabled. That colour has a meaning you didn't intend.

OK, done.

> the log is empty.

I was wondering if there were any errors logged. That's all.

> The Firefox window was unresponsive for 10 seconds (Windows told me so) while importing these 18 files. 

Importing involves asynchronous `FileReader`. It shouldn't take that long though. :thinking: 

> There was no feedback whatsoever that it's doing something.

It usually should takes 1-2 seconds which makes the whole process of creating progress indicator redundant.

> Also, the top tab bar seems to be overlapped by the scripts list box. Its orange border at the bottom isn't completely visible.

I see .... There appears to be some OS differences in action. On Win7 it looks fine but I checked on Ubuntu 21.10 and there is a slight overlap.
I will see how I can improve that without showing a gap between the sidebar and top-bar.

**Comment by ygoe** [comment]
Thank you for the updates.

As for the long delay, it might be my computer. Sometimes, things hang when I access files with my browser. Maybe it's the Windows antivirus. So don't mind me.
