### ISSUE TITLE
[Copy PlainText] Add permission for a shortcut in PDF files

### ISSUE THREAD

**Issue by sbstn87** [erosman/support#419]
Hi,

is it possible to make the extension's shortcut work in the PDF files opened in Firefox?

**Comment by erosman** [comment]
Do you mean the keyboard shortcut?

**Copy PlainText** context-menu, gets the text from Firefox (_up to 16k max or 16,384 characters_).

Keyboard shortcut injects JavaScript into the page to get the selected text which is not possible to some pages.

**Comment by sbstn87** [comment]
Yes, I meant the keyboard shortcut. It does not work for PDFs opened within Firefox. So I assume it will not be possible to implement.

**Comment by erosman** [comment]
AFAIK, it is not possible to inject JavaScript into pages created by Firefox like PDF, Reader View, etc.

**Comment by erosman** [comment]
I checked again with Firefox engineers and it wont be allowed.

ref: [content_scripts won't load with pdf.js tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1454760)
