### ISSUE TITLE
[FireMonkey] UserScript version of "Return YouTube Dislike" not working

### ISSUE THREAD

**Issue by mhetralla** [erosman/support#420]
[Extension homepage](https://returnyoutubedislike.com/)
[Userscript](https://github.com/Anarios/return-youtube-dislike/raw/main/Extensions/UserScript/Return%20Youtube%20Dislike.user.js)
Return YouTube Dislike is a popular extension that brings back the dislike count in the YouTube user interface. It is available as an add-on and as an UserScript. The UserScript works fine with Tampermonkey, but it doesn't load the dislike counter when used with FireMonkey.

**Comment by erosman** [comment]
Some observations:

- Script declares `@grant        GM.xmlHttpRequest` but never use it
- `isVideoNotLiked()` never used
- `isVideoNotDisliked()` never used
- `getState()` never used
- `setLikes(likesCount)` never used
- `checkForJS_Finish(check)` ... `check` never used
- - Line 336 `console.log();` ... log what?

Anyway ..... add`@inject-into page` to **User Metadata** and try
