### ISSUE TITLE
[Copy PlainText] Bug?

### ISSUE THREAD

**Issue by f23948** [erosman/support#422]
Please fix it thank you
https://www.youtube.com/watch?v=PYQQPYXhY1Q

**Comment by erosman** [comment]
Please give a page where it can be tested.

**Comment by f23948** [comment]
> 

https://www.tenforums.com/windows-updates-activation/190747-one-these-kb5010793.html#post2374775

**Comment by erosman** [comment]
I am not sure what the issue is.
When we copy normally or with Copy PlainText we get `ℹ About`.
Should it be different?

**Comment by f23948** [comment]
> I am not sure what the issue is. When we copy normally or with Copy PlainText we get `ℹ About`. Should it be different?

after i clicked on copy plaintext, it doesn't paste non-formatting letter i

**Comment by erosman** [comment]
That `ℹ` is how it is. It is not a formatted `i`. It is a Unicode character.

```html
<code class="cs1" style="padding: 3px 5px; font-family: Consolas, Menlo, Monaco, Lucida Console, 
Courier New, monospace, sans-serif; font-size: 15px; background-color: #eff1f2; 
white-space: pre-wrap;line-height:16px;display:inline-block;border:1px solid #e3e3e3;">ℹ About</code>
```

**Comment by f23948** [comment]
> That `ℹ` is how it is. It is not a formatted `i`. It is a Unicode character.
> 
> ```
> <code class="cs1" style="padding: 3px 5px; font-family: Consolas, Menlo, Monaco, Lucida Console, 
> Courier New, monospace, sans-serif; font-size: 15px; background-color: #eff1f2; 
> white-space: pre-wrap;line-height:16px;display:inline-block;border:1px solid #e3e3e3;">ℹ About</code>
> ```

oh ok
