### ISSUE TITLE
[FireMonkey] Support CodeMirror KeyMaps

### ISSUE THREAD

**Issue by rushsteve1** [erosman/support#423]
The CodeMirror editor supports [a few different key maps](https://codemirror.net/doc/manual.html#keymaps) that users can enable to emulate the keybinds of various other text editors. It would be a great feature if these were imported so that they could be enabled by the user.

Also thanks a lot for this extension (and all your others), it's quickly become my favorite!

**Comment by erosman** [comment]
OK ... I will work on it.

**Comment by erosman** [comment]
Added in v2.43
It can be set in _Options ➜ CodeMirror_
e.g.
```json
{
  "keyMap": "emacs"
}
```

**Comment by erosman** [comment]
v2.43 uploaded
