### ISSUE TITLE
[FireMonkey] W.A.R. Links Checker Premium

### ISSUE THREAD

**Issue by Mystqr4** [erosman/support#425]
Excuse my ignorance but is there anything that can be done on this side of things that will allow this script to run properly or does that fall on the shoulders of the script developer. I don't use this script very often but when I do it comes in handy. Given there is no other script similar anymore I'm curious as to what may preventing it from working with FireMonkey as I do not want to use an alternative user script manager or older version of GreaseMonkey.

I would also like to add that FireMonkey does not seem to remember script settings for some scripts one that comes to mind right now is Youtube polymer engine fixes. I tested the script with Violentmonkey and it worked fine and remembered settings whilst with FireMonkey it failed to remember settings at all.

Thanks for the support and for the great extension.

**Comment by Mystqr4** [comment]
Awesome! Thanks so much for the support. I know a few people would be happy for any sort of backwards compatibility or opportunity for some older scripts to work with FM.

**Comment by Mystqr4** [comment]
Wow! I think that seems to have got W.A.R. Links Checker Premium working. 
That's pretty awesome!

That took you no time at all. Granted it's just a temporary fix and I will have to keep this in mind after every update but it's pretty cool that you got it working again. 

Thank you!

**Comment by erosman** [comment]
I will try to see if I can work out a more robust solution.

**Comment by erosman** [comment]
Actually, I decided to make above automatic so removed `@awaitStorage` entry processing.

It will autmatically comes into effct when userscript has `GM_getValue/GM_setValue/GM_listValues/GM_deleteValue` AND NOT their `GM.` counterparts.

**Comment by erosman** [comment]
v2.43 Uploaded

- Added experimental sync storage compatibility
- Updated GM_getResourceText for improved compatibility

It should work with standard W.A.R. 
There is no need to manually add code to it.
