### ISSUE TITLE
[FoxyTab] Possible sleeping tab wake-up leading to high CPU and memory usage when sorting many (many) tabs

### ISSUE THREAD

**Issue by rolandog** [erosman/support#426]
- FoxyTab version: 2.15
- Operating System + Version: Ubuntu 21.10 x86_64
- Firefox Version: 98.0b4 (64-bit)

### Actual behavior
As I already reported in mozilla/multi-account-containers#2289, I had accumulated at least 2000 open tabs, and a couple of pinned tabs as well.  Sorting results in a very CPU-intensive and memory-intensive process.

I think it may be that tabs are being woken up in order to be re-positioned (when having `browser.tabs.unloadOnLowMemory` set to `true` in about:config).

### Expected behavior
Sorting a lot of tabs should not require so much CPU and Memory (perhaps the tabs were being brought out of sleep just to be able to be re-ordered?)

### Steps to reproduce
1. Have `browser.tabs.unloadOnLowMemory` set to `true`
2. Browse until you have about 2000 tabs in several different containers (+ some pinned tabs)
3. Sort tabs

### Notes
This may need to be reported upstream (to Firefox), but I'm reporting it here, and in Firefox's Multi-Account-Containers repository as well (that also has a sort feature).

Also, this may be related to #250 (though I think that issue can be closed since Firefox now supports `browser.tabs.unloadOnLowMemory` in about:config).

Here is a screenshot of `htop` showing the memory usage of Firefox while sorting by container (I didn't manage to capture one with FoxyTab, as my laptop became unresponsive when it maxed out on memory usage):

![htop-firefox-multi-account-containers-cropped](https://user-images.githubusercontent.com/12400926/154062566-2b6a6407-b512-4066-803e-e27c515ffaaa.png)

And here's a screenshot of `htop` of the laptop's baseline after closing Firefox:

![htop-firefox-closed](https://user-images.githubusercontent.com/12400926/154062852-e15a606c-263e-4ece-9378-966f24882338.png)

**Comment by erosman** [comment]
Thank you for the report. I will look into it.

**Comment by erosman** [comment]
Has there been anything new about this issue?

**Comment by rolandog** [comment]
I'm still not sure. I did report the behavior upstream [(Possible sleeping tab wake-up leading to high CPU and memory usage when sorting many (many) tabs)](https://bugzilla.mozilla.org/show_bug.cgi?id=1755475).
