### ISSUE TITLE
[FireMonkey] Ability to set dark theme through options

### ISSUE THREAD

**Issue by firezt** [erosman/support#428]
Hi!
I'd like to ask if it's possible to add an option to toggle on/off the dark theme (like in Tampermonkey), because when using this pref "privacy.resistFingerprinting = true" the OS/Firefox color theme is ignored, forcing the light one as default. Something like that would be very good in cases like this.

Thanks for the support. :slightly_smiling_face:

**Comment by erosman** [comment]
There is already the feature to set DARK, light theme, via CodeMirror Themes.

FireMonkey automatically adjusts to the CodeMirror Theme.

Options ➜ Script & CSS ➜ 3-dot menu ➜ Theme

**Comment by firezt** [comment]
Ooh I never realized that it applies to the extension theme too... 🤯
I thought it was just for the editor. :sweat_smile:
Now I got it.

Thanks for the explanation and stay safe!

**Comment by firezt** [comment]
> There is already the feature to set Dark/Light theme, via CodeMirror Themes.
FireMonkey automatically adjusts to the CodeMirror Theme.
Options ➜ Script & CSS ➜ 3-dot menu ➜ Theme

Hi,
This no longer seems to apply to the pop-up that opens when clicking on the toolbar icon:
![preview](https://user-images.githubusercontent.com/87192386/205458118-0b087078-d88f-4cc1-baa2-db8965a446bd.gif)

So I'm reopening it so you can take a look.
Just a reminder: This occurs when using `privacy.resistFingerprinting` = `true`, as I mentioned before.

**Comment by erosman** [comment]
Oh, wow.... I checked now and the line to set it was present in v2.32 went missing from v2.33 (Oct 5th, 2021).
It seems not many people use it..... lol

Fixed for v2.67

**Comment by erosman** [comment]
FireMonkey v2.67 uploaded
