### ISSUE TITLE
[Copy PlainText] Error copying

### ISSUE THREAD

**Issue by ghost** [erosman/support#432]
https://www.youtube.com/watch?v=Xy7mAybBiFo

**Comment by f23948** [comment]
[https://www.tenforums.com/drivers-hardware/191870-buying-new-cpu-question-2.html](url)

**Comment by erosman** [comment]
Which addon is that for?
What is the error?

**Comment by f23948** [comment]
please look at my uploaded YouTube video

**Comment by erosman** [comment]
> https://www.tenforums.com/drivers-hardware/191870-buying-new-cpu-question-2.html

I am working on the next upgrade (v1.14) of the extension.
I tested both the context-menu & the keyboard shortcut on above and they are working.
Please note that the page has a listener for `Alt-Shift+C` (in case you are using that) which toggles  **☑ Remember Me?**.
