### ISSUE TITLE
feature request: FireMonkey support editing local files via Native File System API

### ISSUE THREAD

**Issue by ivysrono** [erosman/support#434]
https://github.com/violentmonkey/violentmonkey/issues/1089

BTW, I'm not sure if syncing with local files by this API is possible.

**Comment by erosman** [comment]
Please note:

- ATM, the API is not supported on Firefox
- The API tidies the file read/write which is already available via different APIs e.g. [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) to read and [downloads](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads) to write
- As with `FileReader`, the API requires user action via a **file picker** dialog box

**Comment by ivysrono** [comment]
I just want to edit scripts in local vscode.

**Comment by erosman** [comment]
The above mentioned File System API wouldn't do what you wanted.
I also edit scripts in a dedicated editor, then load the script in browser tab and refresh as often as needed.

Check **Help** under **Self-Update**
