### ISSUE TITLE
[FireMonkey] Version 2.45 broke all my scripts, does not show them anymore

### ISSUE THREAD

**Issue by xstnztk** [erosman/support#435]
After upgrading to version 2.45, my FireMonkey scripts do not work anymore. My scripts usually scrape some data from a website and copy them to the clipboard. I noticed something was wrong when the clipboard contents were only the string "undefined".

When I go to the website for which I wrote the script (@match), FireMonkey 2.45 still shows the correct script name in the tooltip of the extension icon, and when I click on it, it shows the script name with the correct data (name, version, size, matches), but when I click on "Edit" to see the source code of the script, FireMonkey opens the "Options" (!) tab, and the "Scripts & CSS" tab does not show any scripts at all, neither the one for the current website nor any others.

The fact that going to the website causes the string "undefined" to be copied to the clipboard shows that my script is still executed (otherwise the clipboard contents would not be modified) but it is obviously broken.

This happens on Firefox 98.0 from Fedora 35. Downgrading to FireMonkey version 2.44 fixes the problem completely, i.e. all scripts are visible again and everything works as before.

Is this a local problem which only happens in my setup? I read the release notes of version 2.45 but did not see anything obvious. Is there any way I can debug this problem without knowing too much about the extension?

Since the old version 2.44 still works fine and I do not need any new features from 2.45, I can stay with the old version, so this is not an urgent problem but it must be fixed eventually.

Thanks!

**Comment by xstnztk** [comment]
I just noticed that the release notes for 2.45 say: "Added data option to GM setClipboard", which could explain why my scripts only copy "undefined" to the clipboard with the new version (if this new option is mandatory) but since I can neither see nor edit my scripts in FireMonkey 2.45, I cannot try to adapt them.

**Comment by erosman** [comment]
AFA first issue..... I am not sure what the problem is.

re: GM setClipboard
Update to GM setClipboard is optional extra.
There is a typo in the code. I fixed it and release a new versions.

**Comment by xstnztk** [comment]
Great, thanks! I will try it as soon as it is available.

**Comment by erosman** [comment]
> Is there any way I can debug this problem without knowing too much about the extension?

- Go to the Options page, open **Developer Tools** (F12) under **Console** and see if there are errors
- Go to `about:debugging#/runtime/this-firefox` -> FireMonkey -> Inspect .....  and see if there are errors

**Comment by xstnztk** [comment]
I did not see any error messages in the console logs but I think I found the problem with `setClipboard`:

The old version (2.44) took one parameter called `text` (api.js line 220). It passed this information to the background script with `data: {text}`. background.js then called `navigator.clipboard.writeText(e.text)` (line 767).

The new version (2.45) takes two parameters (`data, type`) and passes them to the background script with `data: {data, type}`. background.js first checks if `e.type` is set (line 780), and if not (as in my case), simply executes the old code which still uses `e.text`. `e.text`, however, is not longer set (only `e.data` is), and so Javascript converts `undefined` to the string `"undefined"` which is then written to the clipboard.

So I guess the code at background.js line 788 must be changed to pass `e.data` to `navigator.clipboard.writeText()` instead of `e.text`.

**Comment by erosman** [comment]
Yes.. it was a typo to have `e.text` instead of `e.data`. It is already fixed and v2.46 is already online.

**Comment by xstnztk** [comment]
I just updated the extension, and everything works again. Thanks a lot for the quick fix!

**Comment by frankmoskal** [comment]
re: missing scripts / css files — I see these errors in the console in version 2.46. Clearing the browsing history and restarting seems to (sometimes) fix the issue.

```
Uncaught TypeError: window.frames[i].document.body is null
    addTheme moz-extension://3baf74c1-e069-418f-8984-9b6b514ea775/content/options.js:239
    addTheme moz-extension://3baf74c1-e069-418f-8984-9b6b514ea775/content/options.js:239
    Script moz-extension://3baf74c1-e069-418f-8984-9b6b514ea775/content/options.js:198
    <anonymous> moz-extension://3baf74c1-e069-418f-8984-9b6b514ea775/content/options.js:1152
    
options.js:239:25
Uncaught (in promise) ReferenceError: can't access lexical declaration 'script' before initialization
    <anonymous> moz-extension://3baf74c1-e069-418f-8984-9b6b514ea775/content/options.js:10
options.js:10:3

```

**Comment by erosman** [comment]
> Uncaught TypeError: window.frames[i].document.body is null

Strange ... I don't get that error. It means the frames haven't loaded. The frames are **Help** & **About**. There should not be a problem loading them. 
I will investigate more.

> Uncaught (in promise) ReferenceError: can't access lexical declaration 'script' before initialization

Same as above... I never get that error.
I will investigate more.

---
In case there is a corrupted Firefox cache, try this:
Test 1:
- Go to Options page
- Hard refresh the page e.g. Ctrl + F5

Check if that makes any difference.

Test 2:
- From Option page, Export preferences (that is everything)
- Uninstall FireMonkey
- Restart Firefox
- Reinstall FireMonkey
- From Option page. Import preferences


Check if that makes any difference.

**Comment by frankmoskal** [comment]
Figured it out — tested it locally via an unpacked extension :)

The `getPref()` promise was resolving prior to  `const script = new Script()` firing on line 1152.  I have no idea why this was occurring, but moving the `User Preference` block down to the bottom of the script seems like a simple enough way to ensure it always loads.

**Comment by erosman** [comment]
Let me do some more testing on this.

**Comment by frankmoskal** [comment]
Still seeing the `window.frames[i].document.body is null` error — I think I've tracked it down to it just being a timing issue. The iframes do exist when I check the debugger, and adding a short delay before calling `addTheme` seems to fix it.

**Comment by erosman** [comment]
> Still seeing the `window.frames[i].document.body is null` error — I think I've tracked it down to it just being a timing issue. The iframes do exist when I check the debugger, and adding a short delay before calling `addTheme` seems to fix it.

I don't get that error with Nightly on Windows or Nightly on Ubuntu.
I tested it with Firefox 98.0.2 with new FM installation (without any scripts) and I do see that error.
That part of the code, adds dark/light class to Help/About.
I will change the process to eliminate the error.

**Comment by erosman** [comment]
v2.48 uploaded ... let me know if there are any issues
