### ISSUE TITLE
[FoxyTab] Please add -translations file to the xpi file

### ISSUE THREAD

**Issue by WS-HS** [erosman/support#438]
hi i like this plugin
but extension-translations file not  add to the xpi file ...  long time
 https://github.com/erosman/extension-translations/tree/master/FoxyTab/zh_TW
Please add to the xpi file

**Comment by WS-HS** [comment]
https://github.com/erosman/extension-translations/pull/55

**Comment by erosman** [comment]
v2.16 Uploaded
It will be on AMO as soon as it is reviewed by Mozilla.
You can try the include **Locale Maker** for easy translation.
v2.16 `messages.json` is also uploaded to [extension-translations](https://github.com/erosman/extension-translations)

**Comment by WS-HS** [comment]
ok.  zh_TW translation is update.
Thank you very much for your hard work 👍  : )

**Comment by erosman** [comment]
Done... There is a typo bug in v2.16 URL Ascending. I will release v2.17 with the new translation very soon.
