### ISSUE TITLE
[FoxyTab] Sort URLs Ascending doesn't work.

### ISSUE THREAD

**Issue by John4266** [erosman/support#443]
Browser: Firefox 100.0b4 (64-bit)

Description:
In the latest version (as of now: 2.1.6), the `Sort -> URLs Ascending` button doesn't work.
All the other sorting features work.

P.S.: No errors appeared in the console while debugging the extension.
P.P.S: I tried both incognito and normal browsing modes, both has the same issue.

**Comment by erosman** [comment]
Oops.. a typo :man_facepalming: 

I changed `sortURLAsce` to `sortURLAsc` and left a couple undone.
Fixed in v2.17

Thank you.
I will wait a bit to see if there are other bugs and release v2.17.

**Comment by erosman** [comment]
v2.17 uploaded and will be available as soon as it is reviewed.

**Comment by John4266** [comment]
Hello, I would like to let you know that the sorting features stopped working again (when using incognito) in the latest version (2.19).

**Comment by erosman** [comment]
> Hello, I would like to let you know that the sorting features stopped working again (when using incognito) in the latest version (2.19).

You are right. Fixed for v2.20
