### ISSUE TITLE
[FireMonkey] missing scripts and\or no scripts visible on dropdown

### ISSUE THREAD

**Issue by fmgmfm** [erosman/support#446]
Hello @erosman,
First of all I would like to thank you for your excellent programming and ongoing development on this fine privacy aware extension!

Now, I've been struggling with two issues popping into existence every now and then, since around 2.42 or so.
By the way they sound very similar to #435 

1. All of my scripts would suddenly go missing after exiting the browser, not to be found on the list or on the drop-down menu.
I can still find my scripts when debugging the extension
> about:devtools-toolbox?id=firemonkey%40eros.man&type=extension

and looking at the extension storage
So as you can see Firemonkey still seems to retain its settings...

2. After the former issue is magically resolved or if I import back my scripts one by one, another issue manifests as no scripts being seen when opening the drop-down menu. Usually nothing helps with this and I can go like this for days until something magically fixes it again.

I think it might be related to storage sync since today it happened after I enabled storage sync and deleted an unused script to stay under the 100KB cap.

FF 99.0
FM 2.50
![a](https://user-images.githubusercontent.com/103507608/162966666-e36c11e6-175c-4ceb-a1a9-a80593772152.png)

**Comment by erosman** [comment]
What happens when you Export Preferences?
Are the scripts still there?

**Comment by erosman** [comment]
When scripts dont show, is it only the popup or also the Options page?

**Comment by fmgmfm** [comment]
Only the "Scripts & CSS" tab is affected.
Everything else is there including my global excludes and CodeMirror lint settings

**Comment by erosman** [comment]
Can you try these?

- Open the Options Page
- Open Dev Tool F12
- Check if there are any errors
- Open FireMonkey Extension Toolbox `about:debugging#/runtime/this-firefox` -> FireMonkey -> Inspect
- Open Toolbar popup
- Check if there are any errors

**Comment by erosman** [comment]
You can add another script to go over 100kb.

**Comment by fmgmfm** [comment]
You're mad haha
It actually broke it again! glad I made another backup before trying this

So from the Scripts & CSS page with dev console active:
>Uncaught (in promise) TypeError: item is undefined
    addScript moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:681
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:669
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:669
    <anonymous> moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:1267
options.js:681:5

while from the extention toolbox:
1. >Uncaught (in promise) TypeError: oldValue is undefined
    processPrefUpdate moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/background.js:386
    processPrefUpdate moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/background.js:376
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/background.js:342
background.js:386:11

2. >Uncaught (in promise) TypeError: item is undefined
    addScript moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:681
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:669
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:669
    <anonymous> moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/options.js:1267
options.js:681:5

3. >Uncaught (in promise) TypeError: item is undefined
    addScript moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/popup.js:112
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/popup.js:98
    process moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/popup.js:98
    async* moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/popup.js:336
    promise callback* moz-extension://11faa63e-8c86-4856-ac15-ac122e5e0899/content/popup.js:335
popup.js:112:5

**Comment by fmgmfm** [comment]
By the way, creating a new blank script AFTER deleting an older one to free space brings back only my own written scripts.
The extension storage still holds the ones I've added from greasyfork etc

**Comment by fmgmfm** [comment]
Correct.

**Comment by erosman** [comment]
I have updated the Sync storage process in v2.51
Try it when it is released and let me know how it works out.

**Comment by erosman** [comment]
v2.51 released. Let me know if there are any issues.
