### ISSUE TITLE
[FoxyTab] Merge All Windows Has stopped working

### ISSUE THREAD

**Issue by SomewhatOrangish** [erosman/support#447]
Browser: Firefox 99.0.1 (64-bit)

Description:
In the latest version (as of now: 2.1.6), "Merge All Windows" Doesn't merge windows. "Close other windows" works as expected.

**Comment by erosman** [comment]
Thank You. I will fix that.

**Comment by erosman** [comment]
Are there still having issues with this?

**Comment by SomewhatOrangish** [comment]
> Are there still having issues with this?

It seems fixed! Thank you
