### ISSUE TITLE
foxy tab 'open link in new tab' option (including middle mouse click) from google search results have appended query string

### ISSUE THREAD

**Issue by jdix531** [erosman/support#449]
It seems highly reproducible for me - so long as the page doesn't try to remove query strings on its own which some will. An example page: https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla. I found first result if I searched 'firefox bug' but I happened to notice this extension caused it in my case.

I do like using foxy tab so hope this gets fixed. This occurs on my mac as well as desktop only since latest update.

**Comment by erosman** [comment]
That is a bug and already fixed and new version uploaded.

Disable **Clean URL** for now.

Previously: #445
