### ISSUE TITLE
doesnt work with vertical tabs reloaded un FF

### ISSUE THREAD

**Issue by WHiZSTA** [erosman/support#45]
i had been using tree style tab and this extension worked great, but i just changed t vertical tabs reloaded and it doesn't show in the tab context menu anymore. i'm sad and want to cry myself to sleep without foxytab, please fix asap!

**Comment by erosman** [comment]
Let me check....

**Comment by erosman** [comment]
_Vertical Tabs Reloaded_ (and _Tree Style Tab_) work by:
 - hiding the Firefox Tabs
 - creating a list of what tabs there are

Above is only a list and not real tabs so they won't automatically have the same context-menus as real tabs would have.
_Tree Style Tab_ has made the effort to recreate the menus from the tab context-menu thus showing FoxyTab menu. It seems _Vertical Tabs Reloaded_ hasn't.

![209754](https://user-images.githubusercontent.com/6458876/53588738-e6892880-3ba2-11e9-9e57-24facf2f7553.png)
