### ISSUE TITLE
[FireMonkey] Problem Firefox v99 does not recognize disabled script when reloading

### ISSUE THREAD

**Issue by pstein** [erosman/support#450]
I setup a *.user.js script for certain webpages.
It works.
However sometimes I want to see the original web page.
So I click on FireMonkey toolbar icon and remove the checkmark left of the script and reload the page

Occasionally (but not always) it happens that Firefox v99 (or FireMonkey) does NOT recognize that the script was disabled meanwhile.

All the script statements are applied as before.
Even if I reload the same webpage many times more the script execution is kept.
I have to exit and restart Firefox to really disable the script.

I think this is a bug.

Maybe Firefox looks only into its cache.

Can Firemonkey bypass this cache lookup by forcing Firefox to ALWAYS look at the current state of the script?

**Comment by erosman** [comment]
FireMonkey passes the script to Firefox to handle and from then on, it is all Firefox.
Firefox reloads a tab and using its cache as much as possible.
I often compare pages, but to compare, I open in a new tab.

Just now ...
 - I tested with userCSS and on reload it was removed
 - I tested it with userScript and on reload it was removed
 
 
### Note Some site do not reload
Quite a few sites interrupt reload/refresh/navigation and use JavaScript to change the content of the page. On these sites, the script is only injected at the first loading and as there is no reloading, the script doesn't get injected or removed.

That is a problem for all userscript/userCSS managers.

More Info: FireMonkey Help ➜ Detecting JavaScript Navigation
