### ISSUE TITLE
[FireMonkey] Popup to explain why manual Run button is disabled

### ISSUE THREAD

**Issue by numeralnathan** [erosman/support#453]
When the manual Run button is disabled, please show a popup as to why it is disabled.  This will help the user understand.

**Comment by erosman** [comment]
Do you mean a notification? or alert?

People often complain about unnecessary notifications.

The run is disabled in ONE situation only and that is if the script/CSS is already injected.

FireMonkey Help already explains:

**▷ Run**
- Inject the displayed userScript or userCSS (not userStyle) as long as it was not already injected in the tab

**Comment by numeralnathan** [comment]
Sorry I wasn't clear.  I mean a tooltip that says why the button is disabled.  The tooltip shows up when the person puts their mouse over the button.  The tooltip disappears when they move their mouse away.

**Comment by erosman** [comment]
I see... well, that is possible.

**Comment by erosman** [comment]
Done in v2.51

**Comment by numeralnathan** [comment]
Wow!  That's great that you implemented this so quickly.  Thank you!

**Comment by erosman** [comment]
v2.51
I have updated the process the allow re-injection of already injected JS/CSS.

**Note:** The userScript is injected as plain JavaScript. Its metadata block would not be processed and it has no access to GM API.
