### ISSUE TITLE
[FoxyTab] strange behaviors from v2.19

### ISSUE THREAD

**Issue by nerdCopter** [erosman/support#454]
When pinned tabs exist, there are major problems.

`Reload Tabs to Left` will instead reload all unpinned tabs, no matter which tab triggered from. 
`Sort` no longer sorting. tried both by Title and by URL.
`Move to New Windows, to the Left` moved all unpinned tabs both left and right to a new window.
`Merge All Windows` #447 seems true when pinned tabs exist.

Otherwise tasks seem to work when pinned tabs do not exist in a Firefox window -- i believe all reported problems are when pinned tabs exist.

```
Firefox 91.8.0esr (64-bit)
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
```

**Comment by erosman** [comment]
On request, Modifiers were added in v2.19 and are controlled in the Toolbar popup. (#444)
The default for pinned is off but you can turn it on.

**Comment by irvin** [comment]
> Sort no longer sorting. tried both by Title and by URL.
yap it's also broken at here. 
nightly 101.0a1（2022-04-17）on mac

**Comment by erosman** [comment]
@irvin Please read **Help** under **Modifiers**

**Comment by erosman** [comment]
In v2.21
- Fixed sorting Unpinned Tabs
- Fixed `Reload Tabs to Left`
- Fixed `Move to New Windows to Left` (same issue as previous)


re: `Merge All Windows` 
What is the issue?

**Comment by nerdCopter** [comment]
`Merge All Windows` seems to be working in v2.21
Thank you very much!
