### ISSUE TITLE
Can't change containers in the "Containers" config

### ISSUE THREAD

**Issue by icatalina** [erosman/support#456]
Version 2.20

`options.js` throws an error when trying to swap containers:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/4542735/163924185-e6c3754e-a6d1-41c9-b75f-c78e80381873.png">

It seems like a default value here fixes it, not sure of the downstream repercussions:

```ts
pref.container[id] = pref.container[id] ?? {}; // This fixes the issue

// cache the values
pref.container[id].name = this.textarea.dataset.name;   // update name with current name
pref.container[id].pattern = pattern;
pref.container[id].siteIsolation = this.siteIsolation.checked;
```

**Comment by erosman** [comment]
Are all the containers empty?

I am trying to reproduce the error.

**Comment by icatalina** [comment]
thanks

**Comment by erosman** [comment]
Are there still having issues with this?

**Comment by icatalina** [comment]
Hey, sorry, just checked, working :)
