### ISSUE TITLE
Foxytab on V99.0.1 of Firefox seems to be interfering with file storage download pages and also perhaps Amazon UK

### ISSUE THREAD

**Issue by MannyK2018** [erosman/support#457]
over the past few days I've been getting weird responses when using Firefiox. Firstly the Amazon search window stopped working on its UK homepage but only if you typed in a query. if you selected one of the suggestions that Amazon provides it worked. Also once past the homepage everything works fine in normal searches. However a similar thing occurred if you iried to search your old Amazon Purchase orders. If you typed something in the search window and hit return it defaulted back to the initial display of the last three months PO's. I raised this with Amazon who told me to delete my cookies and cache and do a full reboot. I went further and did a full clean of the system using 3 seperate tools (CCleaner, Wipe and Cleanspace) I rebooted and restarted Firefox

Things then got worse as the Amazon problem still existed and now I could not download from Uloz.to and Shareplace,org which I could prior to the clean and reboot. Uloz.to reports an invalid link at the point when the download should initiate having completed a successful captcha check and shareplace.org defaults to the upload page rather display a specific download page. there were no visible error messages.

 At that point, I restarted Firefox in safe mode and everything worked again. So I've switched off all my add-ons and restarted them one or two at a time starting with what I thought might be the most likely culprits ( i.e. ad, crypto,pop-up, tracker blockers etc) and one by one I loaded them and still everything was OK until I got to Foxytab and as soon as Foxytab was switched on the problems with Uloz.to and shareplace.org downloads returned.  Its frustrating as Foxytab is one of the top five add-ons I actively use, using it several times a day for various basic functions so I don't really want to leave it off and equally am not keen on keep switching it off and when I go to certain pages

Anyway FT definitely seems to be the culprit with the download pages. Amazon I am less sure of as that is now working again despite FT being switched on. I will continue to investigate the Amazon issue to see if another add-on is at fault. However  please can you take a look  at the download page incompatabilities? 

The other add-ons running  swhen I restarted Foxytab were:

CryptoMining Blocker
Don't Track me Google
DuckDuckGo Privacy Essentials
Google Analytics Blocker
Google Analytics Opt Out
Link Gopher
Pop-Up Blocker Ultimate
Privacy Badger
Privacy Possum
uBlock Origin

**Comment by erosman** [comment]
Is **Clean URL** enabled?

FoxyTab 2.16 added **Clean URL** (experimental) and that can interfere with the operation on some sites as it removes tracking strings.

I have updated **Clean URL** in 2.20 and removed amazon but there might be other variables.

If you have **Clean URL** enabled, disable it an then try it.

If you also give a URL that is not working, I will test it.

**Comment by erosman** [comment]
I found the problem with `shareplace.org`
I am working on it.

**Comment by erosman** [comment]
Fixed in v2.21

**Comment by MannyK2018** [comment]
Hi,

just to let you know I've just picked up on your m essages and yes switching off the clean url option resolves the problem and i see you've found the shareplace issue. As requested here is an example uloz.to link

https://ulozto.net/file/MlreRHbGduOk/tony-savarino-the-savtones-o-quaratinearino-rar# 

If you select the slow download and complete the captcha check it will default to and invalid link page if the clean url option is switched on. However hopefully now you've resolved the shareplace issue it will also resolve the uloz.to issue. Thanks for the speedy resolution!

**Comment by erosman** [comment]
Actually the fix is in v2.22 and I am still working on it.

**Comment by MannyK2018** [comment]
Yes spotted that. I rechecked after seeing your post.

**Comment by erosman** [comment]
The fix works fine for `ulozto.net`

Just like `shareplace.org`, the [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) API adds an extra `=` (when parameter doesn't have a value) which makes the resulting URL wrong.
I have added code to remove this extra `=`.
**Clean URL** should be OK in v2.22

**Comment by MannyK2018** [comment]
Good news. I will look forward to the update. Thanks
