### ISSUE TITLE
Creating shortcuts is not working

### ISSUE THREAD

**Issue by kamizoli** [erosman/support#458]
Since version 2.20 of FoxyTab with Firefox 99.0.1 on Windows 11 I can't create shortcuts any more. Nothing happens when choosing create shortcut.

Apart from that the layout changes are very disturbing, the order of my context menu changed with the update and it is a nightmare to set right again.

**Comment by erosman** [comment]
> Since version 2.20 of FoxyTab with Firefox 99.0.1 on Windows 11 I can't create shortcuts any more. 

Oops... an oversight when adding Shortcut Tab, All, Left & Right
Fixed for v2.22

> Apart from that the layout changes are very disturbing, the order of my context menu changed with the update and it is a nightmare to set right again.

Sadly, I haven't found a good way to preserve edited context-menus after new items are added in an upgrade.

**Comment by kamizoli** [comment]
Thank you for your fast response!
Also when doing screenshots nothing happens.

The problem with editing the menu is, that one chooses an item to moove, an it looses focus with each move up or down. One has to select newly after each moove to go on. The old way to choose an item and one could move it up and down without loosing focus of the chosen item was much better.

**Comment by erosman** [comment]
> The old way to choose an item and one could move it up and down without loosing focus of the chosen item was much better.

Let me see how I can improve it.

**Comment by kamizoli** [comment]
Thanks, that would be great!

**Comment by erosman** [comment]
I am sorry to say that v2.23 might be having another context-menu addition which will result in a context-menu reset.

I would suggest waiting to customise menus until FoxyTab has finished with all the changes.

**Comment by erosman** [comment]
Are there still any issues with Create Desktop Shortcut?

**Comment by kamizoli** [comment]
shortcuts are working again! Thank you!
But when using the screenshot funktion, nothing is happening

**Comment by erosman** [comment]
> But when using the screenshot function, nothing is happening

It is copied to Clipboard. I will update the help.

**Comment by erosman** [comment]
> The old way to choose an item and one could move it up and down without loosing focus of the chosen item was much better.

Done for v2.29
