### ISSUE TITLE
[FoxyTab] Weird Issue encountered, unable to sign in to websites

### ISSUE THREAD

**Issue by soloex1991eric** [erosman/support#459]
No Idea what is wrong with the addon. But with it enabled I can't seems to sign in to some websites, as the website keeps throwing an error. Specifically "youtube" refuses to log in at all.

**Comment by erosman** [comment]
Which addon is it?

Is it FoxyTab?
Disable **Clean URL** (if enabled) and try again.

**Comment by soloex1991eric** [comment]
yes it is, will try

**Comment by soloex1991eric** [comment]
Sorry, that did not fix the issue.

**Comment by erosman** [comment]
- Is it FoxyTab that you are talking about?
- Have you setup containers?
- What happens?
- Does it work if FoxyTab is disabled?

**Comment by soloex1991eric** [comment]
- Yes it is foxytabs.
- no I've not setup containers
- websites completely refuses to log me in, e,g shows error or simply does nothing. 
- yes it does work with foxytabs disabled

**Comment by erosman** [comment]
- Which version of FoxyTab is it?
- Have you set up any Redirect?
- I don't have youtube account to test, is there any other site that you are having problems with?
- Can you compare the URL when attempting to login with FoxyTab and the one without FoxyTab?

**Comment by soloex1991eric** [comment]
- v2.22
- No
- https://www.bitrix24.com/
- Not sure how to do that

**Comment by rjameson3** [comment]
Chiming in - the foxytab from april 20th - really broken.  I had to turn it off.   50% of all my sites gave a bunch of errors, could not login to over half of them...from saml errors, odd unknown messages, invalid errors etc.   Spent about 5hrs diagnosing, turning off firefox tracking, clearing data etc.   Nuke'd all my add-ons and enabled 1 by 1.   FFTab is the culprit.

**Comment by rjameson3** [comment]
I turned off the CleanURL and it works - so whatever was done with that - broke the web.

**Comment by erosman** [comment]
> I turned off the CleanURL and it works - so whatever was done with that - broke the web.

Sorry about that. Clean URL has been set to off by default since v2.18.

@soloex1991eric Are you sure that you still have problems with **CLean URL** disabled?

**Comment by monk-time** [comment]
I also had an issue with "Clean URL" breaking websites recently, I don't remember turning it on but can't be 100% sure of that, it's been ages since I looked into settings. The website that I had an issue with uses redirection for search results, and with Clean URL enabled it leads to URLs with spaces between words instead of plus signs, which breaks the site.

A feature like that is really outside the scope of a tab managing utility extension. Had to remove the extension because of that.

**Comment by erosman** [comment]
@monk-time Thank you for the feedback.

> In my opinion, a feature like that is really outside the scope of a tab managing utility extension and should be moved to a different extension. Had to remove the extension because of that.

It was an oversight to have its default to enabled in v2.16 (2022-04-11) and was corrected in 2.18 (2022-04-12).
It is an extra feature that can be turned off/on.

> should lead to
> https://www.icheckmovies.com/movies/forrest+gump/
> but with Clean URL it leads to a 404 page (note the space):
> https://www.icheckmovies.com/movies/forrest gump/

Unfortunately, this was an unexpected side-effect of using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

See Also: #445

**Comment by soloex1991eric** [comment]
Oh sorry... You're right disabling "Clean URL" does appear to solve the issue.
