### ISSUE TITLE
replace sentence ending with a line break

### ISSUE THREAD

**Issue by MTS1** [erosman/support#46]
i wanted to separate each sentence into its own line.  how could i accomplish this with your addon?

for example:  "in the house there were it was.  In modern times"

in the find I have [a-z]. [A-Z] but how do i insert a line break/carriage return at the space marker so it looks like this?

in the house there were it was.  
In modern times"

**Comment by erosman** [comment]
**Replace** accepts normal line breaks

For example:
Find:
`/(.+\. )(.+)/`
Replace
```
$1
$2
```
