### ISSUE TITLE
[FoxyTab] Error 400: "The server cannot process the request because it is malformed. It should not be retried. That’s all we know." + DuckDuckGo Bang Search Failures

### ISSUE THREAD

**Issue by puddlecheese** [erosman/support#460]
Hey all!

Windows 10 64-bit Pro.
Firefox 99.0.1 (64-bit)
FoxyTab Version 2.22
Only other Firefox extension I'm using: UBlock Origin

I'm a bit pressed for time this morning, but did some quick testing.

Basically, I'm unable to login to Gmail with FoxyTab enabled, currently. I receive the same 400 error specified in the title.

If I disable FoxyTab, I am able to login fine.

This may or may not be related to Multi-Container Tabs that are included with FoxyTab.

There are a few issues along those lines noted here: https://github.com/mozilla/multi-account-containers/issues/2021

I have also been experiencing some issues with using DuckDuckGo !bang searches in some instances, which redirect to 400 errors. Disabling FoxyTab and re-enabling it might have addressed this, or I'm just unable to reproduce it at the moment.

Has anyone else been experiencing these issues since the new FoxyTab version / permission request?

Thanks all!

**Comment by erosman** [comment]
If you have **Clean URL** enabled, disable it and try again.

Previously: #445

**Comment by puddlecheese** [comment]
> If you have **Clean URL** enabled, disable it and try again.
> 
> Previously: #445

This seems to have done the trick!

Just tested with Clean URL disabled. I was able to login to Gmail just fine, and DuckDuckGo !bang search functionality restored.

Re-enabled Clean URL, and no longer able to login to Gmail, and DuckDuckGo !bang search functionality hits "400 Bad Request" with some sites (!yt "searchterm", for example).

I will leave Clean URL disabled for the time being. Thank you for your help!

**Comment by erosman** [comment]
It was an oversight to have Clean URL's default to enabled in v2.16 (2022-04-11) and was corrected in 2.18 (2022-04-12).
It is an extra feature that can be turned off/on.

Unfortunately, this was an unexpected side-effect of using [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

I have been working on fixing it in v2.23

**Comment by nandryshak** [comment]
Thank you! :pray:
