### ISSUE TITLE
FoxyTab Problem with SSO login after last update

### ISSUE THREAD

**Issue by suqin-haha** [erosman/support#463]
Hi,

after updated the Foxytab at Firefox, there is problem about SSO login.
it's always shows the page even i cleared all the cookies 
![image](https://user-images.githubusercontent.com/60164317/164815222-369514a3-3bb9-4e2e-9ef4-791403d55a60.png)

test at https://teaching.rice.edu/canvas click the 'Rice login'
it's a good extension, hope it can be fixed.

Thanks

**Comment by puddlecheese** [comment]
Was also experiencing this.
Consider trying what was discussed here: https://github.com/erosman/support/issues/460
TL;DR, in FoxyTab options, try disabling "Clean URL", if you haven't already.
Good luck!

**Comment by suqin-haha** [comment]
Thanks that's works

**Comment by erosman** [comment]
Sorry about the problem and thank you for the help.
v2.23 is already uploaded and waiting for a review.
