### ISSUE TITLE
New update causes bug with DuckDuckGo?

### ISSUE THREAD

**Issue by Kvaks** [erosman/support#464]
I have no idea what is happening here, but recently I started getting 400 Bad Request errors when using !bangs at DuckDuckGo (bangs are DDG's shortcuts for redirecting a query to other sites' search engines). After investigating a bit, I found out that the problem went away when I disabled the FoxyTab plugin.

Example: Go to https://duckduckgo.com  and type in the search query _**!nk Oslo**_
If you get a 404 error, disable FoxyTab and try again.

Not all bangs give an error, but certainly more than one, so it's not just one site. It all started about a week ago.

I don't know if FoxyTab is doing something wrong, or just triggering a bug somewhere else.
My browser is Firefox 99.0

**Comment by erosman** [comment]
Please disable Clean URL ad try again.

Previously: #445

**Comment by Kvaks** [comment]
Yes, that solved it!

**Comment by erosman** [comment]
Sorry about that. Clean URL is experimental and it has been disabled in new release.
