### ISSUE TITLE
[FoxyTab] Tab context menu icon appearance

### ISSUE THREAD

**Issue by Snekbro** [erosman/support#467]
An option to change the orange icon in the tab context menu to a darker/muted color matching the rest of the UI. [feature request]

**Comment by erosman** [comment]
I was also asked why the rest of the icons are black & white (they were in color in v2.15).

Let's see if there is a popular demand for it.

**Comment by erosman** [comment]
v2.26
- Added Alternative Grayscale Icon option

**Comment by Snekbro** [comment]
Much appreciated. Thank you <3

**Comment by erosman** [comment]
### Correction
Alternative Grayscale Icon will only apply to toolbar icon.
AFAIK it is not currently possible to change the main context-menu icon.

> [menus.create()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create)
> **Note:** The top-level menu item uses the [icons](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons) specified in the manifest rather than what is specified with this key.

If that is not desired, let me know and I remove the option for the toolbar icon.
