### ISSUE TITLE
[FireMonkey] (maybe )compatibility issue

### ISSUE THREAD

**Issue by ale82to** [erosman/support#468]
sorry to bother again sometimes I "try to switch" to firemonkey (from vm) but seems really impossible for me .
this super simply UserScript wich copy link url on context menu is not working in firemonkey :
// ==UserScript==
// @name         copy tools
// @namespace    -
// @version      1
// @description   -
// @author       -
// @require      http://code.jquery.com/jquery-3.6.0.min.js
// @author       -
// @match *://*/*
// @exclude https://www.youtube.com/*
// @run-at document-idle
// @grant  GM_setClipboard

// ==/UserScript==
$('body').on('contextmenu',"a:not(a:has(img))",displayContextMenu);
 function displayContextMenu(e) {
         GM_setClipboard(e.target);

};
 any idea what's going on ?

**Comment by erosman** [comment]
To start with, `@match :///*` is invalid.
`@Version` is also wrong but that is not an issue.

Are you trying to copy the HTML?
`e.target` is HTML.

**Comment by ale82to** [comment]
sorry match was right in the originale UserScript (*://*/*)
in vm/tm the UserScript copies link url on right click .

**Comment by erosman** [comment]
`e.target` is HTML. You need `e.target.href`


```js
// ==UserScript==
// @name          copy tools
// @namespace     -
// @version       1
// @description   -
// @author        -
// @require       http://code.jquery.com/jquery-3.6.0.min.js
// @match         *://*/*
// @exclude       https://www.youtube.com/*
// @run-at        document-idle
// @grant         GM_setClipboard

// ==/UserScript==
$('body').on('contextmenu', 'a:not(a:has(img))', displayContextMenu);

function displayContextMenu(e) {
  GM_setClipboard(e.target.href);
}
```

**Comment by ale82to** [comment]
thanks also for explaining I'm still learning ,working fine now .
if you had the change also this UserScript is not working in fm :
https://greasyfork.org/it/scripts/419620-m3u8-mp4-detect

to save time since is not detecting video on every url test this on (working fine in vm/tm ):
https://voe.sx/b9u15vh9v75f

**Comment by erosman** [comment]
> if you had the change also this UserScript is not working in fm :
> https://greasyfork.org/it/scripts/419620-m3u8-mp4-detect

To start with `@match        http*://*/*` is invalid.

It should be: `@match        *://*/*`

It can use `@include` but `@match` is better. They work in GM|TM|VM since they covert them to regex and not really use them as `@match`

Script also declares `@grant        unsafeWindow` but never uses it, but that is not a problem.

The script is trying to overwrite `XMLHttpRequest.prototype.open` which due to a current Firefox bug in `userScripts` context might be having an issue.

You can try `window.XMLHttpRequest.prototype.open` instead.

**Comment by erosman** [comment]
Try v2.53 and see if that helps.
