### ISSUE TITLE
[FoxyTab] IP based server location flag doesn't work with IPv6

### ISSUE THREAD

**Issue by Haxorzz** [erosman/support#469]
IP based server location flag doesn't work with IPv6, it shows a question mark, and hovering over it show map and next to it says "unknown". If it's not possible to show location with IPv6 then just put an ipv6 icon on the search bar instead of a question mark

**Comment by erosman** [comment]
IPv6 database was added in v2.16 but I couldn't fully test it myself.
If it doesn't show location/flag, possibilities are:
- The IP is not included in the database
- There is an error somewhere


Can you test which some other locations and see if IPv6 flag shows anywhere?

**Comment by erosman** [comment]
I found the problem. Firefox/JavaScript converts large numbers to scientific notation (e.g. 1.2998466340184126e+28)

I am working on it to fix it.

**Comment by Haxorzz** [comment]
Oh that's neat! Actually, now that it's getting patched I have a small request, I still liked knowing that i was connecting via IPv6 with a quick glance, do you by chance think you can add some tiny indicator to show that?

**Comment by erosman** [comment]
First question is where to show it?
Extensions only have address bar icon (where the flag is) & toolbar icon.

**Comment by erosman** [comment]
The issue was addressed in v2,26.

Let me know if there are issues.
