### ISSUE TITLE
[FoxyTab] Custom reload value is interpreted as seconds, not minutes.

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#47]
Whatever is entered in the Custom Reload scroller, is interpreted as being in seconds, not minutes. Luckily, I was able to manually type in `1140` to have a 19-minute reload interval.

**Comment by erosman** [comment]
Ooops.. you are right .. I will fix it in the next update

**Comment by smartadblock** [comment]
Man revalidate our extension

**Comment by ReporterX** [comment]
I prefer seconds though because I want to reload some pages in less than 1 minute, like 10 seconds.

If the unit is second, I can type any value to reload ranging from 1 second to  X minutes.

If it is changed into minute, I can no longer reload in less than 1 min. :-(

Perhaps you could let users select the time unit (second/minute).

**Comment by erosman** [comment]
hm ... in that case, lets have more feedback o the issue.

I can set to minutes and allow fractions e.g. 1.25 or change the wording to set to seconds

**Comment by ReporterX** [comment]
I would suggest changing the wording to seconds. 

Second is a better time unit IMHO.

Imagine if you use minute, 10 second would be 0.1666666.. minute. Kinda clumsy and slightly less accurate.

**Comment by adrianog** [comment]
so this is in seconds, right?

**Comment by erosman** [comment]
> so this is in seconds, right?

It is in minutes

**Comment by adrianog** [comment]
I concur that seconds would have been the best choice.

It doesn't let me go below 6 in the custom field - is that by design?

**Comment by erosman** [comment]
> It doesn't let me go below 6 in the custom field - is that by design?

1-5 minutes are already a built-in.

There is not a lot of demand for second accurate reload as the reloading itself takes a number of seconds to perform.

**Comment by adrianog** [comment]
so no chance to put subminute values for seconds? e.g. 0.1 for 6 seconds

**Comment by erosman** [comment]
If there is a popular demand, I can look into it.

However, 6 second reload is not very practical as it results in continues reload. Many tabs take longer than 6 seconds to load and thus it becomes a loop of half loaded tabs.

**Comment by adrianog** [comment]
10 seconds seems kind of fine though

**Comment by erosman** [comment]
If there is a popular demand, I can look into it.
