### ISSUE TITLE
[FoxyTab] "Unpin All" reverses order of my pinned tabs

### ISSUE THREAD

**Issue by jimjoh** [erosman/support#470]
FoxyTab's "Unpin All" reverses order of my pinned tabs.  So if I have pinned tabs A, B, C when I "Unpin All" I'm left with tabs in this order: C, B, A.  I'd like them to retain their order (A, B, C).

I'm using FoxyTab 2.25 with Firefox 91.8.0esr (64-bit) on CentOS 7.9.2009.

BTW, thanks for making this great extension.

**Comment by erosman** [comment]
That is how the API does it. I will reverse them before unpinning them so they end up in the correct order.

Done in v2.26
