### ISSUE TITLE
[FoxyTab] Reload options don't work with pinned tabs 

### ISSUE THREAD

**Issue by jimjoh** [erosman/support#471]
The reload options (reload all, reload left, etc.) don't work with pinned tabs (i.e. pinned tabs don't reload.)

I'm using FoxyTab 2.25 with Firefox 91.8.0esr (64-bit) on CentOS 7.9.2009.

BTW, thanks for making this great extension.

**Comment by erosman** [comment]
At the moment, the pinned tabs will be actioned if the Modifier Pinned is selected.

**Comment by jimjoh** [comment]
Thanks for the quick replies!  Is the only way to set this option is via the FoxyTab toolbar icon?  I temporarily added it to my toolbar, enabled it and then removed it from my toolbar and it's still working.  It'd be nice to also be able to set this from FoxyTab preferences "Options" page.

**Comment by erosman** [comment]
>  It'd be nice to also be able to set this from FoxyTab preferences "Options" page.

It was intentional so that can be changed quickly so one time with, another time without. Options page is for something that is meant to stay the same.

The setting stays until it is changed. It is semi-permanent.

See Also: FoxyTab Help -> Modifiers
