### ISSUE TITLE
[FireMonkey]Can't really delete the userscript

### ISSUE THREAD

**Issue by ACTCD** [erosman/support#473]
Select a script in the extension, click the delete button, confirm the deletion in the pop-up dialog, ok, it disappears from the list of scripts and styles on the left, refresh the page, it magically comes back, I tried many times, Can't really delete it.

**Comment by erosman** [comment]
You are right. 
Let me see what is going on and fix it.

**Comment by erosman** [comment]
Found it. There is an oversight in changes made in in v2.54
I will release v2.55 with a fix
