### ISSUE TITLE
[FoxyTab] Context Menu - Sorting

### ISSUE THREAD

**Issue by merlin555** [erosman/support#478]
Hi,

In the "Context Menu" in the new version, sorting no longer works as before.
With the arrows on the far right, I can only sort individuals and not entire groups as before.

Thanks !

Greetings..

 Merlin

**Comment by erosman** [comment]
Do you mean the in the Options page -> Context Menu?

I am planning to work on that once there are no more issue/bugs.

**Comment by merlin555** [comment]
Yes, exactly.

Before, you could mark it as a group and not just single.

**Comment by erosman** [comment]
Previously: #458

**Comment by erosman** [comment]
Done for v2.29

**Comment by merlin555** [comment]
Great !!
I tried to move them all one by one yesterday.
Only then did I realize that this would go on for far too long.

When is v2.29 coming out?

Thanks..

**Comment by erosman** [comment]
I am still working on it. Mozilla wont review recommended addons on the weekend anyway.

**Comment by merlin555** [comment]
Ok, thanks for the very quick reply.
That's real support !!

**Comment by merlin555** [comment]
Thank you for the update.
Now I'm very happy with it!
Even one can move more than one group together.

A nasty bug has just crept in since more functions have been added to the "context menu".
An "older" settings backup no longer works properly when importing.
Because the new features that have been added will never be released.
You never see the new functions in the context menu and don't even know that they are there.
Factory setting has no effect on it.
Nothing is reset there.

Just deleting and reinstalling the add-on does the trick.
Then reset everything and then export the settings!
When "importing" something very important must be considered.
That's how it is with me.
Each menu in the settings, one should import one by one and then press the "Save" button,
otherwise the settings will not be imported correctly.
Example:
1. go to settings
2. Menu, select "Context menu".
3. Go back to the leftmost menu (Options)
4. "Import" settings
5. Back to the "Context Menu" and only now press "Save".

Export the settings at the very end.

I hope this can be fixed somehow.
It's possible that I'm not quite right with the "example".

Greetings..

 Merlin

**Comment by erosman** [comment]
Since version 2.16, there has been a conceptual change in the way **SAVE** works.

Up to 2.15, there was only one SAVE and clicking it saved the entire data.
Since 2.16, each section has its own SAVE which improves the performance as there are many checks in each section and some require the data to be built before saving.

Side-effect of above is that when importing, the SAVE in the Options only saves the Options, and not other sections. Their SAVE have to be clicked one by one as well (or ignored if desired in some cases).

I can makes changes based on popular demand though.

**Comment by merlin555** [comment]
Thanks for the precise explanation.
I have now also imported the settings to my Ubuntu system.
Works so well !
