### ISSUE TITLE
[FireMonkey] Delete button does nothing.

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#48]
I added a script, then could not delete it. Unless I misunderstand the purpose of that "Trash can" button.

**Comment by erosman** [comment]
Oh.. there seems to be an error.. I will fix it and upload an upgrade

**Comment by rubaboo** [comment]
Speedy! I'll make sure to leave a 5-star review on mozilla.org, to help the adoption. I like the idea of combining user CSS and JS in the same add-on, and UI style and documentation of your add-ons are great.

**Comment by erosman** [comment]
Thank you for your kind comment. :)

**Comment by erosman** [comment]
v1.5 uploaded
