### ISSUE TITLE
[FoxyTab] Tab Numbers Greater than 999 Show Incorrectly

### ISSUE THREAD

**Issue by megamorphg** [erosman/support#486]
When the tab number is 1000 or greater, only the last 3 characters are displayed. For example, I have 1108 tabs open:
![image](https://user-images.githubusercontent.com/1782353/171473912-9b8b014d-2f6d-4d0a-9f5d-6f427216c743.png)

**Comment by erosman** [comment]
Unfortunately, that is due to Firefox design.

Previously: #366
