### ISSUE TITLE
"fetch is read only"

### ISSUE THREAD

**Issue by privacyguy123** [erosman/support#488]
https://github.com/pixeltris/TwitchAdSolutions/raw/master/vaft/vaft.user.js

Works on ViolentMonkey - not sure how to fix or why I would use FireMonkey with these issues in the first place?

**Comment by erosman** [comment]
The userscript is too large for me to debug. If the developer points out the issue, I can work on it.

**Comment by privacyguy123** [comment]
The only ouput FireMonkey gives is "fetch is read only" or something along those lines.

**Comment by erosman** [comment]
The userscript is trying to re-write `fetch` function.

Since it works in VM and VM by default injects into `page` context, try adding the fowllowing to the **User Metadata**

```
@inject-into        page
