### ISSUE TITLE
[FoxyTab] keyboard shortcuts not working for all actions

### ISSUE THREAD

**Issue by xim** [erosman/support#489]
I'm trying to bind the `Host Close` action to `Ctrl+Alt+W` and it isn't working.

If I bind a different action, e.g. `Print`, using the same keys, it works.

FF 100 on Linux (Debian Bookworm)

**Comment by erosman** [comment]
I am traveling and not at my usual set-up.

Does any other keyword combination work or `Host Close` doesn't work with keyboard shortcuts?

**Comment by xim** [comment]
The latter. Haven't tried many different options, but `Host Close` doesn't work with any combinations while `Print` worked with the first shortcut I tried.

**Comment by erosman** [comment]
You are right.. there is a bug. Fixed for v2.38

**Comment by xim** [comment]
Is there an ETA on the next release? I can still only see 2.29 on addons.mozilla.org...

**Comment by erosman** [comment]
I have been working on another addon. I will try to update v2.30 (ps. 2.38 was wrong)

**Comment by erosman** [comment]
v2.30 uploaded and will become available once it is reviewed by the Mozilla team.
