### ISSUE TITLE
[FoxyTab] v2.29 Spelling error on the Context Menu option settings

### ISSUE THREAD

**Issue by David-Maisonave** [erosman/support#492]
There's a spelling error on the Context Menu option settings.
It has **reprder** instead of **reorder**.

<img width="245" alt="FoxyTab spell error" src="https://user-images.githubusercontent.com/47364845/177237525-ea6ebff9-aa4b-4549-a0aa-581dd57b9d26.png">

**Comment by erosman** [comment]
Oops .... Thank you.
Fixed for v2.30
