### ISSUE TITLE
[Firemonkey] installing direct from Github

### ISSUE THREAD

**Issue by privacyguy123** [erosman/support#496]
Getting error "Missing host permission for the tab" - can't seem to find a way to grant this permission.

**Comment by erosman** [comment]
Can you give me an example to test?

**Comment by oczkoisse** [comment]
I'm getting the same error, here's an example link: https://raw.githubusercontent.com/dracula/duckduckgo/master/monkeyscript.user.js

**Comment by erosman** [comment]
Thank you. Let find out the reason.

**Comment by erosman** [comment]
Oops.. found it... fixed for v2.60
I will release it today.

**Comment by oczkoisse** [comment]
Thanks for the quick fix!

**Comment by erosman** [comment]
v2.60 is online
