### ISSUE TITLE
[FoxyTab] Country flag image distorted

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#50]
Checked with Browser Toolbox, the image is 100x50, but in the address bar it's rendered as a square and doesn't look good:

![Screenshot_2019-03-17_03-26-01](https://user-images.githubusercontent.com/212368/54488986-e789ad80-4864-11e9-9571-78ffb67c418b.png)

**Comment by erosman** [comment]
Sadly, the PageAction API reshapes the images to 16x16
Alternative option is to create flags that are 16x16 but with white bars above and under it which has its own complications.

**Comment by rubaboo** [comment]
Someone already created them. [This](https://www.flag-sprites.com/) looks good:

![image](https://user-images.githubusercontent.com/212368/54495718-9fd64680-48a3-11e9-92b3-6f0545a50fc2.png)

Would you really need white bars rather than just centering an image on a transparent background?

**Comment by erosman** [comment]
let me try and see what happens ........

**Comment by erosman** [comment]
The site only has sprites (not individual flags) and I haven't found good ones yet otherwise I will consider it for the next release v2.16.
