### ISSUE TITLE
[FireMonkey] 4chan-x help?

### ISSUE THREAD

**Issue by an1ki** [erosman/support#507]
Hello, apologies if this is the wrong place to post this.

I'm no expert in programming/userscript writing so a lot of the "Help" page is overly-technical jargon.

I am having trouble getting [4chan X](https://github.com/ccd0/4chan-x) to work with Firefox and the latest version of FireMonkey. My 4chan X settings are not being saved upon reopening 4chan(nel). I saw issue #408 and read through it, but don't see `@grant` or `@disable-synchGM` under User Metadata.

additionally, how would I get this script to run automatically rather than needing to manually go in and click "run" each time the page loads?

thanks for any help.

**Comment by erosman** [comment]
> Hello, apologies if this is the wrong place to post this.

Hi. This is the right place. You can also post to #429

> I saw issue https://github.com/erosman/support/issues/408 and read through it, but don't see @grant or `@disable-synchGM` under User Metadata.

`@disable-synchGM` was later removed in v2.42 as its function was automatically applied.


> how would I get this script to run automatically rather than needing to manually go in and click "run" each time the page loads?

If a userscript is enabled it should run every time you go to the page.
The RUN function is for running a userscript that is not enabled, or to re-run it.

Let me ask other users and see if they are having issues with it.

**Comment by an1ki** [comment]
I see. The script does not run automatically for me (despite it saying "enabled" in Scripts & CSS > [JS] 4chan X). I did not do any configuration other than installing FM and the script.

**Comment by erosman** [comment]
Try this.....

- Go to https://www.4chan.org/
- FireMonkey should show that the userscript is active
![image](https://user-images.githubusercontent.com/6458876/192465007-5d85fcab-117e-4aad-bb91-14cba93b2b8c.png)
- Open Developer tool (F12)
- Go to Debugger Tab
- If you don't see `user-script://` refresh the page (F5)
- You should see something like this
![image](https://user-images.githubusercontent.com/6458876/192465683-ab7c5fbd-1771-44f3-aca6-f4549121c12d.png)

Above shows that script is injected.

If the userscript does not seem to run.

### Actually, I found an error .... in Browser Console.
![image](https://user-images.githubusercontent.com/6458876/192466464-9c309b91-6aff-437d-9dd8-5c02e7ef3896.png)

I have posted [Update API type verification in userscript](https://github.com/ccd0/4chan-x/issues/3300).

**Comment by erosman** [comment]
For the time being, try removing these line from the userscript and see:

lines 102-107
```
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.deleteValue
// @grant        GM.listValues
// @grant        GM.openInTab
// @grant        GM.xmlHttpRequest
```

**Comment by g-2-s** [comment]
> **Test 2:** Remove lines 102-107 (keep line 99)
> 
> ```
> // @grant        GM.getValue
> // @grant        GM.setValue
> // @grant        GM.deleteValue
> // @grant        GM.listValues
> // @grant        GM.openInTab
> // @grant        GM.xmlHttpRequest

Doing this seems to make the script work.

**Comment by erosman** [comment]
**Test 3:**

Change line 5550:

```js
if (typeof GM_setValue !== "undefined" && typeof GM_addValueChangeListener !== "undefined" && GM_addValueChangeListener !== null) {
  $.setValue = GM_setValue;
  $.deleteValue = GM_deleteValue;
} 
```

**Comment by g-2-s** [comment]
> **Test 3:**
> 
> Change line 5549 (keep metadata block as original)
> 
> ```js
> if (typeof GM_setValue !== "undefined" && typeof GM_addValueChangeListener !== "undefined" && GM_addValueChangeListener !== null) {
>   $.setValue = GM_setValue;
>   $.deleteValue = GM_deleteValue;
> } 
> ```

This works great and it feels like the userscript runs better than the Test 2 solution.
Only "drawback" with this solution is that if you nuke/sanitize your Firefox data on close the userscript doesn't remember your settings and you have to import or set them again. Also this differentiates between 4chan and 4channel so when importing your settings file, you have to do it on both sites.
Thanks [erosman](https://github.com/erosman) by the way!

**Comment by erosman** [comment]
> I have posted [Update API type verification in userscript](https://github.com/ccd0/4chan-x/issues/3300).

Hopefully they will update the script.

I remember we had a mod script in YaBB & phpBB long time. I might be able to create a process  to make changes to the script but that is fair amount of work and depends on how popular the feature would be.

There is also MV3 (manifest v3) coming up which will change the way userscripting work. The code might have to be altered for MV3.

**Comment by an1ki** [comment]
I apologize for the delayed response.

I did the changes you suggested in Test 2. I am not doing Test 3's changes, as I reset FF's data upon restart which would facilitate my settings-being-reset issue.

The script now runs automatically and remembers settings through restarts. Thank you so much, you have been more than helpful and incredibly punctual.

**Comment by tomato-paste** [comment]
> **Test 2:**
> Remove lines 102-107 (keep line 99)

I had to do this to make the script work.

If GM_* works just fine, wouldn't prioritising GM_* in 4chan X code make it work? FM disables GM_* when GM.* is supported, so I can't try it out.

**Comment by erosman** [comment]
The main issue of the old (pre-Firefox 57) GM3 type API is the sync storage API .e.g. `GM_getValue`, `GM_setValue`, `GM_deleteValue`, `GM_listValues`.

Strangely, the script uses `GM_addValueChangeListener` as a test for the above.

```js
    }
    if (typeof GM_addValueChangeListener !== "undefined" && GM_addValueChangeListener !== null) {
      $.setValue = GM_setValue;
      $.deleteValue = GM_deleteValue;
    }
```


> If GM_* works just fine, wouldn't prioritising GM_* in 4chan X code make it work? FM disables GM_* when GM.* is supported, so I can't try it out.

GM_* is supported but the support has drawbacks and it is not 100%.
On the other hand, GM.* is fully supported.

> FM disables GM_* when GM.* is supported, so I can't try it out.

You can test  by removing GM.* from the metadata block.

**Comment by tomato-paste** [comment]
> The main issue of the old (pre-Firefox 57) GM3 type API is the sync storage API .e.g. `GM_getValue`, `GM_setValue`, `GM_deleteValue`, `GM_listValues`.

Actually, I don't think the code should resort to those in the first place. L5433:
`if (((typeof GM !== "undefined" && GM !== null ? GM.deleteValue : void 0) !== null) && window.BroadcastChannel && (typeof GM_addValueChangeListener === "undefined" || GM_addValueChangeListener === null)) {`
The code attempts to use the GM.* API first. Do you have any idea what is `window.BroadcastChannel`? It probably checks for support of the [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API), but I don't know if that is the correct way.

**Comment by erosman** [comment]
> Do you have any idea what is `window.BroadcastChannel`?

Sorry, I don't. It might be something that is defined in the webpage.

> Also, the FM editor says that the BroadcastChannel() constructor is undefined. (I'm not on an old FF version.)

My guess is that it is related to the webpage.

GM|TM|CM use `content` context which has the same `window` as the webpage, while FM uses the isolated `userScript` context.

You can try:
```js
window.BroadcastChannel = unsafeWindow.BroadcastChannel;
```

**Comment by tomato-paste** [comment]
I also forgot to mention, the actual code uses `!=` for comparison.  I changed that to `!==`, didn't fix it.

> > Do you have any idea what is `window.BroadcastChannel`?
> 
> Sorry, I don't. It might be something that is defined in the webpage.
> 
> > Also, the FM editor says that the BroadcastChannel() constructor is undefined. (I'm not on an old FF version.)
> 
> My guess is that it is related to the webpage.
> 
> GM|TM|CM use `content` context which has the same `window` as the webpage, while FM uses the isolated `userScript` context.
> 
> You can try:
> 
> ```js
> window.BroadcastChannel = unsafeWindow.BroadcastChannel;
> ```

That didn't work. The Mozilla page says that this API is for [workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), I don't know what that is.

**Comment by erosman** [comment]
TBH, it is way too large to try and debug. The userscript developer is more familiar with the userscript code.

**Comment by tomato-paste** [comment]
> TBH, it is way too large to try and debug. The userscript developer is more familiar with the userscript code.

Thanks, I'll try asking in the 4chan X issue tracker tommorow.

**Comment by tomato-paste** [comment]
I figured it out. Although FM disables GM_*, it keeps GM_addValueChangeListener enabled. The code prefers using GM_addValueChangeListener when it's enabled, so it fallbacks to GM_*. (details: https://github.com/ccd0/4chan-x/issues/1534 https://github.com/Tampermonkey/tampermonkey/issues/459)

`if (((typeof GM !== "undefined" && GM !== null ? GM.deleteValue : void 0) !== null) && window.BroadcastChannel) {` works.
But it is extremely slow, it takes around 5-10 seconds for the script to load when it should be instant.

What would be the best solution for this?

**Comment by erosman** [comment]
> Although FM disables GM_*, it keeps GM_addValueChangeListener enabled. 

The reason is that the main difference is in the storage API and there is no difference between `GM_addValueChangeListener` & `GM.addValueChangeListener`.

As I mentioned earlier: "Strangely, the script uses `GM_addValueChangeListener` as a test for the above."

> But it is extremely slow, it takes around 5-10 seconds for the script to load when it should be instant.

The change of the argument in the conditional makes no difference in execution speed. The result of the conditional however, depends on how the code handles it.

`new BroadcastChannel()` might not work in `userScripts` context.
You can try adding the following to the top of the userscript and see if that helps.
```js
BroadcastChannel = window.BroadcastChannel;
```
or...
```js
BroadcastChannel = unsafeWindow.BroadcastChannel;
```

**Comment by tomato-paste** [comment]
> The reason is that the main difference is in the storage API and there is no difference between `GM_addValueChangeListener` & `GM.addValueChangeListener`.
> 
> As I mentioned earlier: "Strangely, the script uses `GM_addValueChangeListener` as a test for the above."

The code resorts to using Broadcast Channel when `GM.*` is supported but `GM_addValueChangeListener` isn't supported. The code assumes `GM_*` is supported when `GM_addValueChangeListener` is supported.

I assume this is because GreaseMonkey removed `addValueChangeListener`, so Broadcast Channel is used as a substitute. Reference: https://github.com/ccd0/4chan-x/commit/8bc6fe1ed3aa8d7418b8efb4cbac5367afc940d7

> The change of the argument in the conditional makes no difference in execution speed. The result of the conditional however, depends on how the code handles it.

I know, I meant that the `GM.*` code was really slow.

> `new BroadcastChannel()` might not work in `userScripts` context. You can try the following and see if that helps.

I don't see any errors about `BroadcastChannel` being undefined in Ctrl+Shift+J, and adding `window.` or `unsafeWindow.` doesn't make a difference.

**Comment by erosman** [comment]
> I meant that the GM.* code was really slow.

It is true that the GM_* storage API is async and slower than the sync GM_* storage API, however the difference should in milliseconds.

```js
(async() => {
  let t;
  const n = 10;

  t = performance.now();
  for (let i = 0; i < n; i++) {
    await browser.storage.local.get('_0 API');
  }
  console.log(`Operation took ${performance.now() - t} milliseconds`); // 4 millisecond
})();
```

It uses a loop to get/set values and I don't know how many get/set are done in that loop.
FireMonkey supports multiple get/set but other userscript managers don't.

Did you try removing the GM_* from the metadata block to force the sync GM_*?

**Comment by tomato-paste** [comment]
> Did you try removing the GM_* from the metadata block to force the sync GM_*?

Yes, the script runs completely fine when I do that.
