### ISSUE TITLE
Thread got hijacked. Feel free to close. I'm satisfied with your response. Unsubscribing.

### ISSUE THREAD

**Issue by rubaboo** [erosman/support#51]
Example mock-up for "the tab is being reloaded every 4 min":

![Screenshot_2019-03-17_03-46-58-check](https://user-images.githubusercontent.com/212368/54489409-2ae61b00-4869-11e9-996e-a9b729b986b1.png)

The emphasis is on "auto reload is currently active", not "it was set to 4 min a while ago, but we don't know if the reload is still happening :(" (Not saying that this really happens, I don't know.)

Ability to set Custom Reload time per tab would be nice as well, but I'll understand if you think that's too much.

**Comment by erosman** [comment]
I had thought about it. It requires a fair amount of extra code and event listeners and the API to change the context menu before it appears was not originally available so it was not possible to do back then.

I will look into it...

**Comment by smartadblock** [comment]
man why have you disabled my firefox extension?

**Comment by erosman** [comment]
> man why have you disabled my firefox extension?
@smartadblock It is not disabled. It is in the queue to be reviewed. You can reply to the email that you received and someone will be looking into it.
If you wish to discuss the issues further, you can reach admin reviewers on IRC #addon-reviewers on irc://mozilla.org/

**Comment by smartadblock** [comment]
no i cant reply to the email when the version changes the mails bounce

went to irc no one is answering

according to the reviewer guideline a requestinfo was the right course of action in this case of jquery version change.

Have you escalated the issue too? the automatic validation should have put it back. it is now in the queue for the week end you are literally ruining our work.

**Comment by erosman** [comment]
> Have you escalated the issue too? the automatic validation should have put it back. it is now in the queue for the week end you are literally ruining our work.

Only admin reviewers can do that (I am not an admin)

**Comment by smartadblock** [comment]
why not simply requested us to change the jquery version how could this be a valid reason for full rejection??? the reviewer policy actually states that it is a case of info request.

**Comment by smartadblock** [comment]
no the emails are no longer delivered when version changes. Why dont you just go and revalidate it now??? Or get in touch with someone who can validate it??? Why did you do this honestly?!!

**Comment by erosman** [comment]
> why not simply requested us to change the jquery version how could this be a valid reason for full rejection??? the reviewer policy actually states that it is a case of info request.

That is not correct. We require bit-identical copy of libraries. The included version did not match the SHA256 of the original and that was the reason for rejection.

[Add-on Policies](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy/Reviews)

> Only release versions of third-party libraries and/or frameworks may be included with an add-on. Modifications to these libraries/frameworks are not permitted.
> Please read our third party library guidelines to avoid unexpected rejections.

> no the emails are no longer delivered when version changes. Why dont you just go and revalidate it now??? Or get in touch with someone who can validate it??? Why did you do this honestly?!!

I have not done anything to the addon, as mentioned before. Only admin can make changes to the queue system.
Sending an email does not depend on the version. There may be some other issues if they are not getting through but again only admin can check it.

Please do not post to the addon support topic. This is not the place for this discussion.

**Comment by smartadblock** [comment]
You are lying the second rejection was about bit identical matching the first rejection was about the use of jquery 2.0 . Why would you that? And why would you lie about it????

**Comment by smartadblock** [comment]
Email when you try to reply to rejection:

Hello,

An email was received, apparently from you. Unfortunately we couldn't process it because of:
You can&#39;t reply to this email as the reply token is no longervalid because it&#39;s for an old version of the addon.

Please visit https://addons.mozilla.org to leave a reply instead.

**Comment by erosman** [comment]
Email when you try to reply to rejection:

> Hello,
> 
> An email was received, apparently from you. Unfortunately we couldn't process it because of:
> You can't reply to this email as the reply token is no longervalid because it's for an old version of the addon.
> 
> Please visit https://addons.mozilla.org to leave a reply instead.

Your Email (_Erosman who is a simple developer..._) has been received and will be handled by the admin.

**Comment by smartadblock** [comment]
oh you find that offensive? you have put our extension offline for almost a day now without a valid reason maybe you should be removed from the add on review program.

**Comment by erosman** [comment]
>  you have put our extension offline for almost a day now without a valid reason 

As I said before, I did not put your extension offline. Please do not post here again. You should contact the admin reviewers to discuss your views.

**Comment by smartadblock** [comment]
you have put our extension offline go have a look. You have no clue about how the reviewer dashboard works if you think you did not put it offline!

**Comment by smartadblock** [comment]
how about you simply send me an email and we ll discuss it there. I post here because there is no way to reach you. you should not be reviewing extensions my dude

**Comment by smartadblock** [comment]
Just chatted on IRC with admins and they say you could put it back ? Why dont you put it back ?
