### ISSUE TITLE
[FireMonkey] (Feature Request) Option to opt into  @requireRemote

### ISSUE THREAD

**Issue by lI-guy-Il** [erosman/support#515]
It'd be nice if you could force @requireRemote instead, so that we don't need to rely on your versions of scripts.

in app.js:

```
...
case 'requireRemote': prop = 'requireRemote'; break;
...    
```

That would do the trick.

**Comment by erosman** [comment]
Can you explain the purpose & reason?

**Comment by lI-guy-Il** [comment]
To not need to rely on your versions of scripts.

**Comment by erosman** [comment]
What do you mean by "your versions of scripts"? 
Do you mean JQuery, Bootstrap, etc?
If so, they are the standard libraries.

**Comment by lI-guy-Il** [comment]
Yes, what if I want to use an updated version manually?

**Comment by erosman** [comment]
You can use a hosted location that is not among these:

```
ajax.aspnetcdn.com
ajax.googleapis.com
apps.bdimg.com
cdn.bootcdn.net
cdn.bootcss.com
cdn.jsdelivr.net
cdn.staticfile.org
cdnjs.cloudflare.com
code.jquery.com
lf*-cdn-tos.bytecdntp.com
lib.baomitu.com
libs.baidu.com
pagecdn.io
unpkg.com
```

**Comment by erosman** [comment]
v2.68
Removed Bundled Libraries feature (#539)

Therefore, all libraries will be remote.
