### ISSUE TITLE
[IMGoogle] Support link (Firefox AddOns > Options > Help > Support) points to Discourse thread

### ISSUE THREAD

**Issue by Crul** [erosman/support#520]
Not sure if this is intentded or an error.

The addon stopped working and [I posted a message on the thread](https://discourse.mozilla.org/t/support-igoogle/12480/31?u=crul) that was [linked on the Options > Help > Support section](https://i.imgur.com/tjxTAFj.png). The [answer there was lightning-speed-fast, and I got redirected here](https://discourse.mozilla.org/t/support-igoogle/12480/32?u=crul).

So, maybe you want to consider changing the Support link to point here?
Thanks

**Comment by erosman** [comment]
Thank you. That was the Help back in 2018 when v2.5 was released. I have already changed that in v2.6.
