### ISSUE TITLE
[FoxyTab] create shortcut now save full web page instead

### ISSUE THREAD

**Issue by foxfoxgo** [erosman/support#521]
Hello,

For a few days now every time I want to keep a shortcut to a web page foxytab save the entire html page.

Thank you

foxytab 2.3/firefox 98/win 7

**Comment by erosman** [comment]
I tried now on Nightly 109, Ubuntu, FoxyTab 2.30, and it created a shortcut.

What is the size of the file created? It should be about 100-150 bytes whereas a saved webpage would be 100+KB.

Can anybody else verify?

**Comment by foxfoxgo** [comment]
> What is the size of the file created? It should be about 100-150 bytes whereas a saved webpage would be 100+KB.

It's a full webpage, saved as single .html file. When I click createshortcut it opens the "save as" dialog window.

I uninstalled foxytab/reboot firefox/reinstalled, no change!

**Comment by erosman** [comment]
> foxytab 2.3/firefox 98/win 7

Is that 2.3 or 2.30?

**Comment by foxfoxgo** [comment]
> Is that 2.3 or 2.30?
 2.30
 
> The shortcut is an HTML file, but a small one.
ok! sorry I didn't noticed, I was opening the file without line wrap option.

But I'm pretty sure it was an [internetshortcut] .url file in previous versions with the small arrow on the bottom left to differentiate it from a webpage. Is it possible to revert to old behaviour?

My problem was elsewhere in fact, Firefox don't want to open these shortcuts but it's because I'm using different portable versions with -no-remote option that is not compatible with sending a link to such an instance of FF!!

**Comment by erosman** [comment]
> But I'm pretty sure it was an [internetshortcut] .url file in previous versions with the small arrow on the bottom left to differentiate it from a webpage. Is it possible to revert to old behaviour?

It was... but the new HTML shortcut is supported by ALL OS so it is the modern way of creating a shortcut as is mentioned in the About & Help.

**Comment by foxfoxgo** [comment]
ok, 
thank you.
