### ISSUE TITLE
[FireMonkey] [Question] How to use with libredirect

### ISSUE THREAD

**Issue by linsui** [erosman/support#522]
I'm using https://github.com/libredirect/libredirect which redirects site to alternative frontend rendomly. I want to use FireMonkey on these sites. Do I have to update the site list manully? Is there anyway to do that automatically? The domain list can be fetched from https://github.com/libredirect/libredirect/blob/master/src/instances/data.json. Is it the good to match all sites and check the domain dynamically? Thanks!

**Comment by erosman** [comment]
Is there a userscript version?

**Comment by erosman** [comment]
There is no easy way to do it within the available features of userscript managers.

The hard way could be:
- Write a script with a `@match *://*/*`
- Add `urlList` from [data.json](https://github.com/libredirect/libredirect/blob/master/src/instances/data.json) e.g. in an array
- Add a test in the script for the URL
- Run function if URL matches

Then inside the script ....
- Periodically, fetch [data.json](https://github.com/libredirect/libredirect/blob/master/src/instances/data.json) and update `urlList`

**Comment by linsui** [comment]
Thanks! It's a little hard, I'll have a try. Maybe I can also update the script with other script and host it on a local webserver so that I can use auto update function. Maybe this function can be added to FireMonkey which can generate a user script with an update script. Not sure if it's a good idea.

**Comment by erosman** [comment]
It is possible to add a feature but that depends on how popular it would be.

Due to changes in MV3, many processes in userscript managers have to be re-written. I am waiting for the finalisation of MV3 userscript support before making any major changes.

**Comment by linsui** [comment]
Then I'll keep this issue open. If you thought it's not likely be added just close it. Thanks!

**Comment by erosman** [comment]
GM getResourceText has been updated in FireMonkey v2.68.

> [getResourceText](https://erosman.github.io/support/content/help.html#getResourceText)
> 
> If Metadata Block contains `@resource` and `GM_getResourceText/GM.getResourceText`, text `@resource` targets (not images) are fetched at the registration time and cached. Consequently, the latest version of the file will always be fetched. (v2.68)

It means that every time the browser starts, or the userscript is enabled, the latest version of the `resource` will be fetched. Browser checks for `Last-Modified `response HTTP header and gets the new version if the file has changed, or use the cached version.

This way, a remote config file can be set as a `@resource`.
