### ISSUE TITLE
Add License metadata field?

### ISSUE THREAD

**Issue by Baerbeisser** [erosman/support#524]
Like `@license     WTFPLV2`.

If so, you maybe want to parse the [SPDX license list](https://github.com/spdx/license-list-XML).

My motivation is, that users should know how they are allowed to use the script. And some userscripts and userstyles already have that field.

**Comment by Baerbeisser** [comment]
Userstyles often have it and Stylus supports it. Found it on [some](https://openuserjs.org/scripts/Bloggerpemula/Bypass_All_Shortlinks_Manual_Captcha/source) userscripts too.

Extensions which do not support it, ignore it, since it's a comment. Should not be an issue.

**Comment by erosman** [comment]
Having any `@entry` does not cause any issues in FireMonkey. They are ignored if not supported.

It is not a problem to add it to the info display, if there are:
- A popular demand for it
- Enough number of userscripts/userStyles that are using it

**Comment by Baerbeisser** [comment]
> A popular demand for it

How do you confirm that, with a poll?

**Comment by erosman** [comment]
> How do you confirm that, with a poll?

Let's see how many people would comment about it here.

**Comment by erosman** [comment]
I have been thinking about `@license`.

Users can check the userScript to see the `@license`.

Processing it, adds an extra field to the data storage while it is only useful when looking at the info page, which is similar to looking at the userscript.

TBH, the license should be checked by the user when installing and/or editing a userscript. At that time, it is visible in the metadata block.

**Comment by Baerbeisser** [comment]
Alright, but why then have the info page? For better visibility, right?

**Comment by erosman** [comment]
Info page is there for a quick reference.
It displays the data that is already parsed, extracted & saved to the storage.

ATM, `@license` is not processed. Processing it and saving it to the storage as a separate field is easy enough, but increases the storage size (tiny amount though).
If it is something that is necessary, then it will be added.
Otherwise, it would depend on how much demand there is for it.

**Comment by erosman** [comment]
v2.68
Added <code>licence</code> to popup Info page (if available)

**Comment by Baerbeisser** [comment]
Thanks for reconsidering.
