### ISSUE TITLE
[FoxyTab] Context menu not appearing

### ISSUE THREAD

**Issue by cl0udrecesses** [erosman/support#527]
the foxytab options are not showing up in my context menu in firefox, even after disabling and then enabling the extension

**Comment by erosman** [comment]
FoxyTab context-menu appears when you right-click on the tab strip on top (not on the page).

![image](https://user-images.githubusercontent.com/6458876/209911971-0b3dacc6-5a81-4b1b-96a0-0a5a724e4cbd.png)

**Comment by cl0udrecesses** [comment]
Got it ! thanks (i feel like a clown sry)
