### ISSUE TITLE
IPV6 country flag not correct

### ISSUE THREAD

**Issue by rubahness** [erosman/support#528]
Hi, I noticed that the country flag for a server I know for a fact to be located in the US is showing up as Russian Federation. Unzipping the extension (December 28 version) and looking at the ipv6 tables, the server should match under 42540578182550394399257000965153226752us, and presumably display US flag. Is this the JavaScript sci notation bug again or maybe off by 1 error?

**Comment by erosman** [comment]
FoxyTab 2.30 IP database is dated 29-Sep-2022 (latest is 29-Dec-2022).

It could be that IP tables have changed. It could also be a processing bug.

What does [IP Address Geolocation Lookup Demo - IP2Location](https://www.ip2location.com/demo) show?

**Comment by rubahness** [comment]
It shows US for the ipv6.

**Comment by erosman** [comment]
I will update the database (in new release 2.31) and see if that works out. Otherwise, I have to check if there is a bug.

Alternatively, if you post post the IPV6 value, I can test it out.

**Comment by rubahness** [comment]
2001:470:382a:0:7eef:7eef:7eef:7eef

**Comment by erosman** [comment]
Thank you. It is a bug. I will fix it.

**Comment by erosman** [comment]
Fixed for v2.31

**Comment by erosman** [comment]
FoxyTab 2.31 uploaded and will be available once it is reviewed by the AMO review team.

Please let me know of there are any issues.
