### ISSUE TITLE
[Bug] Script disappears if I disable FireMonkey

### ISSUE THREAD

**Issue by i2324561w2** [erosman/support#529]
I installed https://greasyfork.org/en/scripts/423918-affinity-to-you, I saw it installed on the addon manager, I temporarily disabled FireMonkey, re-enabled it: the script was deleted.

Also since this is my first time using scripts: since I don't want the Autoupdate, can I be notified about scripts updates?

Thank you for the attention.

**Comment by erosman** [comment]
By install, do you mean clicking the button on greasyfork?

> Also since this is my first time using scripts: since I don't want the Autoupdate, can I be notified about scripts updates?

Currently, there is no process to check for updates without updating.

**Comment by i2324561w2** [comment]
> By install, do you mean clicking the button on greasyfork?

Yes, and after clicking "Install this script", click on "(I already have a user script manager, let me install it!)".

**Comment by erosman** [comment]
After the installation, when you go to the options page, does it show the script?

**Comment by i2324561w2** [comment]
> After the installation, when you go to the options page, does it show the script?

Yes.

Ok, I think I found the culprit: disabling "Enable Storage Sync" (in Firefox Sync I only have Tabs) makes it work.
Also before disabling it I had in Log "QuotaExceededError: storage.sync API call exceeded its quota limitations": maybe this warning could be changed if one doesn't have Firefox Sync enabled (required to synchronize the addon).

Where the scripts should be stored on Windows?

**Comment by erosman** [comment]
As mentioned in the FireMonkey Help, the sync option is not suitable for userscripts. It was only added on request.

Firefox sync is limited to 100kb and it fails when trying to sync larger data.

In both sync & normal, data is saved within Firefox (not windows). However, sync has a limit. Firefox periodically sends the sync data to other devices that are synced (requires login).

**Comment by i2324561w2** [comment]
The script in OP (the only script I have installed right now) weighs way less than 100kb, so I suggested maybe the "QuotaExceededError" warning could be changed if it detects Firefox Sync is disabled. By the way I'm not interested in this sync, it was just my 2 cents.

"Where the scripts should be stored on Windows?" My question here was unrelated to the synching, is there a folder on which the scripts are saved?
Thank you.

**Comment by erosman** [comment]
> "QuotaExceededError" warning could be changed if it detects Firefox Sync is disabled. 

The error is generated by Firefox, not FireMonkey.
100K is the overall limit. There is an 8k limit for each entry.

> "Where the scripts should be stored on Windows?" My question here was unrelated to the synching, is there a folder on which the scripts are saved?

No. Extension storage data is saved within Firefox in a database.

Go to 
about:profiles -> Root Directory -> Open Directory -> /storage/default
