### ISSUE TITLE
Copy plaintext shortcut?

### ISSUE THREAD

**Issue by TomTrottier** [erosman/support#530]
What ARE/IS the shortcut keys for Copy Plaintext?

**Comment by erosman** [comment]
As per included Help

> Preferred Keyboard Shortcut can be set (defaults to **F7**).

Also...


>     Manage extension shortcuts in Firefox
> 
>     You can now change your extensions' keyboard shortcuts on the add-ons page.
> 
>         Click the menu button ☰;, click Add-ons and Themes and select Extensions.
>         Click the Tools for all add-ons cogwheel.
>         Click Manage Extension Shortcuts in the menu.
>         You will see the shortcut options (if available) for your installed add-ons.
> 
>    [Manage extension shortcuts in Firefox](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)
