### ISSUE TITLE
Keyboard Shortcut Saves as PDF Twice

### ISSUE THREAD

**Issue by dstark** [erosman/support#533]
When using a keyboard shortcut to do the "Save Tab as PDF" action, the save process is done twice. It doesn't seem to matter what shortcut is assigned to the action. Any keyboard shortcut produces two save dialog boxes and, if saved with different names, two files.

"Save Tab as PDF" from the context menu saves the page as a PDF only once as expected.

This is with Firefox 109.0 and FoxyTab 2.30 on Windows 10.

**Comment by erosman** [comment]
I will test it out. 

Is it possible that the keys are held for too long and the action repeats?

**Comment by dstark** [comment]
@erosman, it may be. But I don't usually have difficulty triggering an action twice when holding down keys for shortcuts. And even trying to press the combination and release as fast as I possibly can, I still get the doubled saving behavior. Thanks so much for having a look!

**Comment by erosman** [comment]
Which key combination have you set for it?

**Comment by dstark** [comment]
How bizarre. I tried that yesterday, as well as a few other combinations. Today, when I try both that and other combinations, the tab only saves once as expected for me also.

So, my apologies for what seems to have been a temporary glitch on my side.

Thanks so much!
