### ISSUE TITLE
[FoxyTab] Feature Request - Close Tabs to the Right

### ISSUE THREAD

**Issue by CakeOD36** [erosman/support#54]
The move/copy/bookmark/reload tab features include options for at least right/left tabs while close tab is limited to tabs on the left.  Is there any reason that close tabs to the left is omitted here?  If this relates to a lack of previous requests for this functionality please consider this a formal request for this.

**Comment by erosman** [comment]
Firefox already has a built-in "Close Tabs to the Right" menu

![foxytab](https://user-images.githubusercontent.com/6458876/55187729-5fd26600-51b7-11e9-9418-a9841dadd1ac.jpg)
