### ISSUE TITLE
[FoxyTab] FoxyTab does not show up when context menu is opened with the "Shift+F10" shortcut

### ISSUE THREAD

**Issue by fourteen-1** [erosman/support#540]
In Firefox you can call the context menu for the tab by the hotkey Shift+F10. Unfortunately, FoxyTab does not show up in this rendition of the context menu for some reason. 

Could this possibly be fixed?

**Comment by erosman** [comment]
Shift+F10 opens the page context-menu (as if right-clicked on the page).

FoxyTab context-menu belongs to the Tab-strip on top of the browser.

> [menus.ContextType](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType)
> Tab
> Applies when the user context-clicks on a tab (specifically, this refers to the tab-strip or other user interface element enabling the user to switch from one browser tab to another, not to the page itself).
