### ISSUE TITLE
[Copy PlainText] Error with the operation

### ISSUE THREAD

**Issue by Cr8zyIvan** [erosman/support#541]
I'm unable to Copy Link Text.

In Windows 10, I get a Toast message saying: "There was an error with the operation". I tried with the default Keyboard Shortcut (F7), I tried with a Custom Shortcut I assigned and with the Context Menu. They all result in the same message.

**Comment by erosman** [comment]
The key/s that you use as shortcut does not matter. It only triggers the process.

- When using right-click, Firefox passes the selected text, so the extension doesn't need to get it
- When using a keyboard shortcut, there is no text. Therefore, extension has to get the selected text and that is done by injecting a code into the page (no other way)

It is not  possible to inject code into some pages, and that is the reason **Copy PlainText** can not get the selected text and outputs an error.

- Firefox blocks script injection into a number of its own domains (ref: [Content scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts))
- Browsers also  block script injection into webpages with strict [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

In these cases, only the right-click would work.

**Comment by Cr8zyIvan** [comment]
Actually, I think I was mistaken in my initial post. I'm not getting any menu item in the context menu (I don't see anything that resembles "Copy PlainText"). Is there an option I might have missed?

**Comment by erosman** [comment]
There isn't any option.

- Copy PlainText Context-menu appears when there is a selection i.e. some text is selected
- Paste PlainText Context-menu appears when inside a textbox such as textarea, input etc

![image](https://user-images.githubusercontent.com/6458876/226268401-56d1c4a4-08d9-4755-b2d2-78c7cc7e011c.png)

**Comment by Cr8zyIvan** [comment]
Oh! Gotcha. I thought you could hover + right click to Copy Plain Text of a Web Link. Which is more of the functionality I was looking for. In any case, Thank you for specifying.
