### ISSUE TITLE
[FireMonkey] New storage API options: getValue, setValue, deleteValue

### ISSUE THREAD

**Issue by erosman** [erosman/support#545]
New APIs in FireMonkey 2.68 ...

## New GM APIs: getValues, setValues, deleteValues

Userscripts often need to get/set multiple values. Each storage operation result in costly asynchronous read/write which means resources, time, and hard disk wear (especially for SSDs). These new APIs aim to alleviate the aforementioned.

### Single-operation
```js
await GM.setValue('key', 'value');
await GM.setValue('key2', 'value2');
await GM.setValue('key3', 'value3');
await GM.setValue('key4', 'value4');
await GM.setValue('key5', 'value5');
```

### New Multi-operation (2.68 only)

```js
const values = await GM.getValues([key, key2, ...]); // return {key: value, key2: value2, ...}
await GM.setValues({key: value, key2: value2, ...});
await GM.deleteValues([key, key2, ...]);
```

### New Multi-operation (changed in 2.69 as new options for existing APIs)

```js
const values = await GM.getValue([key, key2, ...]); // return {key: value, key2: value2, ...}
await GM.setValue({key: value, key2: value2, ...});
await GM.deleteValue([key, key2, ...]);
```

**Comment by erosman** [comment]
> calling `GM.getValues` without passing a parameter should return all values.


Do you mean  like [StorageArea.get()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get)?

> If you pass `null`, or an `undefined` value, the entire storage contents will be retrieved.

**Comment by erosman** [comment]
There could be an alternative approach.

Keep the old API but add new options to mimic `browser.storage.local.get()`

```js
// A key (string) or keys (an array of strings, or an object specifying default values)
await GM.getValue('key', default)       // arg0 is string
await GM.getValue([key, key2, ...])     // arg0 is array
await GM.getValue({key: default, ...)   // arg0 is object

await GM.setValue(key, value)           // arg0 is string
await GM.setValue({key: value, ...})    // arg0 is object

GM.deleteValue(key)                     // arg0 is string
GM.deleteValue([key, ...])              // arg0 is array
```

**Comment by erosman** [comment]
As you said, it wont affect current users. The extra options would be there if needed, or ignored.
The benefit is keeping the same APIs.

Let me think about it and see if there are more feedbacks from users.

**Comment by hlovdal** [comment]
`GM.deleteValue()` with no argument should throw an error; create a dedicated `GM.deleteAllValues()` for deleting everything.

**Comment by erosman** [comment]
> `GM.deleteValue()` with no argument should throw an error; create a dedicated `GM.deleteAllValues()` for deleting everything.

 ATM, `GM.deleteValue()` with no argument, returns and does nothing.

Currently in FireMonkey, there is a method to delete all values.

```js
GM.deleteValue(GM.listValues());
```
