### ISSUE TITLE
Context menu in Foxytab

### ISSUE THREAD

**Issue by mare1203** [erosman/support#553]
A very useful addon for me.
But, maybe some options in the context menu should be defined more clearly. For example, as far as I've noticed, the options for printing tab and saving tab in pdf format always apply only to active tabs, regardless of whether you click on them from an inactive tab. To avoid confusion, perhaps such options should be better named: save active tab in pdf, print active tab... Of course, if this is not a current bug and the mentioned actions can also apply to inactive tabs.

**Comment by erosman** [comment]
Both [tabs.print()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/print) & [tabs.saveAsPDF()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/saveAsPDF) APIs only work on the active tab.

**FoxyTab** Help mentions it in case of **Print** but not for  **Save Tab as PDF**. I will add it.
