### ISSUE TITLE
[FireMonkey] 'KeyboardEvent' is not defined.

### ISSUE THREAD

**Issue by Margen67** [erosman/support#555]
I'm trying to enter text into a search box and have it react as if I'm typing into it, but this script isn't working in FireMonkey since KeyboardEvent doesn't work.
This code is from ChatGPT because I'm dumb and lazy, but it works aside from KeyboardEvent.
![image](https://github.com/erosman/support/assets/3462541/9ff65a63-aa8c-4b61-abd9-9b3e9518e0e7)
```js
// ==UserScript==
// @name         backpack.tf: Auto-Type Text into Input Box
// @namespace    http://your-namespace-here
// @version      1
// @description  Automatically types text into the search input box on backpack.tf and presses the "Enter" key
// @match        https://backpack.tf/*
// @grant        none
// ==/UserScript==

(function() {
  'use strict';

  const textToType = "avian amante 69";

  function typeTextIntoInputBox() {
    const searchInput = document.querySelector("input[placeholder='Search...']");
    if (searchInput) {
      searchInput.focus();
      searchInput.value = textToType;
      const enterKeyEvent = new KeyboardEvent("keyup", {
        bubbles: true, cancelable: true, keyCode: 13
      });
      searchInput.dispatchEvent(enterKeyEvent);
    } else {
      setTimeout(typeTextIntoInputBox, 1000);
    }
  }

  setTimeout(typeTextIntoInputBox, 3000);
})();
```

**Comment by erosman** [comment]
Is `KeyboardEvent` defined in the `page` context?
If the script works in Tampermonkey & Violentmonkey, then it is due t the fact that they would inject it into the `page` context.

If so, then try setting `@inject-into     page`.

**Comment by Margen67** [comment]
> Is `KeyboardEvent` defined in the `page` context? If the script works in Tampermonkey & Violentmonkey, then it is due t the fact that they would inject it into the `page` context.
> 
> If so, then try setting `@inject-into page`.

Actually it was a mistake on my end. I was using `keydown` and didn't bother testing `keyup` which it needed:
![image](https://github.com/erosman/support/assets/3462541/5549ec33-7f96-44a8-9361-09f24f8fc698)
