### ISSUE TITLE
[FireMonkey] Scripts/CSS not being listed, create new userscript button is broken

### ISSUE THREAD

**Issue by Margen67** [erosman/support#556]
Whenever I click on the `New UserScript` button it takes me to the options instead of the Scripts/CSS page.
I get this error in the log whenever I open a page from the extension:
```
05:31:51.602 Uncaught (in promise) TypeError: can't access property "js", item is undefined
    addScript moz-extension://90e61586-63e5-41cf-a01c-c40d1dccd650/content/options.js:675
    process moz-extension://90e61586-63e5-41cf-a01c-c40d1dccd650/content/options.js:664
    process moz-extension://90e61586-63e5-41cf-a01c-c40d1dccd650/content/options.js:664
    <anonymous> moz-extension://90e61586-63e5-41cf-a01c-c40d1dccd650/content/options.js:1458
    promise callback* moz-extension://90e61586-63e5-41cf-a01c-c40d1dccd650/content/options.js:1456
```
If I click the FireMonkey Extension icon no UserScripts or CSS appear even if I have previously saved them.

Here is my Firefox version:
![image](https://github.com/erosman/support/assets/3462541/bd596cd2-c2b7-4be1-a597-45448333217f)

**Comment by erosman** [comment]
> Whenever I click on the New UserScript button it takes me to the options instead of the Scripts/CSS page.

I am on Nightly 115.0a1 and haven't seen the problem.
I tested now with Firefox 113.0 & FireMonkey 2.67 and there was no problem.

I suggest reinstalling FireMonkey. You should also enable "Run in Private Windows", if needed.

**Comment by Margen67** [comment]
> > Whenever I click on the New UserScript button it takes me to the options instead of the Scripts/CSS page.
> 
> I am on Nightly 115.0a1 and haven't seen the problem. I tested now with Firefox 113.0 & FireMonkey 2.67 and there was no problem.
> 
> > 05:31:51.602 Uncaught (in promise) TypeError: can't access property "js", item is undefined
> 
> It shows that the data that has been saved is corrupt (for some reason).
> 
> I suggest reinstalling FireMonkey. You should also enable "Run in Private Windows", if needed.

Reinstalling it worked. Here are the corrupted settings:
[FireMonkey_2023-05-13.zip](https://github.com/erosman/support/files/11471241/FireMonkey_2023-05-13.zip)

**Comment by erosman** [comment]
The settings appears to be OK :man_shrugging:

**Comment by Margen67** [comment]
> The settings appears to be OK 🤷‍♂️

I just imported them and it works again. I think it had something to do with Winblows forcing Firefox to close while it was updating.
