### ISSUE TITLE
[FoxyTab] An extension, FoxyTab, requires Container Tabs

### ISSUE THREAD

**Issue by jpinnix** [erosman/support#56]
On `about:preferences#general`, in the Tabs section, I am seeing the following message: "An extension, FoxyTab, requires Container Tabs." The (i) button doesn't display anything and I am not sure if I am supposed to take action on something?

<img width="683" alt="Screen Shot 2019-03-31 at 8 29 36 AM" src="https://user-images.githubusercontent.com/4436/55289928-3ae61a80-5392-11e9-9620-de3f95493d87.png">

**Comment by erosman** [comment]
The Firefox message could have been better, ;)

FoxyTab has a feature to customise Container usage per domain if it is enabled. Firefox seems to enable it automatically if an extension is using container API but that can be disabled.

However, you should be able to use FoxyTab without the container and/or use the container normally even after allowing FoxyTab to control containers.

FoxyTab doesn't do anything with containers if the custom container settings are not set within its options.

**Comment by jpinnix** [comment]
Thanks!
