### ISSUE TITLE
Where to download the old Firemonkey v2.67 as *.xpi file?

### ISSUE THREAD

**Issue by pstein** [erosman/support#560]
Where can I download the old Firemonkey v2.67 as *.xpi file?

On

https://github.com/erosman/support/releases

only *.zip files for source are listed

**Comment by erosman** [comment]
Older versions are available on addons.mozilla.org
https://addons.mozilla.org/en-US/firefox/addon/firemonkey/versions/

**Comment by erosman** [comment]
> On
> 
> https://github.com/erosman/support/releases
> 
> only *.zip files for source are listed

That is an incomplete code. It was posted only **"for reference and discussion"**.
