### ISSUE TITLE
Super-preloader script 

### ISSUE THREAD

**Issue by Orriky** [erosman/support#561]
> Hi, [Super-preloader](https://github.com/machsix/Super-preloader) script works on 2.68 version.
> However, I have problems with Google search sites. If I enable iframe the script doesn't work anymore on Google sites
> I'd also like to enable new iframe globally with this custom rule
> 
> {
>   "name": "GoogleAlt",
>   "url": "^https?://www\\.google\\..+/search.+",
>   "useiframe": true,
>   "autopager": {
>       "newIframe": true,
>    },
> }
> 
> 
> 
> @Orriky It would be easier to open a new topic.
> 
>     If I enable iframe the script doesn't work anymore on Google sites
> 
> Did you enable iframe in User Metadata?
> 
>     I'd also like to enable new iframe globally with this custom rule
> 
> What is that rule for/from?

I enable iframe in the script settings (the small square at the top right of the Google page)
I wrote that rule (I added it in the script global settings), it seems ok on violentmonkey however I'm not sure about it

**Comment by erosman** [comment]
Greasemonkey, Tampermonkey, & Violentmonkey by default inject into iframes as well.

FireMonkey by default doesn't inject into iframes.

As per [FireMonkey Help: Quick Fixes](https://erosman.github.io/support/content/help.html#Quick-Fixes):

- 💡 Try setting @run-at   document-end in [User Metadata](https://erosman.github.io/support/content/help.html#User-Metadata)
    See also: [defaults](https://erosman.github.io/support/content/help.html#defaults)

**Comment by Orriky** [comment]
Thanks, now the script works with iframe applying your suggestion.
Unfortunately, my custom rule doesn't. I need it to auto-enable iframe and new-iframe in incognito mode.
Maybe ViolentMonkey accept this regex `^https?://www\.google\..+/search.+` and FireMonkey doesn't.

I had to edit the Storage section under User Metadata to apply the global setting of the script since they are not remembered if applied inside the script settings (the small square at the top right of the Google page)

**Comment by erosman** [comment]
> I need it to auto-enable iframe and new-iframe in incognito mode.

Have you enabled [Extensions in Private Browsing](https://support.mozilla.org/en-US/kb/extensions-private-browsing)?

> Maybe ViolentMonkey accept this regex `^https?://www\.google\..+/search.+` and FireMonkey doesn't.

What is the outcome that you need?
What happens when you set that?

**Comment by Orriky** [comment]
this is the setting pane in an incognito session with ViolentMonkey
[image1](https://imgur.com/a/DLBBAKB)
this is FireMonkey
[image2](https://imgur.com/a/7UuIzz9)

With ViolentMonkey _iframe_ and _new iframe_ are always automatically enabled

**Comment by erosman** [comment]
I see... there are userscript setting. Userscript developers are the best to debug the issue.

If there is an issue in FireMonkey that can be fixed, I will fix it.

**Comment by Orriky** [comment]
Unfortunately no support on Github page of the script.
I removed my custom rule in ViolentMonkey and _iframe_ and _new iframe_ are automatically enabled in private mode too.
So that rule doesn't matter.
Do you have any advice about store these settings in private mode?

**Comment by erosman** [comment]
> Do you have any advice about store these settings in private mode?

It might be that the userscript stores them in web-storage and that is the reason they are not available.
If the userscript uses GM storage, they will be available.

**Comment by erosman** [comment]
I found an issue with sync storage processing in FM. Please wait for v2.69 and try again.

**Comment by erosman** [comment]
I found an issue with sync storage processing in FM 2.68. Please wait for FM 2.69 and try again.

**Comment by erosman** [comment]
Few notes:

The script is 13,548 lines which is hard to debug.

Although not a problem, userscript declares `@grant` that it doesn't use:
```
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_notification
// @grant        GM_xmlhttpRequest
// @grant        GM_registerMenuCommand
```

However, it uses `// @grant        GM.registerMenuCommand` which it didn't include the `@grant` for.

It also has 2 sets of metadata block.

**Comment by Orriky** [comment]
2.68 and 2.69 seem identical to me.
By a VM comparison, I notice that is missing this section in FM

```
  "SITEINFO_D": {
    "enable": true,
    "useiframe": true,
    "viewcontent": false,
    "autopager": {
      "enable": true,
      "force_enable": false,
      "manualA": false,
      "useiframe": true,
      "iloaded": false,
      "itimeout": 0,
      "newIframe": true,
      "remain": 1,
      "maxpage": 99,
      "ipages": [
        false,
        2
      ],
      "separator": true,
      "separatorReal": true,
      "reload": false,
      "sandbox": false,
      "relatedObj": true
    }
  },

```
(I set useiframe and newIframe to true)
I added it and now I have iframe and newIframe enabled in private mode on all sites but Google sites (instead of Google shopping that shows iframe).
I'd like to have them enabled only on Google video search results.

**Comment by erosman** [comment]
Is there a guide on how to add add sites?

**Comment by erosman** [comment]
If the processors uses `JSON.parse()` then the one you posted would run into errors. It should be:

```json
{
  "name": "GoogleAlt",
  "url": "^https?://www\\.google\\..+/search.+",
  "useiframe": true,
  "autopager": {
    "newIframe": true
  }
}
```

**Comment by Orriky** [comment]
Thanks,
That rule doesn't work.
I'm not able to reproduce my VM results even in a new fresh profile with VM.
So, it isn't a FM issue.
I use FM all day, it is my default script/css engine

**Comment by erosman** [comment]
> I don't know how apply it on FireMonkey

Where does it go?
Is it part of the script storage?
Do you have a copy of the script storage from Violentmonkey?

You an copy script's storage from VM and paste it in ... *FM -> 3-dot menu -> Storage* ... and then SAVE

**Comment by Orriky** [comment]
The rule works well using storage of ViolentMonkey.
Here the json file [https://www.mediafire.com/file/x4znb7om64n6397/storage.json/file](https://www.mediafire.com/file/x4znb7om64n6397/storage.json/file)

The rule, however, should be applied in the script global settings.
[https://imgur.com/a/kfMihxZ](https://imgur.com/a/kfMihxZ)
[https://imgur.com/a/ovPMDAd](https://imgur.com/a/ovPMDAd)
These settings are unusable in FireMonkey

**Comment by erosman** [comment]
Check the script storage under that script in Violentmonkey


![image](https://github.com/erosman/support/assets/6458876/871fef5d-cf61-4af8-a773-c3ca2547ab77)

**Comment by Orriky** [comment]
Yes, I did. I posted a MediaFire link with the script storage in my previous post. Is it right?

**Comment by erosman** [comment]
Then paste that into scripts storage in FireMonkey.

FM -> 3-dot menu -> Storage
and then SAVE

**Comment by Orriky** [comment]
Thanks!!!, it is ok now
