### ISSUE TITLE
Script - Run manually vs automatically

### ISSUE THREAD

**Issue by Znrl** [erosman/support#562]
Hello! Sorry if this question is obvious or anything.

I noticed that if I enable a script (run automatically), I can still select the script in FireMonkey and click on "run".
This seems to start the script again seperately(?). E.g. it injects elements a 2nd time to the website.
If I click "run" a 2nd time I get notices about redeclaring variables and such. This is also true if the script was not already started automatically.

Is this intentional or is this likely on my side, browser configuration (private mode), the script, ... or anything?

**Comment by erosman** [comment]
Initially, when I made the "run" feature, I disabled it on the active scripts (scripts that where already injected in that page).

However, there were situations that required the re-run of the script. For example, affecting elements that were added later to the page, after the script has run.
I had a script myself,affecting images on the page, however the page would add images later as well so I needed to re-run the script.

As you have mentioned, some scripts are not suitable for a re-run. The 'run' feature is user-initiated and the user has to decide if the script is suitable for re-run or not.

**Comment by erosman** [comment]
Initially, when I made the "run" feature, I disabled it on the active scripts (scripts that where already injected in that page).

However, there were situations that required the re-run of the script. For example, affecting elements that were added later to the page, after the script has run.
I had a script myself,affecting images on the page, however the page would add images later as well so I needed to re-run the script.

As you have mentioned, some scripts are not suitable for a re-run. The 'run' feature is user-initiated and it is up to the user to decide if the script is suitable for re-run or not.

**Comment by Znrl** [comment]
OK, thank you for your answer.
Is it true then, that the script is executed in a different scope/sandbox in that case?
Because there is no "redeclaration" warning.
I just wonder if I can prevent it from being run twice.
But probably I just need to check for the existence of the added elements in the DOM.

**Comment by erosman** [comment]
> Is it true then, that the script is executed in a different scope/sandbox in that case?

As per FireMonkey Help, the code from Scratchpad and RUN, are injected into `content` scope/context while scripts register to run automatically are injected in the `userScript` context.

There are major differences between the two:

- Script injected from RUN (and scratchpad) don't have access to GM functions
- Using RUN once, usually doesn't get "redeclaration" warning since they are in 2 different contexts
- Using RUN twice, could get into "redeclaration" warning as the script is inject into the same context twice

> I just wonder if I can prevent it from being run twice.
> But probably I just need to check for the existence of the added elements in the DOM.

That would be the easiest.

However, why are you clicking the RUN anyway, if the script is already injected?

**Comment by Znrl** [comment]
Thank you! Now with your comment I found it in the help.
It's more about me potentially not being the user of the script ;)
