### ISSUE TITLE
How to disable Lazy Loading/enforce full load from within a FM script?

### ISSUE THREAD

**Issue by pstein** [erosman/support#563]
I would like to keep Lazy Loading enabled in general.

However for certain web pages I would like to disable Lazy Loading.

How can I force the browser from within a FM *.user.js script to completely load all stuff (=disable lazy loading)?

**Comment by erosman** [comment]
It depends on the elements that are being lazy loaded.

For example:

```html
...
<img decoding="async" loading="lazy" src="https://www...001.jpg" alt="">
...
```

```js
document.querySelectorAll('#readerarea img')?.forEach(i => {
  i.removeAttribute('decoding');
  i.removeAttribute('loading');
});
```

**Comment by pstein** [comment]
Thank you
