### ISSUE TITLE
[Replace]: Which kind of regular expression? Subgroups?

### ISSUE THREAD

**Issue by BerndSchmitt** [erosman/support#564]
Hi, thank you for this addon.
Is there any tutorial/manual/documentation what kind of regular expression is working (things like    \([A-Z].*\)enden -> \1er  does not work )? How do subgroups work in replacement-string?

Thanks,
Bernd

**Comment by erosman** [comment]
Help is included, but the addon hasn't been updated for a long time so it is less visible in the new Firefox user-interface.

Go to: about:addons -> Replace (click on it) -> Preferences -> Help

I shall update the UI once I get some free time.

> How do subgroups work in replacement-string?

It should work like normal regular expressions.
