### ISSUE TITLE
[FireMonkey] Issue Report - Why the UserScript does not run inside Iframe?

### ISSUE THREAD

**Issue by cyfung1031** [erosman/support#565]
## Userscript Sample

```js
// ==UserScript==
// @name                My Test Script 01
// @version             1.0
// @author              Me
// @match               https://www.youtube.com/live_chat*
// @grant               none
// @allFrames
// @inject-into page
// ==/UserScript==

(function () {
    'use strict';

    console.log("Execution in Iframe");
 
})();
```

## Reproduction

Test url: https://www.youtube.com/watch?v=tLQLa6lM3Us
Open the chatroom in the page. The iframe element will load. 

### Verify the iframe element is loaded with url = `https://www.youtube.com/live_chat*`
Open the console window
```js
let iframe = document.getElementById("chatframe");
console.log("iframe.src", iframe.getAttribute("src"));
console.log("iframe.contentWindow.location", iframe.contentWindow.location.href);
```

### The iframe is loaded with the matched url but FireMonkey does not run the script
<img width="664" alt="Screen Shot 2023-06-22 at 21 38 14" src="https://github.com/erosman/support/assets/44498510/9cd372dc-92c2-4528-befe-957b1bf3ede5">

## Expected Result
1. `Execution in Iframe` inside iframe will be logged in the console window.
2. It works correctly in Tampermonkey and Violentmonkey.

**Comment by erosman** [comment]
As mentioned in [FireMonkey Help: defaalts](https://erosman.github.io/support/content/help.html#defaults), the default in FireMonkey is to not run in iframes (which is the same as Firefox/Chrome default script injection behaviour).

GM|TM|VM default is to run in iframes.

As mentieond in [FireMonkey Help: Quick Fixes](https://erosman.github.io/support/content/help.html#Quick-Fixes)

> Userscript needs to run in sub-frames
> - 💡 Try setting @allFrames   true in [User Metadata](https://erosman.github.io/support/content/help.html#User-Metadata)

**Comment by cyfung1031** [comment]
> * allFrames

@allFrames is already set. You can see the sample script above.

Still not running inside iframe

**Comment by erosman** [comment]
It must be `@allFrames   true`

**Comment by cyfung1031** [comment]
OK. I thought it is just opposite to `@noframes`. It works now.
