### ISSUE TITLE
firemonkey not able  to inject any js into gist.githubusercontent.com pages

### ISSUE THREAD

**Issue by ale82to** [erosman/support#567]
i ve created a dead simple userscript:
code :
```js
// ==UserScript==
// @name gitbutton
// @match :///*
// @Version 1.0
// @inject-into content
// ==/UserScript==
alert("notWorking");
const fileName = window.location.pathname.split('/').pop();
const downloadButton = document.createElement('a');
downloadButton.textContent = 'Download';
downloadButton.style.display = 'inline-block';
downloadButton.style.margin = '10px';
downloadButton.style.padding = '5px 10px';
downloadButton.style.backgroundColor = 'lightgray';
downloadButton.style.color = 'black';
downloadButton.setAttribute('download', fileName);
downloadButton.setAttribute('href', window.location.href);
document.body.appendChild(downloadButton);
```
to append a download button on raw github pages , example:
https://gist.githubusercontent.com/ale82to/8c5349090495fd7538a556bdb126320b/raw/e12766d1d262877b99215d57253940d3432f5450/test.js

but its not working at all not even the alert fun; in tampermonkey i ve no problem at all,the userscript is inject without any problem,what am i missing (maybe csp ? but injecting into content should solve csp problems?)
thanks

**Comment by erosman** [comment]
### inject-into
- FireMonkey only supports `page` e.g. `@inject-into    page`
- Note: `content` which is the default injection context for GM|TM|VM does not bypass CSP


### Content Security Policy (CSP)
- The `sandbox` prevents script injection in `gist.githubusercontent.com`
  `content-security-policy | default-src 'none'; style-src 'unsafe-inline'; sandbox`
- TM alters CSP, while FM|GM|VM don't
