### ISSUE TITLE
[Firemonkey] xmlhttpRequest Headers Compatibility 

### ISSUE THREAD

**Issue by HoodB0** [erosman/support#569]
Setting "headers" to null while making a request leads to an error with no trace.
```js
GM_xmlhttpRequest({
  url: "https://example.org",
  method: "GET",
  headers: null, // Error: An unexpected apiScript error occurred
  onload: function(response) {
    console.log(response)
  }
})
```
This doesn't happen in ViolentMonkey (didn't test with TamperMonkey), and yes, scripts do set headers to null (4chan-X).

**Comment by erosman** [comment]
GM|TM|VM also expect `xmlHttpRequest` headers to be an `object`.

Although `null` is also an `object`, it will cause an error on `Object.keys(null)` in FireMonkey.

I will add a check to prevent error when it is set to `null`.

Fixed for v2.72
