### ISSUE TITLE
[Feature request] "Bookmark All Tabs" no longer exists in Firefox 64+. Good to add it. 

### ISSUE THREAD

**Issue by ReporterX** [erosman/support#57]
"Bookmark All Tabs" no longer exists in Firefox 64+. You can't see "Bookmark All Tabs" when you right click on a single tab. It takes some steps if you want to bookmark all.

It makes some sense to add it to FoxyTab now.

**Comment by erosman** [comment]
Sure

**Comment by erosman** [comment]
Added in 2.16
