### ISSUE TITLE
Foxytab Bug

### ISSUE THREAD

**Issue by khabib227** [erosman/support#571]
when I have 2 tabs the counter (badge) show 1 tab. firefox 112

**Comment by erosman** [comment]
Can you explain a bit more?

The containers are handled by Firefox. FoxyTab only handles the opening of links in a container.

**Comment by erosman** [comment]
Do you have 2 tabs in one window?
What is the FoxyTab version?
Tab counter updates every time a new tab is opened or closed, so it will correct itself.
