### ISSUE TITLE
I am getting a "Save to clipboard not allowed" notification on windows 11

### ISSUE THREAD

**Issue by RalfReddings** [erosman/support#574]
I am getting a "Save to clipboard not allowed" notification on windows 11
What does this mean?
I recently started to get it when running the FoxyTab hotkey to copy tab url/title to the clipboard.
![](https://i.imgur.com/rWkkeKz.png)

**Comment by erosman** [comment]
I tried it now but I don't get any error (on Ubuntu).

- Did it start recently?
- Did you install any other extensions that may interfere with it?
- Is it on a normal window or in private mode?

You can try these:

- Disable other addons and try
- Change the keyboard shortcut 
- Reinstall FoxyTab

**Comment by RalfReddings** [comment]
@erosman 
hmm... I decided to just give it some time and a week later it dissapeared. Maybe it was a conflict of extensions, like you suspected. Cheers.
