### ISSUE TITLE
[FoxyTabs] [Issue request] compatability with vertical tabs.

### ISSUE THREAD

**Issue by SpiroExDeus** [erosman/support#575]
Would be great if this would also work with Vertical Tabs Reloaded and/or similar firefox extensions. As I aim to eventually eliminate the horizontal tabs  at the top (probably through userchrome as this is currently not possible via an extension) and as this would be nice to still acess via right-click options then this would be a great addition to foxytabs. The other option would be to add your own vertical tab setup via foxytabs itself.

**Comment by erosman** [comment]
I don't know if there is anything that I can do from here. It depends on those extension.

It was compatible with **Tree Style Tabs** though.

![209754](https://github.com/erosman/support/assets/6458876/95d7386a-c908-484a-a68b-e32edfa6f21b)
