### ISSUE TITLE
Translation lacking

### ISSUE THREAD

**Issue by hubuqi** [erosman/support#578]
Copy Plain Text translation to Chinese gets no updates.

**Comment by erosman** [comment]
Translations are provided by users. Once someone provides the translation, I will include it in the next release.

[Translation: Copy PlainText](https://github.com/erosman/extension-translations/tree/master/Copy%20PlainText)

**Comment by hubuqi** [comment]
Yeah,but I don’t know how to provide my translation

发自我的 iPhone

在 2023年7月20日，00:57，erosman ***@***.***> 写道：

﻿

Translations are provided by users. Once someone provides the translation, I will include it in the next release.

Translation: Copy PlainText<https://github.com/erosman/extension-translations/tree/master/Copy%20PlainText>

**Comment by erosman** [comment]
> Yeah,but I don’t know how to provide my translation

You can use the included "Locale Maker" to make the translation, or you can directly translate the [messages.json](https://github.com/erosman/extension-translations/blob/master/Copy%20PlainText/en/messages.json).

See also: ['ES' Spanish Copy PlainText translation](https://github.com/erosman/extension-translations/issues/77)

**Comment by hubuqi** [comment]
I mean，this project seems not open

发自我的 iPhone

在 2023年7月20日，12:28，erosman ***@***.***> 写道：

﻿

Yeah,but I don’t know how to provide my translation

You can use the included "Locale Maker" to make the translation, or you can directly translate the messages.json<https://github.com/erosman/extension-translations/blob/master/Copy%20PlainText/en/messages.json>.

See also: 'ES' Spanish Copy PlainText translation<https://github.com/erosman/extension-translations/issues/77>

**Comment by erosman** [comment]
You can make a PR.

If you want, post your translation and I will update it.

**Comment by hubuqi** [comment]
Thank you.

卫仁
________________________________
发件人: erosman ***@***.***>
发送时间: 2023年7月20日 13:42
收件人: erosman/support ***@***.***>
抄送: 胡不器 ***@***.***>; Author ***@***.***>
主题: Re: [erosman/support] Translation lacking (Issue #578)


You can make a PR.

If you want, post your translation and I will update it.

―
