### ISSUE TITLE
[Copy PlainText] Error: window.getSelection() is null

### ISSUE THREAD

**Issue by Thomasc5** [erosman/support#579]
Copy PlainText shows an error when the keyboard shortcut is triggered in Amazon.com.

**Steps to reproduce:**
1. Search for any product at Amazon, e.g. https://www.amazon.com/75th-Anniversary-Transistor-Arokia-Nathan/dp/139420244X/
2. In the product page, select some texts, then press the keyboard shortcut for Copy PlainText.

**What has happened:**

A notification pops up saying: 
Selection: There was an error with the operation
Error: window.getSelection() is null

![Copy PlainText](https://github.com/erosman/support/assets/5540385/60ccf94f-f767-4dab-b7e8-922e6f378991)

**What should happen:**
Copy PlainText should copy selected texts.
The previous version of Copy PlainText (version 1.13) does not have this error.

**Comment by erosman** [comment]
Fixed for v1.16
