### ISSUE TITLE
[Replace]: Unable to find code-repository

### ISSUE THREAD

**Issue by BerndSchmitt** [erosman/support#580]
Thank you very much for this helpful extension. I would like to modify it a little bit (loading a list of regular-expression-substitions from a file).  Therefore, I would like to clone the repo for this extension, but I am unable to find the repo-url. 

I did not find it in the list of your repos. Could you post a link to the source-code-repo, please?

Thanks in advance & sorry for me overlooking something obvious
Bernd

**Comment by erosman** [comment]
I don't develop using GitHub or other repo set-ups.
You can access the source code by opening the zip file.

**Comment by BerndSchmitt** [comment]
Thank you very much for your quick answer. 
I would like to set up a public repo to develop some modifications, if this is OK for you (same license, all credits to you).

**Comment by erosman** [comment]
No problem

**Comment by erosman** [comment]
BTW, I am going to work on an update for the **Replace** and I will include the Regular Expression feature.

**Comment by erosman** [comment]
BTW, I am going to work on an update for the **Replace**.
