### ISSUE TITLE
[FireMonkey] Please add Firemonkey to `window.external`

### ISSUE THREAD

**Issue by cyfung1031** [erosman/support#582]
according to [this](https://pastebin.com/WMJiBddk), userscript pages rely on the `window.external.xxxx` to check whether the script is installed or not.

This is already well implemented in Tampermonkey and Violentmonkey, FireMonkey shall follow this practice and ask those pages like "Greasy Fork" to update accordingly.

Without `window.external.xxxx`, no one can detect the script is installed or not in FireMonkey.

### Suggested Usage

window.external.FireMonkey (or Firemonkey)

* string property `version` - indicate the installed version of FireMonkey.
* function property `isInstalled` - accepts two string parameters (`name` and `namespace`) and return a `Promise`.
  * return the version code if it is installed; return null if it is not installed.

**Comment by erosman** [comment]
> according to [this](https://pastebin.com/WMJiBddk), userscript pages rely on the window.external.xxxx to check whether the script is installed or not.

[Window: external property](https://developer.mozilla.org/en-US/docs/Web/API/Window/external) is deprecated. Furthermore, `window` object can be accessible to the webpage which then can interfere with the userscript.

If you mean that the userscript can check which manager it is running on, then the proper method would be `GM_info.scriptHandler` and `GM.info.scriptHandler`.

Manager version is also available under `GM.info.version`.
Script name and other details are available under `GM.info.script`.

- FireMonkey: [GM info](https://erosman.github.io/support/content/help.html#info)
- Greasemonkey: [GM.info](https://wiki.greasespot.net/GM.info)
- Violentmonkey: [GM_info](https://violentmonkey.github.io/api/gm/#gm_info)
- Tampermonkey: [GM_info](https://www.tampermonkey.net/documentation.php#api:GM_info)

**Comment by cyfung1031** [comment]
So how can we know other scripts are installed or not?

For example, I can run in the devTools to check whether a script "MyUserscript" is installed or not.

```js

window.exteneral.Violentmonkey('MyUserscript', 'namespace.com').then(result=>{

if(result) console.log(`MyUserscript is installed, version = ${result}`);
else console.log(`MyUserscript is not installed.`);

});

```


Even I create a UserScript installed in Firemonkey, I can just have GM.info refer to the current script.
It is still unable to obtain the installation status of a particular userscript.

**Comment by erosman** [comment]
> So how can we know other scripts are installed or not?

Userscript managers show the active userscripts in their UI.
Each userscript manager should have details of its own installation, not another extension's installation.

`window` in GM|TM|VM in `content` context is not the same `window` as `userScript` context used by FireMonkey. Even if such a variable is added in FM, it wont be accessible to GM|TM|VM.

`content` context `window` object is accessible to the webpage. 
Webpages should not be allowed to check if user has installed other extensions or userscripts.
Furthermore, a userscript shall not be allowed to check if user has installed other extensions or userscripts.

I am still unsure of what are you trying to achieve.

**Comment by cyfung1031** [comment]
That means it is never possible to let GreasyFork to detect the script is installed or not? Even through the script installed in FireMonkey?

**Comment by erosman** [comment]
> That means it is never possible to let GreasyFork to detect the script is installed or not?

ATM, webpages won't be able to check if a userscript is installed in FireMonkey.
Why should it be allowed?

Please note the following:

- [Window: external property](https://developer.mozilla.org/en-US/docs/Web/API/Window/external) is deprecated
- There can be privacy/security issues
- Its support is not unified
- Greasemonkey does not support `window.external`
- Tampermonkey provides it for _greasyfork.org, sleazyfork.org_
- Violentmonkey provides it for _greasyfork.org_
- Tampermonkey provides the following: 
```
{ 
  getVersion() { }, 
  openOptions() { }, 
  isInstalled() { } 
}
```
- Violentmonkey provides the following: 
```
{ 
  version: '2.15.0',
  isInstalled() { }
}
```

However, a userscript can announce itself, if the userscript developer wants, by creating the object. Here is an example:

```js
// ==UserScript==
// @name         1 window.external #582
// @description  Please add FireMonkey to window.external #582
// @match        https://greasyfork.org/*
// @match        https://sleazyfork.org/*
// ==/UserScript==

const js = `window.external.FireMonkey = {
  version: ${JSON.stringify(GM.info.version)},
  isInstalled(name, namespace) {
    // only for self
    return name === ${JSON.stringify(GM.info.script.name)};
  }
};`;

GM.addElement('script', {textContent: js});
```

**Comment by erosman** [comment]
GreasyFork only checks TM|VM & Stylus

https://github.com/JasonBarnabe/greasyfork/blob/e198546a9c8e61556aee756932abf222506f4541/app/javascript/managers.js#L1-L21

```js
export function getTampermonkey() {
  return window.external?.Tampermonkey
}

export function getViolentmonkey() {
  return window.external?.Violentmonkey
}

export function canInstallUserJS() {
  return getTampermonkey() || getViolentmonkey()
}

export async function canInstallUserCSS() {
  if (localStorage.getItem('stylusDetected') == '1') {
    return true;
  }
  postMessage({ type: 'style-version-query', name: "whatever", namespace: "whatever", url: location.href }, location.origin);
  return new Promise(resolve => setTimeout(function() {
    resolve(localStorage.getItem('stylusDetected') == '1')
  }, 200));
}
```

**Comment by erosman** [comment]
> That means it is never possible to let GreasyFork to detect the script is installed or not?

ATM, webpages won't be able to check if a userscript is installed in FireMonkey.
Why should it be allowed?

Please note the following:

- [Window: external property](https://developer.mozilla.org/en-US/docs/Web/API/Window/external) is deprecated
- There can be privacy/security issues
- Support is not unified
- It appears to be an arrangement between greasyFork and TM|VM

## GreasyFork
GreasyFork only checks TM|VM & Stylus

https://github.com/JasonBarnabe/greasyfork/blob/e198546a9c8e61556aee756932abf222506f4541/app/javascript/managers.js#L1-L21

```js
export function getTampermonkey() {
  return window.external?.Tampermonkey
}

export function getViolentmonkey() {
  return window.external?.Violentmonkey
}

export function canInstallUserJS() {
  return getTampermonkey() || getViolentmonkey()
}

export async function canInstallUserCSS() {
  if (localStorage.getItem('stylusDetected') == '1') {
    return true;
  }
  postMessage({ type: 'style-version-query', name: "whatever", namespace: "whatever", url: location.href }, location.origin);
  return new Promise(resolve => setTimeout(function() {
    resolve(localStorage.getItem('stylusDetected') == '1')
  }, 200));
}
```

## Greasemonkey
- `window.external` is not supported

## Tampermonkey
- Ref: [Add an option to allow communication with cooperate pages](https://github.com/Tampermonkey/tampermonkey/issues/322)
- Available on _greasyfork.org, sleazyfork.org, openuserjs.org_
- Available on normal tabs, but not in containers or private window
- `namespace` is optional
- Returns callback
- Return value is an `object`
```
// window.external.Tampermonkey
{
  getVersion() { },
  openOptions() { },
  isInstalled() { }
}
```

## Violentmonkey
- Available on _greasyfork.org_
- Available on normal tabs, containers and private window
- `namespace` is mandatory
- Returns Promise
- Return value is a `string`
```
// window.external.Violentmonkey
{
  version: '2.15.0',
  isInstalled() { }
}
```


## Privacy/Security
Wherever the object is available:
- The website can snoop on which userscript manager and scripts, user has installed
- Other userscripts can snoop on which userscript manager and scripts, user has installed

Example: Tested On [Text Highlighter - Dynamic](https://greasyfork.org/en/scripts/3719-text-highlighter-dynamic)

### Tampermonkey
```js
!!window.external.Tampermonkey
// true

window.external.Tampermonkey.getVersion(console.log)
// Object { version: "4.19.0", id: "fire" }

window.external.Tampermonkey.isInstalled('W.A.R. Links Checker Premium', 'premium version', console.log)
window.external.Tampermonkey.isInstalled('W.A.R. Links Checker Premium', console.log)
// Object { name: "W.A.R. Links Checker Premium", installed: true, enabled: true, version: "1.5.7.8" }

window.external.Tampermonkey.isInstalled('xyz', console.log)
// Object { name: "xyz", installed: false, enabled: undefined, version: undefined }

window.external.Tampermonkey.openOptions()
// opens options page, allow web site to navigate user to the TM options page
```

### Violentmonkey
```js
!!window.external.Violentmonkey
// true

window.external.Violentmonkey.version
// "2.15.0"

window.external.Violentmonkey.isInstalled('W.A.R. Links Checker Premium', 'premium version').then(console.log)
// "1.6.2.2"

window.external.Violentmonkey.isInstalled('W.A.R. Links Checker Premium').then(console.log)
window.external.Violentmonkey.isInstalled('xyz', 'premium').then(console.log)
// null
```

## Add via UserScript
However, a userscript can announce itself by creating the object. Here is an example:

```js
// ==UserScript==
// @name         window.external #582
// @description  Please add FireMonkey to window.external #582
// @match        https://greasyfork.org/*
// @match        https://sleazyfork.org/*
// @version      1.0
// ==/UserScript==

const js = `window.external.FireMonkey = {
  version: ${JSON.stringify(GM.info.version)},
  isInstalled(name, namespace) {
    // only for self, return script version
    return name === ${JSON.stringify(GM.info.script.name)} ? ${JSON.stringify(GM.info.script.version)} : null;
  }
};`;

GM.addElement('script', {textContent: js});
```

```js
window.external.FireMonkey.version
// "2.73"

window.external.FireMonkey.isInstalled('window.external #582')
// "1.0"
```

## Add via UserScript, return Promise
```js
// ==UserScript==
// @name         window.external #582
// @description  Please add FireMonkey to window.external #582
// @match        https://greasyfork.org/*
// @match        https://sleazyfork.org/*
// @version      1.0
// ==/UserScript==

const js = `window.external.FireMonkey = {
  version: ${JSON.stringify(GM.info.version)},
  async isInstalled(name, namespace) {
    // only for self, return script version
    return name === ${JSON.stringify(GM.info.script.name)} ? ${JSON.stringify(GM.info.script.version)} : null;
  }
};`;

GM.addElement('script', {textContent: js});
```

```js
window.external.FireMonkey.isInstalled('window.external #582').then(console.log)
// 1.0
```

**Comment by gunir** [comment]
Honestly this feature looks dangerous, and it's not that useful rather not relying on it and have a better coding practice.

**Comment by JasonBarnabe** [comment]
> Why should it be allowed?

From Greasy Fork's point of view, there are two features this allows:

1. Detection that a user script manager is present. If there is no user script manager installed, links to `.user.js` files result in the user being presented a JS file with no UI to install it or any kind of instructions, which is a bad user experience. So, when a user clicks to install a script, Greasy Fork will first show a modal to the user to explain how to install things (i.e. install an extension first). If Greasy Fork can detect that there is a user script manager already installed, then it can skip this modal. 
![Screenshot 2024-11-27 14:32:21](https://github.com/user-attachments/assets/d22f5907-029a-458a-810b-eeafef4bd083)

2. Show the proper text on the install button. If Greasy Fork can detect that a specific user script is already installed, then the "Install this script" button will update to something that better reflects what will happen: "Upgrade to version 1.2.3" or "Downgrade to version 1.2.3" or "Reinstall version 1.2.3".

**Comment by erosman** [comment]
@JasonBarnabe The concern here is the privacy and security:

- Data should only be available to GF and not other sites or other userscripts
- Data should only be provided for the specific userscript page and not other installed userscripts
- Data format should be unified between userscript managers


As an example, on visiting ABC on Greasy Fork

**Show**
- Userscript manager itself
- if ABC is installed and the version

**Not Show**
- Any information about any other installed userscripts
- Any information to any other installed userscripts

**Comment by erosman** [comment]
I have posted a new topic to greasyfork repository for further development discussion.

**Comment by erosman** [comment]
Support was added in v2.74

- FireMonkey only provides the installed version of the script matching the GF page (no other scripts)
- available on `greasyfork.org` & `sleazyfork.org`
- available on `/scripts/*` & `/scripts/*/code`
- not available on other pages i.e. `/scripts`, `/scripts/*/feedback`, `/scripts/*/stats`, `/scripts/*/versions`
- FM gets the required data asynchronously on `"document_start"`
- data can then be accessed by GF synchronously

```js
{
  version: '2.74',
  installedScriptVersion: '1.2.3'   // or undefined
}
```

**Comment by cyfung1031** [comment]
Thanks for your effort!
