### ISSUE TITLE
Replacing causes the difference to be inserted twice

### ISSUE THREAD

**Issue by 001Guy001** [erosman/support#585]
For example, if replacing "one" with "onetwo" it will be replaced as "onetwotwo"

**Comment by 001Guy001** [comment]
It happens while editing wiki pages on Reddit

**Comment by erosman** [comment]
I cant reproduce on https://controlc.com/
That is happen on a saved paste?

![image](https://github.com/erosman/support/assets/6458876/d7dfbbc2-23f1-44d6-8603-93c34cab017d)

![image](https://github.com/erosman/support/assets/6458876/465b93f1-c525-4131-ad0b-1ab81cd5f8f7)

**Comment by 001Guy001** [comment]
Hmm it seems to be ok now, not sure what caused that on my end
