### ISSUE TITLE
[Replace] [Suggestion] A toggle option to find and replace as regular text or as regex

### ISSUE THREAD

**Issue by 001Guy001** [erosman/support#586]
Currently the newest version of the addon seems to detect regex automatically, which interferes when trying to update actual regex on a page (that is, when looking for text that includes a regular expression in it)

**Comment by erosman** [comment]
Give me an example and I will test it out.

**Comment by 001Guy001** [comment]
For example replacing (\W|_) with [\W_]

**Comment by 001Guy001** [comment]
Ok. it seems to only happen when trying to replace partial regexes, for example `(^\W*|` with `(^[\W_]*|`

**Comment by erosman** [comment]
Found the problem. Fixed for v1.5
