### ISSUE TITLE
[FoxyTab] Feature request: Rename tabs

### ISSUE THREAD

**Issue by RickVR** [erosman/support#60]
Very nice extension! I like it.

It would be nice to rename tab titles and prevent them from being changed by the site.
Possibly using a combination of manual renaming and RegEx.

Keep up the good coding!!

**Comment by erosman** [comment]
Tab Titles are set from page content. FoxyTab deals with a tab as whole and does not interact with page content at all.

Altering page titles can easily be done with a userscript and a userscript manager such as GreaseMonkey, TamperMoneky, VioletMonkey and my own [FireMonkey](https://addons.mozilla.org/firefox/addon/firemonkey/).
