### ISSUE TITLE
[Copy PlainText] Feature requests: 1. reformat special characters; 2. retain new lines

### ISSUE THREAD

**Issue by arelkin** [erosman/support#61]
Long ago, I contributed two suggestions to another Copy Plain Text plugin similar to this. 
I hope you might add this to the preferences page:
1. retain carriage returns / new lines. (it appears that this plugin strips new lines)
2. convert special characters to plain text characters (I actually found the Javascript). This plugin seems to retain these special characters. Include a checkbox to either convert or not convert. These seem to be the most common special characters a person might encounter, but an exhaustive list could be developed.
      if (CPTOver.ptPrefs.getBoolPref("reformatSpecialCharacters")) {
        string = string.replace(/[„|“|”]+/g, "\"") // fancy quotes
          .replace(/[‘|’]+/g, "'") // fancy apostrophes
          .replace(/[—|–]+/g, "-") // m and n dashes
          .replace(/[ñ]+/g, "n") // tilde
          .replace(/[®]+/g, "\(r\)") // registered trademark
          .replace(/[©]+/g, "\(c\)") // copyright
          .replace(/[•]+/g, "*") // bullet
          .replace(/[™]+/g, "TM") // trademark
          .replace(/[…]+/g, "..."); // ellipsis
      }

**Comment by erosman** [comment]
1- It retains one new line i.e. converts multiple new lines into one. That is how is was expected but if users prefer it, I can add the feature.

2- Altering characters is beyond the description of "copying plain text", however, if there is a popular demand, I will work on it.

**Comment by arelkin** [comment]
Thanks for the quick response. These  could be check mark options to be turned on and off.

**Comment by erosman** [comment]
**Copy PlainText** since v1.13 has a feature to add custom find/replace.
