### ISSUE TITLE
[FireMonkey][Compatibility] Youtube Music fix volume ratio

### ISSUE THREAD

**Issue by oliver-moeller** [erosman/support#617]
[Youtube Music fix volume ratio](https://greasyfork.org/en/scripts/397686-youtube-music-fix-volume-ratio) is a relatively short userscript to fix the volume curve on YouTube Music. It works fine with TamperMonkey (default settings) but doesn't seem to do anything with FireMonkey.

I am not the author of the script, but I suspect there might be a problem with isolation as the description states:
> This script monkey patches the browsers volume setting, not YouTube Music directly.

Does the script use an API FireMonkey does not support? The editor does not mark anything as invalid.

Any pointers are appreciated, thank you.

**Comment by erosman** [comment]
The userscript needs to be injected into the `page` to work.
Tampermonkey by default injects into the `page` when `@grant   none`.

As stated in FireMonkey Help: Quick Fixes

> `@grant   none` & works in TM|VM
>     💡 Try setting `@inject-into   page` in User Metadata

**Comment by oliver-moeller** [comment]
That fixes it, I somehow didn't connect the dots.
Thank you for your time and help 🙏
