### ISSUE TITLE
[FireMonkey] how do I exclude a script from working on specific domains?

### ISSUE THREAD

**Issue by useless642** [erosman/support#620]
hi, I'm using the following script:

https://greasyfork.org/en/scripts/12367-open-links-in-new-tab

and I wanted to know if there was a way to exclude the script from working on specific domains?

like, can I do that from FireMonkey itself?

(the domains would be: google.com, yandex.com)

**Comment by erosman** [comment]
There are 2 options.

### Global Script Exclude Matches

You can globally exclude domains which would apply to all userscripts.
```
*://*. google.com/*
*://*. yandex.com/*
```

### User Metadata

You can also  exclude each userscript individually.

```
@exclude-match        *://*. google.com/*
@exclude-match        *://*. yandex.com/*
```

**Comment by useless642** [comment]
thank you! that worked.

one last question: how do I make the opposite?

run a script **only** on certain domains.

https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes

👆 that script is enabled by default on all websites, but I only want to have it enabled on yandex.com

can I configure that with FireMonkey?

**Comment by erosman** [comment]
> how do I make a script run only on certain domains?
> 
> https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes
> 
> 👆 that script is enabled by default on all websites, but I only want to have it enabled on yandex.com

### User Metadata

Disable userscript match & exclude
Add your own match

```
@disable-match
@disable-exclude
@match        *://*. yandex.com/*
```

More info in the included **FireMonkey Help: User Metadata**

**Comment by useless642** [comment]
thank you so much! 💞
