### ISSUE TITLE
GM.xmlHttpRequest fails when FormData contains ArrayBuffers

### ISSUE THREAD

**Issue by ppixiv** [erosman/support#633]
When GM.xmlHttpRequest is given a FormData body containing an ArrayBuffer, it sends the string "[Object ArrayBuffer}".  Blobs work, but ArrayBuffers don't.  ArrayBuffers in FormData work in other script managers.

**Comment by erosman** [comment]
After checking with Mozilla engineers:

> Could it be that FormData comes from the web page and ArrayBuffer from the user script sandbox, with the web page being unable to read the "higher-privileged" user script properties?

Can you post a minimal test userscript?

**Comment by ppixiv** [comment]
Aha, I mistook the underlying cause--it's definitely a sandboxing issue.  I'm sending requests for GM.xmlHttpRequest calls from the page context to the script context via a MessagePort.  When I receive the message in the script context it checks for ArrayBuffers in the message and converts them to blobs:

    if(value instanceof ArrayBuffer)
        value = new Blob([value]);

In FireMonkey value is an instance of unsafeWindow.ArrayBuffer instead of the script context's ArrayBuffer.

Here's an example: https://gist.github.com/ppixiv/27ca4ac4117ea53d8dfb1b3dd75be4bf

In FireMonkey this prints "false true".  (Violentmonkey prints "true true". I'm not sure what they're doing--that makes it look like there's no sandbox, but there is.  But it explains why this didn't happen there.)

It's odd that messages received by the script on a MessagePort it created contain objects from the other context.  The whole reason for using a MessagePort is to avoid issues with communicating across contexts.

I guess this is probably a Firefox bug and I'll just need to work around it by checking against unsafeWindow.ArrayBuffer too.

**Comment by ppixiv** [comment]
I'm aware that the script runs in a different context.  That's the entire reason for communicating through a MessagePort: they're designed for sending messages between contexts, such as between a webpage and a worker, between different security contexts as in this case, or between entirely different pages.  Messages received on a MessagePort should never be giving objects from a different context.

It's obviously a bug, but it looks to be a bug in Firefox, not this extension, so I'll close this.
