### ISSUE TITLE
Feature Request: Custom Copy Functionality 

### ISSUE THREAD

**Issue by BeenerJeff** [erosman/support#64]
When a user creates a Custom Copy format, why isn't it applied to all the Tab Copy options?

You have 6 copy options listed (URLs All...to Titles, URLS to Right) to copy Multiple Tabs.  However, if a user specifies a Custom Format, you can only copy 1 Tab at a time.  I tried selecting multiple tabs in FF and then selecting Copy/Custom Copy, however it only copies the tab you right clicked.

By applying the Custom Format to all Tab copies, you would only need 3 of the 6 copy options and users could bulk copy in the format they desire.

Also, being able to specify the date format would be beneficial.

When doing research, I have multiple Tabs open.  I copy those Tabs to a repository.  A Tab delimited format allows the data to be copied to word processing, spreadsheet or database table as a single copy command.

I was using Copy URLS Expert until it quit working after FF57.  It provided the ability to both copy multiple Tab data to the clipboard and to open multiple Tabs from data stored on the clipboard.  I moved to Opera because there were extensions that provided this capability.  

This FF extension is the only one I have found that provides copying Tab Titles and URL's in a tab delimited format.  It would be beneficial to be able to use the custom format to copy multiple tabs.

**Comment by erosman** [comment]
1- It is possible to extent the function of custom copy. As it may not be desired at all times, then that would mean creating additional menus for it (Custom All, Left, Right) which may be too many.

It is also possible to add a selected multi-tab feature (without any additional menu) e.g. apply custom to selected/highlighted tabs.

Let's see... I will work on them in the next upgrade.

2- Date format: lets see if there is a demand for it

3- I have a [FoxyLink](https://addons.mozilla.org/en-US/firefox/addon/foxylink/) add-on that might be useful to you.

**Comment by erosman** [comment]
In v2.16

- Added Custom Copy All, Left, Right
