### ISSUE TITLE
add browser name to auto backup filename

### ISSUE THREAD

**Issue by marcuskbr** [erosman/support#648]
I use FoxyProxy in multiple browsers on Linux and use the auto backup option.
Could you add the browser name to the generated filename so that the filename becomes
FoxyProxy_(Firefox|Chrome|...)_<date>...json  ?

Thanks for your work!
Marcus

**Comment by erosman** [comment]
Please post to the [FoxyProxy Issues](https://github.com/foxyproxy/browser-extension/issues).
