### ISSUE TITLE
Feature Request: Copy All Tab_Title URL as Hyperlinked text

### ISSUE THREAD

**Issue by trouxth** [erosman/support#65]
Hello! First - cool extension! Almost exactly what I am looking for.
I write reports for individuals with disabilities about technology that might work for them. I create lists of items with links to websites with more information. For visual accessibility, I am required to use hyperlinked text. 

I'd like to copy all of my Tab Titles and use them as the anchor text for a hyperlink to the corresponding URL.  I've seen some Chrome Extensions that can do this (like "Link" in TabCopy). Is this possible?

Best,
T

**Comment by erosman** [comment]
Hi

It is possible with **Custom Copy** but only for a single tab.

Extending the function of **Custom Copy** to all tabs has been requested in #64 and that would enable you to achieve what you have in mind.

I will work on it in the next upgrade.

**Comment by trouxth** [comment]
What would be the Custom Copy sequence for a single tab to enable the hyperlink? I look forward to the #64 request as well.

**Comment by erosman** [comment]
> What would be the Custom Copy sequence for a single tab to enable the hyperlink?

If you are talking about normal HTML link (not- BBcode), the HTML is like this: `<a href=""></a>`

To create a **Custom Copy** for above: `<a href="{url}">{title}</a>`

**Comment by erosman** [comment]
In v2.16

- Added Custom Copy All, Left, Right
