### ISSUE TITLE
[FireMonkey] Scripts not working when @match URLs contain special characters

### ISSUE THREAD

**Issue by lumijaeger** [erosman/support#652]
Firemonkey doesn´t recognize sites containing special characters, at least the character 'ñ'. I've already tried with these patterns, to no avail:

```
// @match          https://www.coruña.com/*
// @match          https://www.coru%C3%B1a.com/*
// @match          https://www.coru?a.com/*
```

**Comment by erosman** [comment]
> Firemonkey doesn´t recognize sites containing special characters,...

FireMonkey passes the values to the Firefox API which uses [Match Patterns](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/match_patterns) .
If there is an issue, it is that the Firefox API doesn't recognize the pattern.

However, this case is related to the JavaScript navigation where a site changes the content and URL using JavaScript.

- Go to `https://www.coruña.com/`
- Open Developer Tools (F12)
- Go to the Console tab
- type `location.href `
-  Press Enter

You will see the result is `https://www.xn--corua-rta.com/` which means the page is actually `https://www.xn--corua-rta.com/` although the URL shows `https://www.coruña.com/`.

Try the following:

```js
// ==UserScript==
// @name          Scripts not working when @match URLs contain special characters #652
// @match         https://www.coruña.com/*
// @match         https://www.xn--corua-rta.com/*
// ==/UserScript==

console.log(GM.info.script.name);

document.body.style.border = '1px solid red';
```

**Comment by lumijaeger** [comment]
That fixed it, indeed! Thank you very much for your outstanding work
