### ISSUE TITLE
[FireMonkey] user-style failing to load

### ISSUE THREAD

**Issue by wfaulk** [erosman/support#657]
I have a simple user-style that is failing to load on the appropriate page:

```
/*
==UserCSS==
@name             Fix Broadcom support site fonts
@match            https://broadcomcms-software.wolkenservicedesk.com/*
@version          1.0
==/UserCSS==
*/

.brdcm-standard-header {
  font-family: "Montserrat",sans-serif !important;
}
```

FireMonkey's toolbar icon shows that it's matching with a number overlay, and the menu shows the user-style in the top list with a checkmark and not greyed-out, but Developer Tools doesn't show the style in the Inspector tab on the appropriate elements, and there's no FireMonkey "file" that shows up in the left column in the Style Editor tab. (On other sites where user-styles do work, there's a file there for the inserted CSS that has a UUID for the name.)

I've tried changing `@run-at` to each of the options I'm aware of with no improvement.

I'm not sure what other information I can provide.

This is with FireMonkey 2.72 on Firefox 130.0 on MacOS 13.6.9.

**Comment by erosman** [comment]
I cant test it since that site requires a login.
If you give me an example of a site that can be tested, I will check it out.

> Developer Tools doesn't show the style in the Inspector tab on the appropriate elements, and there's no FireMonkey "file" that shows up in the left column in the Style Editor tab

Sometimes that happens. Try testing it with a simple and obvious CSS like:

```css
body {
  border: 3px solid red;
}
```

There is another possibility and that is JavaScript navigation. 
See also: https://github.com/erosman/support/issues/652#issuecomment-2318555012

**Comment by wfaulk** [comment]
The body border sort-of worked, but the border failed to surround portions of the top, which caused me to poke further.

It turns out that the portion of the page I am trying to modify is a *!@%^#$* iframe.

I have now changed the `@match` to match the iframe URL and added `@allFrames true` and now it works.

Sorry for the bogus bug report, and thanks for the help!
