### ISSUE TITLE
URL MultiCopy: shortcuts menu

### ISSUE THREAD

**Issue by gearF** [erosman/support#66]
Hello,

Is there a way to:
- add shortcuts to navigate faster in the menu / submenu.
or
- put [copy / save in clipboard / paste here] at the menu level.
or
- both (maybe a configuration tab to select which letters to associate for each action, should be done).

otherwise thanks for your helpful firefox addon.

**Comment by erosman** [comment]
> add shortcuts to navigate faster in the menu / submenu.
It is possible although with multiple menus, which one should get the shortcut?
Firefox shortcuts are very congested and hard to find easy shortcut sequence.

> put [copy / save in clipboard / paste here] at the menu level.
Firefox allows only ONE menu item per extension so if there are more than one items, they would automatically put in submenus.

> both (maybe a configuration tab to select which letters to associate for each action, should be done).

As above

**Comment by gearF** [comment]
Well, my main action is to copy links then i have to modified them with regex, bytheway what difference between copy / save in clipboard ?

**Comment by erosman** [comment]
To start with, all functionality of **URL MultiCopy** has been added to [FoxyLink](https://addons.mozilla.org/en-US/firefox/addon/foxylink/). I suggest using **FoxyLink**.

> what difference between copy / save in clipboard ?

When you collect links with copy you store them for later use.

When you want to get them back, you get them from storage and save them to clipboard.

The wording will be changed to make it easier to understand.
However, all future developments will be on **FoxyLink**.

**Comment by gearF** [comment]
well, i had installed both but i use  URL MultiCopy instead of FoxyLink because as i have a lot of links to grab, all in different page, so i need the "shortest" way to collect them. That why i asked for shortcut and i use URL MultiCopy because it have the shortest menu of them and "copy" is at the top of the submenu.

thanks for your replies.

PC: sorry for my bad english and i have to admit i don't  understand your  explanation on the difference between copy / save in clipboard

**Comment by erosman** [comment]
**copy:** copy and put in storage
**save to clipboard:** get links from storage and put in clipboard (after with normal PASTE you can paste them)

**Comment by gearF** [comment]
Hello,

thanks it's clear now but i have a few more questions:

when you use copy, you put link(s) in a memory space dedicated to URL MultiCopy app
when you use save to clipboard, you puts link(s) in a memory space "schedulled" by th OS

right?

so using copy, the new link is concatenate to the previous whereas save to clipboard need to take the link in memory add the new(s) and save the whole thing, isn't it or the new link erase the previous

**Comment by erosman** [comment]
> when you use copy, you put link(s) in a memory space dedicated to URL MultiCopy app
when you use save to clipboard, you puts link(s) in a memory space "schedulled" by th OS

Yes ... The URL MultiCopy  memory/storage is permanent so it stays even after Firefox restart or computer restart. It stay until it is transferred to Clipboard.

Any new COPY will be added/concatenated to the previously stored data.

Moving it to Clipboard will clear the storage and populate the OS Clipboard (like normal clipboard function any subsequent OS clipboard action will clear previous data)
