### ISSUE TITLE
Support linting for CSS nesting

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#666]
Firefox officially supported CSS nesting since 117. I have been using it wherever appropriate and enjoyed it. Unfortunately, FireMonkey doesn't properly lint nested CSS out of the box. I also don't find any hint to fix this in the Help section. If this can be solved with config change, please let me know. Otherwise, would you please consider supporting it? Thank you!

I found your post at https://github.com/CSSLint/csslint/issues/776. If you consider switching to stylelint, there is [a way](https://github.com/csstools/stylelint-use-nesting) to enable nesting.

**Comment by erosman** [comment]
Please note that I have created a dedicated [FireMonkey](https://github.com/erosman/firemonkey) repo.

As mentioned in https://github.com/erosman/support/issues/665#issuecomment-2468981171
> The editor uses CodeMirros 5 which uses old CSS & JS linters which don't support new CSS/JS.


[jshint](https://github.com/jshint/jshint)
JSHint 2.13.6 Latest
on Nov 11, 2022

[csslint](https://github.com/CSSLint/csslint)
v1.0.3 Latest
on Sep 20, 2016

[stylelint](https://github.com/stylelint/stylelint) is very good and up-to-date. However, CodeMirros 5 doesnt support it.
CodeMirros 6 was rewritten and can support Stylelint but it has to be complied from NPM and it becomes very large.
I have found any instruction on compiling it either.

**Comment by CrendKing** [comment]
> Please note that I have created a dedicated [FireMonkey](https://github.com/erosman/firemonkey) repo.

Noted.

> CodeMirros 6 was rewritten and can support Stylelint but it has to be complied from NPM and it becomes very large.
> I have found any instruction on compiling it either.

https://codemirror.net/examples/bundle/ mentions Rollup as example bundler. Since [Vite](https://vite.dev/) uses Rollup, and I'm somewhat familiar with Vite, I just tested and it seems working. Bundled size is less than 500KB.

There is a discussion at their forum and this post sums up what I did: https://discuss.codemirror.net/t/is-there-any-documentation-on-how-to-use-this/8550/10. Can you give it a try?

**Comment by erosman** [comment]
I have also been asking around about other editors such as [monaco-editor](https://github.com/microsoft/monaco-editor), [ace](https://github.com/ajaxorg/ace), or even [ESlint Playground](https://eslint.org/play).

I am open to suggestions on alternatives. Any decent "playground" code that can handle JS & CSS would be fine, as long as it has a repo that can be referenced for the source code (AMO requirement).

**Comment by CrendKing** [comment]
It seems stylelint still [does not support running in browser](https://github.com/stylelint/stylelint/issues/3935). So I have to use [the modified version from openstyles](https://github.com/openstyles/stylelint-bundle). I came up with a quick snippet of calling stylelint as a CodeMirror linter. Does it help in any sense?

https://github.com/CrendKing/codemirror-stylelint-test

1. Install dependencies with pnpm or bun: `bun install`
2. Run with `bun run dev`
3. Build bundle with `bun run build`

**Comment by erosman** [comment]
In order to integrate Stylelint into CodeMirror 5, it requires:

- CSS linter e.g. [CSSLint](https://github.com/erosman/firemonkey/blob/main/src/lib/codemirror/external/csslint.js)
- Error parser e.g. [css.js](https://github.com/erosman/firemonkey/blob/main/src/lib/codemirror/mode/fm-css.js)

**Comment by CrendKing** [comment]
Sorry. I was responding to your comment about upgrading to CodeMirror 6 + stylelint. I was saying your can use Rollup to reduce the distribution size.

**Comment by erosman** [comment]
Upgrading to CodeMirror 6 requires a rewrite of the editor and the associated code which is a major undertaking

**Comment by CrendKing** [comment]
I understand that. I'm simply sharing some knowledge that might be helpful. I can live with status quo. Thanks for the work.

**Comment by erosman** [comment]
Thank you for your help.
Nonetheless, I am hoping to update the editor once FireMonkey has to be updated for MV3.
