### ISSUE TITLE
[Historia] Just to confirm-- these expressions NEVER worked??

### ISSUE THREAD

**Issue by realAzazello** [erosman/support#667]
{_Questions for anyone, not just the dev_}
```
/&sttick=/
/(\?|&|\/)(q=|t=)/
/(\?|&|\=)(redirecting|search)/
/(\?|&|\=|\/|\_)(login|logout|signin|signout|signup)/
```
Is that correct?

So we have to find ALL the _specific_ domains that use these parameters, and manually filter EACH domain using them?

So what would be the best regex for **_e.g._** these? : 

```
https://github.com/erosman/support/issues?q=is%3Aissue+Historia

https://www.youtube.com/watch?v=AKZ&sttick=0

https://my.health.org/Authentication/Login?action=logout
```

**Comment by erosman** [comment]
There is no need to escape `=`

If you don't need the full Regular expression power, it is simpler to use the Glob type rules.
For example, instead of `/&sttick=/`  use `&sttick=`.

> So what would be the best regex for e.g. these? :

Is that an exact URL?
If it is an exact URL (no pattern) simply using the URL works fine. It can be improved by adding `^` to the start.

**Comment by realAzazello** [comment]
heeya, thank for response.

I definitely do not want to use specific domains because those above filters hit what shows up most in my browsing, from dozens of domains.

> There is no need to escape `=`

I think you meant `/` (?)

> If you don't need the full Regular expression power, it is simpler to use the Glob type rules. For example, instead of `/&sttick=/` use `&sttick=`.

Will that work the same for the others? e.g. `/(\?|&|\/)(q=|t=)/` becomes `(\?|&|\/)(q=|t=)`

Just wanna be sure I have effective expressions.

**Comment by erosman** [comment]
`&sttick=` does have any regex pattern so there is no need to use a regex. It is a simple string match.

`/(\?|&|\/)(q=|t=)/` has a regex pattern i.e. `? OR & OR /`

> There is no need to escape =

In here
```
/(\?|&|\=)(redirecting|search)/
/(\?|&|\=|\/|\_)(login|logout|signin|signout|signup)/
```

**Comment by realAzazello** [comment]
Right...So....

Are you saying that `/(\?|&|\/)(q=|t=)/` should work as-is? It's definitely **_not_** re: `https://www.google.com/search?q=anything`

And that these will work by NOT escaping `=`, such `/(\?|&|=)(redirecting|search)/` ?

or should it not escape anything? : `/(?|&|=)(redirecting|search)/`

Or `(?|&|=)(redirecting|search)`

Which is correct?

Sorry I'm not a regex expert by any stretch; and regex implementations vary amongst addons/extensions/scripts, so I wanna get it right for Historia.

(And I did search other Issues; I didn't see any that matched what I'm asking. But if wrong, point us to them!)

**Comment by erosman** [comment]
You can test your regex online, for example in [regex101](https://regex101.com/)

- Enter the regex pattern without the start/end slashes
- Enter the target URL in TEST STRING
