### ISSUE TITLE
Feature Request: Select tabs

### ISSUE THREAD

**Issue by thaliel** [erosman/support#67]
I would really like to be able to have the addon perform an action only on selected tabs

**Comment by erosman** [comment]
It will be added

**Comment by erosman** [comment]
I am thinking about doing it this way ...

- If there are selected tabs, then any tab action will only apply to the selected one
- If there are no selected tab, actions will be like what is was

Otherwise, it would require a whole range of new menus just for the selected *****

**Comment by rainyskyboy** [comment]
how can i save mutli-tabs as pdf or desktop shortcut ? selecy group of tabs while holding "ctrl" not working..it's make the action for 1 tab ..

**Comment by erosman** [comment]
@rainyskyboy At the moment, there is no such feature yet. Selected tab feature will be in next next upgrade of FoxyTab.

**Comment by erosman** [comment]
This feature is included in next release v2.16
