### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by wahawley** [erosman/support#670]
Hello,

Although this is a great add-on, this add-on requires a lot of permissions and aside from a short explanation of the permissions required, I can't seem to find a privacy policy for this (and it is closed source). Can you clarify how data is handled? Does any data get sent to you, or is all data stored locally client-side? Is any data shared with third parties, and if so, for what purposes?

The addition of a privacy policy would be great, but if not I would appreciate some more insight as to how users' data is handled.

Thank you.

**Comment by erosman** [comment]
Which addon are you referring to?

**Comment by wahawley** [comment]
This would be FoxyTab

**Comment by erosman** [comment]
FoxyTab is a [Recommended Extensions](https://support.mozilla.org/en-US/kb/add-on-badges#w_recommended-extensions) which means the code has been checked & verified by Mozilla.

> [Recommended Extensions program](https://support.mozilla.org/en-US/kb/recommended-extensions-program)
>
> **Is the extension safe?** 
> Firefox is committed to helping protect you against third-party software that may inadvertently compromise your data – or worse – breach your privacy with malicious intent. Before an extension receives Recommended status, it undergoes rigorous technical review by staff security experts. 


>  I can't seem to find a privacy policy for this

Privacy Policy is usually needed when there is something to report. As mentioned on add-on's page, "None of my extensions contain any tracking, advertising or privacy infringement."

>  (and it is closed source)

FoxyTab (and my other addons) are open-source which means the source is clear (not obfuscated or minified) and available to view by opening the zip.

There is no requirement for an open-source code to be in a repository. Anyone who has the ability to inspect the code, has the ability to open the zip.

> Does any data get sent to you, 

None

> or is all data stored locally client-side? 

All data are stored on user's Firefox profile.

> Is any data shared with third parties, and if so, for what purposes?

None whatsoever

**Comment by wahawley** [comment]
Thank you!
