### ISSUE TITLE
Replace tool

### ISSUE THREAD

**Issue by sraust** [erosman/support#68]
I am having some trouble saving a webpage after using the find/replace tool. It seems the values do not 'stick', and revert back to their original values when I click anywhere on the webpage.

I am trying to do this on the Etsy platform.

Can you help?

**Comment by erosman** [comment]
When you use **Replace** it changes the visible page. If you copy text, then it will copy the replaced text.

I guess when you SAVE the page, Firefox gets the page from its original cache which is unchanged.

**Comment by sraust** [comment]
Oh. Is there any way around this? I am happy to donate to have this work-around.

**Comment by erosman** [comment]
I have to test it and see.

How do you save the page? Via "Save Page As ..." menu?

**Comment by sraust** [comment]
Yes. I am trying to change all the 0000 to a new SKU, then "save as"

http://prntscr.com/o3jjpr

**Comment by erosman** [comment]
It was possible with old Firefox.

The save as PDF (as in my FoxyTab) will save the edited page but save as HTML will save the original page.

I will do some testing when I get some free time to see if there is  a way.

**Comment by sraust** [comment]
https://drive.google.com/open?id=1ldUGeTMftPYupjTXZBQ5cJAWRSrtpkCM

Here is a video of the issue.

**Comment by erosman** [comment]
The data on the page is dynamic and it changes with some action. That is the reason it gets reset.

You are also saving the page from their save process which uses their original data.

The only way is to save the page and then edit that manually on your computer.

There was a possibility to save the generated page in old Firefox (and some older extensions) but I dont see it now so I dont know if that is possible.
