### ISSUE TITLE
FireMonkey - usability issues :)

### ISSUE THREAD

**Issue by icl7126** [erosman/support#69]
Hi,
This is just a friendly advice - you should make your UI much more user friendly.
I'm telling you this here because I've just installed your FireMonkey and I got frustrated because I was not able to create a script. There should be a button for that in the pop-up, not hidden in the Options page - where one may expect to tweak settings, not to perform the main feature of the addon.

The best way to fix these is to watch somebody else interacting with your add-on. Just take some random people from your surroundings (that are a target audience), give them simple task and then just watch and take notes - you will be amazed how many things is suddenly not as intuitive as you would think (I know what I'm talking about, I'm author of many poorly designed UI and learned this the hard way).

Feel free to close this after reading.

I wish you the best of luck with your add-ons!

Best regards,
Juraj Mäsiar

**Comment by erosman** [comment]
Thank you for your suggestions.

By "create script" do you mean to make a new one? Then it would require the edit area to be able to enter code which is a lot for a pop-up.

If you mean to import script via pop-up then that can be a possibility.

**Comment by icl7126** [comment]
Yes, I'm trying to create a script for somebody as fast as I can without reading docs.

**Comment by erosman** [comment]
To create a new script, you need to have a place to write a code and edit and the pop-up doesn't have enough space for that. Furthermore, pop-up will be closed as soon as you click outside of it, therefore pop-up is not the right place to have that feature.

Did GreaseMonkey, TamperMonkey, or ViolentMonkey suit your requirements?

**Comment by icl7126** [comment]
In GreaseMonkey you have a button there "New user script..." that will open tab with edit window. Something like that would be nice to have here.

Some other things to consider:
- Ctrl + S would be nice to have in the editor
- the saving progress bar is really nice, but do I really have to wait that long after each save till the changes are applied? I know I have to reload the page, but can I reload right away or do need to wait for the progressbar?
- the notification about error in the script is nice, but sadly they appear on the main monitor and for users with multiple-monitors this is really uncomfortable if you are editing your screen on not-main monitor - some small errors list could just written below the edit window

Other than that, it looks and feels very nice.

**Comment by erosman** [comment]
> In GreaseMonkey you have a button there "New user script..." that will open tab with edit window. Something like that would be nice to have here.

In FireMOnkey it is Option -> New Script ... 
As FireMonkey can make both JS & CSS, that means adding 2 buttons to the pop-up. It is easy to do, let's see.

> Ctrl + S would be nice to have in the editor

For Save?
It is possible but require a constant click monitor which can be a resource hog.
It also interferes with the Firefox Save Page shortcut.

> the saving progress bar is really nice, but do I really have to wait that long after each save till the changes are applied? I know I have to reload the page, but can I reload right away or do need to wait for the progress-bar?

Not really.. the save process starts immediately. Sometime ago, a friend asked me for a visual representation on SAVE in another addon. I made this bar and added it to all my addons. ;)
However, it is worth noting that un-registering and re registering a script in the API is done asynchronously so it is not immediate (but usually takes a few 100 milliseconds)

> the notification about error in the script is nice, but sadly they appear on the main monitor and for users with multiple-monitors this is really uncomfortable if you are editing your script on not-main monitor - some small errors list could just written below the edit window

I am also on multiple monitor set-up and I am aware of the notification but that is how notification API is and no way to change  it. Alternative would be a modal pop-up which is undesired.
Add the errors to the bottom of the page can also be unsightly, especially in case of long text.

However......  if there is a popular demand, I will do so.

**Comment by icl7126** [comment]
Regarding Ctrl + S - I mean only in the editor while typing the custom script. All you need to do is register onkeypress (or onkeysomething) where you stop propagation and do the save.
But other popular short-keys for common editing would be also nice. Things like commenting out line, deleting row, duplicating row would be really nice to have.

Regarding progress bar - maybe make it faster? It feels like forever now :)

Good luck again. I'm looking forward for new features :)

**Comment by erosman** [comment]
I have already added the New Script New CSS buttons tot he pop-up.

Ctrl + S: onkeypress listener will be fired every-time you type something in the editor. If you type 100 characters, it fires 100 times. Then each time it has to stop propagation, check and process, and complication to restart the propagation (do the original action).. it takes a fair amount of resources. 
Firefox wont allow overriding its default Ctrl + S otherwise there were more possibilities.
Lets see how many user will demand it.

**Comment by icl7126** [comment]
You shouldn't really care about performance in situations where it doesn't matter. Your browser can process thousands of events in no time (really like 1ms). This is how all online web-editors works. Actually this is how many desktop editors works (since there is several written in JavaScript).

Again I'm not talking about overriding anything in manifest or anything complicated. I mean something as simple as this:

```
textArea.addEventListener('keydown', onKeyDown);
function onKeyDown(e) {
  switch (e.key) {
    case 's': 
      if (e.ctrlKey) {
        save();
      } 
      break;
  }
}
```
This will have 0 impact on the performance in the editor and it will actually save time because you won't have to click the save button with your mouse :)

**Comment by erosman** [comment]
I will test the impact on the performance and if it is negligible, I will add the feature to the next upgrade.

**Comment by erosman** [comment]
**Ctrl + S** added to the editor it will be in v1.7
