### ISSUE TITLE
[FoxyTab] More tab count display options

### ISSUE THREAD

**Issue by nollinvoyd** [erosman/support#7]
Hi, 

Would you consider an option to enlarge the tab count font, or perhaps instead the tab count could replace the button icon?

thanks
-------------------------------------------------------------
Windows 10, Fx 63.09b

**Comment by erosman** [comment]
It is not possible the change the font of toolbar icon badges.

It is possible to replace the icon every time with image of a number but the that uses a lot of resources to create an image every time a tab is added or removed. The toolbar icon must be an image.

Furthermore, the toolbar icon is not a lot bigger than the badge so the number wont be noticeably bigger.
