### ISSUE TITLE
Feature Request: Reload Timer Icon

### ISSUE THREAD

**Issue by SpearheadUK** [erosman/support#72]
Currently it is impossible to know how if a reload timer is set for a tab. Could you add some visual aid to show when one is active. For example adding a character to the start of the tab tile or changing the icon? I have seen this on the ReloadMatic extension and is the one thing I really miss.

**Comment by erosman** [comment]
It has already been requested and will be added to the next update (as much as possible).


Changing the Tab Title or icon is not possible at the moment without dealing with & changing Tab content. FoxyTab does not deal with Tab content (page) and only deal with the tab as whole.

I was thinking of adding a tick to the context menu. There is an API being worked on to allow styling individual Tab. That would make it possible to add some colour to the time to mark it.

ref: [Allow styling individual tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1320585)

**Comment by SpearheadUK** [comment]
ahh my mistake. thank you for your quick responce :)
