### ISSUE TITLE
[Edit] How do I open it???

### ISSUE THREAD

**Issue by wooziwoozi** [erosman/support#73]
How do I open it? I would like to have an icon on my toolbar... Ctrl+Shift+Y is what I use to open new tabs, so nothing happens when I press that. Seems like the addon I want because I have been going insane for years without BBCODEXTRA but...... I can't use it since I can't open it back up.

**Comment by erosman** [comment]
If you open the sidebar by clicking the sidebar icon ([Use the Firefox Sidebar to access bookmarks, history and synced tabs](https://support.mozilla.org/en-US/kb/use-firefox-sidebar-access-bookmarks-history-synced)), then you see **Edit** listed among the available sidebar pages.

**Comment by wooziwoozi** [comment]
Oh I see. Thank you!

Also, just a note of something I would liek to see. Is there anyway to make it so that the customs can fill in the middle based on what is in your clipboard? Thats what I used the most from BBCODEXTRA.

**Comment by erosman** [comment]
That is possible but can make it complicated... if text is highlighted, then what? paste from clipboard will replace that text and there is always something in the clipboard.

It is easier to paste first and then apply the Edit.

However, when I start working on the next version, I will consider all requests.

**Comment by wooziwoozi** [comment]
Ah yea, the way BBCODEXTRA worked is if text was highlighted it preferred that, but if nothing was highlighted it would use the clipboard. maybe you could add a checkbox to select the mode you want to use? IDK. anyway, I am happy that it seems to be for the most part doing what I wanted, so good job!
