### ISSUE TITLE
Create Desktop Shortcut

### ISSUE THREAD

**Issue by Occultcg** [erosman/support#77]
Hello there!

If i save a link with "Create Desktop Shortcut", when i try to open it, a "Security Warning" gets in the way asking "Do you want to open this file?" which is annoying (in Windows 7).

It might be this:

When i open a link (properties) where i do not get this notification, the "Type of file:" is "Internet Shortcut (.URL)" vs Internet Shortcut (.url) (<--- small case) saved by "FoxyTab" maybe this is the issue ? (tried to use save as .URL and it changes it but the warning still triggers)

Also, is there a way to have an option (checkbox perhaps?) to bypass the "Save As" window or something in order to eliminate 1 step thus making the process faster ? (the only utility is to choose location and name but some people want to save the URL as it is)

Also, is there any way to make this process ("Create Desktop Shortcut") faster ?
Now you have to right click tab, get to bottom to "FoxyTab" and select "Create Desktop Shortcut" (shortcut would be so useful even if it would overwrite a Firefox default one (it can be done?)

I hope this process can be simplified as Firefox disabled drag and drop URL saving which is sooo annoying!

Thanks for this add-on!

**Comment by erosman** [comment]
> If i save a link with "Create Desktop Shortcut", when i try to open it, a "Security Warning" gets in the way asking "Do you want to open this file?" which is annoying (in Windows 7).

I am also on Windows 7 but I dont get that. I tired drag and drop on Firefox and also double clicking it.

> When i open a link (properties) where i do not get this notification, the "Type of file:" is "Internet Shortcut (.URL)" vs Internet Shortcut (.url) (<--- small case) saved by "FoxyTab" 

The file is actually saved as .url (not .URL). You can see that next time by looking at the filename in the "Save As" dialogue.

> Also, is there a way to have an option (checkbox perhaps?) to bypass the "Save As" window or something in order to eliminate 1 step thus making the process faster ? (the only utility is to choose location and name but some people want to save the URL as it is)

That is possible but Firefox will only save it to the folder set in the Options as download folder. If no such folder is et, then the popup will come automatically.

> Also, is there any way to make this process ("Create Desktop Shortcut") faster ?
Now you have to right click tab, get to bottom to "FoxyTab" and select "Create Desktop Shortcut" (shortcut would be so useful even if it would overwrite a Firefox default one (it can be done?)

It is not possible to move the menu to the top level. Extension will only get 1 menu location and all menu items belonging to the extension will come under it automatically.

> I hope this process can be simplified as Firefox disabled drag and drop URL saving which is sooo annoying!

I will see if it is possible.

**Comment by Occultcg** [comment]
> I am also on Windows 7 but I dont get that. I tired drag and drop on Firefox and also double clicking it.

After i save it that message occurs, maybe it's my windows but i find it weird because on normal save (drag and drop - when it worked) it doesn't do this.

> The file is actually saved as .url (not .URL). You can see that next time by looking at the filename in the "Save As" dialogue.

Yes, i am aware of that but what i was saying, it was that even if i change it to URL and the properties say the same (.URL) the warning still occurs which is very weird.

> That is possible but Firefox will only save it to the folder set in the Options as download folder. If no such folder is et, then the popup will come automatically.

The folder is set, it would be quicker if no pop-up.

> It is not possible to move the menu to the top level. Extension will only get 1 menu location and all menu items belonging to the extension will come under it automatically.

So there is no way for a mega-fast option to save ?

> I will see if it is possible.

Thank you!

P.S. If nothing can be done (as in to be able to save it faster) a stand-alone add-on for this would be so great. I'm sure many people save links on a regular basis and even if drag and drop for saving is reinstated (firefox) it's impossible to drag and drop when you have a full screen app (like a game) which would not let you see the desktop in order to be able to drag and drop) so a stand-alone "Create Desktop Shortcut" would come in handy! I searched for such an add-on but could not find one.

**Comment by Occultcg** [comment]
Wow, this work-around is working :) ! Thank you, i hope it will be addressed in a patch.
Have a good day!


    On Wednesday, July 10, 2019, 9:26:12 PM GMT+3, erosman <notifications@github.com> wrote:  
 
 

If i save a link with "Create Desktop Shortcut", when i try to open it, a "Security Warning" gets in the way asking "Do you want to open this file?" which is annoying (in Windows 7).


I am also on Windows 7 but I dont get that. I tired drag and drop on Firefox and also double clicking it.


When i open a link (properties) where i do not get this notification, the "Type of file:" is "Internet Shortcut (.URL)" vs Internet Shortcut (.url) (<--- small case) saved by "FoxyTab"


The file is actually saved as .url (not .URL). You can see that next time by looking at the filename in the "Save As" dialogue.


Also, is there a way to have an option (checkbox perhaps?) to bypass the "Save As" window or something in order to eliminate 1 step thus making the process faster ? (the only utility is to choose location and name but some people want to save the URL as it is)


That is possible but Firefox will only save it to the folder set in the Options as download folder. If no such folder is et, then the popup will come automatically.


Also, is there any way to make this process ("Create Desktop Shortcut") faster ?
Now you have to right click tab, get to bottom to "FoxyTab" and select "Create Desktop Shortcut" (shortcut would be so useful even if it would overwrite a Firefox default one (it can be done?)


It is not possible to move the menu to the top level. Extension will only get 1 menu location and all menu items belonging to the extension will come under it automatically.


I hope this process can be simplified as Firefox disabled drag and drop URL saving which is sooo annoying!


I will see if it is possible.

**Comment by Occultcg** [comment]
Aw, sorry, wrong email.. Btw, this is a fix for the drag-and-drop issue (Fireox): support.mozilla.org/en-US/kb/windows-administrator-launcher-process-error-fix


    On Wednesday, July 10, 2019, 9:26:12 PM GMT+3, erosman <notifications@github.com> wrote:  
 
 

If i save a link with "Create Desktop Shortcut", when i try to open it, a "Security Warning" gets in the way asking "Do you want to open this file?" which is annoying (in Windows 7).


I am also on Windows 7 but I dont get that. I tired drag and drop on Firefox and also double clicking it.


When i open a link (properties) where i do not get this notification, the "Type of file:" is "Internet Shortcut (.URL)" vs Internet Shortcut (.url) (<--- small case) saved by "FoxyTab"


The file is actually saved as .url (not .URL). You can see that next time by looking at the filename in the "Save As" dialogue.


Also, is there a way to have an option (checkbox perhaps?) to bypass the "Save As" window or something in order to eliminate 1 step thus making the process faster ? (the only utility is to choose location and name but some people want to save the URL as it is)


That is possible but Firefox will only save it to the folder set in the Options as download folder. If no such folder is et, then the popup will come automatically.


Also, is there any way to make this process ("Create Desktop Shortcut") faster ?
Now you have to right click tab, get to bottom to "FoxyTab" and select "Create Desktop Shortcut" (shortcut would be so useful even if it would overwrite a Firefox default one (it can be done?)


It is not possible to move the menu to the top level. Extension will only get 1 menu location and all menu items belonging to the extension will come under it automatically.


I hope this process can be simplified as Firefox disabled drag and drop URL saving which is sooo annoying!


I will see if it is possible.

**Comment by Occultcg** [comment]
Here is the issue and a workaround, i hope they will address this in a future patch/update...

https://support.mozilla.org/en-US/kb/windows-administrator-launcher-process-error-fix

**Comment by erosman** [comment]
Thank you for the information.

**Comment by erosman** [comment]
Just for info ..... in v2.16
- Updated Desktop Shortcut function to cross-platform HTML type

It should make it easier.

**Comment by Occultcg** [comment]
Nice, keep it up !
