### ISSUE TITLE
[FireMonkey] How to access the global scope?

### ISSUE THREAD

**Issue by sn260591** [erosman/support#80]
unsafeWindow does not work.

**Comment by erosman** [comment]
[unsafeWindow](https://wiki.greasespot.net/UnsafeWindow) is unsafe and shouldn't really be used that is why I have not included it.

Some alternative approaches are listed in above page.

**Comment by sn260591** [comment]
> Some alternative approaches are listed in above page.
This does not always work, as eval is blocked by CSP on some sites.

**Comment by erosman** [comment]
You can try to inject the script into a page with `<script>...code... </script>`
That should become part of page scope and able to access page variables, although I have not tested it.

TBH, I have never needed to use `unsafeWindow`

**Comment by sn260591** [comment]
> You can try to inject the script into a page with `<script>...code... </script>`

CSP can also block any js from the current domain, github as an example.

**Comment by erosman** [comment]
CSP is there to ensure security. Without knowing the details, it is difficult to comment.

**Comment by erosman** [comment]
You can also read [Sharing objects with page scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Sharing_objects_with_page_scripts)

**Comment by sn260591** [comment]
Thanks for the link, the trick with wrappedJSObject works fine.

**Comment by erosman** [comment]
v1,24 Added `unsafeWindow` support
