### ISSUE TITLE
FireMonkey, GM_info support

### ISSUE THREAD

**Issue by tiansh** [erosman/support#81]
I'm using `GM.info` to get current script name and version. It is used to:

* Display to user (and user may want feed back any issues to me);
* Check if user script had updated, and show whatsnew in this version
* Compare current version to user imported configures, and show some message based on it

**Comment by erosman** [comment]
As I have mentioned, adding GM.info support is easy but the I have not found a use for it because.........


```
// ==UserScript==
// @name          My Script
// @namespace     http://www.example.com/gmscripts
// @description   Scripting is fun
// @include       http://www.example.com/*
// @include       http://www.example.org/*
// @exclude       http://www.example.org/foo
// @version       1.5.2
// @icon          http://www.example.net/icon.png
// ==/UserScript==

// some code
const info = GM_info;
notify(info.script.version);  // but the developer already knows this info

notify('1.5.2');              // same as
```

I understand it is easier for the developer to copy/paste `info.script.version` into each script instead of entering the value, but each API requires passing code from script, to API handler, to background script of the FireMonkey and back to the script. 

They are all async operations which go into a queue in Firefox and wait to get their turns.

Is that really necessary?

However, if there is a popular demand for it, I will add it.

**Comment by tiansh** [comment]
I knew that there is an old and hacking way to get the version number...

```javascript
const scriptHeader = (function scriptHeader() {
// ==UserScript==
// @name          My Script
// @namespace     http://www.example.com/gmscripts
// @description   Scripting is fun
// @include       http://www.example.com/*
// @include       http://www.example.org/*
// @exclude       http://www.example.org/foo
// @version       1.5.2
// @icon          http://www.example.net/icon.png
// ==/UserScript==
}).toString().replace(/^[\s\S]*?(.*==UserScript==[\s\S]*==\/UserScript.*)[\s\S]*/g, '$1');

alert(scriptHeader.match(/@version\s+(\S*)/)[1]);
```

But it is ugly and I would prefer to avoid this way.

**Comment by tiansh** [comment]
GM_info is not a function. Therefore, it should be constructed before the script executed. And not requiring the content script post data back and wait the result or so.

**Comment by erosman** [comment]
GM_info and any other GM.* are not JavaScript therefore they have to be defined separately.

FireMonkey does not interfere with the script. It injects the script and then listens to specific calls for those specific functions. All of these calls are handle in the background.

Developers can always set the version as a variable.

```
// ==UserScript==
// @name          My Script
// @namespace     http://www.example.com/gmscripts
// @description   Scripting is fun
// @include       http://www.example.com/*
// @include       http://www.example.org/*
// @exclude       http://www.example.org/foo
// @version       1.5.2
// @icon          http://www.example.net/icon.png
// ==/UserScript==

const version = '1.5.2';
 

notify(version);
```

**Comment by tiansh** [comment]
Yes, but writing the version number twice and keep them synced isn't a good idea imo.

**Comment by erosman** [comment]
Adding a lot of async operations so that developers don't have to write a single number isn't that efficient either, IMHO.

The developer always knows the version number and all other details included in the GM.info
It is just a case of entering it.

Let's see how many people would like to have `GM.info` added.

**Comment by tiansh** [comment]
I believe all these could be done without adding any new _async operations_. Here is the patch:

```diff
diff -r firemonkey-1.9-fx-ori/content/background.js firemonkey-1.9-fx/content/background.js
89c89,97
<       name: id
---
>       name: id,
>       version: pref.content[id].version,
>       'run-at': pref.content[id].runAt.replace(/_/g, '-'),
>       namespace: null,
>       description: pref.content[id].description,
>       excludes: pref.content[id].excludeMatches,
>       matches: pref.content[id].matches,
>       includes: pref.content[id].matches,
>       scriptMetaStr: pref.content[id].metaStr,
diff -r firemonkey-1.9-fx-ori/content/common.js firemonkey-1.9-fx/content/common.js
35c35,37
<     runAt: 'document_idle'                                  // "document_start" "document_end" "document_idle" (default)
---
>     runAt: 'document_idle',                                  // "document_start" "document_end" "document_idle" (default)
> 
>     metaStr: metaData[0],
diff -r firemonkey-1.9-fx-ori/content/scriptAPI.js firemonkey-1.9-fx/content/scriptAPI.js
127,128c127,131
<     info() {
<       return null;
---
>     info: {
>       script: JSON.parse(JSON.stringify(script.metadata)),
>       scriptMetaStr: script.metadata.metaStr,
>       scriptHandler: 'FireMonkey',
>       version: browser.runtime.getManifest().version,
```

**Comment by erosman** [comment]
Let's see how much demand there is for it first.

**Comment by tiansh** [comment]
Anyway, I believe my script won't have many Firefox users through.
