### ISSUE TITLE
FireMonkey, Option to disable syntax highlighting or better performance

### ISSUE THREAD

**Issue by tiansh** [erosman/support#82]
Pasting [my script](https://github.com/tiansh/yawf/blob/yawf4/Yet_Another_Weibo_Filter.user.js) into the text area will hang the editor for about 40s on my laptop. It would be helpful to disable the syntax highlighting since I'm only editing my script in Visual Studio and pasting it here.

**Comment by erosman** [comment]
Sadly, the delay is the rendering of editable items by Firefox and not syntax highlighting.

If you look at the bottom right hand-side of the page under the edit area, you should see how long the syntax highlight took place which is in milliseconds.

Frankly, especially for large scripts, I usually edit the script on a proper editor and then import the edited script (or copy/paste it).


However ......................... if there is a popular demand, I can add a setting preference to disable the whole edit area and convert it to textarea which is fast and renders in milliseconds.

**Comment by qsniyg** [comment]
>if there is a popular demand, I can add a setting preference to disable the whole edit area and convert it to textarea which is fast and renders in milliseconds.

Yes, personally I'd find that really useful! :) Although I also import the script instead of pasting it, the reason is that in order to change any of the settings (or delete the userscript), I believe you need to click on the userscript, which will hang until it finishes rendering the code area.

**Comment by erosman** [comment]
It is done and will be in v1.17
