### ISSUE TITLE
Download Copy PlainText for manual installation

### ISSUE THREAD

**Issue by Nagidal** [erosman/support#87]
Is it possible to download the Copy PlainText as a firefox extension file so that I could install it manually? On my work laptop the Firefox somehow doesn't support installing extensions from addons.mozilla.org.

**Comment by erosman** [comment]
Sure ... just right-click on "Add to Firefox" and select "Save Link As... "
It will download it to your desktop and you can manually install it.

**Comment by Nagidal** [comment]
Good idea. This just never crossed my mind because I do not use Firefox anywhere else, so I never saw any "Add to Firefox" button ever.
