### ISSUE TITLE
[FoxyTab] Put selected items on main menu

### ISSUE THREAD

**Issue by nollinvoyd** [erosman/support#9]
This would be great.  Easier access, and sometimes I forget all the great options Foxytab has because I'm not reminded by just right clicking the context menu :)

**Comment by erosman** [comment]
If you mean having multiple menus on top level of context menu, WebExtension API doesn't allow that.

WebExtension API only allows 1 context-menu item per add-on. If add-on has more than 1, then they will all be moved to a submenu of the add-on context-menu.
