### ISSUE TITLE
[Firemonkey] Improve url regex support in @include/@match userscripts

### ISSUE THREAD

**Issue by MikeZeDev** [erosman/support#91]
Hello, i really wanted to switch to Firemonkey instead of Violentmonkey but some of my scripts arent working . 

According to the error i got (which i cant copy, sadly, its no handy) i would guess that some url patterns in @match or @include arent recognized by Firemonkey.

A couple of affected scripts : 

https://github.com/nokeya/direct-links-out/raw/master/direct-links-out.user.js
https://greasyfork.org/en/scripts/33217-dl-protect-direct-link
https://greasyfork.org/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites
https://greasyfork.org/en/scripts/387015-fandom-reject-advertising-cookies
https://greasyfork.org/en/scripts/389357-zone-telechargement-download

**Comment by erosman** [comment]
FireMonkey uses the new secure API for script and that API supports [Match Patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns).

For example in the first one, these are not supported:
```
// @include     *://google.*
// @include     *://www.google.*
// @include     *://encrypted.google.*
```

Wildcard in TLD has been discussed for a long time (I have also been asking for it for many years) but it is not supported in Firefox (or Chrome) Match Patterns. That affect Google, Amazon and a couple of other domain that have many country TLDs.

If you only use one or few of Google TLDs, then you can change above to:

`// @include     *://*.google.com/*`

Above will work for all the original 3 patterns but only for **.com**

**Comment by erosman** [comment]
v1.25 Added TLD wildcard for @matches
