### ISSUE TITLE
Do old Greasemonkey script run (unchanged) with Firemonkey WebExt?

### ISSUE THREAD

**Issue by bsto** [erosman/support#92]
I have a lot of old Greasemonkey scripts which run (only) as old legacy AddOn.

Can I use them unchanged with FireMonkey?

I am especially interested in the working of

GM_addStyle("....");

and 
embedded jQuery   $("...").......

statements

If NOT: What do I have to change to migrate to FireMonkey?

Is there a conversion/bridge script?

Ben

**Comment by erosman** [comment]
Most GM script should run on FireMonkey without any change but not all.

**match/include**  
Some match patterns would require adjusting (some are auto-adjusted)

**Note: Script API**  
Script APIs require costly mostly asynchronous communication with the extension and the browser. They are necessary when there is no other choice,

**GM_addStyle()** 
`GM_addStyle()` was dropped in GM4 since it is easy to do in content scope without the need for costly asynchronous API calls to the extension.
`GM_addStyle()` functionality can be easily added by adding the following to the script:

```

function GM_addStyle(css) {

  const head = document.querySelector('head');
  if (head) {
    const style = document.createElement('style');
    style.textContent = css;
    head.appendChild(style);
  }
}
```

By adding above to the script code, you can use `GM_addStyle()` like pre-GM4.

**JQuery**  

FireMonkey does not support remote script injection due to security risks therefore `GM_getResourceURL`  is not supported at the moment.

JQuery (better to use the slim version) can be copy/pasted into the code of the script in order to use it. It has the exact same effect.

**Comment by bsto** [comment]
@erosman: Thank you for explanation.

You wrote:

"GM_addStyle() was dropped in GM4 since it is easy to do in content scope without the need for costly asynchronous API calls to the extension."

Hmm, so how is the suggested "easy" way to e.g. write the following WITHOUT a GM_addStyle() function call?

GM_addStyle(".sampleclass { font-size: 16px !important; line-height: 16px !important; }");

Furthermore your wrote:

"JQuery (better to use the slim version) can be copy/pasted into the code of the script in order to use it. It has the exact same effect."

So how do  I write e.g. the following jQuery instruction in a *.user.js script

$("#contentad-topbanner").remove();

**Comment by erosman** [comment]
> Hmm, so how is the suggested "easy" way to e.g. write the following WITHOUT a GM_addStyle() function call?
> 
> GM_addStyle(".sampleclass { font-size: 16px !important; line-height: 16px !important; }");

As mentioend previously, copy the `function GM_addStyle(css) { ...}` code and paste it in the script.

For example:
```

// ==UserScript==
// @name          My Script
// @description   Scripting is fun
// @match         http://www.example.com/*
// @match         http://www.example.org/*
// @version       1.0
// ==/UserScript==

function GM_addStyle(css) {

  const head = document.querySelector('head');
  if (head) {
    const style = document.createElement('style');
    style.textContent = css;
    head.appendChild(style);
  }
}

GM_addStyle(".sampleclass { font-size: 16px !important; line-height: 16px !important; }");
```

> So how do I write e.g. the following jQuery instruction in a *.user.js script
> 
> $("#contentad-topbanner").remove();

Personally, I dont use JQuery and I would just write it using pure JavaScript which improves the performance. e.g.:
`document.querySelector('#contentad-topbanner').remove(); `

However, if you need to use JQuery, then copy JQuery code, for example from: 
https://code.jquery.com/jquery-3.4.1.slim.min.js

Then paste the above code inside the script, like the example of pasting `GM_addStyle()` in the code.

**Comment by bsto** [comment]
Great! I will try it.

One more related question:

In old (legacy) Firefox I could write the Greasemonkey *.user.js scripts in a textfile outside of Firefox and drag them from WinExplorer onto Firefox window in order to install them.

I appreciated this way of working.

Unfortunately this procedure doesn't work in new Greasemonkey any more.
I had to write the user.js scripts directly in AddOn of new Firefox.
No dragging is possible any more :-(

May I ask if FireMonkey allows somehow drag&drop of *.user.js scripts like in good ol' times?

Alternatively: Can I pass an external *.user.js script on command line as parameter to new Firefox and install it this way similar to:

Firefox.exe --adduserscript "D:\test\myscript123.user.js"

Thank you

**Comment by erosman** [comment]
At the moment, support for installation via drag/drop or direct from sites have not been included in FireMonkey. I am still undecided about it.

The optimum installation is using **Import** which can import 1 or many (100s) in one operation. Click Import and navigate to the desired file/s on your computer.

Scripts can also be copy/pasted directly, but I usually use the Import.

Scripts/CSS can also be exported, if needed.

Note: JS files dont have to end in '.user.js'.

**Comment by bsto** [comment]
You wrote:

"At the moment, support for installation via drag/drop or direct from sites have not been included in FireMonkey. I am still undecided about it."

Ok, that means drag & drop is possible in general even in new Firefox API?

Then I would like to encourage you to implement it.

I feel uncomfortable if I have no backup of the ~20 scripts inside a tool like Firefox.
Ok, I could export them each time I adjust them but hat requires always many clicks + concentration.
I (and many friends) prefer to have the master copy outside of a Firefox in an own directory
and push them inside the tool by simple drag & drop.

Allmost all text editors, image editors, pdf  editors work that way (at least they are offering it as an option). So it would be great to have drag & drop for user scripts onto FireMonkey & Firefox as well.

Thank you in advance
Ben

**Comment by erosman** [comment]
@bsto Drag & Drop Installation of scripts with name ending with `.user.js` has been added to v1.19

v1.19
    Added Web Install option for greasyfork.org
    Added Direct Install option for files loaded into tab for `https://greasyfork.org/scripts/*.user.js` & `file:///\*/*.user.js`

**Comment by bsto** [comment]
Great!

When will v1.19 be available?

Currently I can see only v1.18

**Comment by erosman** [comment]
@bsto I am still testing  I will upload v1.19 hopefully in a day or two

**Comment by erosman** [comment]
v1.24 Added **GM.addStyle/GM_addStyle**
