### ISSUE TITLE
various things that don't go

### ISSUE THREAD

**Issue by gabri25ele** [erosman/support#93]
- some scripts not works (red cross) for example W.A.R. Links Checker

![Immagine](https://user-images.githubusercontent.com/33927879/64619940-3ca51700-d3e3-11e9-84e4-0f6fd34fe382.png)

- some scripts have their own settings pages and here I don't think you can view... 

 - if I go to a scripts site (example: https://greasyfork.org/it/scripts/2024-w-a-r-links-checker-premium )
and click install script, nothing happens

- exclusion settings (both general and for single script) does not exist?

**Comment by erosman** [comment]
FireMonkey is not GreaseMonkey or its clone. Please read the manual for more information.

FireMonkey is a NEW script manager and works differently.

**Comment by gabri25ele** [comment]
it may work differently, but if it doesn't do what it takes, what's the point?

**Comment by erosman** [comment]
At the moment, direct installation is not supported.

FireMonkey can install 100s of script in one operation from the local computer by using Import. GM doesn't do that and each script has to be installed one by one.
You can download the script to you computer and use Import or copy/paste into FireMoneky.

At the moment, there is no separate settings for scripts. Inclusion/exclusions are done inside the script.

**Comment by gabri25ele** [comment]
At the moment, I must use "other"Monkey

🙊

**Comment by erosman** [comment]
I understand. FireMonkey still is in its early days and will continue to improve and develop further.
