### ISSUE TITLE
[FireMonkey] responseType Implementation

### ISSUE THREAD

**Issue by RETARDMASTER** [erosman/support#96]
Hi. Do you plan to implement responseType for GM_xmlhttpRequest interface? It's present in the fetch API but I don't get the same, "complete" HTTP response with it. 
From what I understand, my script is expecting an Array Buffer and it only gets the response.response/responseText of the expected object with Fetch. Using GM_xmlhttpRequest on FireMonkey, I get a null responseType and trying to convert the stringified json object into a Uint8Array doesn't work. Neither does Buffer.from. I'm trying to make this https://github.com/xonrsoftware/SteamBrowserModDownloader (for Tabletop Simulator workshop) work without having to rely on a privacy invading addon. Since @require isn't allowed I simply copypasted the libs into the script by the way so that's not the issue. 

To be honest both responses (firemonkey/tampermonkey) look -  apart from the responseType - completely the same to me in the console.log. I have no idea how it even works on Tampermonkey using the entire fucking response with the header fields and shit to begin with, and the script itself is an algorithmic mess. I don't technically need the script, but it could be handy for friends. 
Also really like your decent alternative to Tamper/Grease/WhateverMonkey, it pains me to see that the first script I use with it doesn't work.

Thanks

**Comment by erosman** [comment]
`GM.xmlHttpRequest` doesn't have a full `responseType` implementation. 

I can add the support but it would require testing & feedback from users.

I will include it in the next update.

**Comment by erosman** [comment]
BTW, I added the following the the Help

### @require

_@require_ functionality can be easily added by copy/pasting the remote code into the script OR by adding the following to the beginning of the script:

```
const script = document.querySelector('script');
script.src = 'http://www.example.com/example.js';
document.body.appendChild(script);  
```

**Comment by RETARDMASTER** [comment]
Alright thanks. I'll try it again when the next update  comes out

**Comment by erosman** [comment]
v1.14 uploaded with **responseType** support.
Please test it and let me know as I have not tested it.

**Comment by RETARDMASTER** [comment]
Does not seem to work on my end. No callback is triggered, not even onerror/ontimeout/onabort when I use text/arraybuffer/json/document as responseType. I don't get any console.log whatsoever. A gibberish type or "" is ignored.

I think you meant document.createElement('script') by the way. I suggest using let in case you got multiple scripts to add. If the user has an adblocker and/or noscript, it'll probably not work too. Copy pasting the remote code is ugly but seems to be the safest and most reliable solution to me.

**Comment by erosman** [comment]
> I think you meant document.createElement('script') by the way

yes... oops

> No callback is triggered

You need to check ...

```
  responseType              // Optional, '' or 'text' (default), 'arraybuffer', 'blob', 'document', 'json'
                               if used, get the result from response (not responseText)
```

[XMLHttpRequest.responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType#Value)

> When setting responseType to a particular value, the author should make sure that the server is actually sending a response compatible with that format. If the server returns data that is not compatible with the responseType that was set, the value of response will be null.

**Comment by RETARDMASTER** [comment]
I know the response is compatible with at least arraybuffer because the script works fine with TamperMonkey. I checked with the other types for the sake of it. The problem is that I don't even get a null response, no callback seems to be triggered at all when using responseType properly.

**Comment by erosman** [comment]
OK.. it that case, let me do some testing and get back to you.

**Comment by erosman** [comment]
I have been testing and make some minor corrections.

Can you give me an example to test the **'arraybuffer'** with?

**Comment by erosman** [comment]
There is a restriction in Firefox API that prevents the response object from being passed to the content-script. I am discussing it with Firefox & API engineers to resolve it.

**Comment by RETARDMASTER** [comment]
You can try with this script (not mine) : https://pastebin.com/CwE3BQmW Two libs are copy pasted at the beginning, a Buffers module from Node.js I think and a BSON library that I don't know.
Use it on this page https://steamcommunity.com/sharedfiles/filedetails/?id=940113435 or any other mod page for tabletop simulator. You're supposed to have a "Download" button showing up similar to "Subscribe" to download a .json file, in the case of the mod I linked, of 1499 kB looking like this : https://i.imgur.com/j8sfC0U.png

**Comment by erosman** [comment]
Bug filed.
v1.15 Added a workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=1583159
I am testing and will release soon.

**Comment by erosman** [comment]
v1.15 uploaded 
Let me know how it works out

**Comment by RETARDMASTER** [comment]
Alright it works on my end, I receive the proper response. However I have this bug when it comes to do anything with the arraybuffer : _"Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto()."_ utils is undefined and Components is marked as soon deprecated or something. Anyway I solved the problem with this code 
`function copyArray(src)  {
    var dst = new Uint8Array(src.byteLength);
    dst.set(new Uint8Array(src));
    return dst;
}`
