### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by n1trux** [erosman/support#97]
I see you have some repositories on Github but there's no source code available.

Since you licensed your add-ons under MPL, the following seems to apply:

>If You distribute Covered Software in Executable Form then:
>such Covered Software must also be made available in Source Code Form […]

Please create a repository with the source code of your add-ons.

**Comment by erosman** [comment]
> Please create a repository with the source code of your add-ons.

Why?
I don't develop or distribute via GitHub system.

**Comment by n1trux** [comment]
You don't have to create the repository on github.

A download link with the source code would be sufficient.

Even if you're the only developer, please share your code as others can contribute, too. You don't have to accept their pull requests, but if you ever get bored or run over by a truck, others can continue your good work.

**Comment by erosman** [comment]
Thank you. I will take it under advisement.

**Comment by adamency** [comment]
I made a git repository of all the history of the project I could salvage: https://github.com/adamency/firemonkey

I explained my reasoning and motive in detail here: https://github.com/erosman/support/issues/415#issuecomment-1865520465

PS: And I intend on keeping it updated.
